### ISSUE TITLE
bug: flox push for the first time aborts with git remote usage

### ISSUE THREAD

**Issue by networkhermit** [flox/flox#10]
flox version: Version: 0.1.1-r404-0.0.10-r204

Step to reproduce:

1. flox edit -e demo
2. uncomment the packages.nixpkgs-flox.bat line and save
3. flox push -e demo
4. choose github.com and complete the gh authentication
5. floxmeta repo created successfully
6. flox push aborts with following git remote usage:
```text
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 617 bytes | 617.00 KiB/s, done.
From git+ssh://github.com/USER/floxmeta
 * [new branch]      floxmain   -> origin/floxmain
usage: git remote add [<options>] <name> <url>

    -f, --fetch           fetch the remote branches
    --tags                import all tags and associated objects when fetching
                          or do not fetch any tag at all (--no-tags)
    -t, --track <branch>  branch(es) to track
    -m, --master <branch>
                          master branch
    --mirror[=(push|fetch)]
                          set up remote as a mirror to push to or fetch from

```
7. now the newly created floxmeta repo only has floxmain branch
8. flox push -e demo again, this time it's expected:
```text
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 4 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (14/14), 5.31 KiB | 2.66 MiB/s, done.
Total 14 (delta 0), reused 0 (delta 0), pack-reused 0
remote:
remote: Create a pull request for 'x86_64-linux.demo' on GitHub by visiting:
remote:      https://github.com/USER/floxmeta/pull/new/x86_64-linux.demo
remote:
To git+ssh://github.com/networkhermit/floxmeta
 * [new branch]      origin/x86_64-linux.demo -> x86_64-linux.demo
```

**Comment by aakropotkin** [comment]
Thanks for  your report. I'll send this over to engineers that work on the CLI to get some assistance on this one.

**Comment by aakropotkin** [comment]
I was able to reproduce your issue today, and had time to get more info from engineers.

They let me know that `git+ssh` is not currently supported at this time and that they recommend using `https` instead.
I made a recommendation to remove the `git+ssh` option from the prompt until it is actually supported.

Apologies for the confusion. Please let me know if there's anything else I can do to help.
