### ISSUE TITLE
feat(pkgdb): use memory introspection to adjust for speed when > 4g is available

### ISSUE THREAD

**Issue by billlevine** [flox/flox#1006]
Nix scraping is done in child processes to manage memory requirements.  There is a tunable parameter to adjust for more child invocations with the benefit of lower peak memory consumption.  Fewer child invocations will raise peak memory required but will speed up scraping. The current hard coded value is 5k items per invocation which keeps memory constrained to around 2g at the cost of a 15% time penalty.

We should see how much memory is available and using heuristics, adjust the page size up for faster speed.  Adjusting down could allow for us to run down to 1.5g potentially but with pretty high time penalty, 200%?).  We should ensure we limit downward adjustments.

** Decisions to be made **
1. Lower limit of page size (upper limit of performance impact).  2k should keep memory safely under 2g, but nearly 2x time cost.
2. Any user facing messaging.  IFF we scale down beyond some threshold, show a warning to the user, "warning: low memory is impacting performance" or some such?
3. Heuristic rules to adjust page size:   <=2g = 2k, <=3g = 5k, <=4g = 10k, <=6g = 20k, >6g = 100k (max, currently only needs ~21k)
4. Gauge this on *available/free* memory or *physically installed* memory?  To get close to "it always just works" we should use free, but it may 'hide' the fact that performance could be better with user interaction (freeing up memory).. Item 2 would mitigate this.

**Describe a use case of this feature:**
This would allow scraping with a minimum mem requirement of 2g, but still run a peak efficiency if enough memory is available.

**Acceptance criteria:**
1. Test with memory constrained to 2g, 4g, and 8g.  Verify with page size logging (-vvv) and `time` output for peak RSS.  It should work in all cases, and use the maximum page size above around 5g (or other if there is a reason to do so).  Current peak on full page size is about 4.5g.
6. Define a max page size to allow a full scrape in one child.  Current needs are around 20k fwiw.

**Comment by ghudgins** [comment]
do this based on free memory (safest option)
emit a log message for verbose logging that we have limited you
