### ISSUE TITLE
Fix links and backticks in rendered man pages

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1008]
Given the following input:
```
    The values of these variables should be integers
    chosen from the 256-color palette as described in the
    [xterm-256color chart](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg).
```
the rendered man page looks like this (notice the weird formatting of the link):
```
              The values of these variables should be integers chosen from the 256-color palette as described in the
              https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg xterm-256color chart <>.
```

Furthermore, text enclosed in `backticks` is rendered as plain text as if the backticks weren't there.

Look through https://pandoc.org/MANUAL.html#pandocs-markdown to see if there's a way to get these rendered properly both on the web and in the man pages.

**Comment by ghudgins** [comment]
need URL plaintext so users can click on them

**Comment by ghudgins** [comment]
verified
