### ISSUE TITLE
Prep for adding python hook

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1027]
# Acceptance Criteria

**Given** the project has `requirements.txt` file
**And** i'm in the project directory
**When** I `flox init`
**Then** I see an interactive prompt

```
Flox detected a requirements.txt

Python projects typically need:
* python, pip
* A Python virtual environment to install dependencies into

Would you like Flox to apply the standard Python environment? 
You can always revisit the environment's declaration with 'flox edit'

>Yes (default: latest Python version)
No
Show environment manifest

```

- Add an option `--auto-setup` to avoid having to select `Yes`

If the user selects `Yes` or uses `--auto-setup`:
- Add python and pip to the manifest, and build and lock the manifest
- Add the following to the shell hook:
  ```
  # Automatically generated by flox
  # TODO
  # End generated by flox
  ```

Regardless of the above:
- Add a `FLOX_ENV_CACHE` environment variable to flox activate pointing to `.flox/cache` (feel free to change names)

**Comment by zmitchell** [comment]
> * A python venv to install dependencies

I'd amend this to say `virtual environment` since `venv` is actually the name of a Python module.

**Comment by ysndr** [comment]
> Add a FLOX_ENV_CACHE environment variable to flox activate pointing to FLOX_ENV/cache (feel free to change names)

I assume that's supposed to be `<path to .flox>/cache`?
`$FLOX_ENV/cache` is part of a store path, i.e. non writable/removable

**Comment by mkenigs** [comment]
Yeah, fixed. I think that's the most logical place to put it but open to suggestions

**Comment by ysndr** [comment]
Then we still have to find a _different_ place for this when running remote envs, which do't have a .flox dir.
We already have a cache dir for the intall roots, maybe we find a place around there.
Alternatively we can use the same basedir in FLOX_CACHE_HOME identified by e.g. a hash of the env path.
