### ISSUE TITLE
handle token expiration gracefully

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1031]
Max token expiration we can set is 30 days.

# Acceptance Criteria
**Given** I have an expired token
**When** I `flox push` or `install -r` or `edit -r` or `uninstall -r`  <-- _any other commands?_
**Then** I see a message

⚠️ Your login has expired. Please log in again
**And** I see Flox is prompting me to login (standard login)

**Comment by ysndr** [comment]
@ghudgins @jennymahmoudi 
Do we want both the token validation AND login flow to be lazy, i.e. only upon invocation of specific commands, or does it make sense to validate the token eagerly, clearing it if it is expired (which will till trigger the login flow lazily)?

```
flox init
⚠️ Your FloxHub token has expired. You may need to log in again.

# token was removed from the config file, so no further warning appears (optional)
flox list
...
```

```
flox push
⚠️ Your FloxHub token has expired. You may need to log in again.
You are not logged in to FloxHub. Logging in...
! First copy your one-time code: ????-????
...
```

**Comment by ghudgins** [comment]
doesn't seem to have a significant impact either way but eager validation seems slightly better if all things are the same

**Comment by ghudgins** [comment]
looks good!
