### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1032]
There's a number of related logging tweaks we can implement to make our logs more useful for debugging. This will also integrate better with Sentry when we eventually do that integration.

**Acceptance criteria:**
- Use the default formatter (colored output, every log message on one line) with the addition of filename and line number
- ~[Unescape](https://docs.rs/snailquote/latest/snailquote/fn.unescape.html) commands that are printed in the logs to improve readability and make logs more concise~
- End every spinner with a newline character so that log messages that come after the spinner show up on their own line.

**Comment by ysndr** [comment]
> Unescape commands that are printed in the logs to improve readability and make logs more concise
better yet, use "shell_escape" to escape external commands consistently for copy paste into a shell.

Example of how we did that before: https://github.com/flox/runix/blob/main/crates/runix/src/command_line/mod.rs#L64-L111

**Comment by zmitchell** [comment]
This ticket is outdated.
