### ISSUE TITLE
bug(pkgdb): CTRL-C while CLI is scraping/download does not respond

### ISSUE THREAD

**Issue by billlevine** [flox/flox#1035]
**Describe the bug:**
While the CLI is scraping databases (or downloading) the process does not respond.  This is on account of the change to scrape and download in a forked child and wait for it.

**Steps to reproduce:**
1. Clear caches, and issue a `pkgdb search --match-name hello --ga-registry`  command
2. After a few seconds attempt to CTRL-C the command
3.

Result: 
There is no immediate response.

Expected: 
The command immediately aborts.

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

**Comment by tomberek** [comment]
Likely related (merged Jan 4): https://github.com/NixOS/nix/pull/9687
Available in 2.20 and backport to 2.19

**Comment by mkenigs** [comment]
Won't fix since we'll be dropping scraping
