### ISSUE TITLE
flox list error - failed to parse contents of locked manifest: invalid type: null, expected a string

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1039]
STR:
* `flox init`
* `flox install influxdb2`
* `flost list`

Result: "failed to parse contents of locked manifest: invalid type: null, expected a string"

Expected: no error

**Comment by aakropotkin** [comment]
Unless there's a strong case against it, I recommend we remove strictly typed lockfile definition from Rust and interact with the lockfile as a filepath or "raw JSON" only.

We agreed to avoid creating duplicate definitions of these records whenever possible.

**Comment by mkenigs** [comment]
> Unless there's a strong case against it, I recommend we remove strictly typed lockfile definition from Rust and interact with the lockfile as a filepath or "raw JSON" only.

See case against it in https://github.com/flox/flox/pull/707#discussion_r1442730578

**Comment by mkenigs** [comment]
> > Unless there's a strong case against it, I recommend we remove strictly typed lockfile definition from Rust and interact with the lockfile as a filepath or "raw JSON" only.
> 
> See case against it in [#707 (comment)](https://github.com/flox/flox/pull/707#discussion_r1442730578)

We may discuss sync if we need to address this more

**Comment by mkenigs** [comment]
Fixed
```
> flox init
✨ Created environment 1 (aarch64-darwin)

Next:
  $ flox search <package>    <- Search for a package
  $ flox install <package>   <- Install a package into an environment
  $ flox activate            <- Enter the environment

> flox install influxdb2
✅ 'influxdb2' installed to environment 1 at /Users/matthew/flox/1
> flox list
influxdb2: influxdb2 (N/A)
```
