### ISSUE TITLE
Nix/Generic installing 0.3.6 instead of 0.9.0

### ISSUE THREAD

**Issue by nickryand** [flox/flox#1040]
**Describe the bug:**
It looks like the `flake.nix` file is pointing to a version of `0.3.6` instead of `0.9.0`. 

https://github.com/flox/flox/blob/main/flake.lock#L83
```
nix run --impure 'github:flox/flox' -- --version
Version: 0.3.6-dirty
```

Cloning the repository, updating the `flox-latest` input to https instead of ssh and building locally builds `0.9.0`

```
$ nix build .
$ result/bin/flox --version
Version: 0.9.0-13-g7d1df89
```

**Steps to reproduce:**
1. Install using the Nix/Generic method or use `nix run` to execute the flox binary directly.

Result: 
This install method installs 0.3.6 instead of 0.9.0

Expected: 
Nix to install the latest version of flox `0.9.0`

**Comment by ghudgins** [comment]
will be fixed with the next release 🎉
