### ISSUE TITLE
Add Sentry to the Rust CLI

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1055]
Do the bare minimum Sentry integration into the Rust side of the CLI. The CLI needs to initialize the Sentry library with some config:
- A Sentry DSN value
- A Sentry "environment" value (is this instance of the CLI a stable version, a nightly build, etc)

These values will be provided as compile time environment variables by the installer, but the CLI should fall back to reading them from the environment at runtime so that they can be provided by the developer environment. This is the same pattern that we use for setting `PKGDB_BIN` in the Rust side.

**Acceptance criteria:**
- [x] Sentry is initialized at application startup
- [ ] Rust CLI reads `_FLOX_SENTRY_DSN` from the environment at compile time
- [ ] If `_FLOX_SENTRY_DSN` is present at runtime, use that instead of the compile time value.
- [ ] Rust CLI reads `_FLOX_SENTRY_ENV` from the environment at compile time
- [ ] If `_FLOX_SENTRY_ENV` is present at runtime, use that instead of the compile time value.
- [x] The DSN and environment are set at application startup time (when Sentry is initialized).

**Comment by ysndr** [comment]
The variables are called FLOX_SENTTRY_DSN and FLOX_SENTRY_ENV
and are set  by the wrapper of the postBuildHook of our main flox package, so in development when built with cargo, you can export those vars and have overrides, the production packages can currently _not_ be overridden (easy to change however)

https://github.com/flox/flox/blob/66289ce44bf60390d551df542c1a347c9fb097a5/pkgs/flox/default.nix#L40-L41

**Comment by zmitchell** [comment]
Why aren't we prefixing with an underscore, isn't that the convention for internal variables?

**Comment by zmitchell** [comment]
And if it's easy to change why wasn't the runtime override done in the first place?

**Comment by ghudgins** [comment]
can we close this?

**Comment by ysndr** [comment]
In principle yes, let me just chat this over with Zach tomorrow so the question in the thread are not unanswered:)

**Comment by ghudgins** [comment]
closing - reopen if you need to!
