### ISSUE TITLE
Add Sentry instrumentation to Flox

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1059]
The default Sentry integration will only collect errors. We can get more useful information out of the metrics if we add our own instrumentation. This simply entails adding a `#[instrument]` macro to certain functions or calling the `tracing::*_span!` family of macros to mark out spans inside the code.

The first step can simply be instrumenting each command with the `#[instrument]` macro or a `debug_span!` macro inside the command. Note that the `#[instrument]` macro by default will attempt to log all of the arguments passed to the function, which may not be desirable or even work depending on whether the type can be serialized to a `tracing` value. I personally recommend creating the span manually inside the function.

**Acceptance criteria:**
- [ ] Create a span for each command

Up to the implementer and product discretion, but it may also be helpful to create spans or events for search terms, failed package installations, etc.

**Comment by stahnma** [comment]
@zmitchell can this be closed? All PRs attached are merged

**Comment by zmitchell** [comment]
Yeah, the PR was just merged in the last hour or so.
