### ISSUE TITLE
[pkgdb/chore]: Drop dependency on `node-semver`

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#1069]
Drop dependency on `node-semver` and perform parsing in C++ or SQL.

**Comment by aakropotkin** [comment]
@tomberek has some prior art worth referencing

**Comment by tomberek** [comment]
https://github.com/flox/flox/pull/626

**Comment by billlevine** [comment]
> #626

This looks great as far as keeping it in C++.  

There look to be potentially usable extensions for SQLite (https://github.com/asg017/sqlite-semver - work in progress) and PostgreSQL (https://pgxn.org/dist/semver/) to directly support semver queries.  Or update the schema with parsed columns for semver fields (ewww?).  Might be the best option going forward to keep it all in the DB/SQL, but going that route should probably coincide with design decisions for the catalog service and exposed API.

Aside from the risk mentioned in #626, was there another reason that was deferred?

**Comment by mkenigs** [comment]
> Aside from the risk mentioned in #626, was there another reason that was deferred?

I think it was just a prioritization issue
