### ISSUE TITLE
flox init reads pyproject.toml and suggests installation/config

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1071]
# Acceptance Criteria

**Given** the project has `pyconfig.toml` file
**And** i'm in the project directory
**When** I `flox init`
**Then** I see an interactive prompt

```
Flox detected a pyconfig.toml

Poetry projects typically need:
* python3, poetry
* A python venv to install dependencies

Would you like Flox to apply the standard poetry environment? 
You can always revisit the environment's declaration with 'flox edit'

>Yes 
No
Show environment manifest

```

# Details

Suggested installs

```
python3
poetry
```

be inspired by: https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/interpreters/python/hooks

Suggested shell hook
```
     poetry install
     poetry shell
```

**Comment by ysndr** [comment]
when both requirements and a poetry conf are present, we ask and chose one right?

**Comment by mkenigs** [comment]
> when both requirements and a poetry conf are present, we ask and chose one right?

Which tools support pyproject.toml now? https://peps.python.org/pep-0621/

Found this note about the difference in format for poetry and other tools https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#

**Comment by mkenigs** [comment]
@ghudgins I think this one is ready for review

**Comment by ghudgins** [comment]
verified. looks really good!
