### ISSUE TITLE
flox init reads yarn.lock and suggests installation/config

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1072]
# Acceptance Criteria

**Given** the project has `yarn.lock` file 
**And** i'm in the project directory
**When** I `flox init`
**Then** I see an interactive prompt

```
Flox detected a yarn.lock

Yarn projects typically need:
* yarn 
* an installation shell hook

Would you like Flox to apply the standard yarn environment? 
You can always revisit the environment's declaration with 'flox edit'

>Yes 
No
Show environment manifest

```

# Details

Suggested installs

```
yarn
```

be inspired by: https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/interpreters/python/hooks

Suggested shell hook
```
      yarn
```

**Comment by ghudgins** [comment]
@aakropotkin @tanjadev @brendaneamon 👀

**Comment by mkenigs** [comment]
@ghudgins ready for review

**Comment by ghudgins** [comment]
verified
