### ISSUE TITLE
Filter unfree packages at search and resolution time

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1091]
STR:
- flox init
- flox search slack

Expected:
`slack` is hidden since it's unfree

Actual:
`slack` is shown

Our man page says:
```
`allow.unfree`
:   Allows packages with unfree licenses to be installed and appear in search
    results.
    The default is `false`.
```

AC:
- unfree packages are filtered at search and resolution time

**Comment by ghudgins** [comment]
i'm not so sure this is aligned with #492 - can we connect briefly?

**Comment by mkenigs** [comment]
Closing in favor of https://github.com/flox/flox/issues/1091
