### ISSUE TITLE
Re-pulling the same environment by name fails

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1093]
**Describe the bug:**

**Steps to reproduce:**

* `flox pull stahnma/default` 
* `flox activate`
* run `flox pull stahnma/default` again

Result:
```
❌ ERROR: Cannot pull a new environment into an existing one
```

Expected
```
 ⬇️  Remote: pulling and building stahnma/default from https://hub.flox.dev/
```

Note: it works if you just `flox pull` - looks like we need to check that the environment is actually different before we throw the error (vs. just assuming that a pull by name is a new incoming environment.

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

Version: 0.9.0-37-gc68be81

**Comment by mkenigs** [comment]
This is the documented behavior, but seems like we should change it since it's confusing. `man flox-pull`:
```
       When pulling an environment that has already been pulled, -d specifies which environment to sync.  If -d is not specified and the current directory contains an environment, that environment is
       synced.  -f may only be specified in this case, forceably updating the environment locally even if there are local changes not reflected in the remote environment.  <owner>/<name> may not be
       specified in this case, as it would have been specified when the environment was first pulled.
```

**Comment by ghudgins** [comment]
this PR will fix the man page: https://github.com/flox/flox/pull/1300

I believe we can close once #1300 merges as we now print this error:

```
❌ ERROR: An environment already exists at "/Users/ghudgins/floxwebsite/.flox". Use --force to overwrite.
```
and `--force` can be used to do this smoothly

**Comment by ghudgins** [comment]
@stahnma - reopen if you disagree. #1300 is in for docs
