### ISSUE TITLE
docs: custom-packages tutorial in floxdev.com not mention setting meta.mainProgram

### ISSUE THREAD

**Issue by networkhermit** [flox/flox#11]
The official tutorial in https://floxdev.com/docs/custom-packages/#flox-init doesn't mention adding `meta.mainProgram = "hello";` to `pkgs/hello-python/default.nix`, and running `flox run` after `flox init` will cause error:

```text
error: unable to execute '/nix/store/ixilvrv0xy7gdilj4swg3sgq1xlji5rx-python3.10-hello-python-0.0.0/bin/hello-python': No such
 file or directory
```

**Comment by aakropotkin** [comment]
Thanks for the report. I'll get this fixed in the documentation.
