### ISSUE TITLE
flox activate without an environment should prompt to 'flox init'

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1104]
# Acceptance Criteria

**Given** I am in a dir without a .flox
**When** I `flox activate` 
**Then** I see a message

```
❌ ERROR: Did not find an environment in the current directory.
Run 'flox init' to create an environment.
```

**Comment by rchatrath7** [comment]
hi @ghudgins can I take this on? seems like just a copy change but seems like a good way to get comfortable with building and running the repo :)

**Comment by ghudgins** [comment]
that would be wonderful! @rchatrath7
