### ISSUE TITLE
Search for strings with spaces appears to maybe not work?

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1109]
**Describe the bug:**

I am unable to find the `artem` package when searching for "ASCII art"

**Steps to reproduce:**
1.  Search for something in the description. `flox search "ASCII art"
2. Note that it returns nothing. 
3. Search for `art` and you see the `artem` project.

Result: 

I can't find the package searching by the exact string found in the description.

Expected: 

It searches the description and find that package (or any others that have ASCII art in the description). 

**Screenshots/terminal output (if relevant):**

![floxbox01_and_New_Issue_·_flox_flox](https://github.com/flox/flox/assets/6961/18c537fa-0e2d-4638-b916-c2653d59a8b6)

** flox Version (run `flox --version` if possible): **

Version: 0.9.0

**Comment by mkenigs** [comment]
This was a deliberate change because we were getting too many search results. If you use a feature flagged search strategy it works. Closing now but if @ghudgins wants to change it we can reopen
```
FLOX_FEATURES_SEARCH_STRATEGY=match flox search "A small CLI program to convert images to ASCII art"
artem  A small CLI program to convert images to ASCII art

Use 'flox show <package>' to see available versions
```
