### ISSUE TITLE
Shorten prompts where possible

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1116]
Related to https://github.com/flox/flox/issues/1100

That ticket is specifically about shortening environment names where possible. This ticket suggests that we shorten the other text in the prompt as well.

If you run `flox list` with more than one environment active, you see the following prompt:
```text
! Do you want to list using the current environment's flox environment or the active flox environment?
> current directory's flox environment [<name> at <path>]
  current active environment [<name> at <path>]
```
When the names and paths are long, this becomes very wordy (ignore that the command was `floxdev list`, this is a local alias of mine):
<img width="1028" alt="Screenshot 2024-03-03 at 8 24 07 PM" src="https://github.com/flox/flox/assets/10246891/f72d8658-ff47-43ee-8c6a-74ebb23e8107">

A more concise prompt would look like this:
```
$ flox list
! Which environment?
> Current directory (<name>)
  Current active environment (<name>)
```

This prompt removes the following information:
- choices in the question: the question is implied by which command the user just ran, and the choices are listed in the options below
- `flox environment`: the user just ran a `flox` command and don't need to be reminded 3 times that they're operating on Flox environments
- `<path>`: this is extra information that's unlikely to help a user make their decision

**Acceptance criteria:**
- Any prompt that asks the user to choose between environments should use the more concise prompt above (noting the change in capitalization of `current` as well)

**Comment by ghudgins** [comment]
verified what I could!
