### ISSUE TITLE
Capitalize Flox in macos installer

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#1169]
Capitalize Flox everywhere in the Flox macos installer. Hopefully changing it one place will propagate, but these are the places I can see:
* Install flox
* Welcome to the flox installer
* Installing flox

<img width="617" alt="image" src="https://github.com/flox/flox/assets/2687382/614fe287-e973-405d-85e1-e75c792ab425">

<img width="459" alt="image" src="https://github.com/flox/flox/assets/2687382/b9c8ae11-3700-43c9-bcb9-35061d40cdb7">

**Comment by ghudgins** [comment]
related discussion

**Comment by ghudgins** [comment]
@tomberek I know we discussed this already but I think I made the wrong call. Can we go ahead and put some F's in the installer?

**Comment by robinbrantley** [comment]
@ghudgins - I just asked Tom in spatial and he said no, it won't make it this time.

**Comment by ghudgins** [comment]
was just asking for a change in the future, definitely not an urgent thing!
