### ISSUE TITLE
Difference between similar projects like devenv?

### ISSUE THREAD

**Issue by skurfuerst** [flox/flox#117]
Hey,

i was wondering what this project does differently than devenv.sh or devbox?

thanks and all the best,
Sebastian

**Comment by ghudgins** [comment]
hi and thanks for reaching out. there is some functional overlap today but our vision for `flox` will ultimately reach across more than the developer environment. we want to bring the power of nix to all aspects of the SDLC--developer environments, building (without having to build twice), sharing, enterprise managed environments, scanning SBOMs for security, and more. if you have more questions, re-open or reach out (`graham@floxdev.com`)

**Comment by skurfuerst** [comment]
Thanks for explaining :):) all the best!
