### ISSUE TITLE
flox panics when it tries to write to a broken pipe

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1193]
STR:
```
> flox activate --print-script | false
thread 'main' panicked at library/std/src/io/stdio.rs:1019:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Expected:
A nice error, but not a panic

This isn't a big deal, because the panic makes it pretty clear what happened. But we could use `writeln!(std::io::stdout(), ...)?` instead of `println!(...)` if we want to handle these a little more gracefully.

**Comment by zmitchell** [comment]
All that's needed is a single function call at the start of the program: https://github.com/kurtbuilds/sigpipe
