### ISSUE TITLE
Flox search, install, and show by multiple versions

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1197]
## Motivation

_Find old versions_

* **When** I need to find older versions of packages
* **I need** a catalog of nixpkgs revisions over time
* **So I can** search and install from them with flox

_Find fresh versions_

* **When** I need to update my software to use the latest version of software
* **I need** a catalog that has fresh nixpkgs revisions that I can upgrade to
* **So I can** avoid security vulnerabilities and gain performance benefits of updated software

## Acceptance Criteria

**When** I `flox show terraform`
**Then** I see multiple versions available (not just 1.6.4+)
**And When** I `flox install` an old version of Terraform
**And** I `flox activate`
**Then** I see I have the correct older versoion of software
**And When** I `flox edit` and remove the version requirement
**Then** I see terraform is upgraded

Full product requirements: https://github.com/flox/product/blob/main/specifications/catalog-service-release.md
This is a tracking ticket for the epic

**Comment by ghudgins** [comment]
related discourse post - https://discourse.flox.dev/t/installing-older-version-of-package-than-available/757/8

**Comment by PierreBeucher** [comment]
Hi there, I understand this issue is linked to multi-channel support so that not only 23.11 will be supported, am i right? 

Eg. from doc:

> The Flox Catalog is currently tracking version 23.11 of [nixpkgs](https://github.com/NixOS/nixpkgs). Flox has immediate term plans to add support for more versions.

It would be very nice to see this feature coming as some packages version of 23.11 are 6+ months old, quite some time in the software world.

**Comment by ghudgins** [comment]
correct! we'll be doing ~daily updates to available software from unstable. this is very much in the works currently

**Comment by y3lousso** [comment]
Up 😀 
I would like to access vault 16, but it's only available in nixpkg channel 24.05.

Any ETA on when the catalog selection feature will be available on Flox ?

**Comment by ghudgins** [comment]
we're targeting next week for the release

**Comment by ghudgins** [comment]
this will be released with 1.1. if you want to try a RC, here you go!

[DEB (x86_64-linux)](https://downloads.flox.dev/by-env/stable/deb/flox-1.1.0.x86_64-linux.deb)
[DEB (aarch64-linux)](https://downloads.flox.dev/by-env/stable/deb/flox-1.1.0.aarch64-linux.deb)
[RPM (x86_64-linux)](https://downloads.flox.dev/by-env/stable/rpm/flox-1.1.0.x86_64-linux.rpm)
[RPM (aarch64-linux)](https://downloads.flox.dev/by-env/stable/rpm/flox-1.1.0.aarch64-linux.rpm)
[OSX (x86_64-darwin)](https://downloads.flox.dev/by-env/stable/osx/flox-1.1.0.x86_64-darwin.pkg)
[OSX (aarch64-darwin)](https://downloads.flox.dev/by-env/stable/osx/flox-1.1.0.aarch64-darwin.pkg)

closing the issue 🎉

**Comment by etorreborre** [comment]
Hi @ghudgins, I tried to download from the links above but nothing seems to be available.

**Comment by ghudgins** [comment]
🤦 I put the wrong links. edited!
