### ISSUE TITLE
feat: use ~/.local/share/flox/meta to store floxmeta git repos

### ISSUE THREAD

**Issue by networkhermit** [flox/flox#12]
Currently floxmeta environments are stored in ~/.cache/flox/meta, if users accidentally clear the ~/.cache directory then flox environments would be broken and in some cases cannot be easily restored.

Important data should not be placed in ~/.cache directory and it's reasonable to store floxmeta repos alongside ~/.local/share/flox/environments:

https://askubuntu.com/questions/102046/is-it-okay-to-delete-the-cache-folder
https://bbs.archlinux.org/viewtopic.php?id=273652

**Comment by aakropotkin** [comment]
Hey thanks for this report, it's definitely appreciated.
This seems like a sensible change to avoid accidentally losing work, particularly if automatic cache cleanup runs on a machine.
I'm gathering a few engineers to discuss this recommendation.

**Comment by aakropotkin** [comment]
After discussing rationale with the folks who developed the environments I think I can help demystify things a bit.

When things were being designed both `XDG_DATA_HOME` ( `~/.local/share/flox` ) and `XDG_CACHE_HOME` ( `~/.cache/flox` ) were considered, and these files were intentionally chosen to be cached files that are routinely cleaned. The rationale being that "an upstream `git` repository should be the source of truth", and that "the local caches can be safely wiped and regenerated from the upstream repo". These decisions intend to discourage using a local `git` repository which can't be pushed to or pulled from as a "source of truth".

Having said that, and given the context of the "intended usage", you are able to use a local `git` repository that isn't pushed to a remote by setting the environment variable `FLOX_META="${XDG_DATA_HOME:-$HOME/.local/share}/flox/meta";` ( or any other path ) to move the `meta` directory to an alternative location. If you would like to move all cached `flox` files to an alternative location you could instead set `FLOX_CACHE_HOME="$HOME/.flox-cache";` ( which, assuming `FLOX_META` is unset, would also move the `meta` files ).

Hopefully this helps, let me know if you have any follow up questions.

**Comment by aakropotkin** [comment]
I'm going to go ahead and close this, but if you have any follow up questions please feel  free to reopen.

**Comment by networkhermit** [comment]
While I do understand your rationale and intent of choosing XDG_CACHE_HOME, I still think it is a hidden trap:

1. For those who only use local floxmeta repo, environments declaration would be lost and all they have is good luck.
2. For those who pull floxmeta from upstream git repo, extra steps need to taken to regenerate the local environments if the ~/.cache got cleared.
3. For those who pull floxmeta from upstream git repo but forget to commit the local modification in time, changes would be lost and the developer got confused.

I believe excellent developer tooling shoud be frictionless as much as possible and just works, but if you really want to use the XDG_CACHE_HOME, please document the caveats and display a big red warning in flox-cli as long as local repo have uncommited changes. 

P.S.

If you create a crontab to routinely clean the ~/.cache at midnight and the flox-cli workflow not affected by a bit, then it is beyond good design.

**Comment by aakropotkin** [comment]
I agree with this recommendation, thank you for sharing it.

We're rolling this anecdote and use case into our product development discussions.
