### ISSUE TITLE
flox telemetry only sends on debug

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1202]
STR:
* do a bunch of flox commands (`flox init`, `flox activate`, etc)
* do `_FLOX_FORCE_FLUSH_METRICS=1 flox list -vvv`

Result: you only see the telemetry from `flox list`
Expected: you see a larger block of JSON for all the transactions

We are only sending telemetry on debug now.

**Comment by ysndr** [comment]
telemetry traces appear to get filtered by the log filter.
Which is frustratig as the log filter is explicitly set up to only filter events of the logger and requires some research why it also affects the following layers.

The effect of this is that metric traces are only recorded if the log level for `flox` is >= trace, i.e. >= 3 -v

**Comment by ghudgins** [comment]
might be good to knock out https://github.com/flox/product/issues/632 when doing this

**Comment by ghudgins** [comment]
@garbas can we confirm we can have this for the release cutoff?

**Comment by garbas** [comment]
> @garbas can we confirm we can have this for the release cutoff?

Yes, I made it sure we have it :)
