### ISSUE TITLE
Flox pull --force also can overwrite the environment itself

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1205]
STR:

* `flox pull ghudgins/default`
* `flox pull ghudgins/default --force` 

Expected: it pulls regardless of the .flox that's there
Actual: "❌ ERROR: Cannot pull a new environment into an existing one"

**Comment by charmitro** [comment]
Hi, this seems like a good opportunity for something to get familiar with the codebase. Could someone assign the issue to me?

**Comment by ghudgins** [comment]
LGTM
