### ISSUE TITLE
flox init reads go.mod and suggests installation/config

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1209]
# Acceptance Criteria

**Given** the project has `go.mod` file
**And** i'm in the project directory
**When** I `flox init`
**Then** I see an interactive prompt

```
Flox detected a go.mod

Go projects typically need:
* Go
* A shell hook to apply environment variables

Would you like Flox to apply the standard Go environment? 
You can always revisit the environment's declaration with 'flox edit'

>Yes 
No
Show environment manifest

```

# Details

Suggested installs

```
go
```

Suggested shell hook
```
[profile]
common = """
export GOENV="$FLOX_ENV_CACHE/goenv"
"""
```

**Comment by ghudgins** [comment]
related discourse post: https://discourse.flox.dev/t/flox-installed-go-uses-the-global-go-enviornment-is-this-expected/855/4

**Comment by oxcabe** [comment]
I'll be working on this one here in my fork: https://github.com/oxcabe/flox/tree/feat/commands/init-go
