### ISSUE TITLE
config to disable flox prompt globally or for default environments

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1213]
## Motivation

_Don't show me Flox's prompt for the default env_
**When** I am using Flox in my RC file
**I need** to suppress the `ghudgins/default` part of the Flox prompt
**So I can** reclaim valuable space for my project names in the Flox prompt

_Don't show me Flox's prompt_
**When** I have a beautiful prompt ✨ 
**I need** Flox's prompt to never show 
**So I can** shine on without Flox and incorporate what I want to using Flox's environment variables myself

## Acceptance Criteria

_Design not needed? Implementer's choice to some extent?_

A config option `shell_prompt` that has 3 values:
* `hide-default` - A config option that lets me suppress the Flox prompt for default environments
* `hide-all` A config option that lets me totally suppress the Flox prompt
* `show-all` - A config option that reflects today's behavior (always show)

**Comment by eikenb** [comment]
@ghudgins that duplicate link is a 404.

**Comment by oxcabe** [comment]
It probably exists but is internal to members of the org.

**Comment by ghudgins** [comment]
ah, good catch. will keep this open as we work on a solution concept and post here instead

**Comment by ghudgins** [comment]
resolved by https://github.com/flox/flox/commit/19d2599a719809a3672d01d43fb612104159e77d
