### ISSUE TITLE
flox activate closes when command fails

### ISSUE THREAD

**Issue by xy2i** [flox/flox#1214]
**Describe the bug:**
When doing `flox activate`then running a command that fails, I get ejected out of the shell. For example this can happen when a `npm` invocation fails or so on. I'd like to stay in the shell instead

**Steps to reproduce:**
1. flox activate
2. Run a command that fails, like `false`

Result: Flox environment closes and I get ejected out

Expected: Should stay in flox environment

**Screenshots/terminal output (if relevant):**
<img width="537" alt="Screenshot 2024-03-22 at 18 37 01" src="https://github.com/flox/flox/assets/14931040/49c95fbf-b2f3-43a5-80a5-4788d88f7fea">

** flox Version (run `flox --version` if possible): ** 1.0.1

** `uname -a` output: ** Darwin xys-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:45:49 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6020 arm64

**Comment by ghudgins** [comment]
can you share the contents of your manifest `flox list -c` 

I don't get the same behavior on ubuntu
<img width="692" alt="image" src="https://github.com/flox/flox/assets/5465514/91bbd638-1e84-47f5-ba53-147ffdb5ee1b">

**Comment by xy2i** [comment]
Found the issue, I had set in  my manifest.toml `[hook]` section:

```sh
set -euo pipefail
```

which was causing any fail to exit the shell
