### ISSUE TITLE
`flox pull --copy` pull without making remote  

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#1226]
When Flox users share environments to FloxHub, the default behavior is to convert their local environment to a remote environment, with a remote link and a generation lock. As an an alternative to this default behavior, we will support the ability to **pull without making remote** AND **convert remote to local**.

## User Scenario
**Pull without making remote:** The user wants to start a new environment based on an existing environment, without keeping any connection to the original remote environment. 

**Convert remote to local:** The user has pushed a flox environment to FloxHub, but does not want it to be linked to the remote FloxHub environment. They want to convert the remote environment to a local environment. 

## Acceptance Criteria
**Given** I am in a directory without a .flox
**When** I `flox pull --copy`
**Then** I have a local .flox directory with the manifest, but no link to the remote env
**And** I see a message
```
✨ Created path environment from owner/envname

You can activate this environment with 'flox activate'
```

**Given** I am in a directory with a Flox environment that I have pushed to FloxHub
**When** I `flox pull --copy`
**Then** I have a local .flox directory with the manifest, but no link to the remote env
**And** I see a message
```
✨ Created path environment from owner/envname

You can activate this environment with 'flox activate'
```
 
**When** I `man flox pull` or `flox pull --help`
**Then** I see help content for the `--copy` option

**Comment by ghudgins** [comment]
@ysndr can you add estimates
