### ISSUE TITLE
Installation fails on MacOS

### ISSUE THREAD

**Issue by r4mp** [flox/flox#1230]
**Describe the bug:**

When I try to install flox 1.0.1, I only get the message "Installation failed". Is there any way to get more information about the underlying problem?

**Steps to reproduce:**
1. run installer (same problem via GUI and CLI)

Result:

```
❯ sudo installer -pkg flox-1.0.1.aarch64-darwin.pkg -target / -verbose
Password:
installer: Package name is flox
installer: Installing at base path /
installer: Preparing for installation….....
installer: Preparing the disk….....
installer: Preparing flox….....
installer: Waiting for other installations to complete….....
installer: Configuring the installation….....
installer:
#
installer: Running package scripts….....
#
installer: Running package scripts….....
installer: Validating packages….....
#
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “flox-1.0.1.aarch64-darwin.pkg”.)
```

** flox Version (run `flox --version` if possible): **

1.0.1

** `uname -a` output: **

Darwin xxxxxx 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103 arm64

**Comment by ghudgins** [comment]
if you are comfortable, do you mind sending us the Flox snippet of the `/var/log/install.log` file that pertains to this installation? if you don't want to post here feel free to email it to me at graham@flox.dev

**Comment by r4mp** [comment]
Thanks, I forgot to read the `/var/log/install.log` file first 🤦🏻‍♂️
The problem resulted from these old `-before-nix` files. After I deleted them, everything works fine. Thank you very much!

```
❯ ls -alhtr /etc/*before-nix*
-r--r--r--  1 root  wheel   265B Jan 20  2023 /etc/bashrc.backup-before-nix
-r--r--r--  1 root  wheel   3.0K Jan 20  2023 /etc/zshrc.backup-before-nix
-r--r--r--  1 root  wheel   3.0K Mar 21 07:13 /etc/zshrc.before-nix-darwin
-r--r--r--  1 root  wheel   255B Mar 21 07:13 /etc/zprofile.before-nix-darwin
-r--r--r--  1 root  wheel   265B Mar 21 07:13 /etc/bashrc.before-nix-darwin
```
