### ISSUE TITLE
Installing RPM gives a warning on Fedora 39

### ISSUE THREAD

**Issue by sschuberth** [flox/flox#1255]
**Describe the bug:**

Installing the RPM as [documented](https://flox.dev/docs/install-flox/#__tabbed_1_2) gives a warning on Fedora 39 (KDE).

**Steps to reproduce:**

1. Download https://downloads.flox.dev/by-env/stable/rpm/flox-1.0.2.x86_64-linux.rpm
2. Run `sudo rpm -i ~/Downloads/flox-1.0.2.x86_64-linux.rpm`

Result:

    warning: /home/sebastian/Downloads/flox-1.0.2.x86_64-linux.rpm: Header V4 EdDSA/SHA512 Signature, key ID 51c22269: NOKEY

Expected:

No warning should be caused.

**flox Version (run `flox --version` if possible):** `Version: 1.0.2`

**`uname -a` output:** `Linux fedora.fritz.box 6.7.10-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 18 18:56:52 UTC 2024 x86_64 GNU/Linux`

**Comment by mkenigs** [comment]
I believe that error is happening because our RPM is signed, but you haven't imported the key. The warning should go away with `rpm --import https://downloads.flox.dev/by-env/stable/deb/flox-archive-keyring.asc`. We should add that to our docs.

**Comment by stahnma** [comment]
We should add key imports into our docs and test suite.

**Comment by stahnma** [comment]
This fix is in and will be available in the release currently scheduled for April 30 I believe.
