### ISSUE TITLE
`flox --version` should omit the "Version: " prefix from its output

### ISSUE THREAD

**Issue by sschuberth** [flox/flox#1256]
**Describe the bug:**

Running `flox --version` contains a "Version: " prefix as part of its output. However, for easier consumption / version comparison, the "Version: " prefix should be omitted. Also, it's clear that a version is shown as a version was requested.

**Steps to reproduce:**

1. Run `flox --version`

Result:

`Version: 1.0.2`

Expected:

`1.0.2`

**flox Version (run `flox --version` if possible):** `Version: 1.0.2`

**`uname -a` output:** `Linux fedora.fritz.box 6.7.10-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 18 18:56:52 UTC 2024 x86_64 GNU/Linux`

**Comment by sschuberth** [comment]
> is this coming from a standard?

I'm not aware of any.

> I don't really see any consistent pattern when checking commonly used CLIs.

Me neither, but I'm often in the situation of parsing `<tool> --version` output, and am always annoyed if some extra transformation on the string is required to just get the version 😉

**Comment by ghudgins** [comment]
good enough reason for me!
