### ISSUE TITLE
[cli] `InitHook` trait must represent a different type state in order to invalidate subsequent `should_run` calls

### ISSUE THREAD

**Issue by oxcabe** [flox/flox#1266]
## Description
The `InitHook` trait has a `should_run` method that, by design, is supposed to only be executed once and before any other trait method does for the cases where it returns `true`.

https://github.com/flox/flox/blob/f915e3b1458156ba6e54cea6cf79896f16798dfa/cli/flox/src/commands/init/python.rs#L47-L52

Currently, the type system is not aware of this condition, and developers may add valid, compiling code that reaches invalid states.

## Proposed solution

My proposed solution would be to compose `InitHook` by defining `Uninitialized` and `Initialized`  traits that are exclusive and define the corresponding functionality separately.

## Original context
              Yes, this is a known limitation, which when ignored leads to unreachable/panic blocks which is not ideal, but ok, since its currently rather internal.
I wouldn't stress refactoring that here but would welcome a follow up discussion.

_Originally posted by @ysndr in https://github.com/flox/flox/pull/1227#discussion_r1547743764_

**Comment by mkenigs** [comment]
> My proposed solution would be to compose `InitHook` by defining `Uninitialized` and `Initialized` traits that are exclusive and define the corresponding functionality separately.

I think that could work, but I wonder if it would be simpler to just drop `should_run` entirely and change `new() -> Result<Self>` -> `_some_better_name_() -> Result<Option<Self>>`. Are there any cases that wouldn't work for?

**Comment by oxcabe** [comment]
It's simpler and it could work exactly the same. We also avoid adding unnecessary types.
