### ISSUE TITLE
install package from flake in Flox manifest

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1267]
### Motivation

**When** Flox is missing software packaged correctly for my application (or just missing software)
**I need** to express my package / package group as a flake
**So I can** extend Flox with nixlang 
**And** get working software

### Acceptance Criteria

_flake stored in github_
**Given** I have a flake.nix that has package outputs in github
**When** I `flox edit`
**And** add the following lines in the install section

```
[install.tiny]
    flake = "github:someuser/somerepo#tiny"
```

**Then** I see my environment build 
**And When** I `flox activate`
**Then** tiny's packages are available

_flake stored in a file errors out (for now, can always revisit)_
**Given** I have a flake.nix that has package outputs in github
**When** I`flox install .#tiny`
**Then** I see an error `❌ ERROR: flake must be hosted in a remote code repository.` 

_flake installation in flox install_
**Given** I have a flake.nix that has package outputs in github
**When** I`flox install github:someuser/somerepo#tiny`
**Then** I see a package with the id of `tiny` is installed and configured with a flake in my manifest

_flox list shows as much as is easy to get without too much effort_
**Given** I have a flake.nix that has package outputs in github
**And** I`flox install github:someuser/somerepo#tiny`
**When** I `flox list --all` that environment
**Then** I see as much information as is available...

```
tiny: (tiny)
  Description: repo description
  Path:     tiny
  Priority: 5
  Version:  1.2.3 version
  License:  GPL
  Unfree:   false
  Broken:   false
```

_flox upgrade impact_
**Given** I have a flake.nix that has package outputs in github
**And** I have installed this to my flox environment at revision `3ef`
**When** flake.nix in github advances to a new revision `4ef`
**And** I `flox upgrade`
**Then** I see `4ef` in my lockfile 
**And** I have the latest

_flox install -h_
**When** I `flox install -h`
**Then** I don't see a flake mention
**And When** I `man flox-install`
**Then** I see a flake documentation

_flox search and show_ 
**Given** I have a flake.nix that has package outputs in github 
**And** I have installed this to my flox environment `flox install github:someuser/somerepo#tiny`
**When** I `flox search tiny`
**Then** I **do not see** the flake in search results
**And When** I `flox show tiny`
**Then** I **do not see** the flake in show results 

_you can refer to a specific revision of a flake_
...

questions to answer:
* [x] what happens if I `flox push`, how to check the expression is in the .flox and add / scan to FloxHub? A: only support remote flakes
* [x] do we need a 'runtime mode' first? A: no
* [x] do we have to ship install by storepath with this? A: we'll write TODOs and create a follow-on issue

**Comment by matifali** [comment]
Is it possible to create an initial manifest.yaml from a flake.nix?
This will help migrate from using flake.nix to flox.

**Comment by mkenigs** [comment]
> Is it possible to create an initial manifest.yaml from a flake.nix? This will help migrate from using flake.nix to flox.

Currently that's an entirely manual process. When we add this feature (which is essentially to allow importing flakes), we could try to take that use case into consideration, but conversion would be lossy, so I'm not sure trying to do conversion will make sense once importing works.

**Comment by mkenigs** [comment]
nit: `.` is a flakeref, and `github:someuser/somerepo#tiny` is a flake output attribute. `install.foo` could also just be written as `.#foo` for consistency

**Comment by mkenigs** [comment]
Can you edit a `.flox/flake.nix` for a remote environment?

**Comment by mkenigs** [comment]
>     * [ ]  is this more than one issue?

At least from an engineering perspective, I think it makes the most sense to do remote flakerefs first, and bundled flakes second

**Comment by limeytexan** [comment]
I agree with @mkenigs that we're already requiring the user to understand flakeref syntax for the "github:someuser/somerepo#tiny" example, so I don't see why we wouldn't similarly expect the user to exercise that same syntax for ".#foo".

**Comment by ghudgins** [comment]
>I think it makes the most sense to do remote flakerefs first, and bundled flakes second

editing AC to split the bundled one out

>Can you edit a .flox/flake.nix for a remote environment? An environment that's been pulled? (I guess maybe that's what pull --copy would be for?)

Will answer this in the new issue 

>I don't see why we wouldn't similarly expect the user to exercise that same syntax for ".#foo".

will update

**Comment by mkenigs** [comment]
I dislike the `[install.#tiny]` syntax lol

**Comment by ghudgins** [comment]
fixed

**Comment by ysndr** [comment]
further breakdown:

- [ ] support for flakerefs in manifest.toml (already being worked on in https://github.com/flox/flox/pull/1630)
	- **[est. 2]** but parts already done
- [ ] support for flakerefs in manifest.lock
	- flakeref variant of locked packages?
	  generally a locked package already contains flake information where the flake is nixpkgs
      the lockfile schema might thus already support flake outputs unless we need more specific
      structure.
	- during lock: deny flakerefs to local paths, e.g. `..#`
	  could use runix flakeref parsers, or url with some heuristics (no scheme, [git+]file or path scheme)
    - lock flake descriptors separately 
  	  ```
  	  nix flake metadata --json <descriptor.flake> | jq '.url, .revision, .last_modified, .rev_count'
  	  nix eval .#flox --apply 'drv: { 
	      inherit (drv) version name meta drvPath;
	      out-path = drv.outPath;
	      outputs = builtins.listToAttrs 
	  		(map (output: {name = output; value = drv.${output}.outPath;}) drv.outputs);
	  }' --json
	  ```
	  The latter will basically always be faster on multiple runs if its implemented as a pkgdb function rather than inline due to the possibility of using the eval cache.
      Alternatively multiple nix calls  extracting attributes one by one would also be effective but have a linear overhead.
	- **[est. 2-3]** if we keep nix calls low level and push optimization down the road
	- needs additional unit tests for flakerefs
- [ ] allow building of arbitrary flakerefs
	- pkgdb buildenv currently requires the built flakeref to start with github:flox/nixpkgs for historical reasons around denying broken packages etc.
	  Today this is mostly an artificial limitation that we need to rework.
	- **[est. 2-3]**
- [ ] install by flakeref
	- amend `PackageToInstall` to an enum with a variant for flakes
	- amend adding `manifest::insert_package` to understand flake targets as well
	- **[est. 2]**

**Comment by mkenigs** [comment]
> further breakdown:
> 
>     * [ ]  support for flakerefs in manifest.toml (already being worked on in [refactor: add collective type for descriptor variants #1630](https://github.com/flox/flox/pull/1630))
>       
>       * **[est. 2]** but parts already done
> 
>     * [ ]  support for flakerefs in manifest.lock
>       
>       * flakeref variant of locked packages?
>         generally a locked package already contains flake information where the flake is nixpkgs
>         the lockfile schema might thus already support flake outputs unless we need more specific
>         structure.
>       * during lock: deny flakerefs to local paths, e.g. `..#`
>         could use runix flakeref parsers, or url with some heuristics (no scheme, [git+]file or path scheme)
>       * lock flake descriptors separately
>         ```
>         nix flake metadata --json <descriptor.flake> | jq '.url, .revision, .last_modified, .rev_count'
>         nix eval .#flox --apply 'drv: { 
>             inherit (drv) version name meta drvPath;
>             out-path = drv.outPath;
>             outputs = builtins.listToAttrs 
>         		(map (output: {name = output; value = drv.${output}.outPath;}) drv.outputs);
>         }' --json
>         ```
>         
>         
>             
>               
>             
>         
>               
>             
>         
>             
>           
>         The latter will basically always be faster on multiple runs if its implemented as a pkgdb function rather than inline due to the possibility of using the eval cache.
>         Alternatively multiple nix calls  extracting attributes one by one would also be effective but have a linear overhead.
>       * **[est. 2-3]** if we keep nix calls low level and push optimization down the road
>       * needs additional unit tests for flakerefs
> 
>     * [ ]  allow building of arbitrary flakerefs
>       
>       * pkgdb buildenv currently requires the built flakeref to start with github:flox/nixpkgs for historical reasons around denying broken packages etc.
>         Today this is mostly an artificial limitation that we need to rework.
>       * **[est. 2-3]**
> 
>     * [ ]  install by flakeref
>       
>       * amend `PackageToInstall` to an enum with a variant for flakes
>       * amend adding `manifest::insert_package` to understand flake targets as well
>       * **[est. 2]**

We also need upgrade

**Comment by mkenigs** [comment]
>       * during lock: deny flakerefs to local paths, e.g. `..#`
>         could use runix flakeref parsers, or url with some heuristics (no scheme, [git+]file or path scheme)

We can also get that with `nix flake metadata <flake> --json | jq .locked.type`

**Comment by mkenigs** [comment]
>       * lock flake descriptors separately
>         ```
>         nix flake metadata --json <descriptor.flake> | jq '.url, .revision, .last_modified, .rev_count'
>         nix eval .#flox --apply 'drv: { 
>             inherit (drv) version name meta drvPath;
>             out-path = drv.outPath;
>             outputs = builtins.listToAttrs 
>         		(map (output: {name = output; value = drv.${output}.outPath;}) drv.outputs);
>         }' --json
>         ```

We hardcode `legacyPackages` for catalog packages:
https://github.com/flox/flox/blob/d8934858dda27a534371529287dfb02484421c75/pkgdb/src/resolver/lockfile.cc#L458

We can't do that for flakes. So we'll need to add `flake_attr_path` or something to the lockfile. This was stored as `attr_path` in version 0 lockfiles, but we've since changed terminology.

To lock `flake_attr_path`, we need to check for packages in both `packages` and `legacyPackages`, re-implementing something similar to https://github.com/NixOS/nix/blob/f809edba4feb0293768815bce362c5b8993d6335/src/libcmd/installable-flake.cc#L28 and https://github.com/NixOS/nix/blob/f809edba4feb0293768815bce362c5b8993d6335/src/libcmd/installable-flake.cc#L186.

If we're locking all 4 systems, that means best case we have to do 4 evals. If we handle when attribute paths exist for some systems in `packages` but only in `legacyPackages` for others, we'd have to do 8 evals (that's a super edge case, so 4 evals is probably a better estimate).

After a prior evaluation, running
```
for system in aarch64-darwin x86_64-darwin aarch64-linux x86_64-linux; do
  nix eval "github:flox/flox/d8934858dda27a534371529287dfb02484421c75#packages.$system.flox" --json
done
```
averages about 19 seconds (I did 4 runs), whereas

`nix eval /path/to/flake#json --json` with `flake.nix`:
```
{
  inputs.flox.url = github:flox/flox/d8934858dda27a534371529287dfb02484421c75;

  outputs = {
    self,
    flox,
  }:
  {
    json =  {
      aarch64-darwin = flox.packages.aarch64-darwin.flox;
      x86_64-darwin = flox.packages.x86_64-darwin.flox;
      x86_64-linux = flox.packages.x86_64-linux.flox;
      aarch64-linux = flox.packages.aarch64-linux.flox;
    };
  };
}
```
averages about 17 seconds (I did 4 runs).

So it looks like overhead for the multiple evals is ~10%.

Interestingly, `nix eval` doesn't use the eval cache, so doing build:
```
for system in aarch64-darwin x86_64-darwin aarch64-linux x86_64-linux; do
  nix build "github:flox/flox/d8934858dda27a534371529287dfb02484421c75#packages.$system.flox" --json
done
```
only takes ~5 seconds 😆 So the overhead of not using the eval cache is ~200% 😬 

So I think we'd need to be careful to only eval when we really have to, patch `nix eval`, or use C++.

**Comment by mkenigs** [comment]
I tried with `--eval-cache` as well and that didn't seem to make a difference for `nix eval`. @tomberek am I holding it wrong? Or does `nix eval` actually not use the eval cache?

**Comment by ysndr** [comment]
`nix eval` is not using the eval at least for expressions no, thus my comment about using cpp to get a cursor and use that to evaluate packages.

**Comment by ghudgins** [comment]
given we're still working on a few things i'm re-opening

**Comment by ysndr** [comment]
are we still working?
i dont think so..

**Comment by ghudgins** [comment]
closing
