### ISSUE TITLE
Port manifest.toml schema to Rust

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1273]
- Port the C++ manifest schema to Rust except for package descriptors
- Define package descriptors in a way compatible with the API spec
- Add a version field

- If the catalog feature flag is false, pkgdb should parse the manifest as it does currently
- If the catalog feature flag is true, the Rust schema should handle the manifest
  - TODO: discuss what to do if the version field is not present. Probably print a message with how to translate your old manifest or a link to release notes or something?

**Comment by ysndr** [comment]
> If the catalog feature flag is false pkgdb should parse the manifest as it does currently

Does this imply we are converting a v2 manifest with catalog descriptors back to a pkgdb compatible manifest?

> Add a version fiel

are we adding a version field to the "old" format too? (Optional) And thus also to pkgdb?

> (from the spec): Each package descriptor may have the following keys:
> name (required): The name of the package. This is included in the response to correlate resolved package details with requested packages.

Are we making the same change in the manifest as well (i.e. define packages as a list) or keep with the map structure where name/id is the key of the descriptor?
I would assume the latter, even though that may mean we have to translate the `Map<id, descriptor>` to `Set<DescriptorWithName>` somewhere -- we might need that anyway to add individual broken/unfree attributes.

**Comment by mkenigs** [comment]
> > If the catalog feature flag is false pkgdb should parse the manifest as it does currently
> 
> Does this imply we are converting a v2 manifest with catalog descriptors back to a pkgdb compatible manifest?


I don't think we need to since you can only generate a v2 manifest with the feature flag enabled

> > Add a version fiel
> 
> are we adding a version field to the "old" format too? (Optional) And thus also to pkgdb?

I don't think we need to
> 
> > (from the spec): Each package descriptor may have the following keys:
> > name (required): The name of the package. This is included in the response to correlate resolved package details with requested packages.
> 
> Are we making the same change in the manifest as well (i.e. define packages as a list) or keep with the map structure where name/id is the key of the descriptor? I would assume the latter, even though that may mean we have to translate the `Map<id, descriptor>` to `Set<DescriptorWithName>` somewhere -- we might need that anyway to add individual broken/unfree attributes.

I think we should preserve the manifest format

> 
> > derivation: A specific derivation path.
> 
> Is this exposed in the manifest?

Nope

> 
> > Port the C++ manifest schema to Rust except for package descriptors
> 
>     * Are we dropping the `registry` and `env-base` tables?
> 
>     * are we keeping `activation-strategy` and `package-grouping-strategy`? if we keep them, we should assign a default value to them (rather than being a plain string with arbitrary value)

I think we can drop all of those for now

**Comment by zmitchell** [comment]
Can we close this?

**Comment by mkenigs** [comment]
You had said you wanted to review it. And I think you had some proptesting stuff you had done. But otherwise yes we can close
