### ISSUE TITLE
Add manifest.lock schema in Rust

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1274]
Add a schema containing:
- A manifest.toml
- Either a list of locked package groups or a list of package details, which should ideally just be from the shim around autogenerated catalog client code
	- Currently a list of locked PackageGroups but likely to be refactored to a list of packages
- A version

Handled in https://github.com/flox/flox/issues/1284
- ~If the catalog feature flag is false, pkgdb should parse the lock as it does currently~
- ~If the catalog feature flag is true, the Rust schema should handle the lock~
  - ~TODO: discuss what to do if the version field is old. Print a warning that we're re-resolving?~

**Comment by ysndr** [comment]
@mkenigs does this issue mean to implement locking with the catalog service as well or just setting up the schema?
I'd at least split the implementation into two PRs and suggest to make it two issues

**Comment by mkenigs** [comment]
This is just the schema. Locking is in https://github.com/flox/flox/issues/1284
