### ISSUE TITLE
Create catalog testing client that returns static data

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1275]
- Add a trait, implement it for the catalog client, and create a test client that also implements it
- The test client should return static data for API requests
- Unit tests should be able to provide this static data as strings
- Add a feature flag that can be used for both manual and integration testing. The feature flag should point to either a JSON file or a directory
- The static data should contain an array of responses for each needed endpoints

**Comment by mkenigs** [comment]
@zmitchell @ysndr if you think we need a 3rd data source can you explain here?

**Comment by zmitchell** [comment]
I don't think we need a third data source

**Comment by stahnma** [comment]
@billlevine would the database you're using in the server work for this? (I also might be totally wrong)

**Comment by zmitchell** [comment]
I actively do not want a database involved in our CLI tests

**Comment by billlevine** [comment]
We can eventually have integration tests for the CLI that could use the pytest/db stuff I use on the service side to provide a 'live' service with deterministic yet real data.  Another thing we could do, primarily for convenience would be to scrape json responses from the service testing and save them as the start of a test corpus for the CLI.

Handcrafted static test data is fine, and would let us easily test the _known_ corner cases.  But as a supplement, the property based approach for integration tests could be very valuable.  I just added tests for the resolve endpoint which selects 2 to 15 real packages and calls the resolve endpoint.   We can provide real data for search/resolve/show at the CLI level.  Slow, but would be a good integration test, and probably find some additional corner cases.  That said, that's probably a third milestone task.

Happy to help on this when we're ready, but I agree, the first step would be basic unit tests with simple static data.
