### ISSUE TITLE
buildenv: update lock schema with catalog changes

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1283]
- Make any schema modifications based on what fields we add to package details in https://github.com/flox/flox/issues/1274
- Handle both the old schema version and the new version
- This ticket is just parsing the schema. Building it will be in https://github.com/flox/flox/issues/1358

**Comment by billlevine** [comment]
Naively going to take the approach of - 
- Updating `createFloxEnv()` to take the `LockfileRaw` to limit scope
- Rely on json parsing to extract the bits needed for buildenv into the existing (or slightly updated data structures), leaving the rest the same if possible.

**Comment by stahnma** [comment]
Can this be closed now?

**Comment by mkenigs** [comment]
Not yet, the merged PR was a prep PR
