### ISSUE TITLE
Feature flagged locking using mock data

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1284]
- Implement the catalog equivalent of `CoreEnvironment::lock`

The package group to which the package is being added will be resolved with as many constraints as can be successfully enforced.
Try to resolve the group with derivation-locked package descriptors.
If that fails, try to resolve the group with version-locked package descriptors.
If that fails, resolve with the original unlocked package descriptors.
In all cases, other package groups are not modified.

- Test locking using the testing client added in https://github.com/flox/flox/issues/1275
- (optional) if it's easy, when `_FLOX_USE_CATALOG_MOCK` is set to some path containing data for the `/resolve` endpoint and the `use_catalog` feature is set to true, `flox install $something` should install a package using the mock data

**Comment by ysndr** [comment]
@mkenigs wass there ore that you wanted done under thsi ticket?

my understanding is that

>Try to resolve the group with derivation-locked package descriptors.
> If that fails, try to resolve the group with version-locked package descriptors.
> If that fails, resolve with the original unlocked package descriptors.

will be handled by the server.

**Comment by mkenigs** [comment]
Yeah I think we can close. We still need to allow resolving to a page other than latest, but we can do that as followup
