### ISSUE TITLE
Create a local environment registry

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1287]
# Observations

- Path environments don't leave a record of their existence anywhere else on the system
- We currently use a directory of symlinks to point at directories that have had managed environments in them at some point in time
    - These symlinks may be left behind if a user deletes their `.flox` directory manually
    - These symlinks don't record information about which environment has actually been pulled into the target directory
- An environment that has been built creates a symlink that serves as a GC root for its store path

# Problem

- We would like a way to list all environments that the user has on their system, both path and managed.
    - We currently have no way of listing path environments short of searching the filesystem for `.flox` directories, which is infeasible.
- A user may `flox pull`, build the environment, manually delete the `.flox` directory, `flox pull` again, then build the environment again.
    - The two built environments leave GC roots behind, and it's unclear which one can be garbage collected without reading the environment pointer of the current managed environment.
- We need a way to know which environment metadata we can clean up.

# Approach

Keep a local environment registry as a JSON document with the following schema:
```text
{
  "version": <int>,
  "environments": [
    {
      "hash": <truncated hash(path)>,
      "path": "/path/to/env",
      "envs": [
        {
          "kind": "path" | "managed",
          "pointer": null | <env.json contents>,
          "created_at": <timestamp>
        },
        ...
      ]
    },
    ...  
  ]  
}
```

This file will be stored at `XDG_DATA_HOME/flox/env-registry.json`.
We will discontinue use of reverse links in `XDG_DATA_HOME/flox/links`.

This solution addresses the pull/build/delete/pull/build problem mentioned above by keeping a historical record of which environments existed at a particular path so that GC roots that contain the same hash can be easily identified as stale or not.

The `hash(path)` is the same scheme used today to name parts of the symlinks we currently use, but we will truncate the hash to **5** characters.
This make filenames shorter when viewed from `PATH`.

**Environment registration:**
- When an environment is opened, it checks for the presence of this file, attempts to acquire a filesystem lock on it (using available libraries) and creates the file if it doesn't yet exist.
- Once the file is opened, the environment checks whether the key for its path currently exists in the file.
    - The environment reads the `envs` key and checks that the object with the latest `created_at` time matches the same `kind` and `owner`/`name` if applicable.
    - If the latest object doesn't match, a new object is created with the appropriate metadata.
- Write the registry file to a temporary file, then `rename` it to the correct file
- Release the filesystem lock

**Listing environments:**
- Read the registry file
- For each object
    - Check whether the path still exists and matches the latest object in the `envs` section by `created_at` time.
    - Sort the list of known-good entries by `kind`

**Garbage collection:**
- Acquire the lock and read the file
- For each object
    - If path no longer exists, delete each GC root that contains the key for this object
    - If the path does exist, then for each object in `envs` except the most recent one
        - Delete the GC root
        - (enhancement) delete the FloxMeta branch that contains the `hash` value
        - Delete the object from the registry
- Write the registry file to a temporary file, then `rename` it to the correct file
- Release the filesystem lock

**Comment by zmitchell** [comment]
Note that this doesn't handle remote environments at all. That's a future enhancement as we need to decide whether recently activated remote environments belong in this list, how they should be garbage collected, etc.

**Comment by stahnma** [comment]
@zmitchell or @ysndr is there more to do on this ticket? It's in review and the only PR appears to be merged...but want to confirm.

**Comment by limeytexan** [comment]
> Note that this doesn't handle remote environments at all. That's a future enhancement as we need to decide whether recently activated remote environments belong in this list, how they should be garbage collected, etc.

We thought about this with Flox V1 & V2, and the conclusion there was to age out (i.e. delete) symlinks to env generations that hadn't been referenced as the "current" generation in some configurable number of days, and that this process of aging out links are inexpensive enough to be performed in conjunction with other flox invocations. N.B. with rollbacks this means that envs can be aged (deleted) out of order.
