### ISSUE TITLE
docs: possible typo in manpage referring flox.toml

### ISSUE THREAD

**Issue by networkhermit** [flox/flox#13]
Several places in the manpage refers to flox.toml, is it a unreleased feature or should be corrected to flox.nix?

https://floxdev.com/docs/reference/man-pages/flox/#description
https://floxdev.com/docs/reference/man-pages/flox-develop/#description

**Comment by aakropotkin** [comment]
This is a reference to a deprecated feature, thank you for flagging it.
We'll get those updated/removed.

**Comment by robinbrantley** [comment]
Hi @networkhermit - Just a quick update, the 2 links you provided above have also now been updated as well :-)
