### ISSUE TITLE
no spinner on `flox pull -f` when pulling an environment authored on another arch

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1301]
STR:
* be on `aarch64-darwin`
* `flox pull ghudgins/default` 
* `flox pull -f rossturk/default` (x86_64-linux)

Result: no spinner
Expected: spinner / progress notice

<img width="562" alt="image" src="https://github.com/flox/flox/assets/5465514/96182aef-1cd9-4b1c-8d60-c8fd34fb37b2">

**Comment by charmitro** [comment]
Unfortunately, I was unable to replicate the issue. However, I observed something noteworthy. When attempting to pull an environment that is not native to my architecture without using the `--force` option, I'm prompted with the option to `Pull this environment anyway and add 'x86_64-linux' to the supported systems list.` Upon selecting to add my architecture to the list, the download proceeds, but the progress spinner is not visible.

Conversely, when pulling a non-native environment with the `--force` flag, it automatically selects the option to `Pull this environment anyway and add 'x86_64-linux' to the supported systems list,` resulting in the progress spinner disappearing.

**Comment by ghudgins** [comment]
ah good catch. it's related to multi-arch support 

>Conversely, when pulling a non-native environment with the --force flag, it automatically selects the option to Pull this environment anyway and add 'x86_64-linux' to the supported systems list, resulting in the progress spinner disappearing.

this is expected behavior (the auto adding supported systems) but looks like the right culprit of this bug is the lack of showing a progress spinner in this case

**Comment by ghudgins** [comment]
edited the above to clarify. thanks @charmitro!
