### ISSUE TITLE
Speed up eval time for devShell

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1303]
Even on second eval, our `.#devShells.*.default` takes 7 seconds. That makes direnv and nix develop painful to use. For comparison, evaluating nixpkgs#hello takes 1 second

```
> time nix eval .#devShells.aarch64-darwin.default --json
"/nix/store/y5j6by8mv8xhc9wknd62xv45j7l19zql-flox-dev"
nix eval .#devShells.aarch64-darwin.default --json  3.08s user 0.82s system 41% cpu 9.483 total

> time nix eval .#devShells.aarch64-darwin.default --json
"/nix/store/y5j6by8mv8xhc9wknd62xv45j7l19zql-flox-dev"
nix eval .#devShells.aarch64-darwin.default --json  3.02s user 0.69s system 50% cpu 7.313 total

> time nix eval nixpkgs#hello --json
"/nix/store/ccqqsrab7m4kv50bjvv8512dsz6y1768-hello-2.12.1"
nix eval nixpkgs#hello --json  0.70s user 0.21s system 38% cpu 2.386 total

> time nix eval nixpkgs#hello --json
"/nix/store/ccqqsrab7m4kv50bjvv8512dsz6y1768-hello-2.12.1"
nix eval nixpkgs#hello --json  0.58s user 0.16s system 58% cpu 1.276 total
```

**Comment by ysndr** [comment]
To be fair the comparison above is rather skewed as it compares the entire devshell of flox (which is larger than the closure of the `flox package`) with arguably one of the smallest closures in nixpkgs.

i.e. the size of the `hello` derivation (i.e. drv, not the final closure) is 4mb and where hello has 4 direct dependencies:
flox' dev shell is 12.5 MB, and looking at its direct dependencies not much of that is redundant.

(using `nix run nixpkgs#nix-tree -- '.#devShells.aarch64-darwin.default' --derivation`)

That's not to say that we can't make the drv smaller, just that the eval time is naturally going to grow with (apparently at least somewhat linear) with the complexity of the derivation.

**Comment by mkenigs** [comment]
Yeah it may be unavoidable since it's a local flake, but I was wondering if we could look into why we're not getting eval cache speedup. May just be because it's local though

**Comment by mkenigs** [comment]
Hmm seems like we aren't getting it even with a `github` reference for flox itself (as opposed to the devShell):
```
> nix --version
nix (Nix) 2.17.1
> nix -vvv eval github:flox/flox/d3441f04231f83d5a1a52aadce01d48a8868370d#packages.aarch64-darwin.default --json 2>&1 | grep uncached
evaluating uncached attribute 'packages.aarch64-darwin.default'
> nix -vvv eval github:flox/flox/d3441f04231f83d5a1a52aadce01d48a8868370d#packages.aarch64-darwin.default --json 2>&1 | grep uncached
evaluating uncached attribute 'packages.aarch64-darwin.default'
```

**Comment by ysndr** [comment]
^ seeing the same with nix 2.18 and 2.23-pre

locally tested with `'.?ref=HEAD#devShells.aarch64-darwin.default'`

note that `nix build ...` does seem to use the cache alright

**Comment by aakropotkin** [comment]
Was this a regression or are we simply looking for an optimization?
Not sure if I should be investigating changes to the file that may have caused a slowdown or not.

**Comment by mkenigs** [comment]
It's been this way for a while

**Comment by aakropotkin** [comment]
Cool I can look into it.

**Comment by aakropotkin** [comment]
I've been digging and I don't think there's much to be done about this one.

Because we're working in a local source tree, and the tree is dirty, we aren't going to use the eval-cache ( so we're running at the speed of OG `nix-*` commands ).
This reruns evaluation of everything every time you invoke `nix`.

The `nix` evaluator is a bit of a CPU hog.

You can run with `nix eval ... -vvvvv` to see spots where we slow down a bit; and it's basically "we're evaluating like 4 distinct `nixpkgs` closures here".

We could potentially speed things up by consolidating onto fewer `nixpkgs` revs, so I'll look into that.

**Comment by mkenigs** [comment]
I don't think it's worth sinking time into that...if we could use the evalCache when the tree is clean though, that would be nice

**Comment by aakropotkin** [comment]
I dropped it down to a single rev ( the build will likely fail, but eval succeeds ) and it's still ~3s.

**Comment by ysndr** [comment]
The odd observation i had was that neither `nix develop '.?rev=....#devShells.aarch64-darwin.default'` and `nix eval '.?rev=....#devShells.aarch64-darwin.default'` use the eval cache (run with -vvv will say something along the lines of "evaluating uncached attribute devShells.aarch64-darwin.default", while `nix build '.?rev=....#devShells.aarch64-darwin.default'` does use cached attributes:

```
...
trying flake output attribute 'packages.aarch64-darwin.default'
using cached string attribute 'packages.aarch64-darwin.default.type'
using cached string attribute 'packages.aarch64-darwin.default.drvPath'
using cached list of strings attribute 'packages.aarch64-darwin.default.meta.outputsToInstall'
...
```

which led me to believe its an upstream issue of sorts as well

**Comment by mkenigs** [comment]
Did you ever figure out why `nix build` uses the eval cache but `nix develop` doesn't? Is that just an upstream bug?

**Comment by aakropotkin** [comment]
It looks like `nix build` uses eval caches, but `nix develop` doesn't, even in the latest release: https://github.com/NixOS/nix/blob/master/src/nix/develop.cc

You can search in there but I'm not seeing any `attrPathCursor` usage surrounding the parts which hit the evaluator.
