### ISSUE TITLE
FLOX_ENV_LIB_DIRS can't handle multiple directories

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1317]
Currently if two different environments both contain a library that ends up in FLOX_ENV_LIB_DIRS, the environments interfere with each other.

A reproducer and then test case for this issue would be:
- identify two packages containing libraries
- install each package to a different env
- activate both environments sequentially (so that there are two paths in FLOX_ENV_LIB_DIRS)
- attempt to make use of both libs in some way
  - compile a test program, remove its RPATH and see if LD_AUDIT can find both paths

**Comment by mkenigs** [comment]
@limeytexan this is similar to https://github.com/flox/flox/issues/1246 and relates to https://github.com/flox/flox/issues/1268, and my understanding from that ticket is that we should only set development env vars for a single package group in the most recently activated environment (https://github.com/flox/flox/issues/1246#issuecomment-2043301527). While I do think it's probably worth fixing ld-audit for the sake of correctness, it seems like the more complete solution for the CLI would be doing https://github.com/flox/flox/issues/1268

**Comment by limeytexan** [comment]
This was implemented with #1742 - see the table of tests in `ld-floxlib/Makefile` lines [73-84](https://github.com/flox/flox/blob/main/ld-floxlib/Makefile#L73-L84) and corresponding `integration_test_TEMPLATE`.
