### ISSUE TITLE
Spinners with emoji output extraneous new lines (`flox pull` with Kitty/iterm terminal)

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1324]
**Describe the bug:**

Running `flox pull` from within a [kitty](https://sw.kovidgoyal.net/kitty/) terminal causes the spinner to output a new line for each tick.

**Steps to reproduce:**

1. Start [Kitty](https://sw.kovidgoyal.net/kitty/): `nix run 'nixpkgs#kitty'`
1. Force pull an environment: `flox pull ghudgins/default -f`

Result (the spinner prints each tick on a new line and remains after the final message):
```
% flox pull ghudgins/default -f       
⠁ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠁ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠉ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠙ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠚ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠒ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠂ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠂ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠁ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠁ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠉ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
⠙ ⬇️  Remote: pulling and building ghudgins/default from https://hub.flox.dev/ into the current directory
✨ Pulled ghudgins/default from https://hub.flox.dev/

You can activate this environment with 'flox activate'
```

Expected (the spinner updates in place and is replaced by the final message):
```
% flox pull ghudgins/default -f
✨ Pulled ghudgins/default from https://hub.flox.dev/

You can activate this environment with 'flox activate'
```

**Sidenotes**

I found this while looking into https://github.com/flox/flox/issues/1301

I can't reproduce the issue with `nixpkgs#iterm2`, `nixpkgs#alacritty`, or the MacOS default `Terminal`. I ruled out [my kitty config](https://github.com/dcarley/dotfiles/tree/master/.config/kitty) by using `nix run 'nixpkgs#kitty' -- -c /dev/null`. I've tested this with Kitty 0.31.0 and 0.34.0

The bug appears to affect more terminal emulators than just kitty based on this issue in the library that provides the spinner: https://github.com/console-rs/indicatif/issues/638

I think our current options are:

1. Wait for, or attempt to fix, that issue in the library. However there's no clear path forwards at the moment.
1. Stop using emoji, or just two-codepoint emoji, in the spinner ticker messages. However it wouldn't look as pretty for the majority of users and I'm not sure how we'd enforce/test it?

Do we have any usage metrics that would help us make a decision?

**flox Version (run `flox --version` if possible):**
```
% flox --version               
1.0.3-ga8cc066
```

**`uname -a` output:**
```
% uname -a
Darwin mba15.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:08 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8122 arm64 arm Darwin
```

**Comment by stahnma** [comment]
This also happens with iTerm. 

<img width="725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1ZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--faab852c32f7ea8c635f4584c964d6b4bb1d0a6e/Cursor_and_floxbox01_and_update-catalog_populatedb_py_at_main_%C2%B7_flox_update-catalog.png" alt="Cursor_and_floxbox01_and_update-catalog_populatedb_py_at_main_·_flox_update-catalog.png" />

**Comment by ghudgins** [comment]
that's new. marking this regression

**Comment by stahnma** [comment]
Also happenings 1.0.6

**Comment by dcarley** [comment]
Fixed in https://github.com/flox/flox/pull/1549 🚀
