### ISSUE TITLE
Implement building new lockfile format in pkgdb

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1358]
- When passed a lockfile in the format introduced in https://github.com/flox/flox/issues/1283, `pkgdb buildenv` should produce a built flox environment store path with the same behavior as we currently have for pkgdb generated lockfiles

**Comment by billlevine** [comment]
I think the work here is turning into a NOP, given the approach being attempted in #1283

**Comment by billlevine** [comment]
With the currently completed work and a sample v1 lockfile, that PR successfully builds an environment.  Will confirm once that's in and tested against some more substantial lockfiles before closing this out.

**Comment by billlevine** [comment]
With #1283 complete, this should be working, and was indeed with local tests.
