### ISSUE TITLE
Allow to use unstable channel

### ISSUE THREAD

**Issue by sporto** [flox/flox#1377]
**Describe the feature:**

Says here that flox tracks the stable channel https://flox.dev/docs/concepts/packages-and-catalog/#supported-package-metadata
Which I understand updates every six months. https://nixos.wiki/wiki/Nix_channels#:~:text=Stable%20channels%20(%20nixos%2D23.11%20),are%20released%20every%20six%20months.

It would be great if I can use the unstable channel as often cannot find the latest versions on the stable channel.

**Describe a use case of this feature:**

I want to install go 1.22 (released in Feb) with flox, but can't, only 1.21 is available. Which is an issue because code in repo has already been updated. So I cannot install the correct version locally using flox.

This happens with several other packages as the 6 month releases of the stable channel is too slow.

**Acceptance criteria:**

Allow me to get packages from the unstable channel. Is it possible atm?
Thanks

**Comment by billlevine** [comment]
Some aspects of this are currently very active in engineering, being tracked by the following ticket:
https://github.com/flox/flox/issues/1197

While that does not specifically allow one to track a particular stability by name, I think it allows the full breadth of version selection that's desired.  This capability is expected in the very near term.

Does that sound like it addresses your desired functionality?

**Comment by sporto** [comment]
@billlevine thanks, that issues seems focused on allowing to install older versions. But if this will make it possible to installer newer versions as well then this will be great. By newer version I mean a version that is newer than the one in the stable channel.

**Comment by billlevine** [comment]
Yes, that's what we're working on.  I'm going to close this issue as a _duplicate_ but we appreciate the write up and it will remain referenced in the tracking ticket.  We look forward to getting this feature set into your hands!
