### ISSUE TITLE
[bug] flox dev commands output in non-flake directories.

### ISSUE THREAD

**Issue by ysndr** [flox/flox#138]
**Describe the bug:**

`flox develop` and other flox commands for package development don't have the cleanest output when the current directory is not a flake.

**Steps to reproduce:**
1. `flox develop` in a directory outside of a flake
2. `flox build` in a directory outside of a flake

Result: 

`flox develop` has some `jq` processing spilling over and could do a better noticing that there is in fact no flake at the current directory.

```
$ flox develop
jq: error (at <stdin>:0): Cannot iterate over null (null)

ERROR: cannot find attribute path - have you run 'flox init'?
```

`flox build` and friends are _better_, in that they say they were unable to locate a flake in the current directory but do so with inconsistent logging styles.

```
$ flox build
[WARN] [flox_rust_sdk::flox] Could not parse flake_ref .
    Unable to find a flake before encountering file system boundary at "/Volumes"
    
ERROR: No matching installables found
```

Expected: 

The output should contain
* the _correct_ issue (Can't resolve/infer an installable)
* the cause (Unable to find a flake before encountering file system boundary at "/Volumes")
* steps to resolve the problem

**Comment by aakropotkin** [comment]
No longer relevant after GA scope changes.
