### ISSUE TITLE
Calls to pkgdb in integration tests are failing due to `pkgdb` being removed from the PATH

### ISSUE THREAD

**Issue by ysndr** [flox/flox#1386]
flox calls pkgdb with essentially:

```
Command::new($PKGDB_BIN).env("PATH", "NIX_PKG_BIN_DIR")
```

`flox-cli-tests` runs the test suite with [`PKGDB_BIN=pkgdb`](https://github.com/flox/flox/blob/e3116eff4fe643445bc4a78a9e85932fdb4d82b0/pkgs/flox-cli-tests/default.nix#L131-L135) which means the command becomes 

```
Command::new("pkgdb").env("PATH", "NIX_PKG_BIN_DIR")
```

if not an absolute path `Command::new(_)` resolves the path using the `PATH` in the _spawned commands env_ i.e. in `PATH=NIX_PKG_BIN_DIR`, which means `pkgdb` is not found.
Thus, we either need to resolve `pkgdb`, _before_ calling it in rust or before setting up the vars in the test suite or add its parent path to the PATH when constructing the `Command`

**Comment by mkenigs** [comment]
This is a regression from 1299. A workaround is running `just ...`

**Comment by ysndr** [comment]
hmm, does seem to stumble anyway?

https://github.com/flox/flox/actions/runs/8911377953/job/24472561695?pr=1387#step:7:195

**Comment by mkenigs** [comment]
Hmm why is it just the catalog test that's failing

**Comment by ysndr** [comment]
because i committed my local path into it 🤦🏼‍♂️

**Comment by ysndr** [comment]
closed by https://github.com/flox/flox/pull/1443
