### ISSUE TITLE
[bug]: flox develop installable handling for subdirectory

### ISSUE THREAD

**Issue by tomberek** [flox/flox#139]
**Describe the bug:**
Incorrect installable handling in `flox develop

The logic at https://github.com/flox/flox/blob/main/flox-bash/lib/commands/development.sh#L317-L319 makes it difficult to refer to a devShell in a subdirectory easily. In this case, someone wanted to refer to a subdirectory, not the root of the project, and it results in a silent exit.

**Steps to reproduce:**
1. git clone https://github.com/mrinalwadhwa/try-flox
2. cd try-flox && git checkout 7bd2d935133abba0896e2f5291ec9849058029c2
3. flox --debug develop ./tools/nix

Result: 
Exit with error code 1.

Expected: 
Open devShell and run hooks.

Note: thanks to @mrinalwadhwa

**Comment by limeytexan** [comment]
@mrinalwadhwa: appending response from discord in case you hadn't seen it:

*Tom Bereknyei* — `Today at 5:22 PM`
Here is a temporary workaround that changes the handler for develop to use our rust backend that will behave as expected.
```
FLOX_FEATURES_DEVELOP=rust flox develop ./tools/nix
```

**Comment by ghudgins** [comment]
stale issue for `flox develop`
