### ISSUE TITLE
bug: flox subscribe fails when invoked from unreadable directory

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#142]
**Describe the bug:**

When invoked from a directory that the user does not own and has no read or execute privileges, the `flox subscribe` command fails with `ERROR: could not verify channel URL`.

flox version: 0.2.3-r539

**Steps to reproduce:**
1. Change to your home directory with `cd ~/.`
2. Set the mode of your home directory to 700 with `chmod 700 ~/.`
3. Attempt to subscribe to a channel as another user from that directory with `sudo -u <user> flox subscribe`

Result: 

<pre><span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:~]$</b></span> sudo -u floxfan flox subscribe
Enter channel name to be added: flox-examples
Enter URL for &apos;flox-examples&apos; channel: github:flox-examples/floxpkgs/master
<span style="color:#FF5555"><b>error:</b></span> failed to extract archive (<span style="color:#FF55FF"><b>Could not open /tmp/nix-3493788-0/flox-examples-floxpkgs-3f2306c</b></span>)
(use &apos;--show-trace&apos; to show detailed location information)

<b>ERROR: could not verify channel URL: &quot;github:flox-examples/floxpkgs/master&quot;</b>
</pre>

The expected result can be seen by first changing directory to the `floxfan` home directory before invoking `flox`:

<pre>
<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:~]$</b></span> sudo -u floxfan sh -c &apos;cd ~floxfan &amp;&amp; flox subscribe&apos;
Enter channel name to be added: flox-examples
Enter URL for &apos;flox-examples&apos; channel: github:flox-examples/floxpkgs/master
<span style="color:#FF55FF"><b>warning:</b></span> input &apos;nixpkgs&apos; has an override for a non-existent input &apos;floxpkgs&apos;
<span style="color:#FF55FF"><b>warning:</b></span> input &apos;nixpkgs/flox&apos; has an override for a non-existent input &apos;nixpkgs-flox&apos;
warning: remote HEAD refers to nonexistent ref, unable to checkout
<b>subscribed channel &apos;flox-examples&apos;</b>
</pre>

**Screenshots/terminal output (if relevant):**

`strace` reveals that this is failing because an underlying `nix flake metadata github:flox-examples/floxpkgs/master` invocation is failing with:

<pre><span style="color:#FFFF55">3487775</span> openat<span style="color:#FFFF55">(</span><span style="color:#55FFFF"><b>AT_FDCWD</b></span>, <span style="color:#FF55FF">&quot;.&quot;</span>, <span style="color:#55FFFF"><b>O_RDONLY</b></span>|<span style="color:#55FFFF"><b>O_CLOEXEC</b></span>|<span style="color:#55FFFF"><b>O_PATH</b></span>|<span style="color:#55FFFF"><b>O_DIRECTORY</b></span><span style="color:#FFFF55">)</span> <span style="color:#87FFAF">=</span> <span style="color:#87FFAF">-1</span> <span style="color:#55FFFF"><b>EACCES</b></span> <span style="color:#55FFFF">(Permission denied)</span>
</pre>

<pre>
<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:~]$</b></span> ls -ld .
drwx------ 5 brantley users 11 Jul  3 17:27 <span style="color:#5555FF"><b>.</b></span>
</pre>

**Comment by charmitro** [comment]
I believe this issue can be closed, as commit 595345074b783f372e4272278efd4135cec85b57 removed the subscribe command (among others).

**Comment by ghudgins** [comment]
thank you!
