### ISSUE TITLE
set catalog feature flag for integration tests (list)

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1420]
Either:
- Copy any tests in `list.bats` that are impacted by the catalog and run them with the catalog feature flag set. Make any small changes required to get them passing

Or:
- Port those tests to unit tests run with the catalog feature set

In both cases:
- Set `FLOX_FEATURES_USE_CATALOG=true` and  `_FLOX_USE_CATALOG_MOCK=/dev/null` for all other tests in the file
- If anything that isn't minor breaks, skip copied tests and create followup tickets

**Comment by mkenigs** [comment]
Looks like the following should be unit tests: 
- 'flox list' lists packages of environment in the current dir; shows different paths
- 'flox list' lists packages of environment in the current dir; shows different id
- 'flox list' hides packages not installed for the current system
- 'flox list' tolerates missing version

The following need to be modified to run with the catalog:
- (this could be a unit test, but I think it's probably good to have at least one integration test for `flox list`?) 'flox list' lists packages of environment in the current dir; One package from nixpkgs

**Comment by ysndr** [comment]
what about these do we want to unit test though?
almost all of the current tests mostly check the output (formatting), the "installation side" (whether the right data goes into the manifest) of these tests is already covered in the .. install tests

so do we want to test
- the formatters[1]
- whether we convert the lockfile without information loss [2] (which in the catalog case is basically an image of `LockedPackageCatalog` only the pkgdb case does a bit more work there) or 
- whether filter systems correctly with `.filter(|system| system == pacakge.system)`?

Further, we dont really have "missing versions" anymore as our scraping seems to default to the package name if no version is specified, that may be an upstream issue.


[1] https://github.com/flox/flox/blob/15171d5fa8366d81094ef41b67b770122f01c6c2/cli/flox/src/commands/list.rs#L106-L164

[2] https://github.com/flox/flox/blob/15171d5fa8366d81094ef41b67b770122f01c6c2/cli/flox-rust-sdk/src/models/lockfile.rs#L283-L304
