### ISSUE TITLE
set catalog feature flag for integration tests (install)

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1428]
- Copy any tests in `install.bats` that are impacted by the catalog and run them with the catalog feature flag set. Make any small changes required to get them passing
- Set `FLOX_FEATURES_USE_CATALOG=true` and  `_FLOX_USE_CATALOG_MOCK="$TESTS_DIR/catalog_responses/empty_responses.json"` for any other tests in the files to assert that they don't depend on the catalog
- If anything that isn't minor breaks, skip copied tests and create followup tickets

**Comment by dcarley** [comment]
Notes from refinement:
- Everything is affected here and there's a wide variety of package sets.
