### ISSUE TITLE
set catalog feature flag for integration tests (ld-floxlib)

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1429]
- Copy any tests in `ld-floxlib.bats` that are impacted by the catalog and run them with the catalog feature flag set. Make any small changes required to get them passing
- Set `FLOX_FEATURES_USE_CATALOG=true` and  `_FLOX_USE_CATALOG_MOCK="$TESTS_DIR/catalog_responses/empty_responses.json"` for any other tests in the files to assert that they don't depend on the catalog
- If anything that isn't minor breaks, skip copied tests and create followup tickets

**Comment by dcarley** [comment]
Notes from refinement:
- this test pins specific versions of `nix` and `glibc` but those semvers are available from the catalog
