### ISSUE TITLE
set catalog feature flag for integration tests (upgrade)

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1435]
- Copy any tests in `upgrade.bats` that are impacted by the catalog and run them with the catalog feature flag set. Make any small changes required to get them passing
- Set `FLOX_FEATURES_USE_CATALOG=true` and  `_FLOX_USE_CATALOG_MOCK=/dev/null` for all other tests in the file
- If anything that isn't minor breaks, skip copied tests and create followup tickets

**Comment by zmitchell** [comment]
These tests likely need to be completely rewritten, but most of them can be made into unit tests.

Notes:
- We recently discussed what it means to upgrade by install id. I don't know where that decision was written down or what the final outcome was, but it needs to be encoded as a test.
- `""'flox upgrade' upgrades with catalog"` should be separate tests

**Comment by mkenigs** [comment]
Closing, added a note to https://github.com/flox/flox/issues/1485 to unskip tests
