### ISSUE TITLE
set catalog feature flag for integration tests (pkgdb)

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1436]
- Assess any behaviors in `groups.bats`, `lockfile.bats`, and `search.bats` that are relevant to the catalog. Ensure they are tested in either the CLI or serverside that are impacted by the catalog and run them with the catalog feature flag set. Make any small changes required to get them passing
- If anything that isn't minor breaks, create followup tickets

**Comment by mkenigs** [comment]
There should be serverside tests for:
groups.bats
- packages in different groups can resolve to different pages
- impossible constraints in the same group fails

search.bats
- exact version works
- semver tests:
    - range works
    - partial semvers work (18, 18.18)
    - * works (18.*)
- prefer-pre-releases
- nodePackages

(testing of unfree and broken filtering are deferred until we implement that)

There should be a CLI test for:
lockfile.bats
- the per package system field is handled correctly

**Comment by billlevine** [comment]
> * the per package system field is handled correctly

It looks like `make_params_limit_systems` , `make_params_override_systems`, `make_params_multiple_systems` in `lockfile.rs` cover this functionality in the CLI.

flox/catalog-server#56 - covers the review of the service side tests.

Based on these factors, I believe this ticket may be closed.
