### ISSUE TITLE
Use `runix::flakeref` within `flox_types`

### ISSUE THREAD

**Issue by ysndr** [flox/flox#144]
https://github.com/flox/flox/blob/56517b0cddadfc9ed401cbabf420a1b2f268cab2/crates/flox-types/src/catalog/source.rs#L18-L51

https://github.com/flox/flox/blob/d508f9a3bb49d3056cc6f755ffc780886ea0e871/crates/flox-types/src/catalog/mod.rs#L34

This would break builtfilter (which depends on flox_types) as `allRefs` is not supported here.
The work around is currently to not use most of `CatalogEntry` within builtfilter.

Nb. this will likely also block the rust flox publish implementation.

**Comment by aakropotkin** [comment]
No longer relevant
