### ISSUE TITLE
Change layout for flox show output

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1441]
Judging from output in the spec, the output for `flox show` was designed to handle different pkg_paths:
```
nodejs - A yadaa ydaa thingy
  nodejs-14_x    nodejs@14.21.3
  nodejs-16_x    nodejs@16.20.1
  nodejs-18_x    nodejs@18.16.1
  nodejs_14      nodejs@14.21.3
  nodejs_16      nodejs@16.20.1
  nodejs_18      nodejs@18.16.1
  nodejs_20      nodejs@20.4.0
  nodejs_latest  nodejs@20.4.0
```

`show` is now restricted to a single pkg_path, so we should:
- make `--all` the default/completely drop it as an option
- change the layout to be:
```
bash - GNU Bourne-Again Shell, the de facto standard shell on Linux
    bash@5.2p26
    bash@5.2-p21
```

We can make this change for both catalog and pkgdb code paths.

**Comment by ghudgins** [comment]
@jennymahmoudi this LGTM but wanted to confirm with you too

**Comment by jennymahmoudi** [comment]
Is this because the values in the left column would always be the same now? If so 👍 👍 👍

**Comment by ghudgins** [comment]
@jennymahmoudi yes. show was designed to be fuzzy originally I think and now it's not. so you'll only ever get a single package

verified this on the branch!
