### ISSUE TITLE
Update login message to match updated auth0 flow

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#1453]
We are [simplifying the auth0 device flow](https://github.com/flox/floxhub-auth0/issues/15) so that you don't have the enter the device code *and* confirm the code. Now, you will just need to confirm the code. This ticket will need to be coordinated with the auth0 changes.

Anywhere the device auth flow is initiated (flox push, flox auth login), update the CLI message, from this:
![image](https://github.com/flox/floxhub-auth0/assets/2687382/93f8974f-e750-4f1d-be25-f85c97391101)

to this:
```
Your one-time activation code is: AAAA-BBBB

Press enter to open hub.flox.dev in your browser...
```

**Comment by nicklewis** [comment]
Change `verification_uri` to `verification_uri_complete`:
https://github.com/flox/flox/blob/main/cli/flox/src/commands/auth.rs#L114

**Comment by jennymahmoudi** [comment]
reviewed & approved!
