### ISSUE TITLE
WSL 2 Debian install instructions missing prerequisites

### ISSUE THREAD

**Issue by billewanick** [flox/flox#146]
**Describe the bug:**

The WSL 2 instructions for Debian do not contain all the dependencies required for my machine.

**Steps to reproduce:**
1. Provision a Windows 10 System
2. Install WSL 2, and create a VM using a Debian image
3. Follow [these instructions](https://floxdev.com/docs/install-flox/#install-flox) to install Flox
4. See the errors about missing dependencies.

Result: 
```bash
bill@Bill-Alienware:/workspace$ sudo dpkg -i flox/flox.x86_64-linux.deb
Selecting previously unselected package flox.
dpkg: regarding flox/flox.x86_64-linux.deb containing flox, pre-dependency problem:
 flox pre-depends on policycoreutils
  policycoreutils is not installed.

dpkg: error processing archive flox/flox.x86_64-linux.deb (--install):
 pre-dependency problem - not installing flox
Errors were encountered while processing:
 flox/flox.x86_64-linux.deb
```

Expected: 

Flox should be installed

**Fix**

- Fixed this by adding policycoreutils and semodule-utils to the `Install Prerequisites` step.
  -  It should read like this instead:
  - `$ sudo apt-get install policycoreutils semodule-utils tar wget xz-utils`

**Comment by snth** [comment]
Thanks @billewanick ! I just had the same issue and your Fix resolved it beautifully.
