### ISSUE TITLE
'flox activate' overwrites ZDOTDIR when eval'd (and unsets it when run)

### ISSUE THREAD

**Issue by eikenb** [flox/flox#1463]
**Describe the bug:**

The latest release (1.0.5) broke my ZSH config usage of ZDOTDIR, as flox overwrites the ZDOTDIR setting in my .zshenv. Here's the offending ZDOTDIR bits extracted from the eval'd command...

```sh 
[~]print $(flox activate) | tr ';' '\n' | grep ZDOTDIR
 export FLOX_ORIG_ZDOTDIR=""
 export ZDOTDIR="/nix/store/dazajghiiqr0cc9hpgawdpksgn73kl3s-flox-activate.d/zdotdir"
```

If I run `flox activate` at the command line, ZDOTDIR is unset.

Downgrading back to 1.0.4 didn't help as I was still getting errors and at that point I just  nuked everything and recreated my environments as I needed a working environment.

**Steps to reproduce:**
1. install flox 1.0.5
2. set ZDOTDIR to something
3. eval $(flox activate)
4. ZDOTDIR overwritten to new value (see above)
Alt..
1. install flox 1.0.5
2. set ZDOTDIR to something
3. `flox activate` at the CLI
4. ZDOTDIR unset
 
Result:
ZDOTDIR is modified.

Expected:
Flox to not change (or if it does, to fix it after) a core ZSH environment variable.

**flox Version (run `flox --version` if possible):**
1.0.5

**`uname -a` output:**
Linux alia 6.5.0-0.deb12.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1~bpo12+1 (2023-11-23) x86_64 GNU/Linux

**Comment by eikenb** [comment]
One note about how I set my ZDOTDIR... I have this in my .zshenv to set it.

```sh
export BASE_ZDOTDIR=$HOME/.zsh
if [ -z "$ZDOTDIR" ]; then
    export ZDOTDIR=$BASE_ZDOTDIR
fi
```

I set it this way as I have a couple other uses of ZDOTDIR where I still want to keep references to my original. But I thought this might interfere with your resetting it.

I found the [Flox zdotdir README](https://github.com/flox/flox/blob/main/pkgdb/src/buildenv/assets/activate.d/README.md), so it does look like you are trying to handle this correctly and it must be some conflict in setups and this is the first thing I could think of.

I can try to test this some more in a VM if there isn't something obvious. I can look  at this later as well... after work.

**Comment by limeytexan** [comment]
Many thanks @eikenb for the bug report! Yes - you're right that we're trying to preserve your original `ZDOTDIR`, but I suspect this is the bug (as computed from the `activate-package` branch):
```
diff --git a/pkgdb/src/buildenv/assets/activate b/pkgdb/src/buildenv/assets/activate
index 8d2d82fd..d49844ea 100755
--- a/pkgdb/src/buildenv/assets/activate
+++ b/pkgdb/src/buildenv/assets/activate
@@ -283,7 +283,7 @@ case "$FLOX_SHELL" in
   *zsh)
     echo "export FLOX_ENV=\"$FLOX_ENV\";"
     echo "export _FLOX_PKGDB_VERBOSITY=\"$_FLOX_PKGDB_VERBOSITY\";"
-    echo "export FLOX_ORIG_ZDOTDIR=\"$FLOX_ORIG_ZDOTDIR\";"
+    echo "export FLOX_ORIG_ZDOTDIR=\"$ZDOTDIR\";"
     echo "export ZDOTDIR=\"$_zdotdir\";"
     echo "export FLOX_ZSH_INIT_SCRIPT=\"$FLOX_ENV/activate.d/zsh\";"
     echo "export _add_env=\"$_add_env\";"
```

We'll get this tested and fixed asap, but I just wanted to share that with you. Again, thanks for the bug report!

**Comment by eikenb** [comment]
Great. Saved me from looking into it more tomorrow. I'm finding flox very useful and am happy to help. 
Thanks for the great tool!

**Comment by limeytexan** [comment]
As usual this effort turned into a larger refactor, but I'm confident that #1467 should fix the problem for you. We'll try to get it through the review pipeline in time for the next release. Thanks again @eikenb for the bug report!

**Comment by mkenigs** [comment]
Should be fixed by https://github.com/flox/flox/pull/1467 which will be released next Tuesday. Re-open if that doesn't fix it!

**Comment by AndydeCleyre** [comment]
Ah! I figured out my issue with this, and maybe it will help someone else:

Usually, it's not necessary to *export* `ZDOTDIR`, as it's the same Zsh process reading it that sets it. In my `.zshenv` I have a line that starts `ZDOTDIR=`..., and that's find for Zsh's needs.

All `flox` commands, however, are new processes, rather than shell functions, so won't have access to the parameter unless it's exported. So for flox to work properly, I need to `export ZDOTDIR=`..., not just set it.

That's reasonable, but I'll mention that an alternative possibility would be providing a `flox` shell function, which would have access to even un-`exported` parameters.
