### ISSUE TITLE
Flox Install on WSL 2 Debian hangs while waiting for confirmation

### ISSUE THREAD

**Issue by billewanick** [flox/flox#147]
**Describe the bug:**

When installing Flox onto a new WSL 2 system from Windows 10 desktop, my prompt hangs as it is expecting a confirmation but the screen is being captured and not displayed.

**Steps to reproduce:**
1. Provision a Windows 10 machine
2. Install WSL 2 and a Debian VM
3. Follow [the installation instructions](https://floxdev.com/docs/install-flox/#install-flox) for Flox (and note the issue with the dependencies [here](https://github.com/flox/flox/issues/146))
4. Run the install command, `sudo dpkg -i /path/to/flox.deb`

Result: 

The terminal window hangs waiting for input

Expected: 

The terminal should have asked me for confirmation, and finished the install

**WorkAround**

- I was able to get past this but using the `yes` command
  - `yes | sudo dpkg -i /path/to/flox.deb`
  - Discovered this via a [ServerFault answer](https://serverfault.com/a/817521)

**Comment by billewanick** [comment]
Install hangs

![FloxInstallHangs-WSL2](https://github.com/flox/flox/assets/13324165/6cd0316a-84f9-4be5-a25b-3c18f9af9b5a)

Install succeeds
![FloxInstall-Success](https://github.com/flox/flox/assets/13324165/32f7944c-7549-4526-9266-95afefa7979d)

Error message from terminal
![FloxInstallHangs-ErrorMessage](https://github.com/flox/flox/assets/13324165/f1856e34-8239-427b-9a12-64361b0637bf)

Error log 
[flox-installation.log.1688751809.txt](https://github.com/flox/flox/files/11984611/flox-installation.log.1688751809.txt)

**Comment by ghudgins** [comment]
we have fixed this issue in 0.3.7+ but are still working another issue to make flox not require sudo for WSL #785 

stay tuned for the release of 0.3.7+ coming very soon. it's been awhile since we have done a release and there are a lot of new and re-imagined features in this upcoming version
