### ISSUE TITLE
Remove "enter the code" step on device login flow 

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1472]
I've observed a few research participants get confused at the second device confirmation step we have. After entering the code, they are asked to confirm it, and they pause, and wonder out loud if they've done something wrong. 

When we first implemented this, I got the impression that this step is required, but now I understand we can remove the first "enter the code" step. So let's remove the "enter the code" step.

### Remove this:
![image](https://github.com/flox/floxhub-auth0/assets/2687382/4826203d-db30-4eca-9551-852fc56963b0)

### Keep this:
![image](https://github.com/flox/floxhub-auth0/assets/2687382/4eb9b9d2-76f7-483e-a05d-244c16520094)

### CLI message
And we will have a separate ticket to update the CLI message, from this:
![image](https://github.com/flox/floxhub-auth0/assets/2687382/93f8974f-e750-4f1d-be25-f85c97391101)

to this:
```
Your one-time activation code is: AAAA-BBBB

Press enter to open hub.flox.dev in your browser...
```

**Comment by nicklewis** [comment]
Change `verification_uri` to `verification_uri_complete`:
https://github.com/flox/flox/blob/main/cli/flox/src/commands/auth.rs#L114

**Comment by ghudgins** [comment]
verified product side in the PR. this can close when it merges
