### ISSUE TITLE
search suggestions missing in catalog search

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1483]
STR:

* enable catalog service feature flag
* `flox search node`

Result:  Image
<img width="877" alt="image" src="https://github.com/flox/flox/assets/5465514/dfe2e239-1a6e-4155-b9bb-4faf526cdb29">

Expected: `nodejs` suggestion still has values

**Comment by mkenigs** [comment]
@ghudgins I think this might be a dup of https://github.com/flox/flox/issues/1506? The title is a little confusing, because search still provides suggestions:
```
> FLOX_FEATURES_USE_CATALOG=true flox search node
nodenv     Manage multiple NodeJS versions
nodejs     Event-driven I/O framework for the V8 JavaScript engine
nodehun    The Hunspell binding for NodeJS that exposes as much of Hunspell as possible and also adds new features
nodeinfo   A command line tool to query nodeinfo based on a given domain
node2nix   Generate Nix expressions to build NPM packages
leafnode   Implementation of a store & forward NNTP proxy, under development
nodejs_22  Event-driven I/O framework for the V8 JavaScript engine
nodejs_21  Event-driven I/O framework for the V8 JavaScript engine
nodejs_20  Event-driven I/O framework for the V8 JavaScript engine
nodejs_18  Event-driven I/O framework for the V8 JavaScript engine

Showing 10 of 193 results. Use `flox search node --all` to see the full list.

Use 'flox show <package>' to see available versions

Related search results for 'nodejs':
nodejs               Event-driven I/O framework for the V8 JavaScript engine
elmPackages.nodejs   Event-driven I/O framework for the V8 JavaScript engine
nodePackages.nodejs  Event-driven I/O framework for the V8 JavaScript engine
```

(although actually those suggestions are coming from pkgdb, so we do need to fix that)

**Comment by ghudgins** [comment]
sorry, the AC is wrong. it should be `flox search node`...the suggestions are now blank for the reasons you mention above I think

<img width="877" alt="image" src="https://github.com/flox/flox/assets/5465514/53f3f19b-764c-45c1-b135-361a5d145127">

**Comment by dcarley** [comment]
Notes for refinement:

- do we spread catalog/pkgdb branching logic down into `DidYouMean`?
