### ISSUE TITLE
Display systems in `show`

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1499]
When a package version is available on less than 4 systems, display it with the systems it supports, e.g if `nodejs@14.16.1` only supports two systems, it should display:

```
nodejs - Event-driven I/O framework for the V8 JavaScript engine
...
    nodejs@14.16.1 (x86_64-darwin, x86_64-linux only)
```

`show` already gets records that include system, so they just need to be aggregated.

**Comment by mkenigs** [comment]
@ghudgins @jennymahmoudi any thoughts on format? We could do columns or something instead

**Comment by ghudgins** [comment]
honestly this looks good enough to me as a first pass. the worst case is it breaks 80 characters and goes to the next line and I think that'll look okay. @jennymahmoudi what do you think?

**Comment by jennymahmoudi** [comment]
Yep good enough. 

For the future, I'm wondering if it's going to be common to see a version with the systems in the same list as version(s) that support more than 4 systems (and therefore doesn't list them). I could see that being confusing but not enough to do anything different today.

**Comment by zmitchell** [comment]
> For the future, I'm wondering if it's going to be common to see a version with the systems in the same list as version(s) that support more than 4 systems (and therefore doesn't list them).

I think that will be common.

Implementation notes:
- Search results are per-system, so you'll need to collect the results by version in an order-preserving way (assuming they're already in some order as returned to us by catalog service).

**Comment by zmitchell** [comment]
- Catalog returns packages sorted by version, but the version is a string so it's a lexical sort

**Comment by billlevine** [comment]
> * Catalog returns packages sorted by version, but the version is a string so it's a lexical sort

ticketed in flox/catalog-server#103

**Comment by ghudgins** [comment]
tested on the branch and it LGTM.
