### ISSUE TITLE
Add a deprecation message for `flox update`

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1509]
When the catalog feature flag is set, instead of running `flox update`, print:
```
❌ ERROR: 'flox update' has been removed. To upgrade packages, run 'flox upgrade'. See flox-upgrade(1) for more.
```

Copy and remove any "update" and "base catalog" references from `cli/flox/doc` to `cli/flox/doc-catalog`.

**Comment by ghudgins** [comment]
no 'simply' (I edited)
