### ISSUE TITLE
flox destroy (perhaps others) doesn't parse combined short opts

### ISSUE THREAD

**Issue by rossturk** [flox/flox#151]
**Describe the bug:**

When you combine the short options `-o` and `-f` into a single (like `-of`), `flox destroy` fails to parse the options separately. This doesn't seem to be consistent with standard `getopt` behavior.

This may happen elsewhere besides `flox destroy`.

**Steps to reproduce:**
1. `flox create -e fooenv`
2. `flox destroy -fo -e fooenv`

Result: 

`ERROR: -fo is not expected in this context`

Expected: 

The environment is forcibly destroyed locally and in the remote registry.

**Comment by aakropotkin** [comment]
No longer relevant after cutting non-GA features.
