### ISSUE TITLE
disable flox prompt configuration while preserving $FLOX_PROMPT_ENVIRONMENTS

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#1521]
Issue #1213 tracked the effort to make the contents of `$FLOX_PROMPT_ENVIRONMENTS` configurable by way of the `shell_prompt` config option, but it also attempted to address the requirement for disabling flox prompt modifications altogether with the property of this variable being empty. That turns out to be not exactly what users are looking for because they are wanting to use `$FLOX_PROMPT_ENVIRONMENTS` as part of their own efforts to maintain their own prompt (by whatever means).

The goal of this issue is to provide users with:
1. a way to prevent flox from modifying the prompt
2. while still setting `$FLOX_PROMPT_ENVIRONMENTS` as documented in `flox-activate(1)`

We [previously](https://github.com/flox/flox-bash/blob/main/lib/commands/activate.sh#L299) did this by way of the `$FLOX_PROMPT_DISABLE` variable, and this same approach could be applied by modifying each of `pkgdb/src/buildenv/assets/activate.d/{bash,fish,tcsh,zsh}` and `cli/flox/doc/flox-activate.md`.

---
edit @mkenigs

AC
- `set_prompt` and `hide_default_prompt` are added as config options
- `set_prompt` defaults to true and configures whether activate modifies the prompt
- `hide_default_prompt` defaults to false and configures whether environments named `default` are added to both the prompt and the environment variable `FLOX_PROMPT_ENVIRONMENTS`
- `shell_prompt` is marked deprecated in the man page. If it is set and `set_prompt`/`hide_default_prompt` are unset, it is used to configure the values of `set_prompt`/`hide_default_prompt`. show-all -> true/false, hide-default -> true/true, hide-all -> false/false. If it is set when either of `set_prompt`/`hide_default_prompt` are set, we error.

**Comment by mkenigs** [comment]
@jennymahmoudi @ghudgins @limeytexan updated the AC
