### ISSUE TITLE
Investigate slow test runs on x86_64-darwin

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1527]
We've had some incredibly slow test runs which appear to be due to the runner, not any code changes. See for example a test that took almost 3 mins (`remote can not be pulled into diverged environment`): https://github.com/flox/flox/actions/runs/9310522985/job/25628101369#step:6:192

Which sometimes takes 4 seconds: https://github.com/flox/flox/actions/runs/9321573239/job/25660909199#step:6:157

**Comment by stahnma** [comment]
Duplicated by deltaops#323

**Comment by stahnma** [comment]
This appears to resolved as of the 7th.

**Comment by stahnma** [comment]
@mkenigs If this is still an issue, please re-open.
