### ISSUE TITLE
Use a single package group to resolve multiple systems

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1529]
The server will support adding system to a package descriptor rather than an entire group, allowing a package group to be expressed as a single package group (currently a package group has to be split up into multiple system specific package groups).

Update `LockedManifestCatalog::lock_manifest` to leverage this format rather than splitting groups up.

**Comment by ysndr** [comment]
Mostly covered in https://github.com/flox/flox/pull/1544 with the remaining new tests added in #1552
