### ISSUE TITLE
Command suggestions do not take flakeref into account

### ISSUE THREAD

**Issue by ysndr** [flox/flox#153]
**Describe the bug:**

When running a flox command without specifying an attrpath, flox will provide an interactive selection, and a hint how to skip the interactive selection in the future.

This works with both local **and remote projects**, however for remote projects the suggestion will be invalid as the address to the remote location is not present

**Steps to reproduce:**
1. `flox build github:flox/flox`
2. select any package interactively
3. observe the incorrect suggestion

Result: 

```
$ flox build github:flox/flox

? Select a package for flox build  
> flox
  flox-bash
  flox-src
  flox-tests
  nix-editor
  semver
[↑↓ to move, enter to select, type to filter]

<enter>

HINT: avoid selecting a package next time with:
      $ flox build flox
```

Expected: 

```
$ flox build github:flox/flox

? Select a package for flox build  
> flox
  flox-bash
  flox-src
  flox-tests
  nix-editor
  semver
[↑↓ to move, enter to select, type to filter]

<enter>

HINT: avoid selecting a package next time with:
      $ flox build github:flox/flox#flox
```

**Comment by ghudgins** [comment]
will revisit when we do build. closing for now
