### ISSUE TITLE
bug: cannot remove packages installed by `/nix/store` path

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#154]
**Describe the bug:**
Cannot remove a package installed by `/nix/store` path.

**Steps to reproduce:**
1. install to an environment by `/nix/store` path
2. attempt (and fail) to remove it

### Result: 

<pre><span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@saas-dev:~/src/floxEM]$</b></span> flox install -e testrm `flox --prefix`
<span style="color:#AAAAAA">wrapper&gt; warning: AWS error uploading &apos;nix-cache-info&apos;: Access Denied</span>
<span style="color:#AAAAAA">profile&gt; warning: AWS error uploading &apos;nix-cache-info&apos;: Access Denied</span>
<span style="color:#AAAAAA">profile&gt; warning: AWS error uploading &apos;nix-cache-info&apos;: Access Denied</span>
<span style="color:#AAAAAA">profile&gt; warning: AWS error uploading &apos;nix-cache-info&apos;: Access Denied</span>
<span style="color:#AAAAAA">profile&gt; /nix/store/rxqkd0z3hln7r3bm5ma8119fcggiskzh-profile</span>
<span style="color:#AAAAAA">wrapper&gt; ++ /nix/store/zz4khfifdxijpfrj32lfxqrycilbvzaa-perl-5.36.0/bin/perl -w /nix/store/42p1h90d93lk9fdh11xxcv8qs6mhs7fm-builder.pl</span>
<span style="color:#AAAAAA">wrapper&gt; warning: creating dangling symlink `/nix/store/xg7d88c8x0sssr4zypcnrps6w4icgzz3-wrapper//manifest.nix&apos; -&gt; `/nix/store/r8l782xq0ka0c5cifip27j43y3b4px41-wrapper/manifest.nix&apos; -&gt; `unused&apos;</span>
<span style="color:#AAAAAA">wrapper&gt; created 7 symlinks in user environment</span>
<span style="color:#AAAAAA">wrapper&gt; ++ set +x</span>
<span style="color:#AAAAAA">floxShell&gt; warning: AWS error uploading &apos;nix-cache-info&apos;: Access Denied</span>
<b>Installed &apos;/nix/store/0c454n5gxgvb1vmvpkq7psj2wnyrlivc-flox-prerelease-0.2.3-r544&apos; package(s) into &apos;testrm&apos; environment.</b>

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@saas-dev:~/src/floxEM]$</b></span> flox list -e testrm
limeytexan/x86_64-linux.testrm
    Alias     testrm
    System    x86_64-linux
    Path      /home/brantley/.local/share/flox/environments/limeytexan/x86_64-linux.testrm
    Curr Gen  1

Packages
    0  /nix/store/0c454n5gxgvb1vmvpkq7psj2wnyrlivc-flox-prerelease-0.2.3-r544  0c454n5g

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@saas-dev:~/src/floxEM]$</b></span> flox rm -e testrm 0
<span style="color:#AA0000">error:</span> cannot modify &apos;<span style="color:#AA00AA">packages.&quot;/nix/store/0c454n5gxgvb1vmvpkq7psj2wnyrlivc-flox-prerelease-0.2.3-r544&quot;</span>&apos; : <span style="color:#AA00AA">No such attribute</span>

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@saas-dev:~/src/floxEM]$</b></span> flox rm -e testrm 0c454n5g

<b>ERROR: Package &apos;0c454n5g&apos; not found in &apos;testrm&apos; environment.</b>

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@saas-dev:~/src/floxEM]$</b></span> flox rm -e testrm /nix/store/0c454n5gxgvb1vmvpkq7psj2wnyrlivc-flox-prerelease-0.2.3-r544
<span style="color:#AA0000">error:</span> cannot modify &apos;<span style="color:#AA00AA">packages.&quot;/nix/store/0c454n5gxgvb1vmvpkq7psj2wnyrlivc-flox-prerelease-0.2.3-r544&quot;</span>&apos; : <span style="color:#AA00AA">No such attribute</span>

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@saas-dev:~/src/floxEM]$</b></span> 
</pre>

**Comment by aakropotkin** [comment]
I might have fixed this with https://github.com/flox/flox/pull/191
But need to confirm

**Comment by stahnma** [comment]
@aakropotkin can you confirm?

**Comment by ghudgins** [comment]
@aakropotkin - ping - looking for a quick update

**Comment by aakropotkin** [comment]
Nah this problem still exists:
```console
~ % nix build nixpkgs#hello                                                                          18:11:10
~ % flox install -e py2 $( readlink -f ./result; )                                                   18:11:15
warning: remote HEAD refers to nonexistent ref, unable to checkout
warning: input 'flox-floxpkgs/etc-profiles' has an override for a non-existent input 'flox-floxpkgs'
profile> /nix/store/llgcd5364qaqihv77n5xgfrwiq3m1zsp-profile
wrapper> ++ /nix/store/zz4khfifdxijpfrj32lfxqrycilbvzaa-perl-5.36.0/bin/perl -w /nix/store/42p1h90d93lk9fdh11xxcv8qs6mhs7fm-builder.pl
wrapper> warning: creating dangling symlink `/nix/store/bdgxhkhw3zafw0p8y3p063hyj7dxdiag-wrapper//manifest.nix' -> `/nix/store/zdbd3xhxb0wzb7bnzhinnc1bm879kw6f-wrapper/manifest.nix' -> `unused'
wrapper> created 28 symlinks in user environment
wrapper> ++ set +x
Installed '/nix/store/s66mzxpvicwk07gjbjfw9izjfa797vsw-hello-2.12.1' package(s) into 'py2' environment.
~ % flox remove -e py2 $( readlink -f ./result; )                                                    18:11:33
warning: remote HEAD refers to nonexistent ref, unable to checkout
error: cannot modify 'packages."/nix/store/s66mzxpvicwk07gjbjfw9izjfa797vsw-hello-2.12.1"' : No such attribute
~ 1 % flox list -e py2                                                                               18:11:42
aakropotkin/x86_64-linux.py2
    Alias     py2
    System    x86_64-linux
    Path      /home/camus/.local/share/flox/environments/aakropotkin/x86_64-linux.py2
    Curr Gen  2

Packages
    0  stable.nixpkgs-flox.python2                               python-2.7.18.5
    1  /nix/store/s66mzxpvicwk07gjbjfw9izjfa797vsw-hello-2.12.1  s66mzxpv
~ %
```

**Comment by ghudgins** [comment]
will be addressed by new manifest. we do not have a requirement to support installations to underlying flox primitives directly.
