### ISSUE TITLE
Pushing an environment that has been deleted upstream fails

### ISSUE THREAD

**Issue by nicklewis** [flox/flox#1565]
**Describe the bug:**

**Steps to reproduce:**
1. `flox init`
2. `flox push`
3. Delete environment in FloxHub
4. `flox push`

Result:

Push fails with the message:

```
❌ ERROR: Failed to fetch updates for environment: ref not found
```

Expected:

Successful push.

**Analysis**

It seems this happens because we first try to pull updates before pushing. If that fails, we should treat the environment as a new push.

**Comment by ghudgins** [comment]
@nicklewis / @ysndr to confirm estimate
