### ISSUE TITLE
Improve messaging when upgrade only changes catalog page

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1570]
In some cases, a `flox upgrade` will preserve derivations of all packages, but the catalog page/revision of nixpkgs will change. This prints the message:
```
ℹ️  No packages need to be upgraded in environment 'name'.
```
but then the lockfile is modified, which could be confusing.

We could either:
1. Not write the changes to the lockfile. That discards the information that there isn't an upgrade at some point in time, which isn't meaningless. I'm not sure if it's valuable.
2.  Print the message (needs rewording):
  ```
  ℹ️  No packages need to be upgraded in environment 'main'. A record of checking for an 'upgrade' was written to the lockfile.
  ```

**Comment by mkenigs** [comment]
Deciding between 1. and 2. above is user-facing, ping @ghudgins @jennymahmoudi

**Comment by jennymahmoudi** [comment]
I would choose #1.

It sounds like we don't tell the user that "the catalog page/revision of nixpkgs will change" at all and if so, I'd agree that probably is not something we need to be user-facing right now.
