### ISSUE TITLE
Start process-compose on activation with flag

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1581]
Activating an environment with the `--start-services` flag should start process compose with the config rendered from the `services` manifest section.
- Add the `flox activate --start-services` flag
- In the `activate` script, start `process-compose` after `hook.on-activate` has run, passing `process-compose` the path to the rendered YAML file that's stored in the environment and the path to store the socket.
- Add an integration test that covers the socket being recreated if a stale file already exists.
- Continue integration testing with a "service" that writes a file until #1753

**Comment by zmitchell** [comment]
This should also detect and clean up a socket file left behind by a prior process-compose instance that crashed.

**Comment by mkenigs** [comment]
Starting process-compose should be pretty straightforward (just use `--config` and `--unix-socket`)

Issues are:
- Passing unix socket to the activate script
- Passing start services true/false to the activate script

We could do that with 2 env vars, but we keep adding more and more env vars so I'm starting to think it may be cleaner to pass a flat JSON file.

We should have an integration test to check that `process-compose` is up and can connect via the unix socket. To do that we'll need the socket path, so either we need to write the integration tests in Rust, or we need to make it easy to figure out the socket path in Bash.

**Comment by mkenigs** [comment]
> This should also detect and clean up a socket file left behind by a prior process-compose instance that crashed.

Does `process-compose` already do this?

**Comment by mkenigs** [comment]
Do we need to record the process-compose PID somewhere?

**Comment by mkenigs** [comment]
> > This should also detect and clean up a socket file left behind by a prior process-compose instance that crashed.
> 
> Does `process-compose` already do this?

`process-compose --unix-socket /tmp/flox.sock up`, `killall -9 process-compose`, `process-compose --unix-socket /tmp/flox.sock up` seems to work fine, so I'm not sure if any additional cleanup is necessary?

**Comment by mkenigs** [comment]
Should we pass the unix socket and whether to start services to the activation script as env vars or in a JSON file?

**Comment by zmitchell** [comment]
I think:
- Should the activation script accept arguments
- If so which data should be passed as arguments vs environment variables

are both questions that are larger than this ticket.

**Comment by mkenigs** [comment]
> I think:
> 
>     * Should the activation script accept arguments
> 
>     * If so which data should be passed as arguments vs environment variables
> 
> 
> are both questions that are larger than this ticket.

Because two pieces of data have to be passed for this ticket, I think it's reasonable to pass them in a JSON file if that's non-controversial and low effort. If it's controversial or high effort, I think the questions you're asking should be addressed later

**Comment by zmitchell** [comment]
Looks like it removes it on startup: https://github.com/F1bonacc1/process-compose/blob/3cd252df8d3a6852aea56efddf5f77eece7d5406/src/api/server.go#L17

**Comment by dcarley** [comment]
I jumped the gun slightly, before seeing the conversation, and passed an environment variable for the socket down in https://github.com/flox/flox/pull/1712 which had the side-effect of making the integration tests slightly easier and wiring in the existing socket path code. I think we should do the same for the config, for now, and then refactor later.
