### ISSUE TITLE
Ensure starting services is idempotent for projects

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1584]
`flox activate --start-services` and `flox services start` should not start services again if services are already running for this project.
- You can accomplish this by checking for the presence of the socket file for this path.
- It may be possible for `process-compose` to leave the socket file behind if it crashes, so you should perform a simple call to `process-compose` to see if it's still alive. If it's alive, services are presumably already running, if it's dead, then you can clean up the socket file and start the services.

**Comment by mkenigs** [comment]
What do we do in the case that services have been modified since starting services? I think we probably need to check if the environment has been rebuilt since the last activation, and if it has, we need to check if services have changed. Or we can defer that?

**Comment by mkenigs** [comment]
If the running services are out of sync with the manifest, just error for now. For now, if the environment needs a rebuild for any kind of change, treat that as out of sync

**Comment by dcarley** [comment]
I think we should do the simplest thing of checking whether the socket is present and working for now. Then changes to services will be handled later in https://github.com/flox/flox/issues/1615 and https://github.com/flox/flox/issues/1592

**Comment by mkenigs** [comment]
Are you saying we shouldn't even check if the environment needs a rebuild?

**Comment by zmitchell** [comment]
Discussed offline and came to this resolution:
- If services are not running, silently start them as part of activation (we already do this).
- If services _are_ running, continue the activation with a warning.

The warning should look like this:
```
⚠️ Skipped starting services, services are already running
```

This allows a user to get into a weird state if they have running services, change their manifest, then `flox activate -s` expecting new services, but we have tickets planned for detecting manifest changes and messaging to the user that action is required on their part so it shouldn't be a surprise at activation-time.
