### ISSUE TITLE
Don't allow remote environments to start services

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1585]
We haven't designed how service management should handle remote environments, so for now we'll prevent remote environments from starting services at all.

Display an error message when trying to start services from a remote environment:
```text
$ flox activate -r owner/name --start-services
❌ Error: Services are not yet supported for remote environments
```

**Comment by dcarley** [comment]
This is already done: https://github.com/flox/flox/blob/545f9a455fa337f8202e954cea4e6fa005d04c83/cli/tests/environment-remote.bats#L370-L385

I'll raise a small PR to tweak the wording for capitalisation.
