### ISSUE TITLE
Start services imperatively

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1591]
When within an activation:
- `flox services start` starts all services
- `flox services start [name ...]` starts the named services
- The above commands:
  - Start `process-compose` in the background
  - If there is a running `process-compose`, but all the services are stopped, the running instance of `process-compose` is killed and a new one is started.
  - If there are stopped services and `start` is called without additional arguments, the stopped services are started.
  - Noop with a message if the service(s) are already started
  - ~block until the `process-compose` command returns~ (not reasonable until we have health checks)
  - Error if any of the named services don't exist
  - Error if called within a remote environment

When not within in activation:

- an error is returned because we can't ensure that a newly started `process-compose` will be shutdown

**Comment by zmitchell** [comment]
If the environment has been rebuilt while the services are running you likely need a reactivation in order for the next startup of services to pick up the changes, otherwise a start/restart may have surprising behavior (e.g. read the recently-built config and try to start a service which may use binaries that are only present after the rebuild).

**Comment by dcarley** [comment]
Notes for refinement:
- `process start` only takes a single name argument so we'll have to loop over them like we do for `stop` but implementing both at the same time isn't any harder
- `process start` does distinguish from [already started and unknown services](https://github.com/F1bonacc1/process-compose/blob/v1.9.0/src/app/project_runner.go#L258-L271) unlike `stop` in #1771
- `process start` returns before the actual process has been [started in a goroutine](https://github.com/F1bonacc1/process-compose/blob/v1.9.0/src/app/project_runner.go#L126-L137) but the "blocking" behaviour would be consistent with the experience of `flox activate --start-services`
- we are now allowing imperative commands from outside an activation
- we don't need to prompt for re-activation if services weren't previously running because `_FLOX_SERVICES_SOCKET` is only used by activation scripts and tests; everything else gets a deterministic path for the environment
- does "register with watchdog" now mean? should flox always pass a socket path and klaus only attempt to shutdown if it exists?

**Comment by ysndr** [comment]
> start process-compose in the background

Don't we unconditionally start process compose in the background with each activation?
Is that supposed to get dropped in favor of starting process-compose from flox, or do we require _both_, starting from `$FLOX_ENV/activate` and `flox service start`?

**Comment by dcarley** [comment]
> Don't we unconditionally start process compose in the background with each activation?

Only when `--start-services` is provided and subsequent calls with the flag are idempotent.

> Is that supposed to get dropped in favor of starting process-compose from flox, or do we require _both_, starting from `$FLOX_ENV/activate` and `flox service start`?

We require both, which is shame because we'll need to maintain implementations in both Bash and Rust 😞
