### ISSUE TITLE
Stop services imperatively

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1593]
When within an activation:
- `flox services stop` stops all services
- `flox services stop [name ...]` stops the named services
- the above commands:
  - don't do anything if the service(s) are already stopped
  - block until the services have finished stopping
  - error if any of the named services don't exist
  - error if called within a remote environment

When not within in activation
- an error is returned because we are only supporting services within activations for now.

**Comment by mkenigs** [comment]
- `process-compose process stop` appears to be blocking
- Seems like integration tests will fit pretty well here

**Comment by mkenigs** [comment]
> When within an activation:
> When not within in activation
> 
>     * an error is returned because we are only supporting services within activations for now.

We decided `stop` doesn't need to be run from inside an activation https://github.com/flox/flox/pull/1763#discussion_r1676174096
