### ISSUE TITLE
Restart services imperatively

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1594]
When within an activation:
- `flox services restart` restarts all services
- `flox services restart [name ...]` restarts the named services 
- the above commands:
  - the running `process-compose` is killed and a new instance is created when:
    - either all services are currently stopped or no `name` argument is given
    - this is needed to pick up manifest changes per https://github.com/flox/flox/issues/1885
    - new `process-compose` should be started in an ephemeral activation
    - expose the ability for the provider to stop `process-compose` and re-use the same function in the watchdog after https://github.com/flox/flox/pull/1871
  - starts the included service(s) if they are currently stopped
  - ~block until the services have finished restarting~ (not reasonable until we have health checks)
  - error if any of the named services don't exist
  - error if called within a remote environment

When not within in activation:

- an error is returned because we can't ensure that a newly started process-compose will be shutdown

**Comment by zmitchell** [comment]
We decided that we should support commands other than `start` from outside an activation given that #1770 means we no longer need to worry about a particular shell owning the lifecycle of services.

**Comment by zmitchell** [comment]
If the environment has been rebuilt while the services are running you likely need a reactivation in order for the next startup of services to pick up the changes, otherwise a `start`/`restart` may have surprising behavior (e.g. read the recently-built config and try to start a service which may use binaries that are only present after the rebuild).

**Comment by dcarley** [comment]
> We decided that we should support commands other than `start` from outside an activation given that #1770 means we no longer need to worry about a particular shell owning the lifecycle of services.

Updated back to denying outside activation because like #1770 we need to start `process-compose` in an activation where it will be cleaned up. We can improve this behaviour later by being more clever about whether services are currently running.
