### ISSUE TITLE
Add service status command

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1597]
Inside or outside of an activation:
- `flox services status` shows the status of all services
- `flox services status [name ...]` shows the status of the named services
- the above commands:
  - error if any of the named services don't exist
  - error if called within a remote environment

CLI output
https://www.notion.so/floxdev/Services-status-output-53ee184e2b5b4b7d8d565041b5b555bf?d=aa55b8bc81ec4d75a7dc443f730431cb#9f6f13a0bae14428ad80204d6f0f826a

**Comment by mkenigs** [comment]
Seems like this needs some design for exactly what these commands output.

Other than that, assuming the info below is all we need, it looks like this will be a pretty straightforward passthrough to
`process-compose process list -o json`, which gives the following info:
```
	{
		"name": "name",
		"namespace": "default",
		"status": "Running",
		"system_time": "3m",
		"age": 201176524083,
		"is_ready": "-",
		"restarts": 0,
		"exit_code": 0,
		"pid": 16083,
		"IsRunning": true
	}
```

**Comment by mkenigs** [comment]
From refinement: add a `flox-services-status` man page in a separate docs directory

**Comment by mkenigs** [comment]
We already have most of the plumbing for this

**Comment by jennymahmoudi** [comment]
Draft of output in Notion so we can comment:
https://www.notion.so/floxdev/Services-status-output-53ee184e2b5b4b7d8d565041b5b555bf?pvs=4

**Comment by dcarley** [comment]
One more PR to come because Jenny suggested wrapping inactive PIDs in square brackets:
- https://flox-dev.slack.com/archives/C05P6A5J6U8/p1722870163091989
- https://www.notion.so/floxdev/Services-status-output-53ee184e2b5b4b7d8d565041b5b555bf
