### ISSUE TITLE
Indicate to user which activation owns and will stop services when exited

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1600]
When services are first started by `flox activate`, `flox services start`, or `flox services restart`:
- output an info message explaining that the services will be stopped when the activation is exited
- update the shell prompt with an emoji to indicate that the activation "owns" the services
  - Q: do we skip if the user has already modified their prompt?

We're tying the watchdog cleanup of services (#1588) to the first activation that has started services because we don't currently have an easy way to track the last remaining activation. If we don't warn the user about this then the services may be shutdown unexpectedly when they exit that first activation.

**Comment by jennymahmoudi** [comment]
If you do `flox activate --start-services`, can you use `flox services stop` to stop services in another shell? Or does `flox services stop` also need to be used in the first activation shell?

**Comment by jennymahmoudi** [comment]
Depending on the answer to my previous question, might need to change the wording, but how about:

```
flox activate --start-services
✅ You are now using the environment 'myenvironment' with services.
To stop the services, use 'flox services stop' or 'exit' in this shell. 

flox [myenvironment (services)]
```

If you activate the environment elsewhere, you would see the normal activation message and the normal env prompt without the `(services)` label. 
```
flox activate 
✅ You are now using the environment 'myenvironment'.
To stop using this environment, type 'exit'

flox [myenvironment]
```

I'd prefer to be explicit about services in the prompt, following the `(remote)` pattern rather than an emoji, but open to hear other ideas here.

**Comment by dcarley** [comment]
> If you do flox activate --start-services, can you use flox services stop to stop services in another shell? Or does flox services stop also need to be used in the first activation shell?

Good question. My initial reaction was that we should allow the imperative service commands from anywhere once the service manager has already been started because the fact that the lifetime is currently tied to the first activation is a technical limitation that's pretty arbitrary to the user. However, whilst we have that limitation, restricting the write commands (start, stop, restart) to that first activation might make it clearer that the first activation is currently "special". Read commands (status, logs) could still happen from anywhere though.

**Comment by jennymahmoudi** [comment]
> > If you do flox activate --start-services, can you use flox services stop to stop services in another shell? Or does flox services stop also need to be used in the first activation shell?
> 
> Good question. My initial reaction was that we should allow the imperative service commands from anywhere once the service manager has already been started because the fact that the lifetime is currently tied to the first activation is a technical limitation that's pretty arbitrary to the user. However, whilst we have that limitation, restricting the write commands (start, stop, restart) to that first activation might make it clearer that the first activation is currently "special". Read commands (status, logs) could still happen from anywhere though.

Agreed. I think limiting write commands to the first activation is the best option. How temporary is this limitation? Indefinitely? Or is there a specific milestone where we won't have this limitation?

That would avoid situations like this which could happen if we allowed write commands from any shell:
`Activation #1` starts services, and is "special"
`Activation #2` uses `services stop` and now the first activation is no longer special

But maybe we are being too limiting. Consider this situation:
`Activation #1` starts services, and is "special"
`Activation #2` cannot start, stop or restart services
`Activation #1` exits, so services are stopped.

Can activation #2 now start services?



If we do limit write commands, for write commands done in another shell, we'll need some error messaging there. Something along the lines of...
```
❌ ERROR: Can not <command-name> services
Services must be controlled in the shell where they started. The prompt will contain '(services)'  
```

**Comment by zmitchell** [comment]
Limiting write commands to the first activation feels very restrictive to me.

Currently in that second scenario you would need to start services in a third activation. Furthermore, that second activation currently has no way of starting services at all since the existing `process-compose` will get cleaned up when the first activation terminates. The second activation also has no way of spawning a new `process-compose` instance. That's an easy workaround (e.g. "if starting services and there's no `process-compose`, start a new one"), but now you're in a pickle because the watchdog for the second activation has no idea it's supposed to clean up this new `process-compose`, and we currently have no way to "promote" it to being responsible for cleanup duty.

What makes sense to me is a mechanism for transferring ownership of cleanup duty. I think you could transfer ownership based on which services were stopped and whether new ones were started.
- If _all_ services have been stopped, and a different activation starts services, it now owns cleanup duty.
- If _all_ services have been stopped, but no new ones have been started, the original activation still owns cleanup duty.
- If _some_ services have been stopped, the original activation still owns cleanup duty.
- If the owning activation has terminated, any other activation can start services and will own cleanup duty.

Transferring ownership of cleanup duty is, technically speaking, a bit of a circus.

On macOS you can tell a process to listen for termination of an arbitrary process, but you can't do that on Linux, so you can't transfer a watchdog between processes. What you _can_ do is tell a watchdog that it's no longer responsible for cleanup. We can use signals for this.

The watchdog will already use a signal handler on Linux to be notified when its activation has terminated (the particular signal is configurable and I believe we'll use SIGUSR1), and I imagine we would build the same signal handler into macOS for feature parity. We can use a second signal to tell the watchdog that it's no longer responsible for cleanup, and a third signal to tell a watchdog that it's newly responsible for cleanup. We can use SIGUSR2 for one of these and some other random, rarely used signal for the other.

How do you know which watchdog to send signals to? One way to do this would be for the watchdog of the activation that starts services to write its PID to `.flox/cache/watchdog.pid` on startup. Now any activation that wants to take ownership can read the PID in that file, send a signal to that watchdog, then write its own PID to the file. When the owning activation is terminated, its watchdog cleans up the file to signal to other watchdogs that no one is in currently in charge.

How does an activation promote its own watchdog? During activation it can store the PID of its watchdog in an environment variable. Now any `flox` invocation can read that environment variable to find the watchdog for that activation.

Like I said, it's a circus, but ultimately I think being able to start and stop services from any activation is necessary.

This actually all becomes _way_ easier if we have a Flox daemon. The way that would work is when you activate you register the activation for that project with the daemon. The daemon keeps track of whether there is a `process-compose` for the project. Service commands go through the daemon and the daemon is responsible for cleaning up `process-compose` when the last activation for that project terminates. You no longer need a watchdog at all because when you register with the daemon it can keep track of the PIDs for the activations and monitor them for termination (using `kqueue` on macOS like a civilized person, and just polling to see if the PID still exists on Linux like a barbarian). Of course you could also keep the watchdog around and when its parent terminates have it notify the daemon.

**Comment by dcarley** [comment]
> Could we just start a watchdog for every single activation and add the watchdog's PID to the environment registry. Then when the parent exits, the watchdog removes itself from the environment registry, and if it's the last one, it performs cleanup duty?

Yep! We previously punted on "last activation out" because we couldn't determine the last activation but this looks like it will do fine. I've created https://github.com/flox/flox/issues/1770 and updated https://github.com/flox/flox/issues/1588 and then we'll close this ticket if we don't foresee any other issues by the end of the week.

**Comment by dcarley** [comment]
Closing in favour of https://github.com/flox/flox/issues/1770
