### ISSUE TITLE
Provide service specific reactivation advice when manifest changes

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1615]
Warn the user to reactivate the current activation _and_ the shell that started services when the manifest has `[services]` and other sections of the manifest have changed which may affect the behaviour of services such as `[vars]` and `[hooks]`.

The idea is that `hook` and `vars` changes require a reactivation regardless of the presence of services, so the current shell needs to reactivate. However, changing `hook` and `vars` could also affect service configuration, so the shell that started the services also needs to reactivate to pick up the new config for the services.

If the user has _only_ edited the `services` section, we should show the user a message indicating whether they need to reactivate the current shell (if the current shell started services) or some other shell (the shell that started services).

**Comment by zmitchell** [comment]
Another scenario is that the user has changed the `[install]` section without changing `[services]`. If a user changes a version constraint on `foo` and they're using `foo` inside a service, then they likely want the new version of `foo` running in that service.

So really, `profile` is the only section where changes don't potentially affect services.

**Comment by zmitchell** [comment]
This ticket is outdated, closed in favor of https://github.com/flox/flox/issues/1885
