### ISSUE TITLE
Block activate on services starting

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1640]
`flox activate --start-services` prints a spinner while services are starting. When finished, a message and exit code indicate whether the services were successfully started.

We won't have implemented `flox services logs` or `flox services restart` by this point so the failure message can only give minimal advice.

**Comment by zmitchell** [comment]
The complexity here is determining when services are up and "healthy". Consider a few scenarios:
1. The user's services start and successfully complete very quickly (e.g. `touch hello.txt`).
2. The user's services start and immediately crash.
3. The user's services start and some immediately crash.

That's all assuming `process-compose` itself starts up successfully. You also need to handle the case where it crashes and deletes the socket as it shuts down.

The way you would normally check that everything is up and running is via the `process-compose process list -o json` command. If you get non-empty JSON back, that indicates that at least `process-compose` is running. Should that count as "good enough" to proceed with the activation?

**Comment by mkenigs** [comment]
- We need to make sure process-compose starts successfully
- We can't meaningfully wait any time period for services to be running until we have healthchecks
- Maybe add some messaging that makes it clear that we aren't guaranteeing services are healthy, or at least something in the man page
- Poll `process-compose process list`, fail the activation after some timeout. Do polling and messaging in Bash, maybe output stderr from process-compose. Either redirect stderr to a file or use `process-compose` flags for logs

**Comment by dcarley** [comment]
Somewhere between "the socket is created and functioning" sounds fine to me. It would allow us to remove [this check in our integration tests](https://github.com/flox/flox/blob/d2328ffa08a5908fb3a50f30f5934128313be86c/cli/tests/services/start_and_cleanup.sh#L23-L25) but wouldn't necessarily allow us to prevent issues like https://github.com/flox/flox/pull/1779 in normal usage.
