### ISSUE TITLE
remove flox update from flox --help

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1642]
as of 1.1 it's no longer a part of Flox...we should not display it in the results of `flox --help`

STR:
* `flox --help`

Result: see `update` listed
Expected: no `update` command listed

from @robinbrantley:

![image](https://github.com/flox/flox/assets/5465514/6eda6561-30e5-4919-bd29-da70bfce0e53)

**Comment by ysndr** [comment]
ah i did hide it but its manually added so that's why its still there...
