### ISSUE TITLE
Cleanup the `Git` wrapper

### ISSUE THREAD

**Issue by ysndr** [flox/flox#165]
We carry the `GitProvider` abstractions for an awfully long time without ever unstubbing the `libgit` implementation.

* We have a lot of git generic code that is practically only ever called with `GitCommandProvider`
* The trait makes every change take 3x time because we have to add type declarations and methods in both impls.
* There's also very little though given on control and security around the `GitProvider` trait which it inherited from the `git2` crate (and based on the fact that git is a huge side effect and majorly impure from the view of another program)
* git2 already implements the methods in `GitProvider` and even more granularly

To be done: 

- [x] remove the libgit2 impl or git shell impl
- [x] remove git trait
- [x] remove the generics around git
- [ ] ~make a safer/simpler abstractions per usecase~

To Discuss

- [x] why a trait? We're not making use of it should we double down on it instead e.g. for mocking?

**Comment by mkenigs** [comment]
I think at one point we also discussed using libgit2 for some things and git for other things. Can you remind me why we don't want to use libgit2 everywhere?

**Comment by ysndr** [comment]
I think git2 was said to be somewhat wonky about playing with existing configurations and authentication and errors.
We never used it for anything though.

Mixing them will be quite confusing since the implementation types are part of the state and can't easily be interchanged.

That said, using a higher level typed interface (git2) would actually be preferable over trying to parse git output for some commands.
We might be able to remove the entire git thing and build use case related wrappers like the `UpstreamRepo` one for publish, where we need them.

**Comment by zmitchell** [comment]
If we can use a wrapper that doesn't require `async` then we can remove `async` from `flox` entirely, and that would certainly simplify things. For instance, you currently can't write any recursive `async` functions that do `git` operations at any level because the `GitProvider` trait doesn't require that its Futures are `Send`.

I'm a huge proponent of limiting `async` to where it's actually useful, and that's not something we currently need. It's also a big dependency to pull in and makes the rest of the application more complex to build and debug.

**Comment by ysndr** [comment]
nb nix calls still require async so changing git does not quite allow us to remove all async stuff (https://github.com/flox/runix/issues/6)

Going forward i think we can make smaller "git wrappers" where they are needed.
E.g. models like `Upstream{Repo,Catalog}` which only implement git commands they need.
For perhaps easier commands there's https://docs.rs/execute/latest/execute/ or duct(?).

Anyway, we can mock those out at that level rather than bubbling through "the one and only" git abstraction that needs to implement methods that are mostly just used once.

**Comment by ghudgins** [comment]
closing in favor of the other issues
