### ISSUE TITLE
Remove pkgdb scrape

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1674]

**Comment by mkenigs** [comment]
Afaict this shouldn't happen without explicitly setting `FLOX_FEATURES_USE_CATALOG=false`. We scrape in update, which is deprecated:
https://github.com/flox/flox/blob/93a11d728b796ab4ec41d23f52a3deb85d952a07/cli/flox/src/commands/update.rs#L182

And we scrape in init, but that's behind a check for the catalog being disabled:
https://github.com/flox/flox/blob/93a11d728b796ab4ec41d23f52a3deb85d952a07/cli/flox/src/commands/init/mod.rs#L147

Lock can implicitly trigger a scrape, which could still happen if someone has a version 0 manifest and runs flox activate, but I think that's enough of an edge case that we can leave that one for now, and we have https://github.com/flox/flox/issues/1624 to address that.

Reopen if I've missed a case we need to remove!
