### ISSUE TITLE
New Stray Output in Flox

### ISSUE THREAD

**Issue by stahnma** [flox/flox#168]
**Describe the bug:**

New stray output in flox.

Flox version: Version: 0.2.5-r553

**Steps to reproduce:**
1. `flox install <any package>`

Result: 
```

flox [flox/prerelease default] [0] stahnma@floxbox01 ~ № flox install -e bazel bazel
warning: input 'flox' has an override for a non-existent input 'nixpkgs-flox'
warning: input 'flox' has an override for a non-existent input 'nixpkgs-flox'
warning: input 'flox' has an override for a non-existent input 'nixpkgs-flox'
profile> /nix/store/9bix0iysn96853y3zvnq0niicjab0gch-profile
wrapper> ++ /nix/store/mbpzlzp2b291yqwybvsjfv5hdg0c6vd6-perl-5.36.0/bin/perl -w /nix/store/v1xl81d7q1zi9vc5a8a4vrqzqrrq4z3d-builder.pl
wrapper> warning: creating dangling symlink `/nix/store/b4lily3h2r7vw9y01f8y5jqw0vw6zsxm-wrapper//manifest.nix' -> `/nix/store/2nym458waslz5r7c8ycgggwz8gzhp0rs-wrapper/manifest.nix' -> `unused'
wrapper> created 7 symlinks in user environment
wrapper> ++ set +x
Installed 'bazel' package(s) into 'bazel' environment.
```

Expected: 
```
flox [flox/prerelease default] [0] stahnma@floxbox01 ~ № flox install -e bazel bazel
Installed 'bazel' package(s) into 'bazel' environment.
```

**Screenshots/terminal output (if relevant):**

⚠️ I know there are other tickets on the "input overrides" already. This is specific about the new "wrapper" and "profile" things.

**Comment by samrose** [comment]
Do we have a ticket anywhere for turning on debugging messages for flox, and for error handling? 

Usually when a tool like flox is produced, there is an option for turning on debug output for end users vs errors that we specifically want to display to end users @stahnma

**Comment by tomberek** [comment]
I am suspecting this is caused by: https://github.com/flox/flox/commit/b8df6326ea4900a7ed59a739998c81a609c1c750#diff-6e0214d8e9e75c53551ed10513e3de50739ad1c374cf8882135b9ea2bb82a154R485

It might be a debugging change that crept in.

**Comment by tomberek** [comment]
https://github.com/flox/flox/pull/212 for Review

**Comment by tomberek** [comment]
https://github.com/flox/nixpkgs-flox/pull/7
https://github.com/flox/floxpkgs/pull/162 (in spite of: ~~https://github.com/flox/floxpkgs/pull/158~~)
https://github.com/flox-examples/floxpkgs/pull/4

**Comment by nicklewis** [comment]
With the nixpkgs-flox/floxpkgs changes on 0.2.7:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmNWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7d85aec4810e7fdb0b0ddddc0d5716f12e09356c/image.png)
