### ISSUE TITLE
flox search with `.` 

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1684]
STR:
* `flox search rubyPackages_3_3.ruby2_keywords`

Expected: results
Actual: no resutls

**Comment by billlevine** [comment]
This is (at least) a current restriction in the service, to be addressed with flox/catalog-server#125.  If there is no restriction in the CLI, then this can be closed as a duplicate.

**Comment by mkenigs** [comment]
Afaict we're sending terms with `.` and just getting empty responses at the moment
