### ISSUE TITLE
Certain local git configuration can break flox pull

### ISSUE THREAD

**Issue by nicklewis** [flox/flox#169]
**Describe the bug:**

Including the following config in `~/.gitconfig` breaks `flox pull`.

```ini
[push]
default = upstream
```

**Steps to reproduce:**
1. Set the above config in `~/.gitconfig`
2. `flox pull` from a registry that has updates available

This happens because flox tries to push to the repo in `~/.cache` using simply the command `git push origin` without specifying a ref to push. The default behavior for that scenario (`default = simple`) is to push the current branch to a matching branch name, but `default = upstream` instructs git to push to the tracked upstream branch instead. There are several other values for this setting that will also cause problems (`default = nothing`, `default = matching`, etc).

This behavior should either be specified explicitly in the git `config` in the local cache repo or we should explicitly pass the refs to push to/from (`git push origin <ref>:<ref>`), to avoid interference from the user's `~/.gitconfig`.

Result: 

```
fatal: You are pushing to remote 'origin', which is not the upstream of
your current branch 'aarch64-darwin.default', without telling me what to push
to update which remote branch.
```

Expected: 

The pull should succeed.

**Comment by ysndr** [comment]
might be solved with https://github.com/flox/flox/pull/184 and is related to flox pull that is actively being redesigned, should we at least tag this issue as "legacy support"?

**Comment by nicklewis** [comment]
I think it's fine to close it as superseded by #184.
