### ISSUE TITLE
Delete pkgdb dead code and tests

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1696]
We no longer primarily use `pkgdb` as the backend for search and resolution. We should delete as much `pkgdb` code as possible that isn't necessary for building environments or activating old environments. This will cut down on build times in CI and in local development.

**Comment by zmitchell** [comment]
Breakdown:
- The main data structures outside of `buildenv`/`linkenv` are `LockedPackageRaw` and `LockedInputRaw`. There's also `Options::Allows`, but at first glance I can't tell if we need to keep that going forward.
- As far as I can tell, the only other dependencies outside of `nix` and `nlohmann-json` are on `types`, `utils`, and some other miscellaneous stuff.
- Since `buildenv` doesn't parse the manifest into a `Lockfile` or `LockfileRaw`, I think we can drop that entirely, which I think means we can also drop the `Manifest*` types.
- `LockedInputRaw` refers to `RegistryInput`s, so we probably need to keep that as well.
- Untangling the Makefile will be fun.

**Comment by mkenigs** [comment]
We may need to commit some v0 lockfiles rather than generating them during tests for behaviors we'll continue to support, i.e. buildenv
