### ISSUE TITLE
consider adding nodePackages_latest to Flox Catalog

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1697]
# Acceptance Criteria

* Ideally... `flox search nodePackages` returns results from `nodePackages_latest`

We should discuss this before doing it

**Comment by nicklewis** [comment]
@ghudgins Can we discuss on the ticket? What needs to be considered before doing this?

**Comment by ghudgins** [comment]
I think it's mostly an addition...but there was maybe some trepidation when we originally discussed it. I think it can proceed

**Comment by billlevine** [comment]
We can add an additional scrape path to `update-catalog` but will need to trigger a full re-scrape. Anything else we want to add at this time?

**Comment by ghudgins** [comment]
@billlevine should I see results for `flox search nodePackages`

**Comment by nicklewis** [comment]
@ghudgins We don't search by prefix unless you include a dot, so `nodePackages_latest.` shows results, as does a search for a specific node package.

**Comment by billlevine** [comment]
No, we don't search on upper parts of the attr path tuple.  You can search for 'vercel' as an example that will come up with stuff under nodePackages_latest.

I left this open while I monitor the re-scrape so I remember to check that it finished without error.  It's processing still and should be complete in the next 4-6 hours.  So, I'll follow up and close this once that's finished.

**Comment by ghudgins** [comment]
cool, LGTM!

**Comment by ghudgins** [comment]
cool, LGTM!

**Comment by billlevine** [comment]
Completed.
