### ISSUE TITLE
Abstract interacting with environment variables

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1699]
Some `flox` functionality reads environment variables (e.g. detecting the presence of a feature flag). Rust tests are run in parallel on separate threads in the same process, so setting an environment variable to test this functionality would leak the environment variable into _all_ tests.

In order to test this functionality I propose we add an abstraction for retrieving environment variables so that the environment can be mocked in testing. Something like this:
```rust
use std::env::VarError;

pub trait EnvVars {
    fn get(&self, key: impl AsRef<str>) -> Result<String, VarError>;
    fn set(&mut self, key: impl AsRef<str>, value: impl AsRef<str>);
    fn get_all(&self) -> BTreeMap<String, String>;
}

pub struct RealEnvVars;

impl EnvVars for RealEnvVars {
    fn get(&self, key: impl AsRef<str>) -> Result<String, VarError> {
        std::env::var(key.as_ref())
    }

    fn set(&mut self, key: impl AsRef<str>, value: impl AsRef<str>) {
        std::env::set_var(key.as_ref(), value.as_ref())
    }

    fn get_all(&self) -> BTreeMap<String, String> {
        std::env::vars().collect::<_>()
    }
}

pub struct MockEnvVars {
    pub vars: BTreeMap<String, String>,
}

impl MockEnvVars {
    pub fn new() -> Self {
        Self {
            vars: RealEnvVars.get_all(),
        }
    }
}

impl EnvVars for MockEnvVars {
    fn get(&self, key: impl AsRef<str>) -> Result<String, VarError> {
        self.vars
            .get(key.as_ref())
            .cloned()
            .ok_or(VarError::NotPresent)
    }

    fn set(&mut self, key: impl AsRef<str>, value: impl AsRef<str>) {
        self.vars
            .insert(key.as_ref().to_string(), value.as_ref().to_string());
    }

    fn get_all(&self) -> BTreeMap<String, String> {
        self.vars.clone()
    }
}
```

We would then add this struct to `Flox` at startup since `Flox` has become the place for storing global state during a `Flox` invocation.

**Comment by mkenigs** [comment]
We use `temp_env` in a few places. Are there cases that doesn't work for?
https://github.com/flox/flox/blob/353d4213491bb55db716d62e8cf9bff26b7fcc2c/cli/flox/src/utils/openers.rs#L199

**Comment by ysndr** [comment]
temp_env ensures some locking internally such that no two threads (that use temp_env) run at the same time.

abstracting out env vars like this would (probably minimally) speed up tests and may avoid vars set by a thread with temp_env leak into other tests that dont use this.
We havent observed the latter a far as i'm aware probably because we dont do a lot of env sensitive things in the `flox-rust-sdk` crate and do less unit testing in general in the `flox` crate. Nextests threading behavior might also be somewhat different.

From an ergonomics site i guess the `temp_env` approach is fine, although it is a bit in the way of a central testing infra.

**Comment by zmitchell** [comment]
So, I didn't know that `temp_env` existed, that's good to know, but like Yannik said it uses some locking internally. A case where it may cause a problem is if you're doing some work that checks an environment variable over the duration of the test (no current examples come to mind), which would block all other `temp_env` tests from proceeding. That's an edge case, but it exists.

I actually think that `temp_env` is fine, I just didn't know it existed or that we were using it already.
