### ISSUE TITLE
`list`: update lockfile if necessary

### ISSUE THREAD

**Issue by ysndr** [flox/flox#1710]
Currently, `flox list` uses the existing lockfile of an environment, and does not lock the env again (which would break listing other people's environment on floxhub with the current impl).

For `PathEnvironments` and (v. soon) `ManagedEnvironments` that means that manual edits of the manifest are not reflected in the commands output. I.e. the following tests currently fail:

```
@test "'flox list' shows local manifest (path)" {
  flox init
  tomlq -i -t '.install.hello."pkg-path" = "hello"' .flox/env/manifest.toml

  run "$FLOX_BIN" list
  assert_success
  assert_output --partial "hello"
}

# or with managed environments: 
@test "'flox list' shows local manifest" {
  make_empty_remote_env
  tomlq -i -t '.install.hello."pkg-path" = "hello"' .flox/env/manifest.toml

  run "$FLOX_BIN" list
  assert_success
  assert_output --partial "hello"
}
```

Possible changes are 
- check if `list` is listing a .flox managed environment and if yes, lock the environment
- ~change the impl of lockfile_path to lock if the manifest changed similar to activation path~

the latter would change the semantics of the method, and appears to introduce inconsistencies as the same method for remote envs would keep its semantics.

**Comment by ghudgins** [comment]
the related issues are all closed, can this be closed?

**Comment by ysndr** [comment]
I.e. path and managed environments will lock remote ends won't
