### ISSUE TITLE
Allow querying Sentry attributes

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1711]
Right now the data stored on a span (e.g. which command was run, options, etc) are not submitted to Sentry in a way that's queryable (or more generally, useful).

See this issue: https://github.com/getsentry/sentry-rust/issues/653

Note that our data is not prefixed with `tag` as in this issue. Once that issue is resolved we would need to change the names of our span attributes to start with `tags.` so that they're queryable in Sentry.

Once that data is queryable it becomes much more useful for answering questions like "how long did it take to install package X" or "how long did it take to perform a search with query X".

**Comment by ysndr** [comment]
should we create a new issue for the "upstreaming" part and change this issue to reflect our workaround?

**Comment by ghudgins** [comment]
"add description and close it" 
- standup today
