### ISSUE TITLE
bug: need to infer a default shell in the absence of `$SHELL`

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#1722]
**Describe the bug:**

Interactive invocations of `flox activate` currently require that one of `FLOX_SHELL` or `SHELL` be set in the environment, but this is not always the case, particularly when working in containers.

**Steps to reproduce:**
1. `unset SHELL`
2. `flox activate` (with any valid environment)

Result:

```
brantley@Michaels-MBP ~ % unset SHELL
brantley@Michaels-MBP ~ % flox activate -r limeytexan/default
❌ ERROR: SHELL environment variable not set: environment variable not found
brantley@Michaels-MBP ~ % 
```

Expected:

In a [slack thread discussion with David Aronchick](https://floxcommunitygroup.slack.com/archives/C06NYALM8P8/p1719843188646829?thread_ts=1719198502.521589&cid=C06NYALM8P8) we arrived upon the following desired behaviour:

* if `$FLOX_SHELL` defined then use that
    * else if `$SHELL` defined use that
        * else if parent process executable looks like a shell use that
            * else use the same `bashInteractive` that comes packaged with flox

**flox Version (run `flox --version` if possible):**

```
brantley@Michaels-MBP ~ % flox --version
1.1.0
```

**`uname -a` output:**

```
brantley@Michaels-MBP ~ % uname -a
Darwin Michaels-MBP.localdomain 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64
```

**Comment by mkenigs** [comment]
Not sure if it would be any better than falling back to `bashInteractive` but we could also fall back to the user's login shell

**Comment by limeytexan** [comment]
> Not sure if it would be any better than falling back to `bashInteractive` but we could also fall back to the user's login shell

Good suggestion! That's probably preferable to falling back to `bashInteractive`. FTR we would look that up with `getent passwd $USER | cut -d: -f7`, which would require the `unixtools.getent` package on Mac (which is perfectly fine).

**Comment by limeytexan** [comment]
Hmmm ... just saw this comment in the `bash(1)` man page:
```
SHELL  This variable expands to the full pathname to the shell.  If it is not set when the shell starts, bash assigns to it the full pathname of the current user's login shell.
```
Seems like `bash` should already be doing what we're contemplating, so perhaps we just need to change the logic on the rust to be more tolerant of a missing SHELL variable. I had thought this error was happening within the activate script side (perhaps it's manifesting in different ways on both sides).

**Comment by ysndr** [comment]
From the mentioned slack discussion i cannot tell whether the issue actually was that `SHELL` is unset in the said container.
In containers the entrypoint is also often set to `sh`, which we currently don't detect (as either bash or anything else)

**Comment by ysndr** [comment]
> FTR we would look that up with getent passwd $USER | cut -d: -f7, which would require the unixtools.getent package on Mac (which is perfectly fine).

macos does not use passwd to manage users...

on macos you could use 

```
sudo dscl . read /users/$USER UserShell |  cut -c 12-
```

**Comment by ysndr** [comment]
I think detecting the current parent shell would be concsistent with in-place activations (even though the priority is inverted).
Though in either case we should look at detecting `sh` either as bash or a separate shell to not fall over in containers with (only) sh, or indeed fall back to a flox provided bash(Interactive)

**Comment by mkenigs** [comment]
For now we're just falling back to bash. If we decide it's worth looking at /etc/passwd we can do that in a separate ticket
