### ISSUE TITLE
Improve cross-system support now with catalog service

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1723]
**Describe the feature:**

Since the 1.1 release, if you attempt to imperatively install a package only available on one architecture it will fail. There is no way to make this work without manually editing the `manifest.toml`. I'd suggest that in several cases, we could simply install the package and limit the systems in the manifest directly. As an example if I have an enviornment and I run `flox install glibc`, I would expect that to work and to restrict `glibc` to be restricted to `linux` systems. 

If a package only has a subset of systems, and the installation is coming from one of those systems, we should make it just work™.  

As a further enhancement, we could look at all version of the package and see what systems it has been available for, and then give more helpful information to the user. 

**Acceptance criteria:**
1. I can run `flox init; flox install glibc` on a linux client and have it lock.

**Comment by ghudgins** [comment]
+1 from https://discourse.flox.dev/t/error-resolution-failed/928/1

**Comment by ghudgins** [comment]
consider keying off of `attr_path_not_found.not_found_for_all_systems` error code, once it's added

**Comment by ghudgins** [comment]
+1 from the `tart` package on darwin

**Comment by ghudgins** [comment]
possible ways to solve this:
* when installing capture the error for systems
* if the systems the resolution suggests limiting to match current systems then continue
* re-resolve with setting `package.systems = current system` for the package that errored

user sees it installed

**Comment by ghudgins** [comment]
messages LGTM! thanks for adding those (apologies for the bad screenshot)
<img width="910" alt="image" src="https://github.com/user-attachments/assets/7a5d2461-3a73-4f31-9e7f-d064ef07b3b8">
