### ISSUE TITLE
Allow for process-compose socket in envs with long path names

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1724]
**Acceptance criteria**

Ensure that the `process-compose` socket can be created when an environment's path is long/deep (i.e. > 104 characters). Add an integration test that confirms it.

**Why**

Based on https://github.com/flox/flox/issues/1583 and subsequent tickets we will be starting `process-compose` with a UNIX domain socket in `.flox/cache`. There is a character limit on sockets, as previously seen in https://github.com/flox/flox/pull/1331, which means that we'll be unable to create the socket if the environment's path is too long/deep.

I hit this problem when running the integration tests from https://github.com/flox/flox/issues/1579 in combination with [nix-direnv](https://github.com/nix-community/nix-direnv) on MacOS which resulted in:

- `TMPDIR=/var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.vfDA8u`
- `SOCKET_FILE: /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.vfDA8u/bats-run-luqb2b/test/3/test/service.sock`

**Refinement notes**

Ideas to explore:

- Extend the use of `${XDG_CACHE_HOME:-$HOME/.cache}/.flox`
  - Find a structure that would work for path, managed, and eventually remote envs
  - Consider encoding PID or hostname to prevent conflicts with machines sharing storage
- Use platform appropriate store like `/var/run`
  - Benefit of being `tmpfs` backed
  - Unlikely to be user-writeable

**Comment by mkenigs** [comment]
On systemd Linux we should use `$XDG_RUNTIME_DIR` per https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html (and not `/run/user` directly per https://www.freedesktop.org/software/systemd/man/latest/file-hierarchy.html). That will be something like `/run/user/$UID`. If that's unset I guess we should try to use `/tmp`. `XDG_RUNTIME_DIR` won't be set in containers, and `TMPDIR` will often be too long.

On macOS `/var/run` isn't writeable, so I think our best bet is `/private/tmp`.

**Comment by ysndr** [comment]
fyi on macos `XDG_RUNTIME_DIR` is unset, and there is not default, so

```rust
xdg::BaseDirectories::new().unwrap().get_runtime_directory()
```

will fail with `Err(XdgRuntimeDirMissing)`
