### ISSUE TITLE
Upgrade message may have a logic error

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1725]
**Describe the bug:**

When using flox, you get a reminder to upgrade to a newer version if one is available. However, in this case the version it recommends is older. 

```
stahnma@fedora:~/bar
> flox pull rossturk/flaim
✨ Pulled rossturk/flaim from https://hub.flox.dev/

You can activate this environment with 'flox activate'


🚀  Flox has a new version available. 1.1.0-31-g56301cd9 -> 1.1.0-28-g84a33517

Get the latest at https://flox.dev/docs/install-flox/#upgrade-existing-flox-installation
```

**Steps to reproduce:**
1. Run 1.1.0-31

Result:
Got output shown above

Expected:
To tell there isn't a new version, or if there is for it to actually be newer. 

Note: This was installed from by-commit channel. 

**`uname -a` output:**
Linux fedora 6.9.6-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 21 15:46:57 UTC 2024 x86_64 GNU/Linux

**Comment by mkenigs** [comment]
Do we have both a nightly channel and by-commit? It looks like we're probably setting `FLOX_SENTRY_ENV` to `nightly`for `by-commit` builds:
```
> curl https://downloads.flox.dev/by-env/nightly/LATEST_VERSION
1.1.0-28-g84a33517
```

**Comment by stahnma** [comment]
Step 1 is sort properly. :)

**Comment by stahnma** [comment]
Step 1 is sort properly. :)

**Comment by garbas** [comment]
> Do we have both a nightly channel and by-commit? It looks like we're probably setting `FLOX_SENTRY_ENV` to `nightly`for `by-commit` builds:
> 
> ```
> > curl https://downloads.flox.dev/by-env/nightly/LATEST_VERSION
> 1.1.0-28-g84a33517
> ```

There is no `by-commit` channel really. Each of `by-commit/<commit-sha>` could be considered a channel, but since there is always going to be only one version in `by-commit/<commit-sha>` there is no way to upgrade from it.

The sensible way was to make it `nightly` and if we only suggest to upgrade to newer version than this would not be a problem anymore.

**Comment by mkenigs** [comment]
> There is no `by-commit` channel really. Each of `by-commit/<commit-sha>` could be considered a channel, but since there is always going to be only one version in `by-commit/<commit-sha>` there is no way to upgrade from it.

So seems like we should never print an update notification for a by-commit build then?
