### ISSUE TITLE
`flox install` that builds from source should notify user

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1726]
**Describe the feature:**

It tells the user that a compilation or package build is happening. 

**Describe a use case of this feature:**

I run `flox install <somepackage not in the cache>` and I get a build happening. 

**Acceptance criteria:**
1. We tell the user that a build is happening and therefore may take a while. 

For an example: `flox install python311Packages.pytorch-bin` (at least for me)

**Comment by ghudgins** [comment]
the solution should mirror with https://github.com/flox/flox/issues/2219

**Comment by stealthybox** [comment]
Just noting that this output needs to consistent in all places that could cause a build of a dependency
- install
- activate (ex: git clone / flox activate -r flox/verba)
- edit
- build ? (would this show more information?)

are there any others?

**Comment by mkenigs** [comment]
> are there any others?

pull. I think push too actually (git clone && flox push)

**Comment by mkenigs** [comment]
Closing in favor of https://github.com/flox/flox/issues/2219
