### ISSUE TITLE
Mac Install bug: `brew install flox` --> `flox not found`

### ISSUE THREAD

**Issue by neoakris** [flox/flox#1732]
**Describe the bug:**
The docs say to run `brew install flox` to install on mac, I get a false positive success message, because it says install succeeded, yet flox command not found. 

**Steps to reproduce:**
1. I'm on a Mac M3 (ARM based) so maybe the current Mac install only works for Intel Macs?
2. `brew install flox`
```console
==> Downloading https://downloads.flox.dev/by-env/stable/osx/flox-1.1.0.aarch64-darwin.pkg
############################################################################################################################## 100.0%
==> Installing Cask flox
==> Running installer for flox with sudo; the password may be necessary.
installer: Package name is Flox
installer: Installing at base path /
installer: The install was successful.
🍺  flox was successfully installed!
```
3. `brew install flox`
```console
==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: Not upgrading flox, the latest version is already installed
```
4. (Open a fresh terminal, then) `which flox`
```console
flox not found
```

**Result vs Expectations:**
I'd figure the installer would have put flox in my path, but doesn't seem to work.
Luckily the MacOS - Pkg GUI based installer worked without issue.

**flox Version (run `flox --version` if possible):**
Can't run, but brew tried to install 1.1.0

**`uname -a` output:**
```console
Darwin Chriss-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030 arm64
```

**Comment by tomberek** [comment]
Did you already have Nix installed? (if so, which installer?). What is your PATH set to?

Any logs you can send us from ~/Library/Logs/Homebrew that might shed some light?

**Comment by neoakris** [comment]
**Q1: Did you already have Nix installed? (if so, which installer?).** 
A1: Yes I had tried out devbox, then devenv (which had me manually install nix), I wasn't satisfied with either so I then tried flox.dev. (`brew` never complained about nix being pre-installed, but the Mac OS pkg GUI based installer noticed it was preinstalled and mentioned a message about removing and recreating a nix install.)

**Q2: What is your PATH set to?**
A2: Note: This is after I installed flox using the MacOS pgk method (which placed it at /usr/local/bin/flox) (Also other apps installed view brew have worked fine)
`echo $PATH`
```console
/Users/chris.m/.gem/bin:/opt/homebrew/opt/node@20/bin:/Users/chris.m/.rd/bin:/Users/chris.m/.krew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/terminal kitty.app/Contents/MacOS:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/chris.m/.rd/bin
```

**Q3: Any logs you can send us from ~/Library/Logs/Homebrew that might shed some light?**
A3: `ls -lah ~/Library/Logs/Homebrew` seems to show nothing related to flox
```console
drwxr-xr-x@  7 chris.m  staff  224 Jun 28 16:57 .
drwx------+ 25 chris.m  staff  800 Jun 23 20:14 ..
drwxr-xr-x   2 chris.m  staff   64 Jun 28 16:56 ca-certificates
drwxr-xr-x   2 chris.m  staff   64 Jun 28 16:57 node
drwxr-xr-x   2 chris.m  staff   64 Jun 28 16:57 node@20
drwxr-xr-x   2 chris.m  staff   64 Jun 28 16:57 openssl@3
drwxr-xr-x   4 chris.m  staff  128 Jun 28 16:57 python@3.11
```

**Comment by stahnma** [comment]
Should we close this as unable to reproduce?

**Comment by neoakris** [comment]
Had some WIP to take care of before being able to circle back to this. 

It failed for me, when flox v1.1.0 was the latest. 
After seeing Tom's comment, I retested by uninstalling the version of flox I had installed, then used brew to reinstall, now latest flox (v1.2.1) installed successfully using brew, so the issue seems to be fixed now. 

Thanks all!
