### ISSUE TITLE
Mac Package Install Bug: `flox install nodePackages.aws-cdk@2.133.0`

### ISSUE THREAD

**Issue by neoakris** [flox/flox#1733]
**Describe the bug:**
Please correct me if I'm wrong, but I think I've found a bug. 
(I'll give some background context b4 diving into the bug, to help the issue be understood.)

While investigating AWS CDK Blueprints for EKS
I noticed the latest version of the project's README.md mentions 
```text
cdk --version
# must output 2.147.3
```

The project has an older release tag (blueprints-1.14.1)
https://github.com/aws-quickstart/cdk-eks-blueprints/tree/blueprints-1.14.1?tab=readme-ov-file#getting-started-1
that mentions
```text
cdk --version
# must output 2.133.0
```

`flox show nodePackages.aws-cdk`
```console
nodePackages.aws-cdk - CDK Toolkit, the command line tool for CDK apps
    nodePackages.aws-cdk@2.146.0
    nodePackages.aws-cdk@2.144.0
    nodePackages.aws-cdk@2.133.0
    nodePackages.aws-cdk@2.128.0
    nodePackages.aws-cdk@2.125.0
    nodePackages.aws-cdk@2.118.0 (aarch64-darwin only)
    nodePackages.aws-cdk@2.110.0
    nodePackages.aws-cdk@2.105.0
    nodePackages.aws-cdk@2.99.1
    nodePackages.aws-cdk@2.96.2
    nodePackages.aws-cdk@2.90.0
    nodePackages.aws-cdk@2.87.0
    nodePackages.aws-cdk@2.83.1
    nodePackages.aws-cdk@2.80.0
    nodePackages.aws-cdk@2.68.0
    nodePackages.aws-cdk@2.63.2
    nodePackages.aws-cdk@2.60.0
    nodePackages.aws-cdk@2.53.0
    nodePackages.aws-cdk@2.50.0
    nodePackages.aws-cdk@2.47.0
    nodePackages.aws-cdk@2.42.0
    nodePackages.aws-cdk@2.38.0 (aarch64-darwin only)
```
NixOS packages are slightly behind and don't have the latest version of aws-cdk, which the latest version of EKS Blueprints needs. 
But the older release of EKS blueprints says I should be able to use `aws cdk version 2.133.0`, and the above says that's available in Nix packages.

Earlier today I did some basic testing of a similar project that also uses NixOS called devbox
The following devbox.json, works fine, which I mention to offer proof that aws cdk 2.133.0 supplied via Nix Packages works on ARM based Mac. (That's the relevance of me mentioning devbox.)
```json
{
    "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.12.0/.schema/devbox.schema.json",
    "packages": [ 
      "awscli2@2.16.4",
      "nodejs@22.3.0",
      "typescript@5.5.2",
      "nodePackages.aws-cdk@2.133.0"
    ],
    "shell": {
      "init_hook": [
        "echo 'Welcome to devbox!' > /dev/null"
      ],
      "scripts": {
        "test": [
          "echo \"Error: no test specified\" && exit 1"
        ]
      }
    }
}
```

Here's the relevant snippet of a flox's manifest.toml that's equivalent in terms of installed packages
```toml
[install]    # (List of packages installed in environment)
aws = { pkg-path = "awscli2", version = "2.17.0" }
aws_cdk_dependency_nodejs = { pkg-path = "nodejs_22", version = "nodejs-22.3.0" }
aws_cdk_dependency_ts = { pkg-path = "typescript", version = "5.5.2" }
cdk = { pkg-path = "nodePackages.aws-cdk", version = "2.133.0" }
# cdk = { pkg-path = "nodePackages.aws-cdk", version = "2.146.0" }
```

`flox activate` fails with the above config on M3 Mac when I use "2.133.0", but works when I use ["2.146.0", "2", "^2.133.0"] (all of which resolve to 2.146.0, per cdk --version)
For the sake of curiousity I spun up an Amazon Linux EC2 instance and was able to install 2.133.0 just fine on linux(x86_64), but it fails on ARM based Mac (when using flox, but I don't think it should fail on ARM based Mac since it works on dev box.)

**Steps to reproduce:**
1. Make a new folder & cd to it or `rm -rf .flox` (for the sake of a fresh env)
2.  `flox init`  <-- to make a fresh env
3. `flox show nodePackages.aws-cdk`
     (shows the same results as seen above regardless of if I run it on Mac or Linux)
4. `flox install nodePackages.aws-cdk@2.133.0`
     (works on Linux, fails on Mac)
* Linux (Amazon Linux 2 on x86_64) returns 
  ```console
  ✅ 'aws-cdk' installed to environment 'default'
  ```
* Mac (ARM based M3) returns
  ```console
  ❌ ERROR: resolution failed: constraints for group 'toplevel' are too tight
  
     Use 'flox edit' to adjust version constraints in the [install] section,
     or isolate dependencies in a new group with '<pkg>.pkg-group = "newgroup"'
  ```

**Result:**
Mac and Linux give different results
flox.dev on Mac and devbox on Mac give different results.

**Expected:**
flox.dev and devbox to work the same on Mac, Linux since they're both based on NixOS.
I'd expect flox.dev and devbox would give similar results, because I theorize that they're pulling from the same Nix Packages. 

**Screenshots/terminal output (if relevant):**
`flox show nodePackages.aws-cdk`
`flox install nodePackages.aws-cdk@2.133.0`
```console
❌ ERROR: resolution failed: constraints for group 'toplevel' are too tight

   Use 'flox edit' to adjust version constraints in the [install] section,
   or isolate dependencies in a new group with '<pkg>.pkg-group = "newgroup"'
```

**flox Version (run `flox --version` if possible):**
1.1.0

**`uname -a` output:**
(ARM based M3 Macbook Pro)
Darwin Chriss-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030 arm64

**Comment by ghudgins** [comment]
I am able to install `2.133.0`

<img width="580" alt="image" src="https://github.com/flox/flox/assets/5465514/95a229c1-1cb0-4577-8396-32bae4f4a07f">

Try changing your manifest so that the cdk package is in its own `pkg-group`

```
[install]    # (List of packages installed in environment)
aws = { pkg-path = "awscli2", version = "2.17.0" }
aws_cdk_dependency_nodejs = { pkg-path = "nodejs_22", version = "nodejs-22.3.0" }
aws_cdk_dependency_ts = { pkg-path = "typescript", version = "5.5.2" }
cdk = { pkg-path = "nodePackages.aws-cdk", version = "2.133.0", pkg-group = "aws-cdk" } # this line is different!
# cdk = { pkg-path = "nodePackages.aws-cdk", version = "2.146.0" }
```

does that help? we have more to do to improve the error messages and help here!

**Comment by neoakris** [comment]
Can you add clarifying details. When you say you're able to install it, is that from an ARM based Mac? 
using my earlier config I too was able to install cdk 2.133.0 (on x86_64 based Amazon Linux 2)
but I'm not able to install cdk 2.133.0 (on ARM based M3 MacOS)

O actually, cool I used your additional configuration on M3 MacOS and it went through :)
(Yeah that's very unintuitive to UX, given it worked without that additional configuration, on Linux, and for the above 3 packages, and I don't recall seeing an example of this 3 entry syntax in the docs.)

I'm gonna give flox.dev another shot was about to go down devbox path, but I like yaml/toml config significantly better than json.

My original issue is solved, I'll mark as closed and see if there's a pre-existing feature request for improved error message, if not I'll make one.

**Comment by ghudgins** [comment]
pkg-group is useful when you have multiple version constraints and you don't need them to be sharing dependencies. behind the scenes each group is aligned to a common revision of nixpkgs so that developer dependencies can work together but sometimes, especially for CLI tools, this behavior causes more harm than good. 

read more about this here - https://flox.dev/docs/concepts/manifest/#installing-packages-to-package-groups

**Comment by neoakris** [comment]
Hum... darn... 
Your fix allowed me to run 
`cdk --version` so I thought it installed correctly.
but
`cdk init app --language typescript` fails with odd AWS CDK (cli tool specific) error of `Cannot read properties of undefined (reading 'replace')` when using cdk v2.133.0 existing in flox shell, yet works using same version install on local machine, might be a niche problem.

That said thanks a lot your comment helped me get unstuck.
