### ISSUE TITLE
Cannot `flox edit` when EDITOR contains args

### ISSUE THREAD

**Issue by stealthybox** [flox/flox#1744]
```shell
❯ EDITOR="code -w" flox edit
❌ ERROR: editor command failed: No such file or directory (os error 2)
```
Expected behavior is the terminal should block and open up the manifest in a tab in VSCode.
Saving and closing the file will return to the terminal.

This EDITOR string works with `git commit`, `kubectl edit`, and etc.

Investigate if the CLI is not splitting the EDITOR env-var string into args before calling exec.
_____
```shell
❯ flox --version && uname -v
1.1.0
Darwin Kernel Version 23.5.0: Tue Mar 26 20:56:58 PDT 2024; root:xnu-10063.120.88.501.3~2/RELEASE_ARM64_T8103
```

**Comment by ghudgins** [comment]
@stealthybox this is back to you, will keep tracking on the board
