### ISSUE TITLE
Integration test a service that binds ports

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1753]
**Acceptance criteria**

Add an integration test that uses a long-running service that binds a TCP port and checks that it can be accessed. Could be Python's SimpleHTTPServer, Redis, etc.

**Why**

We deferred this from #1579 and #1581, because preventing port conflicts for tests that don't run in a container is hard and we wanted to keep making progress on initial tickets, however it's important that we test this aspect because it's how services will be used in real life.

**Comment by mkenigs** [comment]
- Setup: have to make sure `process-compose` is running
- Need to grab a unique port. See `flox_portgrab` for ideas
