### ISSUE TITLE
Better error reporting for imperatively stopping services

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1771]
`process-compose` does not differentiate between a service that exists and is no longer running vs. a service that never existed in the first place. Right now we pass that ambiguity on to the user. We can provide a better experience by catching this error (which we currently do to get the service name), then comparing it against the output of `process-compose process list` to see if the service in question is simply completed or whether it never existed in the first place.

Similarly, when you attempt to stop multiple services and one of them is invalid or already stopped, the order in which the services are specified will provide different behavior. `process-compose` stops the services in the order that they're provided, and will raise an error when encountering a bad service without reporting any of the services that it did stop. We can compare the list of running services before and after the call to `process-compose process stop` to see which services were actually stopped. Once we have that information we can provide a similar output to `flox install` where the services that were stopped are listed with checkmarks and the service that errored is given a red X.

I've raised these enhancements upstream:
- https://github.com/F1bonacc1/process-compose/issues/198
- https://github.com/F1bonacc1/process-compose/issues/199

**Comment by mkenigs** [comment]
Seems like we should start with a `list` to check that any processes requested to be stopped exist. If any don't exist, we should error. Then we should loop through the processes. For any that exist but aren't running, display a ⚠️  already stopped. For any that are running, call `process-compose process stop`, and display ✅ or ❌  for each.

Since `process-compose process stop` fails fast, I don't think it makes sense to call it with multiple processes and then try to figure out after the fact which ones actually got stopped.

**Comment by ysndr** [comment]
> For any that are running, call process-compose process stop, and display ✅ or ❌ for each.

do we want to abort if we fail to stop a service or message and continue with the rest?

**Comment by zmitchell** [comment]
Message and continue with the rest is my preference

**Comment by zmitchell** [comment]
Essentially I think we should call stop for each process individually since process-compose doesn't return much information when stopping more than one

**Comment by ysndr** [comment]
sorry @zmitchell i updated my comment and added two more points, Zenhub didnt update the issue with your answers

**Comment by ysndr** [comment]
Ok, good!
The current tested situation is different so before i go ahead and change tested behaviour i figured i'll check first.
