### ISSUE TITLE
(Documentation request) Document how to build from source

### ISSUE THREAD

**Issue by hardBSDk** [flox/flox#1773]
This program seems complex to package, does the repository data is added on the final executable of the CLI tool?

**Comment by ghudgins** [comment]
can you clarify what repository data you are referring to?

**Comment by hardBSDk** [comment]
@ghudgins The files that aren't source code.

**Comment by ghudgins** [comment]
Currently you need Nix to build Flox, and our catalog only contains packages for macOS and Linux, so building Flox for another OS wouldn’t turn out to be very useful. We look forward to supporting Redox someday, but for now we’re going to focus our efforts on macOS and Linux.

**Comment by ghudgins** [comment]
Cool! If nixpkgs is ever built for Redox OS, we could revisit whether it’s worth flox supporting Redox
