### ISSUE TITLE
Odd Output when activating from another directory

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1781]
**Describe the bug:**

Be in a directory that does not have a `.flox`. Then run `flox activate -d ~`.  (assuming you have an environment in your home dir). My `$HOME` environment is on FloxHub, so is remote, if that could be a factor. 

⚠️  This also happens if you use `$HOME` or `/Users/stahnma`. I _think_ this is a regression, but am not positive. Either way, I wouldn't expect to see a success and failure for the same operation. 
**Result:**

```
 $ flox activate -d ~
✅ You are now using the environment 'stahnma/default'.
To stop using this environment, type 'exit'

❌ ERROR: Did not find an environment in the current directory.

Create an environment with 'flox init'
```

Expected:

```
 $ flox activate -d ~
✅ You are now using the environment 'stahnma/default'.
To stop using this environment, type 'exit'
```

**flox Version (run `flox --version` if possible):** 1.2.0-14-g98bd44b3

**`uname -a` output:** Darwin floxbox01.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64 arm Darwin

**Comment by ghudgins** [comment]
@stahnma I wasn't able to recreate....
<img width="556" alt="image" src="https://github.com/user-attachments/assets/1790bf77-b2eb-4bfe-8124-35eb3c600085">

any ideas what's different for you?

**Comment by stahnma** [comment]
Ok. I can't reproduce this today either. Closing.

**Comment by stahnma** [comment]
Hmm. I found something smilar.

```
Last login: Mon Jul 29 10:40:46 on ttys010
flox [stahnma/default] [0] stahnma@floxbox01 ~ $ cd development/handbook/
flox [stahnma/default] [0] stahnma@floxbox01 ~/development/handbook [dependabot/pip/all-c4cce17917] $ nix develop
❌ ERROR: Did not find an environment in the current directory.

Create an environment with 'flox init'
Welcome to floxHandbook!

For local preview run:
mkdocs serve

For production build run:
mkdocs build

Happy documenting!

You may need to run Installing dependencies from lock file

No dependencies to install or update first (then exit the nix shell and re-enter)
[0] stahnma@floxbox01 ~/development/handbook [dependabot/pip/all-c4cce17917] $ flox --version
1.2.2-11-g05f5a618
[0] stahnma@floxbox01 ~/development/handbook [dependabot/pip/all-c4cce17917] $
```

**Comment by ghudgins** [comment]
don't believe those new instructions match the bug description. also I couldn't reproduce this either....

<img width="896" alt="image" src="https://github.com/user-attachments/assets/83ac360c-f394-40a2-b407-d6f0f47eb8e8">


i'll try with your environment...

**Comment by ghudgins** [comment]
also couldn't reproduce using `flox activate -r stahnma/default` as my base.

**Comment by ghudgins** [comment]
help me @stahnma -bewan kenobi, you're my only hope

**Comment by mkenigs** [comment]
Reproducer is stale (`nix develop` no longer works at all in floxhandbook)
