### ISSUE TITLE
flake installable descriptor additions

### ISSUE THREAD

**Issue by ysndr** [flox/flox#1788]
- [ ] descriptors should allow to set `systems` that the installable is resolved for. a) to allow installing a flake package only on specific systems, and install packages on matching systems from non default attrpaths at all.
- [ ] descriptors should provide a `priority` field with the same semantics as catalog descriptors
- [ ] lock result should include `priority := meta.priority`

**Comment by mkenigs** [comment]
@ysndr is it a convention for packages to have `meta.priority`?
```
> nix eval nixpkgs#curl.meta.priority --json
error: flake 'flake:nixpkgs' does not provide attribute 'packages.aarch64-darwin.curl.meta.priority', 'legacyPackages.aarch64-darwin.curl.meta.priority' or 'curl.meta.priority'
```
