### ISSUE TITLE
Parameterize the output streams

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1816]
Right now one of pain points in testing is that in order to test that a user-facing message has been shown, you need to create an integration test that invokes `flox`. This covers much more code than it likely intends to test, and is generally much slower than running a targeted unit test.

If we add the ability to mock the output streams with buffers, we can write smaller, more focused unit tests.

One approach would be to add `out_stream` and `err_stream` fields to `Flox`:
```rust
pub struct Flox<T: Write, U: Write> {
    ...,
    out_stream: T,
    err_stream: U,
}
```
then any code that displays user-facing text would write to `Flox.out_stream` or `Flox.err_stream` instead of using `println!`, etc. This has the benefit of being able to pass in buffers during testing and the real streams during normal usage.

The downside to this approach is that we would now need to pass the `Flox` struct anywhere that could possible print. This could mean touching several interfaces, but I think it's worth the churn since it would potentially allow us to migrate several integration tests to unit tests.

**Comment by zmitchell** [comment]
Discussed in the meeting this morning:
- Using generics within the `Flox` struct means that any `trait Environment` method that takes a `Flox` struct prevents the `Environment` trait from being turned into a trait object.
- This may not be the worst thing in the world as we can probably use `enum_dispatch` to remove our trait object usage.
- @ysndr mentioned just doing this on `ConcreteEnvironment`
-  @ysndr also mentioned that instead of writing to buffers as in the ticket description above we instead redirect the output to a file and read the file. One benefit is that depending on where that file is, we may be able to inspect it after a test run, but it does add some complexity (where to store the file, etc) over simply writing to buffers.

**Comment by mkenigs** [comment]
- Need to figure out runtime local history
- Need to think about times we stream, e.g. containerize

**Comment by mkenigs** [comment]
> * Need to figure out runtime local history

We might be able to use `task_local`?

**Comment by mkenigs** [comment]
Seemed to work for me with 8 `concurrent_async_` tests and `#[tokio::test(flavor = "multi_thread", worker_threads = 4)]`. Were you seeing it fail somehow when not using a single-threaded runtime?
