### ISSUE TITLE
Git is not included in x86_64-darwin closure

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1820]
git is not included in the flox package on x86_64-darwin even though it's included for every other architecture.
```
> git checkout v1.2.2
> nix build .#packages.x86_64-linux.flox --out-link x86_64-linux
> nix build .#packages.aarch64-linux.flox --out-link aarch64-linux
> nix build .#packages.aarch64-darwin.flox --out-link aarch64-darwin
> nix build .#packages.x86_64-darwin.flox --out-link x86_64-darwin
> nix-store --query -R ./x86_64-linux | grep git
/nix/store/f7b2yl226nbikiv6sbdhmaxg2452c8h5-git-minimal-2.42.0
> nix-store --query -R ./aarch64-linux | grep git
/nix/store/h67a939ykn165vsi5687lk8glcpswx4v-git-minimal-2.42.0
> nix-store --query -R ./aarch64-darwin | grep git
/nix/store/p9i7qfwxgchxbvxprcdbjqiqx73kqz39-git-minimal-2.42.0
> nix-store --query -R ./x86_64-darwin | grep git
>
```

This can lead to the following error on an x86_64-darwin host without git:
```
> flox activate -r flox/anthropic
:x: ERROR: Failed to get latest version of remote environment: Failed to clone environment: Failed to run git: No such file or directory (os error 2)`
```

**Comment by stahnma** [comment]
Shouldn't the fixup stage of a nix-build catch this?

**Comment by mkenigs** [comment]
> Shouldn't the fixup stage of a nix-build catch this?

I really wish software always did what it should

**Comment by mkenigs** [comment]
> Shouldn't the fixup stage of a nix-build catch this?

But yeah not sure why it's not. The debug logs have
```
2024-07-23T17:39:32.390733Z DEBUG flox_rust_sdk::providers::git: running git command: /nix/store/hkkkpxwdcnfk6jwld8968vbz475jhcaw-git-minimal-2.42.0/bin/git -c 'credential.https://api.flox.dev/git.helper='\!'f(){ echo "username=oauth"; echo "password=$FLOX_FLOXHUB_TOKEN"; }; f' -c 'remote.dynamicorigin.url=https://api.flox.dev/git/flox/floxmeta' -c 'user.email=floxuser@example.invalid' -c 'user.name=Flox User' clone --quiet --single-branch --no-tags --branch anthropic 'https://api.flox.dev/git/flox/floxmeta' /Users/daedalus/.local/share/flox/meta/flox --bare
```

So the /nix/store path is getting embedded in the Rust binary as we would expect

**Comment by mkenigs** [comment]
If you have git installed and export `GIT_PKG=$(which git)`, does that workaround it?

**Comment by keeban-io** [comment]
Unfortunately specifying `GIT_PKG` didn't help. Also tried different versions of flox from 1.0.6~1.2.2, but it all failed.

**Comment by keeban-io** [comment]
Oh I think I found a workaround while looking into the [source code](https://github.com/flox/flox/blob/cc9b2e56a41fb01dcadc8075bab6b348b280260e/cli/flox-rust-sdk/src/providers/git.rs#L18).
For example, if `$(which git)` result is `/usr/bin/git`, setting `GIT_PKG=/usr` actually helps.
