### ISSUE TITLE
Fix test flake where bats never exits

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1833]
Copying from https://github.com/flox/flox/pull/1824

We have seen some integration test jobs hang in CI since 28b33d6. I originally thought that this was due to a bad builder:

- https://github.com/flox/flox/actions/runs/10067670807/job/27831900822
- https://github.com/flox/flox/actions/runs/10067670807/job/27847053039
- https://github.com/flox/flox/actions/runs/10073963290/job/27849361521

However it has also failed on `main` on a GitHub Runner instance after that change was merged, which no longer suggests that it was our builder at fault:

- https://github.com/flox/flox/actions/runs/10084240104/job/27882612749

The attempted fix in #1824 of closing FD 3 didn't solve the problem; there was another failure:
https://github.com/flox/flox/actions/runs/10096488059/job/27919238140

**Comment by mkenigs** [comment]
Here's what I've found so far. I've been able to cause a hang on both our aarch64-darwin and aarch64-linux builders. In both cases, using `ps -A` I found some `sleep` processes. After `sudo kill`ing them, bats seemed to exit. The most narrow reproducer I've had so far is on our aarch64-linux builder:

```
nix build \
      --accept-flake-config \
      --extra-experimental-features '"nix-command flakes"' \
      "github:flox/flox/2cf2c78bce1034fefa3bd65a920c9afff91bf4b6#packages.aarch64-linux.flox-cli-tests"
for i in {1..50}; do ./result/bin/flox-cli-tests -- --filter-tags services -f blocking
```

When I run just 1 of the blocking tests at a time, I've seen all 3 of them get through 50 runs without failing. When running all 3, it usually blocks within a few runs.

Running all 3 on aarch64-darwin hasn't hung yet and I'm at at least 100 runs.

**Comment by zmitchell** [comment]
When you say you run "1 at a time" what do you mean? As far as I can tell, the tests are run sequentially.

**Comment by dcarley** [comment]
> When you say you run "1 at a time" what do you mean? As far as I can tell, the tests are run sequentially.

I took it to mean filtering on 1 vs 3 of them.

**Comment by mkenigs** [comment]
Yeah I meant running all 3 with `-f blocking` usually hangs, I haven't seen `-f "blocking: error message when startup times out"` hang yet

**Comment by zmitchell** [comment]
That one basically doesn't do anything since it tries to have `process-compose` start with a socket in `/`. I don't think that provides a useful signal as to the source of the block.

**Comment by zmitchell** [comment]
My first attempt at the commands you listed above hung on the first iteration of `flox-cli-tests` at `"blocking: process-compose writes logs to file"`. Trying to install a new version of `lsof` is apparently rebuilding the entire world so I'll report back when I have more information.

**Comment by mkenigs** [comment]
I didn't see `blocking: activation blocks on socket creation` or `blocking: process-compose writes logs to file` hang when run alone either
