### ISSUE TITLE
Transient/Dependency packages are added to environment

### ISSUE THREAD

**Issue by dg-nvm** [flox/flox#1845]
**Describe the bug:**

I installed `gimme-aws-creds` that is a Python package. It installed bunch of other packages and also python3-3.11.9. This python will overshadow the system Python. Given that gimme-aws-creds is wrapped package that has PATH changed, should the dependencies of it be added to bin automatically? binary will auto-find it's dependencies from extended PATH from wrapper, we do not need to make it global as well.

**Steps to reproduce:**
1. mkdir -p ~/t/flox-overshadowing
2. cd ~/t/flox-overshadowing
3. flox init
4. flox activate
5. flox install gimme-aws-creds
6. hash -r
7. which python3

Result:

/home/dgoslawski/t/flox-overshadowing/.flox/run/x86_64-linux.flox-overshadowing/bin/python3

Expected:

/usr/bin/python3

**Screenshots/terminal output (if relevant):**

**flox Version (run `flox --version` if possible):**

1.2.0

**`uname -a` output:**

`Linux VONJLP55M3 6.6.36.3-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Sat Jun 29 07:01:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ghudgins** [comment]
right now we are linking development dependencies intentionally. we do want to enhance Flox to let you control this behavior. https://github.com/flox/flox/issues/1268

**Comment by mkenigs** [comment]
If you don't want transient dependencies, you can now activate with `flox activate -m run`
```
/private/tmp  > flox --version
1.3.8

/private/tmp  > flox activate
✅ You are now using the environment 'tmp'.
To stop using this environment, type 'exit'

flox [tmp] /private/tmp  > which python3
/private/tmp/.flox/run/aarch64-darwin.tmp.dev/bin/python3

/private/tmp  > flox activate -m run
✅ You are now using the environment 'tmp'.
To stop using this environment, type 'exit'

flox [tmp] /private/tmp  > which python3
/usr/bin/python3
```
