### ISSUE TITLE
Stress the primary use case more clearly in the documentation

### ISSUE THREAD

**Issue by przemek-pokrywka** [flox/flox#185]
**Describe the feature:**
I propose to update the website and the documentation so it clearly states that flox is for regular packages and not for software that integrates with the operating system more closely, like system services or desktop apps.

**Describe a use case of this feature:**
The use case is that a new user gets the message just by reading the documentation and not after they waste their time failing at installing apps/services.

**Acceptance criteria:**
1. a new user reads flox webpage and docs
2. the user sees it clearly that flox is for packages and that system services or apps won't enjoy much support 
3. the user does not waste time trying to install Slack, Signal Desktop or Docker through flox

**Comment by aakropotkin** [comment]
Thanks for the recommendation, I can see about getting more relevant documentation prioritized.

**Comment by ghudgins** [comment]
we recently overhauled the product and the documentation. can you check it out?
