### ISSUE TITLE
^C within activation stops services

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1850]
Activate an environment with services and see `process-compose` running:
```
(2) ~/projects/flox/flox on HEAD (3bfcf28f) [$]
% FLOX_FEATURES_SERVICES=true flox activate --start-services -d ~/tmp
✅ You are now using the environment 'tmp'.
To stop using this environment, type 'exit'

flox [tmp dcarley/shell (remote)] 
(3) ~/projects/flox/flox on HEAD (3bfcf28f) [$]
% pstree -ws process-compose
-+= 00001 root /sbin/launchd
 \-+= 01378 dcarley /Applications/flox-kitty.app/Contents/MacOS/applet
   \-+- 01379 dcarley /Users/dcarley/.cache/flox/remote/dcarley/shell/.flox/run/bin/kitty
     \-+= 01612 root /usr/bin/login -f -l -p dcarley /nix/store/2jwdy3fbd5qv3l6aq9pi92x9glk8ccsp-kitty-0.35.0/Applications/kitty.app/Contents/MacOS/kitten run-shell --shell /bin/zsh --shell-integration enabled --cwd=/
       \-+= 01614 dcarley -zsh
         \-+= 90025 dcarley /bin/zsh -o NO_GLOBAL_RCS
           \-+- 90046 dcarley /nix/store/hhi4abjsvn4d790d8fbqzyha8cff6m0h-process-compose-1.6.1/bin/process-compose up -f /Users/dcarley/tmp/.flox/run/aarch64-darwin.tmp/service-config.yaml -u /Users/dcarley/.cache/flox/run/flox.ee4e7845.sock -L /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.TkouYc/tmp.QJp08qKiDm --tui=false
             |--= 90052 dcarley sleep infinity
             \--= 90054 dcarley redis-server *:6379
```

^C in the shell and `process-compose` is no longer running:
```
flox [tmp dcarley/shell (remote)] 
(3) ~/projects/flox/flox on HEAD (3bfcf28f) [$]
% ^C
flox [tmp dcarley/shell (remote)] 
(3) ~/projects/flox/flox on HEAD (3bfcf28f) [$]
130 % pstree -ws process-compose
flox [tmp dcarley/shell (remote)] 
(3) ~/projects/flox/flox on HEAD (3bfcf28f) [$]
%
```

(edited: the 130 exit code isn't that interesting because that's normal behaviour of the shell)

**Comment by zmitchell** [comment]
I think this is caused by `process-compose` being in the foreground process group, and thus being part of the group that gets job control signals delivered to it when you press Ctrl-C. I think `process-compose` needs to be in a separate process group from the activation.

Looks like we need the `setsid` utility: https://stackoverflow.com/questions/22160196/how-to-spawn-process-on-linux-by-using-new-process-group-id-in-bash

**Comment by zmitchell** [comment]
And it looks like the only package that provides that utility across platform is the `toybox` package. The other package `util-linux` and `busybox` are Linux-only.

**Comment by ysndr** [comment]
fwiw, linux-util _does_ work on macos, it just installs a subset of packages instead of the full suite avalable on linux.
Fortunately one of these is `setsid`
