### ISSUE TITLE
Conflict with nix on Linux systems (abort installation for now) 

### ISSUE THREAD

**Issue by stahnma** [flox/flox#1855]
Right now we have trouble adopting existing nix installations on debian/rpm systems. We should conflict with debian-nix, nix, things like that. Basically, let's abort and tell the user how to be successful. We could use some documentation on what to do if you run into this conflict.

**Comment by tomberek** [comment]
I'm thinking there might be a fix for the problem related to our handling of the service/socket files. PR is inbound.

**Comment by stahnma** [comment]
We should still conflict with nix or deb-nix or whatever packages exist though for RPM/Deb right?

**Comment by tomberek** [comment]
@stahnma yes, we added the nix conflict (nix-bin + nix-setup-systemd) for DEB. Is there one needed for RPM?

**Comment by jhult** [comment]
Related to https://github.com/flox/flox/issues/1177
