### ISSUE TITLE
Drop or port integration tests with `FLOX_FEATURES_USE_CATALOG=false`

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1857]
Drop or port all instances of `FLOX_FEATURES_USE_CATALOG=false` in integration tests.
- Port any integration tests for v0 behaviors that we want to support going forward (e.g. activate, list). Commit v0 manifests and locks rather than generating during tests
- Drop any integration tests for v0 behaviors we don't need to support anymore (e.g. install)

**Comment by ysndr** [comment]
i figure you mean `FLOX_FEATURES_USE_CATALOG=false` right?

**Comment by mkenigs** [comment]
> * [ ]  i figure you mean `FLOX_FEATURES_USE_CATALOG=false`

Whoops yep

>     * [ ]  confirming; pulling pkgdb envs is still possible, since they dont lock

Yep

>     * [ ]  do we still want to test the full range of pull behavior (arg, env detecting) for pkgdb envs? i think the manifest should not paly a role in tests like "pulling without namespace/environment respects --dir"

Yeah I think if we're confident it won't regress we can drop it
