### ISSUE TITLE
Change service error messages, like, a lot

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1858]
`flox services logs` and `flox services stop` currently print an error for 4 different cases:
- there are no activations
- there is an activation without services started, and the command is run within that activation
- there is an activation without services started, but the command is run in a separate shell
- there is an activation of an environment that doesn't have services at all

In all 4 cases we print
```
❌ ERROR: couldn't connect to service manager
```

This is user facing behavior, and it is currently determined by `ProcessStates::read`. It's not very obvious that `ProcessStates::read` should control that behavior.

We should:
- Add code comments explaining that `ProcessStates::read` is responsible for that behavior
- Add unit tests for the 3 user facing cases mentioned above
- Change messaging to be
    - there are no activations: `There are no services running. Start services with flox activate --start-services`
    - there is an activation without services started, and the command is run within that activation: `Couldn’t connect to service manager. Start services with flox activate --start-services`
    - there is an activation without services started, but the command is run in a separate shell: `Couldn’t connect to service manager. Start services with flox activate --start-services`
    - there is an activation of an environment that doesn’t have services at all: `Environment doesn’t have any services`

**Comment by mkenigs** [comment]
>       * there is an activation of an environment that doesn’t have services at all: `Environment doesn’t have any services`

In this case we also need to check if `process-compose` is running from a prior version of the environment that did have services. In which case we need to stop `process-compose`

**Comment by ysndr** [comment]
> in this case we also need to check if process-compose is running from a prior version of the environment that did have services. In which case we need to stop process-compose

is this in the case of "stop" particularly?
