### ISSUE TITLE
bug: flox fails to start if it cannot read the current directory

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#187]
**Describe the bug:**

flox cannot run any command if it is unable to read the current directory, for example in the event it has been deleted.

**Steps to reproduce:**

<pre><span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:~]$</b></span> cd $(mktemp -d)

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:/tmp/tmp.ppvRA5ejxS]$</b></span> flox nix repl
nix-repl&gt; 

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:/tmp/tmp.ppvRA5ejxS]$</b></span> rmdir /tmp/tmp.ppvRA5ejxS

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:/tmp/tmp.ppvRA5ejxS]$</b></span> flox nix repl
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
<span style="color:#FF5555"><b>error:</b></span> cannot get cwd: <span style="color:#FF55FF"><b>No such file or directory</b></span>
<span style="color:#D7D7AF"><b>ERROR: </b></span><b>Nix call unsuccessful: [exit status: 1]</b>

<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:/tmp/tmp.ppvRA5ejxS]$</b></span> flox --version
Version: 0.2.5-r561
</pre>

**Comment by aakropotkin** [comment]
The case Matthew shows seems expected to me.

Your shell and most other software aren't going to be happy if you delete
the process' `CWD`.

**Comment by ghudgins** [comment]
we no longer expose nix - closing this.
