### ISSUE TITLE
Garbage collect watchdog and process-compose log files

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1870]
The watchdog creates a log file in `.flox/log` (previously `.flox/cache`) for every activation. We are also exposing `process-compose` logs in https://github.com/flox/flox/issues/1927. At some point we need to clean these up.

We need to keep 3 days worth and not remove logs while they are still open for writing.

This could be done by a separate thread spawned by the watchdog before it waits on signals, for instance.

**Comment by mkenigs** [comment]
`klaus` cleans up logs after 3 days. Use `mtime` if available. Check if the logfile is still used with either the env registry or lsof. If `mtime` is disabled, we don't care too much.

**Comment by mkenigs** [comment]
Use `.flox/log`
