### ISSUE TITLE
Warn about services for manifest changes

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1885]
There are very few scenarios in which a change to the manifest doesn't require services to be restarted, the only real case being an update to the `profile` section.
- If a manifest has a `services` section
- and you have running services
- and if the manifest has changes outside of the `profile` section
- Show a warning:
```
:warning: Your manifest has changes that may require running `flox services restart`
```

We need to do this after anything that modifies the manifest - edit, install, remove, upgrade, pull

**Comment by mkenigs** [comment]
We need to do this after anything that modifies the manifest - edit, install, remove, upgrade

**Comment by dcarley** [comment]
This doesn't depend on the other machinery for stale in epic 4 so could be pulled in sooner if we have time before release.

**Comment by zmitchell** [comment]
Breakdown:
- Pretty simple to detect when to show the message
    - Check whether you have running services after an edit
    - If so and the manifest made any changes outside of `profile`
    - Display the message
- Probably want to combine messages with the reactivation message so we can display something more compact

example:
```
Your manifest changes were recorded but cannot be automatically applied:
- You may need to reactivate in order to ...
- You may need to restart services with `flox services restart`
```

**Comment by dcarley** [comment]
Follow-up:
- implement and test for `flox pull`
- combine warnings for `flox edit`, maybe

**Comment by mkenigs** [comment]
>     * combine warnings for `flox edit`, maybe

https://github.com/flox/flox/pull/1967 ended up getting closed without merging
