### ISSUE TITLE
`start` and `restart` should be able to create `process-compose` in an ephemeral activation

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1886]
When starting services where the manifest on disk is not the manifest that `process-compose` was started with, we need to start a `process-compose` instance in the context of the latest, on-disk manifest. The easiest and fastest way to accomplish this is to start a short-lived activation and start `process-compose` in that context. We don't need a watchdog in that scenario, so we need a way to start an activation without spawning a new watchdog.

**Comment by dcarley** [comment]
Is there much harm in starting a watchdog in this scenario? Will supporting two types of behaviour be likely to help or hinder us as we add other functionality to the watchdog in the future?
