### ISSUE TITLE
Use new URI parser

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#190]
We've added a new URI parser to `runix` that needs to be incorporated into `flox`. The complication is that resolving URIs now requires internet access and our builds/tests run in the sandbox with no internet access.

**Comment by aakropotkin** [comment]
When working this ticket there's two test cases marked `skip` that can be treated as acceptance tests: https://github.com/flox/flox/blob/main/tests/flox-init.bats#L219

Additional acceptance tests absolutely should be created, but these are a starting point.

**Comment by tomberek** [comment]
Currently ran into an issue where the configuration of PARSER_UTIL was different from that used by Runix/Nix. Things like `flake-registry`, somewhat important for flake URL resolution.

**Comment by zmitchell** [comment]
More specifically, we need a way to pass in the Nix config to `FlakeRef::from_url` which is the underlying method that's getting called in `FlakeRef::from_str`. Unfortunately that can't be inferred from the environment easily in `runix` without reimplementing some `flox` functionality, so the solution I've chosen is to replace calls to `FlakeRef::from_str` or `str::parse::<FlakeRef>` with calls to `FlakeRef::from_url`, adding an argument of type `runix::command_line::DefaultArgs` to be handed down from `flox`.

**Comment by zmitchell** [comment]
This is going to be complicated. After looking into our codebase more there's _a lot_ of it that assumes you can just parse from a string without any other inputs, so this will touch a large chunk of the codebase.

**Comment by aakropotkin** [comment]
> Sam Lowry : Can you fix it?
> 
> Harry Tuttle : No, I can't. But I can bypass it with one of these.
> 
> [Holds up a `bash` script and 200 lines of C++]
