### ISSUE TITLE
Remove services feature flag (default on)

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1908]
# Acceptance criteria

Remove the `FLOX_FEATURES_SERVICES` feature flag (and all references including tests) so that services are available by default.

# Why

So that users can use services without needing to opt-in, once we are happy that enough functionality is in place.

**Comment by mkenigs** [comment]
We only set feature flag in services tests, so that should be easy to change

We already start the watchdog unconditionally, so hopefully we've already suffered through any unforseen breakage that enabling unconditionally will cause 🤞
