### ISSUE TITLE
flox edit -h has two "-r" aliases

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1915]
STR:
* `flox edit -h`

**Result:** There are two `-r` alias pointing to `remote` and `reset`
**Expected:** Only one `-r` alias pointing to `remote`

Note: the functionality work this way, just the help text is wrong.
Second note: I tried to fix this and couldn't figure out how 🫠

**Comment by ysndr** [comment]
Remove the `short` in 

https://github.com/flox/flox/blob/13aa3aae019bd531b2a99e671dc4b49cc19901ac/cli/flox/src/commands/edit.rs#L73-L79
