### ISSUE TITLE
Store process-compose logs in new directory

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1927]
Right now the process-compose logs are stored in a tempfile that's not exposed to the user in all cases (only if process-compose times out while starting services). If process-compose crashes, a user is no longer able to retrieve the location of this log file and can't debug the failure. We should store the logs in a well-known location so that they can be retrieved even if process-compose has crashed.

Garbage collection is covered in https://github.com/flox/flox/issues/1870

**Comment by mkenigs** [comment]
How about `.flox/run/process-compose.log`?

**Comment by zmitchell** [comment]
You'll need a unique key in the filename so it's not overwritten by later runs. We could move both the `klaus` and `process-compose` logs to a `.flox/cache/logs` directory so they don't clutter anything else up. I don't have strong preferences for `run` vs. `cache`.

**Comment by mkenigs** [comment]
I was thinking we'd just overwrite it so we don't have to deal with gc. We should only ever have one `process-compose` running per `.flox`, right?

**Comment by mkenigs** [comment]
We could also just add `.flox/log`

**Comment by zmitchell** [comment]
We should only ever have one running for an environment, but we may not want the logs from the latest one. Say a user encounters an error, flails until they get a working setup, and only then lets us know about the bug. If those logs are overwritten we have a harder time debugging.

**Comment by mkenigs** [comment]
`klaus` cleans up logs after 3 days. Use `mtime` if available. Check if the logfile is still used with either the env registry or lsof. If `mtime` is disabled, we don't care too much.

**Comment by mkenigs** [comment]
Use `.flox/log`
