### ISSUE TITLE
CLI Update Check runs on every invocation when CLI is current version

### ISSUE THREAD

**Issue by stealthybox** [flox/flox#1934]
Bug found by @NikitaVoloboev -- Thanks!
_______
We have a bug where the `~/.flox/cache/update-notification.json` is only written when a new version is identified.
This means the file is never written when the CLI is up to date.
In this state, the update check is run every CLI invocation.
This affects CLI exit latency significantly and becomes much worse the slower your internet connection is.

The bug is `fs::write(&self.notification_file` is done in [`fn print_new_version_available`](https://github.com/flox/flox/blob/a37478592a93768c83cef9ed8c4bc58ab381c5c4/cli/flox/src/commands/mod.rs#L582) which is only called when there is a match on an update_notification.

This write needs to move unconditionally into some part of `fn check_for_update` or `fn handle_update_result`.

nit: the field inside of the update file should probably be renamed from `last_notification` to `last_update_check`.
_________
nice to have:
It would be good to have 2 timers/intervals:
- 24 hours for interactive TTY use
- 1 week for non-interactive use.

That way, update notifications are more likely to occur when a user types in a `flox` command.

Rationale:
- It's not good to slow down in-place activations
- Output to stderr is often swallowed up by a user's custom shellrc (or even their terminal emulator -- ex: Warp)
- Some users may only ever use in-place activations, so it's good to have a fallback that can notify them in most cases

Pseudocode:
```
if (is_a_tty),
  check_interval = 24h
else
  check_interval = 1 week

read(update_file)
if (update_file doesn't exist || last_update_check older than check_interval)
  http_req(UPDATE_URL)
  if (no http_error)
    write(update_file)
  if (new_version)
    notify()
```

**Comment by ysndr** [comment]
> nit: the field inside of the update file should probably be renamed from `last_notification` to `last_update_check`.

i kinda agree, but changing the contents of the file comes with errors when observing an old file.
unless that's critical i may consider pushing that

tty checks are a good idea to add

**Comment by stealthybox** [comment]
if we change the file name too, it will never collide:
`~/.flox/cache/update-notification.json` -> `~/.flox/cache/update-check.json`

could also support deserializing the old field, and just completely ignore it.

it is mostly a nit

**Comment by mkenigs** [comment]
We didn't add a second interval for non-interactive use, but we did fix the bug and rename the file. If a second interval seems important, we can create a follow-up issue at some point
