### ISSUE TITLE
Reduce comment verbosity in manifest template

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1960]
### Motivation

Flox's manifest is pretty simple however the default template is quite long and does not look simple. Can we communicate the minimum possible and rely more heavily on man pages and doc for a robust walkthrough?

### Acceptance Criteria

Design a shorter default manifest template and update Flox to present that after the user `flox init`

Follow-up from https://github.com/flox/flox/pull/1957#discussion_r1721948201 and internal discussion [in slack](https://flox-dev.slack.com/archives/C05P6A5J6U8/p1724078785395059?thread_ts=1723857560.092069&cid=C05P6A5J6U8)

**Comment by ysndr** [comment]
If we're already working on that document we could also address #1758 while we're at it.
That one should really be a simple line change.

**Comment by ghudgins** [comment]
+1 from @garbas today

**Comment by garbas** [comment]
Ticket created here -> https://github.com/flox/flox/issues/2446
