### ISSUE TITLE
Add metric for v0 vs v1 lockfiles

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1972]
In order to be able to decide whether to continue supporting v0 lockfiles, we need information about whether literally anybody at all is using a v0 manifest. Add a `subcommand_metrics` call in `flox activate` that reports which lockfile version the environment uses.

**Comment by dcarley** [comment]
Double checking what we need to do to see these metrics in: https://flox-dev.slack.com/archives/C05FFKDRRJA/p1724839345122299

**Comment by dcarley** [comment]
Verified that they are submitted to our in-house metrics.

Ingesting the new field and making it available to Databox will be tracked in https://github.com/flox/datalake/issues/6
