### ISSUE TITLE
Sentry: fix tracing for watchdog

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1988]
**Acceptance criteria**

`flox-watchdog` should submit some basic traces, e.g.

- how long it has run for
- device UUID
- parent trace from activation (even if we don't currently submit a span).

**Why**

It will give us some information about how the watchdog is working in real life.

We copied over the basic setup from the CLI but we don't appear to be getting any traces.

**Refinement notes**

The easiest way to see what it might be doing is by running `mitmproxy` from the `devShell` to inspect the payloads, e.g.
```console
export HTTPS_PROXY=http://localhost:8080 SSL_CERT_FILE=~/.mitmproxy/mitmproxy-ca-cert.pem
export FLOX_SENTRY_DSN=REDACTED_UNTIL_https://github.com/flox/flox/issues/1986
% (_FLOX_WATCHDOG_LOG_LEVEL=debug flox-watchdog --registry ~/.local/share/flox/env-registry.json --hash ee4e7845 --socket /dev/null --logs /dev/stdout --pid $$) &
kill $!
```

Curiously someone appears to be running an older nightly version of Flox that is emitting traces from `klaus::listen::signal_listener` ([here](https://flox-dev.sentry.io/traces/?project=4506548241825792&query=klaus&source=traces&statsPeriod=7d&utc=true)) which was removed in https://github.com/flox/flox/commit/2c1db320b91b2b4592465672b4fda94c8ffa98d6 but there don't appear to be any traces from "watchdog" today ([here](https://flox-dev.sentry.io/traces/?project=4506548241825792&query=watchdog&source=traces&statsPeriod=7d&utc=true)).

**Comment by ysndr** [comment]
- [ ] make it work
Likely an odd filtering order issue, we have seen those before in flox' logging -- tracings layers+filters are not entirely intuitive.


- [ ] add more information

**Comment by dcarley** [comment]
> device UUID
> parent trace from activation (even if we don't currently submit a span).

I've rolled these into https://github.com/flox/flox/issues/1715 so we can consider this done after https://github.com/flox/flox/pull/2038.
