### ISSUE TITLE
❌ ERROR: Not a directory (os error 20)

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1995]
STR:

This is a bit tricky to recreate. I'm guessing here

* have an environment created on an older version like 1.1
* upgrade to 1.3
* maybe also upgrade to macOS Sequoia (maybe)
* `flox activate` the environment from 1.1

Result: ❌ ERROR: Not a directory (os error 20)
Expected: activated environment

**Comment by ghudgins** [comment]
as I understand from @ysndr this will be fixed by https://github.com/flox/flox/pull/1991

**Comment by mkenigs** [comment]
I could not reproduce this with
```
> flox-1.1.0 init
> flox-1.1.0 install hello
> flox-1.3.0 activate
```
so I'll let @ysndr or @zmitchell confirm this is fixed

**Comment by mkenigs** [comment]
> I have a device that has the issue that I can test the fix on. ready for testing?

Yep 1991 has merged

**Comment by ghudgins** [comment]
kk works on my reproducer machine after a whitespace `flox edit`. closing
