### ISSUE TITLE
Fix watchdog race condition and remove register_cleanup.sh

### ISSUE THREAD

**Issue by dcarley** [flox/flox#2002]
**Acceptance criteria**

`register_cleanup.sh` is removed from `services.bats` and all tests run reliably without hanging.

**Why**

We added `register_cleanup.sh` before we had the watchdog and have been reluctant to remove it due to unknown race conditions in the tests. However it's plastering over some behaviours that we care about.

The new test in https://github.com/flox/flox/pull/2001/ wasn't using `register_cleanup.sh` and was hanging for me locally with, leaving the following processes around:
```console
% pstree -ws bats
-+= 00001 root /sbin/launchd
 |-+= 57076 dcarley /nix/store/j5dp1ha8v91iayzjxw87fm3wzmrqzhky-process-compose-1.9.0/bin/process-compose up -f /private/var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.Qswp9C/bats-run-rs3ICZ/test/1/test/one/.flox/run/aarch64-darwin.one/service-config.yaml -u /private/tmp/flox.tests.WOkTHP/tmp.Pcm7K0egxe/run/flox.71a1edaa.sock -L /private/var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.Qswp9C/bats-run-rs3ICZ/test/1/test/one/.flox/log/services.20240827111336010806.log --tui=false
 | \--= 57080 dcarley /nix/store/h0fgpyxfav7ybnw5sdg8jpyv9f95x4w0-coreutils-9.3/bin/sleep infinity
 |-+= 57110 dcarley /nix/store/j5dp1ha8v91iayzjxw87fm3wzmrqzhky-process-compose-1.9.0/bin/process-compose up -f /private/var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.Qswp9C/bats-run-rs3ICZ/test/1/test/two/.flox/run/aarch64-darwin.two/service-config.yaml -u /private/tmp/flox.tests.WOkTHP/tmp.Pcm7K0egxe/run/flox.bdbeba83.sock -L /private/var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.Qswp9C/bats-run-rs3ICZ/test/1/test/two/.flox/log/services.20240827111336180292.log --tui=false
 | \--= 57115 dcarley /nix/store/h0fgpyxfav7ybnw5sdg8jpyv9f95x4w0-coreutils-9.3/bin/sleep infinity
 \-+= 70586 dcarley /Applications/flox-kitty.app/Contents/MacOS/applet
   \-+- 70587 dcarley /Users/dcarley/.cache/flox/remote/dcarley/shell/.flox/run/bin/kitty
     \-+= 30959 root /usr/bin/login -f -l -p dcarley /nix/store/2jwdy3fbd5qv3l6aq9pi92x9glk8ccsp-kitty-0.35.0/Applications/kitty.app/Contents/MacOS/kitten run-shell --shell /bin/zsh --shell-integration enabled --cwd=/Users/dcarley/projects/flox/flox
       \-+= 30960 dcarley -zsh
         \-+= 56682 dcarley just integ-tests services.bats -- -f layered
           \-+- 56900 dcarley /nix/store/x1xxsh1gp6y389hyl40a0i74dkxiprl7-bash-5.2-p15/bin/bash /nix/store/x71jh8m0gslm3pvrr2kg4idfrin1bx32-bats-1.10.0/libexec/bats-core/bats --print-output-on-failure --verbose-run --timing -f layered services.bats
             |--- 56913 dcarley /nix/store/x1xxsh1gp6y389hyl40a0i74dkxiprl7-bash-5.2-p15/bin/bash /nix/store/x71jh8m0gslm3pvrr2kg4idfrin1bx32-bats-1.10.0/libexec/bats-core/bats --print-output-on-failure --verbose-run --timing -f layered services.bats
             \--- 56914 dcarley /nix/store/x1xxsh1gp6y389hyl40a0i74dkxiprl7-bash-5.2-p15/bin/bash /nix/store/x71jh8m0gslm3pvrr2kg4idfrin1bx32-bats-1.10.0/libexec/bats-core/bats-format-pretty --dummy-flag -T --base-path services.bats
```

Persisting the logs outside of the test directory showed that the watchdog wasn't getting past registering with kqueue because the parent PID no longer exists:

- https://github.com/flox/flox/blob/00ecaa60d5c1f1c69dec002557e9121b9cad273f/cli/flox-watchdog/src/main.rs#L116

This bypasses the cleanup that we do later on when checking if the parent PID still exists:

- https://github.com/flox/flox/blob/00ecaa60d5c1f1c69dec002557e9121b9cad273f/cli/flox-watchdog/src/main.rs#L129-L143

`register_cleanup.sh` has been covering up this bug for short-lived activations because it both a) adds some time to the activation to allow the watchdog to start, and b) always forces `process-compose` to shutdown.

It's worth noting that we may also run into problems with BATS deleting the project directory that contains the socket path before the watchdog has finished cleaning up.

This issue is similar but not exactly the same as:

- https://github.com/flox/flox/issues/1904

**Comment by mkenigs** [comment]
Are the logs saying `failed to register watcher`? Or is `watcher.watch()` hanging?

**Comment by dcarley** [comment]
> Are the logs saying `failed to register watcher`? Or is `watcher.watch()` hanging?

The logs only contained `flox_watchdog: starting` because the error from `watcher.watch().context(…)` exits `main()` and goes to STDERR, which we can't see because the watchdog is forked. I temporarily logged the result to debug it. We probably need to catch and log everything.
