### ISSUE TITLE
What is "floxmeta" and why is it missing?

### ISSUE THREAD

**Issue by aronchick** [flox/flox#2015]
When i run the following command from a script...

```
## Running: /usr/local/bin/flox activate -r "aronchick/andaime" -t -- golangci-lint run --fix .flox/env/manifest.toml

❌ ERROR: Failed to get latest version of remote environment: Failed to clone environment: Git failed with: [exit code 128]
  stdout:
  stderr: fatal: remote error: FATAL: invalid repo name: '"aronchick/floxmeta'
```

When i run it from my full shell, it's fine.

**Comment by mkenigs** [comment]
What's your flox version?

**Comment by mkenigs** [comment]
If you have something lower than 1.3.0, this may be https://github.com/flox/flox/issues/1820

**Comment by aronchick** [comment]
No i have 1.3.0. It turns out it was because i hadn't pushed the repo to flox cloud.

**Comment by ysndr** [comment]
There's a `"` in the error that shouldnt be there (`"aronchick/floxmeta`)
There is an implementation for better error messages in the case that the env does not exist on the hub, this however is a bug. Thanks for reporting!

**Comment by mkenigs** [comment]
I can only reproduce this by explicitly passing in a `"`, i.e. `flox activate -r '"owner/name'`
