### ISSUE TITLE
Flox failing when using fish shell

### ISSUE THREAD

**Issue by watadarkstar** [flox/flox#2016]
**Describe the bug:**

When I run `flox activate -r flox/flaim` it fails with an error (I'm using a fish shell):

```
~/.cache/flox/remote/flox/flaim/.flox/run/activate.d/fish (line 17): 'return' outside of function definition
  return 1
  ^
from sourcing file ~/.cache/flox/remote/flox/flaim/.flox/run/activate.d/fish
source: Error while reading file '/Users/adriancaroll/.cache/flox/remote/flox/flaim/.flox/run/activate.d/fish'
```

**Steps to reproduce:**
1. Use a fish shell on M1 Mac
2. Run `flox activate -r flox/flaim`
3. Try running `genimg "foo"`

Result:
```
~/.cache/flox/remote/flox/flaim/.flox/run/activate.d/fish (line 17): 'return' outside of function definition
  return 1
  ^
from sourcing file ~/.cache/flox/remote/flox/flaim/.flox/run/activate.d/fish
source: Error while reading file '/Users/adriancaroll/.cache/flox/remote/flox/flaim/.flox/run/activate.d/fish'
```

Expected:
No errors.

**Screenshots/terminal output (if relevant):**
![Screenshot 2024-08-29 at 1 55 29 PM](https://github.com/user-attachments/assets/290088ff-ae59-40d3-b01a-44f6171eeab9)

**Flox Version (run `flox --version` if possible):**
1.3.0

**`uname -a` output:**
Darwin Adrians-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103 x86_64

**Comment by ghudgins** [comment]
what version of fish are you running?

**Comment by watadarkstar** [comment]
> what version of fish are you running?

fish, version 3.2.2

**Comment by watadarkstar** [comment]
@ghudgins I upgraded fish to version 3.7.1 but same issue:

![Screenshot 2024-08-29 at 4 06 53 PM](https://github.com/user-attachments/assets/747a9aa0-f56f-4f5c-ab90-5254d4d29581)

**Comment by ghudgins** [comment]
@limeytexan has a proposal that I think should solve this but we should confirm.

**Comment by mkenigs** [comment]
fish 3.2.2 is fixed by https://github.com/flox/flox/pull/2077 and that will be in the next release

I just opened https://github.com/flox/flox/issues/2082 to track the error you have for `flox activate -r flox/flaim` - that's due to that environment using unicode
