### ISSUE TITLE
TRACE logging showing up in non-development mode

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#2017]
STR:
* add your default env to your `.zshrc` i.e. `eval "$(flox activate -r ghudgins/default)"`
* do a `flox activate`

Result: active environment with this TRACE debug line:
```
2024-08-29T21:27:03.366492Z TRACE flox_command: subcommand="activate#version" lockfile_version=1
```

Expected: active environment without TRACE debug line

Version: 1.3.0-60-gf302067a

**Comment by ghudgins** [comment]
could be related to https://github.com/flox/flox/pull/1982/files

**Comment by ysndr** [comment]
This should be fixed now, please reopen or create a new ticket if this still happens on main and later
