### ISSUE TITLE
Document manifest builds / `flox build`

### ISSUE THREAD

**Issue by ysndr** [flox/flox#2041]
- [ ] Manpage for flox build (including an **Experimental** notice)
- [ ] floxdocs section for building (including an **Experimental** notice)

**Comment by mkenigs** [comment]
Seems like we should add these in separate folders so they don't actually get released yet?

**Comment by mkenigs** [comment]
I think we should go ahead and do this, but we shouldn't spend too much time on polish yet as behavior could change before we release

**Comment by ysndr** [comment]
I'm planning to at least write some manpages so that the application itself is self documenting.
IMO those can go directly into `doc` with the appropriate notice that the command is experimental and it semantics aren't  fully polished yet.

Floxdocs can perhaps wait a bit longer or iterated on a preview branch until we know how to best document/explain builds.

**Comment by mkenigs** [comment]
Manpage merged, still needs floxdocs page

**Comment by ysndr** [comment]
do we want to write the floxdocs now already or wait till we know better how to use build?
if we do the latter i'd move this back to the backlog (or create a follow up)

**Comment by mkenigs** [comment]
> do we want to write the floxdocs now already or wait till we know better how to use build? if we do the latter i'd move this back to the backlog (or create a follow up)

If we can do docs work now we won't throw away or waste time re-writing, I have a slight preference to add that now. It could just be an unpolished draft though. But I'm kinda on the fence, so open to closing this and creating followup

**Comment by mkenigs** [comment]
> I'm planning to at least write some manpages so that the application itself is self documenting. IMO those can go directly into `doc` with the appropriate notice that the command is experimental and it semantics aren't fully polished yet.

^also sorry I missed that comment before
