### ISSUE TITLE
Add python activation logic for jupyter labextensions

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#2068]
### Motivation

Hard to troubleshoot issue with using Jupyter labextension with Flox provided notebooks

### Acceptance Criteria

**When** I have `flox activate` an environment that has `jupyter` installed
**Then** I see `echo $JUPYTER_DATA_DIR` is equal to `"$FLOX_ENV/share/jupyter"`

thanks to a community member for reporting: https://discourse.flox.dev/t/issues-using-jupyterlab-extensions-with-flox/958/9

### Longer AC

**Given** my environment is

```

version = 1

# List packages you wish to install in your environment inside
# the `[install]` section.
[install]
psycopg.pkg-path = "python312Packages.psycopg"
tqdm.pkg-path = "python312Packages.tqdm"
datasets.pkg-path = "python312Packages.datasets"
ipywidgets.pkg-path = "python312Packages.ipywidgets"
huggingface-hub.pkg-path = "python312Packages.huggingface-hub"
jupyterlab-widgets.pkg-path = "python312Packages.jupyterlab-widgets"
nodejs.pkg-path = "nodejs"
widgetsnbextension.pkg-path = "python312Packages.widgetsnbextension"
pip.pkg-path = "python312Packages.pip"
jupyter.pkg-path = "jupyter"
btop.pkg-path = "btop"
postgresql_15.pkg-path = "postgresql_15"
tmux.pkg-path = "tmux"
ripgrep.pkg-path = "ripgrep"
[hook]
on-activate = '''
   # export JUPYTER_DATA_DIR="$FLOX_ENV/share/jupyter"
'''
[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
```
**And** I have `flox activate`-ed this environment
**When** I run `jupyter labextension list`
**Then** I see a successful execution

**Comment by ghudgins** [comment]
duplicate of #2067

**Comment by mkenigs** [comment]
Re-closing as dup
