### ISSUE TITLE
Parallelize bats tests

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2070]
In the past we didn't use `--jobs` with bats because we had pkgdb concurrency issues. Now that we aren't using pkgdb, we should be able to run tests in parallel.

**Comment by mkenigs** [comment]
Our current `wait_for_watchdogs` waits for all watchdogs started with `FLOX_DATA_DIR`, so we may need to make that a bit more specific if tests are running in parallel

**Comment by mkenigs** [comment]
Seems this may have caused https://github.com/flox/flox/actions/runs/11002060724/job/30548213768#step:5:303

**Comment by ysndr** [comment]
the remote tests were actually _not_  run in parallel.

The mentioned ci issues will be addressed by https://github.com/flox/flox/pull/2124
