### ISSUE TITLE
Optimize nixpkgs fetch for manifest builder

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2084]
Our current manifest builder fetches a pinned version of nixpkgs:
https://github.com/flox/flox/blob/868a7abe002c85dce7954a4c9f9b366423a76301/package-builder/build-manifest.nix#L2

- We should consider using the same nixpkgs as we build flox with, which might slightly decrease how many extra store paths this fetches
- We could ship a more minimal nixpkgs, since we currently only depend on `runCommandNoCC`

**Comment by mkenigs** [comment]
We could also use the same nixpkgs as the toplevel group is coming from

**Comment by limeytexan** [comment]
The `build-manifest.nix` will be evaluated at _build time_, so therefore needs to be evaluated in the context of the build, which will be using whatever Nixpkgs version that is pertinent to the build, be it the base page as selected from the `toplevel` manifest group or in the case of NEF builds a revision chosen from one of the stability branches.

So while it's not bad to have a default to fall back on, I definitely agree that `flox build` should always be supplying the `pkgs` override to use the same nixpkgs revision as the one being used for the build.

**Comment by ysndr** [comment]
I think this is closed through #2234?

**Comment by mkenigs** [comment]
I think you meant https://github.com/flox/flox/pull/2289
