### ISSUE TITLE
Monorepository Support

### ISSUE THREAD

**Issue by rawkode** [flox/flox#2087]
**Describe the feature:**

I'd like the ability to list other environments within the manifest.toml that when activated, layers on multiple environments.

In my monorepository, I'd like to provide a series of common environments near the top of the repository.

- NodeJS
- Bun
- Turso
- PostgreSQL
- Rust
- Zig

Then individual projects / services can cherry pick which ones make sense for them. In a Rust project, it may wish:

```toml
environments = [
  "floxhub://rawkode/rust",
  "gitroot://flox/turso",
  "gitroot://flox/bun"
]

```

Where `floxhub://` designates a remote environment, but `gitroot://` designates from the root of the current Git repository.

**Comment by mkenigs** [comment]
Is this the same as https://github.com/flox/flox/issues/1251?

**Comment by rawkode** [comment]
Very much so! Subscribed over there.

Thanks

**Comment by mkenigs** [comment]
Cool we'd love any extra input on that issue!
