### ISSUE TITLE
`flox-watchdog` should not be installed to `/usr/local/bin`

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2101]
Currently on mac we're installing `/usr/local/bin/flox-watchdog`. We should move `flox-watchdog` to libexec within the flox package or completely outside the flox package so it doesn't get installed

**Comment by limeytexan** [comment]
+1 ... either a link from `$out/libexec` or rewriting a path in source at build time.

**Comment by stahnma** [comment]
Blocked on me being able to verify a flox installation

**Comment by stahnma** [comment]
Verified on 1.3.3-177-g9ea2d3aa
