### ISSUE TITLE
flox build doesn't tell me it needs outputs in bin/ or lib/

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#2119]
### Motivation

**When** I am attempting a go build with `go build -o $out`
**I need** to see an error / warning telling me Flox needs binaries in `bin/` or libraries in `lib/` so the build can be wrapped correctly
**So I can** correct my build command accordingly

### Acceptance Criteria

_Bootstrapping design follows. Feel free to change_

_See a warning when build is passing but is missing known outputs_
**Given** I am developing https://github.com/charmbracelet/vhs
**And** I have build feature flag enabled
**And** I have an environment with `flox install go ffmpeg ttyd`
**And** I `flox edit` and add the following build

```
[build.vhs]
command = '''
go mod tidy
go build -o $out
'''
```

**When** I `flox build`
**Then** I see a warning:

```
....
✨ Build completed successfully
⚠️ Flox did not detect a bin/ or lib/ in the build output. 
It's recommended to provide build outputs to $out using bin/ and lib/.
Please 'flox edit' and update the build command and try again 
```

_Don't show the warning when the build is failing_
**And When** I break the build command
**And** run `flox build`
**Then** I don't see the warning

**Comment by ghudgins** [comment]
@bryanhonof +1 to this from today's research

**Comment by dcarley** [comment]
+1 from [this thread](https://flox-dev.slack.com/archives/C074WPYRJUB/p1728321737055899) where a binary copied to `$out` couldn't access a package from the environment because it wasn't wrapped like `$out/bin` is.

**Comment by dcarley** [comment]
Bumping to the top of the backlog because it came up again in research: https://flox-dev.slack.com/archives/C074WPYRJUB/p1729699763726569

**Comment by mkenigs** [comment]
Seems like we should check if `bin` does not exist, and if it doesn't, find any executables in the build output.
- Should we use `find` or write something in Rust?
- I think we need to follow symlinks?
- Any directories to exclude? We could do `libexec`.

I don't know that we need to do anything regarding `lib` at this point
