### ISSUE TITLE
flox build clean

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#2122]
### Motivation

**When** I have a bunch of half run builds
**I need** a command that cleans out the Flox files i'm unfamiliar with
**So I can** reset and get my build working

### Acceptance Criteria

_Clean up files when running new clean command_
**Given** I am using https://github.com/charmbracelet/vhs
**And** I have `flox pull --copy stahnma/vhs`
**And** I run `flox build` a few times
**When** I run `flox build clean`
**Then** I see result & buildcache symlinks have been removed

_builds with the name clean can still run_
**And When** I change the name of my build to 'clean' 
**And** run `flox build -- clean`
**Then** I see my build runs

Additional AC:

* update help
* update man pages

### Notes

Solution ideas:
* clean symlinks and delete the stable temporary directory (easiest)
* ~snapshot filesystem before build and after and then remove the deltas. (roughly `find` + `comm` + `rm`)~

**Comment by ysndr** [comment]
# Breakdown

- change `commands::build::Build::packages: Vec<String>` to `SubcommandOrBuildTargets`:

```diff
diff --git a/cli/flox/src/commands/build.rs b/cli/flox/src/commands/build.rs
index bebcc2a58..4fc6a5349 100644
--- a/cli/flox/src/commands/build.rs
+++ b/cli/flox/src/commands/build.rs
@@ -22,11 +22,28 @@ pub struct Build {
     #[bpaf(short('L'), long)]
     build_logs: bool,
 
-    /// The package to build, corresponds to the entries in
-    /// the 'build' table in the environment's manifest.toml.
-    /// If not specified, all packages are built.
-    #[bpaf(positional("build"))]
-    packages: Vec<String>,
+    #[bpaf(external(subcommand_or_build_targets))]
+    subcommand_or_targets: SubcommandOrBuildTargets,
+}
+
+#[derive(Debug, Bpaf, Clone)]
+enum SubcommandOrBuildTargets {
+    #[bpaf(command)]
+    Clean {
+        /// The package to clean, corresponds to the entries in
+        /// the 'build' table in the environment's manifest.toml.
+        /// If not specified, all packages are cleaned.
+        #[bpaf(positional("clean"))]
+        packages: Vec<String>,
+    },
+
+    BuildTargets {
+        /// The package to build, corresponds to the entries in
+        /// the 'build' table in the environment's manifest.toml.
+        /// If not specified, all packages are built.
+        #[bpaf(positional("build"))]
+        targets: Vec<String>,
+    },
 }
 
 impl Build {

```

- with `Clean`:
for every cleaned target delete result link,
if cache link exists delete cache link and run `nix store delete <store path of cache link>`

if no targets are provided, clean `{}-result` _symlinks_, and buildcache links as above

**Comment by limeytexan** [comment]
Spoke with Yannik offline about this to update the plan slightly:

* makefile tasks:
    * create a `__flox_clean__` target in `flox-build.mk` that will perform the clean
        * the makefile already calculates the known result symlinks, path to stable tmpdir, etc. so it's in a better position to know what needs to be deleted
* rust CLI tasks:
    * perform special-case logic to rewrite the "clean" build target
         * e.g. `flox build clean` will result in an invocation of `make -f .../flox-build.mk __flox_clean__`
         * this way users can have a build called "clean" and invoke that using the command `flox build -- clean`

I'll go ahead and create a branch and commit the makefile changes now and tag @ysndr to follow up with the rust updates.
