### ISSUE TITLE
Implement flox-activation set-ready and attach

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2132]
- `set-ready` should lock activations.json, set `ready = true`, and then unlock activations.json
- `attach` should support the following
    - `flox-activation attach --timeout X --pid <PID>  --flox-env <path> --id <id>`
        - Lock activations.json
        - Add { pid: PID, expiration: now+X } to the list of activations
        - Unlock activations.json

    - `flox-activation attach --remove PID1 --pid <PID2> --flox-env <path> --id <id>`
        - Lock activations.json
        - Adds { pid: PID2, expiration: None } to the list of activations
        - Removes { pid: PID1, expiration: _ } from the list of activations
        - Unlock activations.json

**Comment by ysndr** [comment]
> attach should do either of the following

should it do both but only one of them at once depending on the args or literally either?

**Comment by mkenigs** [comment]
> should it do both but only one of them at once depending on the args or literally either?

Only one of them at once depending on the args
