### ISSUE TITLE
Compatibility issue with andsens/homeschick

### ISSUE THREAD

**Issue by sudermanjr** [flox/flox#2159]
**Describe the bug:**
I use https://github.com/andsens/homeshick to track dotfiles and manage them in a uniform way. Ideally, I would track my default flox env by doing `homeschick symlink dotfiles .flox/env/manifest.toml` (and the other files I _think_ I would need). 

When I do this, homeschick moves the file, and then symlinks it into my shell. This breaks the flox environment going forward. 

This may not be so much of a bug as much as a question, but either way, open to suggestions on the best way to manage this, or more information so that I can figure out a workaround.

**Steps to reproduce:**
1. Move the .flox/manifest/env folder, and the .flox/env.json files to another location
2. Symlink those files back to their intended location
3. Run `flox install` of any tool

Result:

```
▶ flox install kubectl
❌ ERROR: Failed to open manifest for reading: No such file or directory (os error 2)

Please ensure that you have read permissions to '.flox/env/manifest.toml'.
```

Expected:
no error

**Screenshots/terminal output (if relevant):**
(see output above)

**Flox Version (run `flox --version` if possible):**
1.3.1

**`uname -a` output:**
```
Darwin thanos.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:49:48 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T8103 arm64
```

**Comment by ghudgins** [comment]
hey there - we'll check this out. my initial reaction: can you configure the tool to ignore the directories in `./flox/.gitignore`? the environment is fully reproducible with the env files, the manifest, and most importantly the manifest.lock. the resulting symlinks should be thought of as a temp file and will get created by Flox if they are absent on a system

**Comment by sudermanjr** [comment]
It's the env files and the manifest files that I would like the tool to focus on - essentially it moves them _into_ a git repo and then symlinks them back into the home environment so that it can centralize the management of them without writing a _massive_ gitignore for my $HOME.

It's a bit of a weird pattern, and I'm thinking that if I went all-in on flox, I might actually replace the tool entirely with Flox, but in the meantime I would love to support both.

The alternative is to probably just keep flox in its own repo and then maybe do some magic with submodules, or just init my flox environment separate from my dotfiles. Haven't gotten too far down the rabbit hole yet though.

**Comment by stealthybox** [comment]
Hey andy!
It looks like we might have a bug here following symlinks. This maybe isn't too hard to fix, but I'll look into it.

github.com/andsens/homeshick looks cool!
Never seen it before -- I'll try to reproduce.

Also, my initial instinct here is that `homeschick symlink dotfiles .flox/` may work.
The `.flox/` dir should have a .gitignore in it which should check-in to your repo nicely.
This would make it so that the manifest, env.json, and lockfile would never be separated from each other.
From the homeshick docs, this looks like it's called a shallow symlink: https://github.com/andsens/homeshick/wiki/Symlinking#shallow-symlinking
I'll also try that out.

**Comment by sudermanjr** [comment]
:wave:

I did try `homeschick track dotfiles .flox/` to pull in the whole directory, which does have the intended effect of ignoring certain files:

```
▶ homeshick track dotfiles .flox/
        track .flox/env.json
        track .flox/env/manifest.toml
        track .flox/env/manifest.lock
        track .flox/.gitignore
      ignored The file .flox/log/watchdog.69511.log would be ignored by git.
      ignored The file .flox/run/aarch64-darwin.default would be ignored by git.
```

I then also re-ran `homeschick symlink`, and got the same error as before.

Running `homeschick symlink dotfiles .flox/` doesn't do anything in particular, because `.flox` is not a "castle" in homeschick.  

```
9s ✗ homeshick symlink dotfiles .flox/
        error Could not link .flox/, expected /Users/asuderma/.homesick/repos/.flox/ to exist
```

Here's the symlinks:

```
▶ tree -L 2 -l .flox
.flox
├── cache
├── env
│   ├── manifest.lock -> ../../.homesick/repos/dotfiles/home/.flox/env/manifest.lock
│   └── manifest.toml -> ../../.homesick/repos/dotfiles/home/.flox/env/manifest.toml
├── env.json -> ../.homesick/repos/dotfiles/home/.flox/env.json
├── log
│   └── watchdog.69511.log
└── run
    └── aarch64-darwin.default -> /nix/store/534g98c2plgfacahzarpkklxl0kmjg9c-environment
```

**Comment by sudermanjr** [comment]
Just read the shallow symlinking bit, and I think that might work - I see what you're saying now.

I'm also exploring just managing more of this without homeschick to see what it would look like.

**Comment by stealthybox** [comment]
I can replicate your issue with directly symlinking the manifest, lock, and env.json!

Flox can do readonly operations on these symlinks just fine, but anytime flox tries write to these files, it fails saying the file doesn't exist:
- ./env/manifest.toml
- ./env/manifest.lock
- ./env.json

This occurs with `install` or `uninstall`/`remove` and `edit`.
Fixing this isn't too difficult.

Notably `flox push` is also broken, because the remote doesn't allow symlinks within `.flox/` to be pushed to FloxHub.
Fixing this probably involves following the symlinks and writing a local copy of the files or heavily modifying our pushing logic in some way. It's also fine if this is broken though since directly symlinked manifests are probably managed by something else other than FloxHub.

### Logs:
<details>
<summary>generate repo & track</summary>

```
❯ homeshick generate broken-flox
     generate broken-flox

❯ homeshick track broken-flox ~/.flox/env*
        track .flox/env/manifest.toml
        track .flox/env/manifest.lock
        track .flox/env.json

❯ ls -l ~/.flox/env*
lrwxr-xr-x  1 stealthybox  staff  50 Oct  3 19:49 /Users/stealthybox/.flox/env.json -> ../.homesick/repos/broken-flox/home/.flox/env.json

/Users/stealthybox/.flox/env:
total 0
lrwxr-xr-x  1 stealthybox  staff  62 Oct  3 19:49 manifest.lock -> ../../.homesick/repos/broken-flox/home/.flox/env/manifest.lock
lrwxr-xr-x  1 stealthybox  staff  62 Oct  3 19:49 manifest.toml -> ../../.homesick/repos/broken-flox/home/.flox/env/manifest.toml
```
</details>
<details>
<summary>working readonly stuff</summary>

```
❯ flox list
bat: bat (0.24.0)
bruno: bruno (1.6.1)
coreutils: coreutils (9.4)
curl: curl (8.6.0)
fd: fd (9.0.0)
git-lfs: git-lfs (3.5.0)
go: go (1.21.7)
htop: htop (3.3.0)
nil: nil (2023-08-09)
nix-top: nix-top (0.3.0)
toml-cli: toml-cli (0.2.3)

❯ flox install go
⚠️  Package with id 'go' already installed to environment 'default'
```
</details>
<details>
<summary>broken write operations</summary>

```
❯ flox remove go
❌ ERROR: Failed to open manifest for reading: No such file or directory (os error 2)

Please ensure that you have read permissions to '.flox/env/manifest.toml'.


❯ flox edit
❌ ERROR: Failed to open manifest for reading: No such file or directory (os error 2)

Please ensure that you have read permissions to '.flox/env/manifest.toml'.

```
</details>
<details>
<summary>rejected push</summary>

```
❯ flox push
❌ ERROR: failed to push environment: Git failed with: [exit code 1]
  stdout: To https://api.flox.dev/git/stealthybox/floxmeta
!	HEAD:refs/heads/default	[remote rejected] (hook declined)
Done

  stderr: remote: *** Symbolic links are not allowed in this repository
remote: FATAL: VREF/validate-env: helper program exit status 256
remote: error: hook declined to update refs/heads/default
error: failed to push some refs to 'https://api.flox.dev/git/stealthybox/floxmeta'

```
</details>

**Comment by stealthybox** [comment]
Luckily, the shallow symlink totally works, even for pushing to FloxHub.

Here's how I got my default flox environment working in homeshick:
```
❯ homeshick generate shallow-flox
     generate shallow-flox

❯ homeshick cd shallow-flox

❯ mv ~/.flox flox-default

❯ ln -sf ../flox-default home/.flox

❯ git add .
```
note: the `git add .` is important, or else homeshick won't link the directory
```
❯ cd ~

❯ homeshick link shallow-flox
      symlink .flox

❯ flox remove go
🗑️  'go' uninstalled from environment 'default'

❯ flox install go
✅ 'go' installed to environment 'default'

❯ flox push
✅ default successfully pushed to FloxHub

Use 'flox pull stealthybox/default' to get this environment in any other location.
```

**Comment by sudermanjr** [comment]
Awesome, thanks. I'll give that a shot. Appreciate the help!

**Comment by stealthybox** [comment]
ty for sharing homeshick! :)
