### ISSUE TITLE
Gate activate and services commands on activation version

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2162]
We may make backwards incompatible changes to how activations work. When we do this, `activate` and any `services` command should error with something like:
```
❌ ERROR: environment XXX has already been activated with an older incompatible version of 'flox'

Exit all activations of the environment and try again.
```

We can check for an old activation at the start of all `services` commands. For `activate`, we should probably make this check as part of `flox-activation start-or-attach` so that builds and containers don't attempt to attach to an incompatible activation.

We can detect an old activation by checking if there's an activation of an environment in env-registry.json but not in activations.json. In the future, we can check if the version of activations.json matches the version supported by `flox-activation`.

**Comment by ysndr** [comment]
NB if `flox-activations`, `flox-watchdog` _and_ `flox` need to read and write the activations file, should those activations.json impls go into flox_core then?

**Comment by mkenigs** [comment]
> NB if `flox-activations`, `flox-watchdog` _and_ `flox` need to read and write the activations file, should those activations.json impls go into flox_core then?

Yeah I think so
