### ISSUE TITLE
the error message text for missing $out is incorrect

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#2171]
The builder currently issues this "hint" when detecting that `$out` has not been populated by a build:
```
echo "- copy multiple files with 'mkdir -p \$out && cp bin/* \$out/'" 1>&2
```

That hint isn't exactly correct because it would copy a bunch of executables to the root directory of the `$out` package, and executables belong in the `$out/bin` directory.

We probably want it to read:
```
echo "- copy multiple files with 'mkdir -p \$out/bin && cp bin/* \$out/bin'" 1>&2
```
(or similar)

**Comment by limeytexan** [comment]
Fixed with #2379
