### ISSUE TITLE
Test and fix nested RC activations for non-zsh shells

### ISSUE THREAD

**Issue by dcarley** [flox/flox#2194]
**Acceptance criteria**

Add tests that verify `hook` and `profile` scripts are run for nested activations of non-zsh shells where:

- outer activation is in-place from an RC file
- inner activation is interactive (must use `expect`)

Fix our activation scripts if the tests don't pass.

**Why**

We fixed this for `zsh` in https://github.com/flox/flox/issues/1946 and https://github.com/flox/flox/pull/2153 but suspect that the same issue might be present for other shells.

**Notes**

In doing so we should re-evaluate or defer to a separate ticket the following from https://github.com/flox/flox/pull/2153:

> changing to passing all the args to the zsh activation scripts with a file or maybe regenerating ZDOTDIR for every activation or something. I just feel like depending on FLOX_ENV from the environment is bug prone once you get nesting happening inside another activation. We have to set that for users, but that doesn't mean we have to make all of our code depend on it

**Comment by mkenigs** [comment]
I think this will close https://github.com/flox/flox/issues/2181

**Comment by billlevine** [comment]
Confirmed this is an issue in bash.

**Comment by dcarley** [comment]
Looks like this was closed by mistake.

**Comment by mkenigs** [comment]
We don't have tests for `hook`, but we do have tests for aliases that come from `profile` and `PATH` so I think that's good enough for now
