### ISSUE TITLE
Additional instrumentation for installs and the catalog client

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2200]
We've received multiple reports of installations/first time activations that take 10 minutes. Looking at our Sentry instrumentation, we don't actually break down install times at all, so it's unclear where those 10 minutes are spent (resolution or building the lockfile).

Addressing this means adding `tracing` support to `flox-rust-sdk` to distinguish different code paths in the `install` path. While we're at it, we may as well add instrumentation to the catalog client for the different methods.

**Comment by mkenigs** [comment]
Could we lump adding a metric for `flox activate --start-services` and one for `flox activate -r` in this ticket?

**Comment by zmitchell** [comment]
They’re all very simple additions, so sure

**Comment by mkenigs** [comment]
Closing in favor of slow operations epic for now
