### ISSUE TITLE
Lockfile formatting inconsistency

### ISSUE THREAD

**Issue by tomberek** [flox/flox#2201]
**Describe the bug:**
manifest.lock format (JSON is one-line instead of pretty-indented) changes when running `flox upgrade`

**Steps to reproduce:**
1. `flox init`
2. `flox install hello` ; cat .flox/env/manifest.lock
3. `flox upgrade` ; cat .flox/env/manifest.lock

Result:
Different format, even when the upgrade reports "No packages need to be upgraded in environment".

Expected:
No diff.

**Flox Version (run `flox --version` if possible):**
1.3.3 (9506c575d2558d4e97538572eb2e4a7075bd2d4a)

**`uname -a` output:**
Linux tframe 6.6.47 #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:04:32 UTC 2024 x86_64 GNU/Linux

**Comment by ysndr** [comment]
should have been closed by #2391
