### ISSUE TITLE
3-pt timebox for testing `flox-activations`

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2203]
In our meeting this morning we discussed what of `flox-activations` we want to test, with what degree of rigor, and on what timescales. Here's how to make that happen.

## Runtime breakpoints

There will be situations in which two shells make calls to `flox-activations` at similar times, and we need to ensure that the operations they perform and their interleavings don't leave us in a bad state. `flox-activations` is intentionally small and single-threaded, so mocking time using something like `tokio::time` is out of the question, as are other deterministic simulation techniques. Instead I proposed a "breakpoint"-like mechanism using sentinel files.

The idea looks like this:
- At various points in the `flox-activations` code where we want a breakpoint, you call a macro `test_breakpoint!(<name>)`.
- This macro produces an `if` statement that's conditionally compiled (probably included in `debug` profile?) such that it's not included in the production binary.
- When compiled in, the macro checks the environment for the presence of a variable named `_FLOX_BREAKPOINT_<name>`.
    - If this variable exists, contains a file path, and the file exists, block in a polling loop until the file is removed.

This would look like (see the [debug_assertions feature](https://doc.rust-lang.org/stable/reference/conditional-compilation.html?highlight=debug_ass#debug_assertions)):
```rust
macro_rules! test_breakpoint {
    ($name:literal) => {
        #[cfg(debug_assertions)]
        if let Ok(value) = std::os::env("_FLOX_BREAKPOINT_$name") {
            // if value is a path, and path exists, wait, ...
        }
    }
}
```

This allows us to have various pause points in the execution of `flox-activations` that we can enable at runtime without needing to recompile `flox-activations` for different tests.
This is quick and lets us test the race conditions that we know about.

This should be the first stab at testing because it's quick and lets us deliver functionality with some kind of test coverage.

## Event simulation

It's very, very hard to predict all of the race conditions that exists between multiple interacting systems, so coming up with ordered sequences of operations between an arbitrary number of `flox-activations` calls is best left to a computer.
The general pattern for this technique is to put each operation into an enum variant, then generate a sequence of enum instances:
```rust
enum Ops {
    StartOrAttach { pid: i32},
    SetReady { pid: i32 },
    AttachWithTimeout { pid: i32 },
    ...
}

let ops = vec![StartOrAttach{ pid: 1 }, StartOrAttach{ pid: 2}, SetReady{ pid: 1}, ...];
```

We already use `proptest` to generate arbitrary data for tests, but usually to verify data integrity, not to verify temporal ordering.
That's because (1) we haven't had the need, and (2) it's tricky.
The hard part about this technique is that it's very easy to generate nonsense sequences e.g. the first operation is an `attach` to an activation that doesn't exist.

Instead we'll go with a hybrid approach that prepares the system in a known good initial state such as:
- Activation already exists, watchdog already exists
- Activation doesn't exist, watchdog doesn't exist
- ...(more examples left as an exercise to the reader)

### Actors

There's a few different moving pieces to how activations work now, and they each have different operations that they
(can) perform:
- "leader": the shell that starts the activation
- "follower": a shell that's trying to attach
- watchdog

Even within "follower" there are multiple kinds of activation e.g. in-place vs subshell.
Those two different types of activations have different operations that it makes sense to perform,
and a single actor interleaving actions from different kinds of "activation modes" is nonsense that we don't want to generate.

I think that means we need to keep track of which actors we're generating and which "flavor" they are.
In pseudo-code that would look like
```text
Use proptest to generate a number of actors
    Pick one of them to be a Leader
    Assign the rest to be followers of one flavor or another
    Make a watchdog actor
Generate operations for each actor
Interleave the operations
    The first operation comes from the leader
    Everything else gets interleaved between actors, but order is preserved for operations from a single actor
```

For actors that have multiple operations e.g. `StartOrAttach` and `SetReady` for the leader, those operations will go into
a dedicate enum for that actor type.
For actors that have a single operationg e.g. `Attach` for subshell follower, `AttachWithTimeout` for in-place follower,
those can probably be put into a `MiscOps` enum since it doesn't make sense to have a single-variant enum.
That `MiscOps` enum would also hold an `Advance` variant for advancing time, but we'll get to that later.

In order to generate a `Vec` of all of these operations they all need to have the same type, so in the end you'll need
a parent enum that holds a variant for each actor flavor:
```rust
enum Ops {
    Leader(LeaderOp),
    SubshellFollower(MiscOps),
    InPlaceFollower(MiscOps),
    Watchdog(WatchdogOps),
    Misc(MiscOps)
}
```

### `flox-activations` implementation details
In order to perform the operations generated by `proptest`, the actual implementations need to be able to be called with the data that we can generate from `proptest`.
In short, the operations need to be pure.
As an example, the `set-ready` command would internally delegate to a function like this:
```rust
fn set_ready(cache_dir: impl AsRef<Path>, flox_env: impl AsRef<Path>, id: impl AsRef<str>) -> Result<(), Error> { ... }
```

In the test you wouldn't generate those paths randomly, you would use a tempfile inside each test, but the `id` would be generated by `proptest`.

Another thing to consider is that some of these operations will block in a polling loop in their actual implementation.
If you're trying to simulate something else happening concurrently, this will block the test while that loop spins.
For example, consider this sequence:
- leader starts an activation
- follower wants to attach so it waits in a loop

In the test if you actually call the loop in the follower, it will never succeed if run as a whole because it probably
blocks while waiting on the leader, which we can't run because we're blocked on the follower.
That means you probably need some level of atomicity to the operations inside the `flox-activations` commands so that
you can call them individually e.g. `attach` would be broken into `check_ready()`, `check_leader_is_alive()`, etc.

I'm not _exactly_ sure if that's how we want to do this since it starts to dictate the implementation of `flox-activations`
and uses internal APIs for tests, but we do need to figure out some way to get around the "this operation will block forever" issue.

### Time

For the operations that read or set timeouts, you need to be a little creative in order to mock time.
You can parameterize those operations with a closure that can be called to get the current time, you can pass in the current `SystemTime`, etc.
This allows you to add/subtract `Durations` from the "current time" to skip time forward and exercise timeouts.
That would look something like this:
```rust
fn attach_with_remove(..., get_time: Fn() -> SystemTime) -> ... {}

// In production
attach_with_remove(..., SytemTime::now);

// In test
let mut now = Arc::new(SystemTime::now());
// ...do something...
// advance time outside however you'd like, it's an Arc
attach_with_remove(... || {
    // Advance time inside by 10ms each time this is called.
    let advance_interval = Duration::from_millis(10);
    let prev = *now.clone();
    now += advance_interval;
    prev
});
```

Since some of the operations either set a timeout or loop on 

You probably also want to stagger some of these operations so that they don't happen at _exactly the same time,
so one of the enum variants could be `Advance { ms: Duration }` which would only have the effect of moving time forwards
without being attached to a particular operation.

**Comment by mkenigs** [comment]
> macro_rules! test_breakpoint {
>     ($name:literal) => {
>         #[cfg(debug_assertions)]
>         if let Ok(value) = std::os::env("_FLOX_BREAKPOINT_$name") {
>             // if value is a path, and path exists, wait, ...
>         }
>     }
> }

What happens if multiple actors hit the same breakpoint? Don't we need a way to specify which one goes first?

> 
>     * "leader": the shell that starts the activation
> 
>     * "follower": a shell that's trying to attach
> 
>     * watchdog

How does that test something like two activations starting at approximately the same time? We need to test that whoever gets to the lock first becomes the leader. I guess maybe we do that with how we order breakpoints for the leader vs the follower? I think the high level approach you're describing makes sense to me, but it's still pretty fuzzy what it would actually look like in practice. Might be helpful to write some pseudocode for testing a scenario like two activations starting around the same time.


> For actors that have multiple operations e.g. `StartOrAttach` and `SetReady` for the leader, those operations will go into a dedicate enum for that actor type. For actors that have a single operationg e.g. `Attach` for subshell follower, `AttachWithTimeout` for in-place follower, those can probably be put into a `MiscOps` enum since it doesn't make sense to have a single-variant enum. That `MiscOps` enum would also hold an `Advance` variant for advancing time, but we'll get to that later.

Nit: attach and attach with timeout should always come after a start or attach, so I think they'd still be in a sequence

**Comment by zmitchell** [comment]
> What happens if multiple actors hit the same breakpoint? Don't we need a way to specify which one goes first?

What I was imagining for tests that use this starting two `Command`s, one for each `flox-activations`, and you would stop each one at a different breakpoint. So, in short, "don't do that with this method." For a given breakpoint and two actors, there's only two possible orderings, so I figured we would be writing those out as the first stab at testing.

> How does that test something like two activations starting at approximately the same time? We need to test that whoever gets to the lock first becomes the leader.

It depends on which breakpoints exist (how granular they are) and how you interleave them. Also, it doesn't actually look like the locking semantics are spelled out in the diagram or the document, so we should agree on that before really digging into this.

**Comment by mkenigs** [comment]
> So, in short, "don't do that with this method."

If we want to support e.g. multiple `start-or-attach` runs having different breakpoints, we could pass something into functions like `start_or_attach(breakpoint)`. We could also probably use something in-memory in that case rather than using a file as well

**Comment by mkenigs** [comment]
I'm wondering if it would be more straightforward to just factor out pieces of functionality that we want to sequence in any order, and then just trust the lock. E.g.
```
first_part_of_start_or_attach(pid1)
first_part_of_start_or_attach(pid2)
attach_if_ready(pid2)
start(pid1)
attach_if_ready(pid2)
```

That doesn't exercise our polling code, but if our polling code just loops trying to `attach_if_ready`, it seems like the test is probably thorough enough

**Comment by mkenigs** [comment]
It may be helpful to mock PIDs for this, see https://github.com/flox/flox/issues/2168

If the simpler approach works, we should go with that

**Comment by zmitchell** [comment]
Given that we don't want to test this super thoroughly and we already have unit tests for individual steps in the activation process, I'm going to close this.
