### ISSUE TITLE
Use `pkgdb realisepkgs` and `buildenv.nix` to build environments

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2207]
Instead of using `pkgdb buildenv` to build an environment, build an environment in two stages:
1. Call `pkgdb realisepkgs`
2. Run `nix build buildenv.nix`
3. Link just the development output to `.flox/run/{system}.{name}` for now

**Comment by mkenigs** [comment]
Counterpoint: ensurePath will repair corrupt paths

**Comment by ysndr** [comment]
`ensurePath` also checks the database whether a path is currently being build which `stat`ing the outpath itself does not do

**Comment by mkenigs** [comment]
> `ensurePath` also checks the database whether a path is currently being build which `stat`ing the outpath itself does not do

Does the path get created before the build finishes? If it's transactional at the end of the build I don't think that's a problem

**Comment by mkenigs** [comment]
@limeytexan has a Bash script that functions as a drop in wrapper for pkgdb. We could consider using that instead of doing all of 1, 2, and 3 if we think that's faster

**Comment by mkenigs** [comment]
Removing attachment from 2226 as my understanding is that's adding the Nix builder. This ticket is for integrating that builder in Rust

**Comment by mkenigs** [comment]
> I'd need to check but considering that $out generally points to the final store path I think it's created at start of building and later chowned or deleted if the build fails

That would make sense, but actually...it doesn't even get deleted if the build fails lol. And it gets created while the build is running:
```
> cat expr.nix
(import <nixpkgs> {}).runCommand "sleep" {} ''
  for i in {1..10}; do
    echo "$i" >> "$out"
    sleep .2
  done
  false
''

> nix eval --file expr.nix --json
"/nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep"

> cat /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep
cat: /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep: No such file or directory

> nix build --file expr.nix 2>/dev/null >/dev/null &
[1] 24395

> cat /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep
cat: /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep: No such file or directory

> cat /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep
1
2
3
4
5
6

>
[1]  + exit 1     nix build --file expr.nix 2> /dev/null > /dev/null

> cat /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep
1
2
3
4
5
6
7
8
9
10

> nix-store --realise /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep
don't know how to build these paths:
  /nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep
error: build of '/nix/store/hq2dw3iry9adp8ypk4a569l4g7ylczrv-sleep' failed
```

So I think you're right it might be better to use `ensurePath`. Especially once we add install by storePath
