### ISSUE TITLE
Integrate new buildenv.nix environment builder into builds and support package runtimes

### ISSUE THREAD

**Issue by ysndr** [flox/flox#2238]
Split out from #2065.

Make the necessary changes to a) provide environments that the build runs in b) build with different runtime envs  (flox-build.mk, manifest-build.nix) c) provide specific environments for individual packages.

Remaining questions:

* what is the runtime environment of a package A that depends on another (flox built) package B?
  - runtime environment of Package A
  - the union of runtime environment of Package A and B
* exact changes to flox-build.mk, which environment variants it needs and how we pass them

**Comment by limeytexan** [comment]
This issue may have been addressed by #2226. To be clear, there are just two environments involved with a manifest build:

1. the "develop" environment, which is the very same environment that the user uses on the command line, used to perform the build
2. the package-specific "runtime" environment which is used to wrap applications in `bin` and `sbin`

And both of these are now built by default with the new buildenv implementation.

**Comment by ysndr** [comment]
I think this is actually addressed now with #2343
