### ISSUE TITLE
Ask if we should put an in-place activation in their shell startup on first run of Flox

### ISSUE THREAD

**Issue by stahnma** [flox/flox#2253]
We should ask the user if they'd like to have their default environment activated upon shell launch the first time they run flox install. 

AC:
 
- [ ] The user is asked if they want a startup shell activation automatically
- [ ] If they say no, we display the text they could manually add to their shell rc. 
- [ ] If yes, we modify the shell rc files. 
- [ ] The answer is recorded so the user is not asked again. 

/cc @jennymahmoudi 

**When** I flox install <package-name> in a directory without a Flox environment,
**And** I do not have any other active Flox environments,
**And** I have never been asked to create a default environment before,
**And** I respond **YES** when asked if I want to install to the user default environment (via #2254)
**Then** I see a prompt (specific to their shell type) asking if I want the user default environment to be activated on shell launch (by modifying their rc file):
```
The 'default' environment can be activated automatically for every new shell
by adding one line to your .zshrc file:  
eval "$(flox activate --mode=run --dir ~)"  

Would you like Flox to add this configuration to your .zshrc file now?
> Yes
   No
```
Selecting `yes` will add the configuration, and show a confirmation, before continuing with the install:
```
✅ Configuration added to your .zshrc file. 
The 'default' environment will be activated for every new shell.
-> Restart your shell to continue using the default environment 
-> More about the 'default' environment: https://flox.dev/docs/tutorials/layering-multiple-environments/#create-your-default-home-environment
```

Selecting `no` will provide the docs link and continue with the install:
```
-> More about the 'default' environment at: https://flox.dev/docs/tutorials/layering-multiple-environments/#create-your-default-home-environment
```

**Comment by limeytexan** [comment]
@stahnma are you missing the "if they say yes we update their shell rc file(s) for them" case above?

**Comment by mkenigs** [comment]
I don't quite understand how this fits with creating a default environment. #2254 says we don't create the default environment until `flox install` is run. But then if they run `flox --help`, do we leave their shell rc in a bad state, activating an environment that hasn't been init'ed?

**Comment by stahnma** [comment]
@limeytexan yup. Somehow missed that important part. It's there now.

**Comment by stahnma** [comment]
@mkenigs updated to say upon first time running `flox install`. Hopefully that clear it up?

**Comment by zmitchell** [comment]
From @limeytexan: When adding the line to a user's RC file, store their original RC file as a backup in case the edit goes horribly wrong.

```text
Packages must be installed into a Flox environment, which can be a
user default environment or attached to a directory.
```

Suggestion:
```text
Packages must be installed into a Flox environment, which can be a
per-user global environment called 'default', or attached to a directory.
```

Once you explain here that the `default` environment exists and is global for each user, you don't need to use the phrase "user default" repeatedly (it feels verbose to me).

**Comment by stahnma** [comment]
I still prefer not to use global, as it's "per-user" and not global to the system.

**Comment by jennymahmoudi** [comment]
> Once you explain here that the default environment exists and is global for each user, you don't need to use the phrase "user default" repeatedly (it feels verbose to me).

Agreed! Made some adjustments.

**Comment by mkenigs** [comment]
I think we should also update
```
The 'default' environment will now be activated for every new shell.
```
to also tell them to restart their shell immediately. If e.g. they immediately run another `flox install`, we would want that to work

**Comment by jennymahmoudi** [comment]
> tell them to restart their shell immediately. If e.g. they immediately run another flox install, we would want that to work

Why wouldn't a second install work without restarting? Aren't we activating the default env for them?

**Comment by mkenigs** [comment]
> Why wouldn't a second install work without restarting? Aren't we activating the default env for them?

We're putting the activation in their rc files, so the default env will be activated for every new shell, but not the current one. We either need to tell them to restart their shell (which will run the `eval "$(flox activate -d ~)"` that we put in their shell startup) or tell them to manually run `eval "$(flox activate -d ~)"` (we could also start a subshell, but that's not the expected way to use a default environment, so I don't think that's best)

Homebrew for comparison tells the user to run the eval command:

![Image](https://github.com/user-attachments/assets/46d166bc-80a6-45e4-98ac-fce1018ffc11)

**Comment by jennymahmoudi** [comment]
I think restarting the shell is the simplest option that shows them exactly how it will work from there on.

How about this:
![Image](https://github.com/user-attachments/assets/d63548fb-8a70-45f6-90a6-30797310aeca)

**Comment by jennymahmoudi** [comment]
> Nit: should we put a newline before the URL?

Implementer's choice. I think it's going to wrap either way?

**Comment by mkenigs** [comment]
> Implementer's choice. I think it's going to wrap either way?

Style guide says we wrap at 80, but I'm not sure we've been diligent about that...

**Comment by mkenigs** [comment]
@jennymahmoudi ready for review
