### ISSUE TITLE
Default env should be initialized automatically

### ISSUE THREAD

**Issue by stahnma** [flox/flox#2254]
When a user types `flox install foo`, I want `foo` to be installed in their default environment, so the initial experience with flox has fewer steps. 

A/C

- [ ] Without first creating a default env using `flox init`, a `flox install` works.
- [ ] If they are not in `~`, running `flox install` should prompt if they want to create a default env or one attached to the current directory they are in
- [ ] If the user selects 'no', we output a small `flox init` explanation so they can perform the operations themselves later
- [ ] metrics for triggering this prompt

/cc @jennymahmoudi 

**When** I `flox install <package-name>` or `flox install <package1> <package2> <package3>` in a directory without a Flox environment, 
**And** I do not have any other active Flox environments,
**And** I have never been asked to create a default environment before,
**Then** I see a prompt asking if I want to install to the user default environment:
### single package
```
Packages must be installed into a Flox environment, which can be a user 'default' environment or attached to a directory.  

Would you like to install 'package-name' to the 'default' environment?
> Yes
   No
```
### multiple packages
```
Packages must be installed into a Flox environment, which can be a user default environment or attached to a directory.  

Would you like to install 'package1, package2, ...' to the 'default' environment?
> Yes
   No
```

### Yes
Selecting `Yes` would proceed with the install after the following prompt...
**And** prompts for rc shell modification in #2253

### No
Selecting `No` would cancel the install, and if possible, add the message for what to do instead:
```
You can create an environment with 'flox init' 
Or specify another environment with 'flox install <package-name> --dir <PATH>'
```

### Note:
* This does not specify that we are creating a default environment -- we could, but I think if we want to make this seamless, we should just act as though it's already there, and not burden with the extra information.

**Comment by jennymahmoudi** [comment]
We should only ask this one time, so I would add "Do not ask again when attempting to install in a directory without a flox environment."

That also means that they might have several environments already before they encounter the case where they try installing into a directory without an environment. That would be the first and only time they get prompted if they want to use the default/global env.

**Comment by jennymahmoudi** [comment]
@stahnma could also add to this ticket or create a new one:

**When** I `flox install <package-name>` in a directory without a Flox environment, 
**And** I do not have any other active Flox environments,
**And** there is a default environment but it's not activated,
**Then** I see a message asking if I want to activate it and install to the default env 
```
message tbd
```

This is so that they don't see the error message even if they don't add activation to their RC file

**Comment by ghudgins** [comment]
>something like globally

maybe "user default environment"?

**Comment by stahnma** [comment]
@jennymahmoudi for that second idea, let's hold off for now.

**Comment by mkenigs** [comment]
Breakdown notes:

- We can trigger this logic when `detect_concrete_environment` returns an `Err`
- We could add a file in ~/.cache/flox to save whether we've prompted. Should we combine this with `update-check-timestamp.json` or add a separate file?

**Comment by mkenigs** [comment]
@jennymahmoudi if the `install` fails, I assume we leave behind the environment we `flox init`ed. Does that count as having prompted? It's likely someone would correct a typo `flox install whoops` to `flox install fixed`, but they might not have the environment activated at that point and might need to activate it or pass `-d`

**Comment by jennymahmoudi** [comment]
> [@jennymahmoudi](https://github.com/jennymahmoudi) if the `install` fails, I assume we leave behind the environment we `flox init`ed. Does that count as having prompted? It's likely someone would correct a typo `flox install whoops` to `flox install fixed`, but they might not have the environment activated at that point and might need to activate it or pass `-d`

I don't think this will be an issue...
If you look at the whole workflow in the [prototype](https://www.figma.com/proto/BhhO9T0kt8CpA8ocArFwrJ/FloxHub?page-id=1881%3A3413&node-id=1881-3435&node-type=frame&viewport=723%2C-273%2C0.9&t=tuZMKndLYx2wKE7d-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1881%3A3435), they will be asked immediately after creating the default env if they want to set up the activation. So even if the install fails, they would have already been prompted to do those things. LMK if that seems right to you too.

**Comment by mkenigs** [comment]
> I don't think this will be an issue... If you look at the whole workflow in the [prototype](https://www.figma.com/proto/BhhO9T0kt8CpA8ocArFwrJ/FloxHub?page-id=1881%3A3413&node-id=1881-3435&node-type=frame&viewport=723%2C-273%2C0.9&t=tuZMKndLYx2wKE7d-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1881%3A3435), they will be asked immediately after creating the default env if they want to set up the activation. So even if the install fails, they would have already been prompted to do those things. LMK if that seems right to you too.

If we tell them to restart their shell (https://github.com/flox/flox/issues/2253#issuecomment-2448634305) I think that's fine

**Comment by zmitchell** [comment]
Couple of other wording suggestions:
- The user might be installing multiple packages, so I think we should truncate the list of packages in the message to two and add an ellipsis e.g. `Would you like to install 'hello, ripgrep, ...' to the 'default' environment?`
- I think the confirmation dialog can simply be "yes" or "no", I don't think we need to repeat what they're deciding three times.

**Comment by jennymahmoudi** [comment]
> * The user might be installing multiple packages, so I think we should truncate the list of packages in the message to two and add an ellipsis e.g. `Would you like to install 'hello, ripgrep, ...' to the 'default' environment?`

Sounds good. If it would be any easier, if there is more than one, could we say `packages` as in  `Would you like to install packages to the 'default' environment?"`

> * I think the confirmation dialog can simply be "yes" or "no", I don't think we need to repeat what they're deciding three times.

If it was a [y/n] at the end of the line I agree, but the way our prompts work now, the response gets highlighted as a record of what you decided. I would like to keep the verbosity of the response for clarity, even if it feels redundant.
![Image](https://github.com/user-attachments/assets/0a277ba4-0c1a-49e5-81c5-1ac812fcbc3b)

**Comment by jennymahmoudi** [comment]
Aaaaaaand I was wrong about that. We do already have a "Yes / No" option for the `flox init` language suggestions:
![Image](https://github.com/user-attachments/assets/92ade5db-0b62-4047-a862-8c08836e5889)

Updating the messages to `Yes` and `No`!

**Comment by mkenigs** [comment]
@jennymahmoudi ready for review
