### ISSUE TITLE
Unify PID status checking

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2265]
We check the status of PIDs (running, zombie, etc) in three different places:
- `PidWatcher` in `flox-watchdog`
- `ActivationPid` in `env_registry.rs` (uses kill, bad)
- `AttachedPid` in `flox-activations` (uses kill, bad)

We should standardize on one way for checking process status and use that in all three locations.

The methods for getting the PID status on `PidWatcher` are actually static methods, so they can just be called wherever you need them. I think it makes sense to refactor those into free standing functions in `flox-core` since we use them in three different crates. This also prevents us from being surprised by different status behavior.

**Comment by mkenigs** [comment]
https://github.com/flox/flox/pull/2501
