### ISSUE TITLE
After successful build, tell the user where the output is

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#2267]
### Motivation

**When** I am using Flox builds for the first time and my build completes successfully
**I need** to know where to go to find the result
**So I can** verify the output

### Acceptance Criteria

**When** I `flox build` successfully
**Then** I see ....

```
✨ Build completed successfully. Output created: ./result-vhs
```

**Comment by ghudgins** [comment]
+1 from user research (Julio S.)

**Comment by jennymahmoudi** [comment]
+1 from user research (Gene L.)

**Comment by billlevine** [comment]
Ticket #2312 is in to provide structured output of this info for use in publish.  It could also be used for this purpose.
