### ISSUE TITLE
Fix `timeout 2 cat started` flakey test

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2280]
We've seen `timeout 2 cat started` failures for two different tests relatively frequently. Fix at least one of them

remote: can interact with services from outside the activation in 2428ms
(in test file services.bats, line 1024)
`timeout 2 cat started' failed with status 124
https://github.com/flox/flox/actions/runs/11141467142/job/30962466132#step:5:477
https://github.com/flox/flox/actions/runs/11239601634/job/31247170599#step:5:475
https://github.com/flox/flox/actions/runs/11277180298/job/31362840660#step:5:517

not ok 348 remote: only have a single instance of services in 2398ms
`timeout 2 cat started' failed with status 124
https://github.com/flox/flox/actions/runs/11168264408/job/31046366440#step:5:471
https://github.com/flox/flox/actions/runs/11436599296/job/31818213707

**Comment by mkenigs** [comment]
I can reproduce this about every ~50 runs on Linux. I added `-vvv` and copied out the logs and got:
```
2024-11-04T21:03:04.499754Z TRACE flox::utils::errors: formatting environment_error: RemoteEnvironment(WriteNewOutlink(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
2024-11-04T21:03:04.499814Z TRACE flox::utils::errors: formatting remote_environment_error: WriteNewOutlink(Os { code: 2, kind: NotFound, message: "No such file or directory" })
❌ ERROR: could not set a new install prefix: No such file or directory (os error 2)
2024-11-04T21:03:04.500526Z DEBUG flox::utils::metrics: No metrics client setup, skipping flush
```

**Comment by ysndr** [comment]
> After doing some more debugging, it seems like there are a few more errors that make it seem like directories are being deleted during the test, and then the test fails at random points throughout the test. Failures I've seen:

I think this is expected as the teardown will remove the exact directory that holds the started fifo

```mermaid
sequenceDiagram
    test_process ->>+ Activation_1: start

    test_process ->>+ Started_timer: wait

    Activation_1 ->>+ Activation_1_build: building
    note right of Activation_1_build: up to 1s+  
    
    Activation_1_build ->>- Activation_1: 


    Activation_1 ->>+ Activation_1_starting: running init

    Started_timer -x- test_process: timeout

    test_process ->> test_process: teardown
    note over test_process: removes test tempdirs



    Activation_1_starting -X- Activation_1: 
    note over Activation_1_starting: fails to find pwd


    Activation_1 -->>- test_process: notify started



    
    test_process -->>+ Activation_2: start

    
            
```




Follow up notes:

* the rust side of activation takes about 1 second from the first log to the

```
2024-11-06T13:33:00.048909Z DEBUG flox: set _FLOX_PKGDB_VERBOSITY=4    
2024-11-06T13:33:01.063292Z DEBUG flox::commands::activate: running activation command
```

* the activation sources the _running user's_ rc files (in contrast to using isolated ones provided buy the testsuite)

```
++ source /Users/yannik/.bashrc
```

* it also uses the user's SHELL but that may be intentional to capture platform details.

**Comment by mkenigs** [comment]
Sometimes on x86_64-linux we're seeing the Nix daemon block us for a few seconds https://flox-dev.slack.com/archives/C054SAD6NLD/p1730930886040019

**Comment by mkenigs** [comment]
I wonder if we should do anything that does a Nix build outside of the timeout (maybe a dummy `flox edit`) and then the timeout would only apply to things that won't block on the Nix daemon
