### ISSUE TITLE
build: Wrapped binaries shouldn't exec hooks or block other activations

### ISSUE THREAD

**Issue by dcarley** [flox/flox#2287]
⚠ Requires design and refinement.

**Acceptance criteria**

Executing a wrapped binary from `flox build` should not:

- execute `hook.on-activate`
- "start" an activation and subsequently block it from being cleaned up

**Why**

The wrapper currently calls `${FLOX_ENV}/activate --turbo` which bypasses some shell profile scripts but still:

- runs hooks, which could be surprising and slow
- uses the complete `flox-activations` flow which could prevent cleanup or hooks being executed for interactive activations whilst the command is running

This ticket has been split from https://github.com/flox/flox/pull/2276

**Comment by mkenigs** [comment]
I think per the decision in 010-Manifest-build-executable-wrapper we can close this for now. We can re-open if we get complaints or change our mind
