### ISSUE TITLE
Add "--mode" flag to activate

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2295]
To enable "runtime" mode we need to expose a `--mode/-m <name>` flag. We also need to decide on a name for the "runtime" mode. No one seems to love "run", but "bin" doesn't feel great either.

**Comment by zmitchell** [comment]
We've decided that the modes will be called `run` and `dev`, and for now the `dev` mode is a no-op since the default behavior at the moment is already dev-mode.

**Comment by mkenigs** [comment]
We should change the prompt to add a default environment to rc files to add `--mode run` as part of this
