### ISSUE TITLE
Request to pretty print the lockfile

### ISSUE THREAD

**Issue by stahnma** [flox/flox#2321]
When I am reviewing a environment for differences, I want to see them at a field level so I can review them with intelligence rather than just see that the whole file has changed. 

I think this could be accomplished if we pretty-printed the lockfile, and then the diff would only show the fields that changed.

**Comment by stahnma** [comment]
This is probably related to #2201 as well.

**Comment by ysndr** [comment]
Only `CoreEnvironment::lock` and `upgrade` should write lockfiles at all.

`lock` is already using `to_string_pretty`, while `upgrade` uses `json!(...).to_string()` [1] which will write the condensed format.

Can you confirm that you have pretty printed lockfiles after an install or similar action, and that the fix needs to apply to `flox ugrade` only?

[1]
https://github.com/flox/flox/blob/e54d776d24764d358e381f02d9ef80127ac99f02/cli/flox-rust-sdk/src/models/environment/core_environment.rs#L679-L681

diff to fix the upgrade case:

```diff
diff --git a/cli/flox-rust-sdk/src/models/environment/core_environment.rs b/cli/flox-rust-sdk/src/models/environment/core_environment.rs
index c331f56cf..20f41ee91 100644
--- a/cli/flox-rust-sdk/src/models/environment/core_environment.rs
+++ b/cli/flox-rust-sdk/src/models/environment/core_environment.rs
@@ -676,8 +676,12 @@ impl CoreEnvironment<ReadOnly> {
             (lockfile, upgraded)
         };
 
+        // SAFETY: serde_json::to_string_pretty is only documented to fail if
+        // the "Serialize decides to fail, or if T contains a map with non-string keys",
+        // neither of which should happen here.
+        let lockfile_contents = serde_json::to_string_pretty(&lockfile).unwrap();
         let store_path =
-            self.transact_with_lockfile_contents(serde_json::json!(&lockfile).to_string(), flox)?;
+            self.transact_with_lockfile_contents(lockfile_contents, flox)?;
 
         Ok(UpgradeResult {
             packages: upgraded,

```

**Comment by stahnma** [comment]
Confirmed that it happens only upon upgrade.
