### ISSUE TITLE
package fails to install from catalog

### ISSUE THREAD

**Issue by stahnma** [flox/flox#2330]
```
[0] stahnma@floxbox01 ~ > flox install yubikey-manager
❌ ERROR: Failed to build package 'yubikey-manager': error: 1 dependencies of derivation '/nix/store/v0n15d68z6plwav8df377apr2lkw2vfr-python3.12-yubikey-manager-5.5.1.drv' failed to build
[1] stahnma@floxbox01 ~ > nix shell 'nixpkgs#yubikey-manager'
[0] stahnma@floxbox01 ~ > echo $?
```
How do I figure out if this is flox specific? 

Flox version: 1.3.3-177-g9ea2d3aa

**Comment by mkenigs** [comment]
You can set `_FLOX_CATALOG_DUMP_RESPONSE_FILE=something.json` and then check the locked_url and attr_path. And then do a `nix build $locked_url#$attr_path`

**Comment by tomberek** [comment]
1. Find the system. First i grab the resolved locked_url from a verbose flox output.
```
$ parallel -j1 --tag nix eval github:NixOS/nixpkgs/7ffd9ae656aec493492b44d0ddfb28e79a1ea25d#legacyPackages.{1}-{2}.yubikey-manager.drvPath ::: x86_64 aarch64 ::: darwin linux
x86_64 darwin	"/nix/store/gax4bkswfhyy7a3fbx7i44fzbsm2nzbn-python3.12-yubikey-manager-5.5.1.drv"
x86_64 linux	"/nix/store/4vbhkpnh1niq1hl5max0f0cnbmvda1jk-python3.12-yubikey-manager-5.5.1.drv"
aarch64 darwin	"/nix/store/v0n15d68z6plwav8df377apr2lkw2vfr-python3.12-yubikey-manager-5.5.1.drv"
aarch64 linux	"/nix/store/83ljp5wga11j0x1b1z0blwfp5mqmvcvv-python3.12-yubikey-manager-5.5.1.drv"
```
Looks like it is aarch64-darwin.

2. Try to build
```
nix build github:NixOS/nixpkgs/7ffd9ae656aec493492b44d0ddfb28e79a1ea25d#legacyPackages.aarch64-darwin.yubikey-manager -L
```
.... and it fails. I tried on all systems and the failure is the same. A missing swig dependency while building python312Packages.pyscard. So this is a proper error.

This can be confirmed in Hydra:
- https://hydra.nixos.org/job/nixpkgs/trunk/python312Packages.pyscard.aarch64-darwin
- https://hydra.nixos.org/build/276787082/nixlog/1/tail

3. Search in github Nixpkgs
This was fixed 4 days ago
- commit: https://github.com/NixOS/nixpkgs/commit/f6296625b0f89627261344894df6df7633882b1c
- PR: https://github.com/NixOS/nixpkgs/pull/353230

**Comment by stahnma** [comment]
Thanks @tomberek . I now have the steps to take to figure it out.
