### ISSUE TITLE
Allow for an empty base catalog page in published packages

### ISSUE THREAD

**Issue by billlevine** [flox/flox#2354]
**Describe the feature:**

A user package need not have any dependencies and thus could have an empty base catalog page.  This is currently disallowed, but we would like to allow for it.  The catalog API should be setup to allow for it already, but there will need to be work done to handle proper package resolution in this case.  This ticket is just to allow the CLI to identify and call the catalog API properly.

**Comment by nicklewis** [comment]
Closing this. See https://github.com/flox/catalog-server/issues/201 for details.
