### ISSUE TITLE
Publish fails if not already logged in with `flox auth login`

### ISSUE THREAD

**Issue by billlevine** [flox/flox#2366]
The token is always taken from the config, so if you are not logged in and it is triggered, then it will not pick up the new token.  We should refactor the `ensure_floxhub_token` function to return the current or new token so clients can always get it from there.

**Comment by dcarley** [comment]
I can't reproduce this as described:
```
% flox auth logout
⚠️  You are not logged in

% FLOX_FEATURES_PUBLISH=true ft publish hello
You are not logged in to FloxHub. Logging in...
> Your one-time activation code is: FSKX-ZXKS

Press enter to open hub.flox.dev in your browser...
```

[`ensure_floxhub_token`](https://github.com/flox/flox/blob/d2e1441984f4aa8ff8d88741d260bf5fb3ea13c5/cli/flox/src/commands/mod.rs#L1596-L1628) will prompt if it's running with a TTY. Was this related to https://github.com/flox/flox/pull/2324#discussion_r1837749795?

**Comment by billlevine** [comment]
Yes, related to that comment.  It will trigger the prompt yes, but the subsequent publish action will fail b/c we are still trying to get it from the config file (or the `flox` object) which was not updated in that instance.  If you try again, it should not prompt and work.  The expectation is that the single command should prompt and then proceed to work properly.  I still get that behavior on `main`.
