### ISSUE TITLE
flox-watchdog is compute, storage-intensive

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#2383]
**Describe the bug:**

After upgrading to flox 1.3.4 the `flox-watchdog` process is creating huge logs:
```
$ ps -ef | grep libexec/flox-watchdog | awk '{print $10 " " $11}'
--log-dir /Users/brantley/.flox/log
--log-dir /Users/brantley/.flox/log
--log-dir /Users/brantley/src/demo-project/.flox/log
--log-dir /Users/brantley/.flox/log
--log-dir /private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.kAl7RErO0I/.flox/log
 
$ ps -ef | grep libexec/flox-watchdog | awk '{print $11}' | sort -u | xargs du -sh
5.9G    /Users/brantley/.flox/log
1.1G    /Users/brantley/src/demo-project/.flox/log
2.1M    /private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.kAl7RErO0I/.flox/log
$ 
```

Looking at one of these logs I see it grows by 10 lines a second, and this is at least in part because `wait_for_termination()` in `cli/flox-watchdog/src/process.rs` fires every `WATCHER_SLEEP_INTERVAL` which is set to 100ms.

Looking at the accumulated runtime for these processes with `htop` I also see runtimes in excess of 2 hours for processes started less than a week ago. 

**Steps to reproduce:**
1. `flox activate` any environment
2. run `ps -ef | grep flox-watchdog` to inspect the `--log-dir` parameter for that invocation
3. run `tail -f` on the file in that directory and observe it grow by 10 lines per second 

Result:

As described above.

Expected:

Would not expect anything written to logs for long-lived processes except perhaps when signalled to convey status information in the logs.

**Screenshots/terminal output (if relevant):**

An example 3 adjacent lines in a log:
```
2024-11-17T19:37:41.574578Z DEBUG watchdog{socket="/Users/brantley/.cache/flox/run/flox.36d62f4a.sock" log_dir="/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.kAl7RErO0I/.flox/log"}: flox_watchdog::process: still watching PIDs {AttachedPid { pid: 90788, expiration: None }}
2024-11-17T19:37:41.681000Z DEBUG watchdog{socket="/Users/brantley/.cache/flox/run/flox.36d62f4a.sock" log_dir="/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.kAl7RErO0I/.flox/log"}: flox_watchdog::process: still watching PIDs {AttachedPid { pid: 90788, expiration: None }}
2024-11-17T19:37:41.787276Z DEBUG watchdog{socket="/Users/brantley/.cache/flox/run/flox.36d62f4a.sock" log_dir="/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.kAl7RErO0I/.flox/log"}: flox_watchdog::process: still watching PIDs {AttachedPid { pid: 90788, expiration: None }}
```

**Flox Version (run `flox --version` if possible):**
```
% flox --version
1.3.4
```

**`uname -a` output:**
```
% uname -a
Darwin Michaels-MBP.localdomain 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:50:00 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6031 arm64 arm Darwin
```

**Comment by eikenb** [comment]
I'm also seeing this. Just noticed this in ~/.flox/log..

```sh
[~]ls -lah
total 61G
drwxr-xr-x 2 jae jae 4.0K Nov 17 13:40 ./
drwxr-xr-x 6 jae jae 4.0K Nov 17 13:11 ../
-rw-r--r-- 1 jae jae 135M Nov 17 16:53 watchdog.23fafa22.log
-rw-r--r-- 1 jae jae  61G Nov 17 16:53 watchdog.6c180917.log
```
And both files are still growing at a regular rate. My other .flox environments had similar, large log files. They seem mostly filled with lines like..

```
2024-11-18T00:57:21.625777Z  WARN watchdog{socket="/run/user/1000/flox.9d74be68.sock" log_dir="/home/jae/.flox/log"}: flox_watchdog::process: failed to parse /proc/<pid>/stat, treating as not running err=No such file or directory (os error 2) pid=506799
```

I killed the rogue processes and log files. What ran these? How can I disable them?

**Comment by limeytexan** [comment]
@eikenb thanks for the feedback. Apologies I didn't reference the [discourse posting](https://discourse.flox.dev/t/large-log-files-generated-by-watchdog/985/2) from which this was originally reported, in which I suggested the following workaround while we work to release a hotfix:
```
pkill -CONT flox-watchdog
sleep 1
pkill -STOP flox-watchdog
```

It's brute force and low tech, but doing the above will wake up any watchdogs that need to clean up after any concluded activations before again stopping the still active ones until the next time.

**Comment by mkenigs** [comment]
- We can fix logs immediately
- For compute:
  - We should check if we're cleaning up PIDs
  - Not quite sure if we want to change the polling interval

**Comment by mkenigs** [comment]
We've fixed the logging in https://github.com/flox/flox/pull/2392 and will use https://github.com/flox/flox/issues/2398 to track improvements for compute
