### ISSUE TITLE
Allow setting alternative Store in pkgdb commands

### ISSUE THREAD

**Issue by ysndr** [flox/flox#2411]
**Describe the feature:**

Parse a `_FLOX_NIX_STORE_URL` and open a store at that location (instead of openeing the `auto` store, if provided.

**Describe a use case of this feature:**

Use a passthrough nix daemon in nix isolated tests.

**Acceptance criteria:**
1. `_FLOX_NIX_STORE_URL=<store url> pkgdb realise` should use the store at `<store url>`
2. alternatively parse a complete nix config provided in a `_FLOX_NIX_CONFIG` variable
3. do the least complex given the imminent removal of pkgdb

**Comment by zmitchell** [comment]
Do we also need to set the store in Flox or just pkgdb?

https://github.com/flox/flox/blob/main/cli/flox-rust-sdk/src/providers/buildenv.rs#L206

**Comment by ysndr** [comment]
yes i think we do, any nix invocation basically, via pkgdb or nix proper.

However, i think this issue will be subsumed by https://github.com/flox/flox/issues/2423
