### ISSUE TITLE
[rexpect] Add a "flox-test-utils" crate

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2436]
This crate should be importable by multiple `flox` crates, not just `flox` or `flox-rust-sdk`, so it shouldn't use types from either of those crates.

This initial ticket is part of a sequence adding support for `rexpect` tests, so the scope for this one is:
- Make the crate
- Include the `IsolatedHome` struct

**Comment by mkenigs** [comment]
This might require touching our Nix builds
