### ISSUE TITLE
[rexpect] Move process status checking to flox-core

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2437]
The code for checking process statuses doesn't depend on anything else in `flox-watchdog` and is cross-platform. We also check process statuses in multiple places throughout the codebase, so it makes sense to settle on one way to do it. 

This ticket adds support in `flox-core` for checking process statuses, but doesn't migrate any other code to using it so that the migration and any related regressions can be monitored separately.

This ticket is part of a sequence adding support for rexpect tests, so the scope for this one is:
- Copy the `ProcessStatus` enum and process status checking functions from `flox-watchdog`
- Add those to `flox-core` as bare functions under a `proc_status` module
- Add a conditional compilation feature (`proc_status`) to enable this module when desired so that it's disabled by default.

**Comment by mkenigs** [comment]
- We should use this throughout the codebase for process status checking
- We can add the feature flag if it's easy

**Comment by mkenigs** [comment]
https://github.com/flox/flox/pull/2501
