### ISSUE TITLE
Fall back to best available editor if one isn't set.

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#245]
## Observations
- `flox edit` fails if called interactively without `EDITOR` set

## Problem
- The user likely has _an_ editor installed somewhere on their system
- It would be a better user experience if we could use one of the installed editors even if the user hasn't set `EDITOR`

## Approaches
- Check for the existence of a one of several common editors and fall back to one of those
- For prior art see: https://github.com/flox/flox/blob/4da62348a2d499ee62ab3476f2a78fed7e5ca2e7/flox-bash/lib/utils.sh#L179-L180

## (optional) Acceptance Criteria
- [ ] `export EDITOR=emacs`

**Comment by aakropotkin** [comment]
```shell
_flox() {
  : "${EDITOR:=nix run 'nixpkgs#emacs' --}";
  export EDITOR;
  command exec flox "$@";
}
alias flox=_flox;
```

**Comment by ghudgins** [comment]
+1 from @rossturk's initial playthrough

**Comment by limeytexan** [comment]
> ```shell
>   : "${EDITOR:=nix run 'nixpkgs#emacs' --}";
> ```

Kicking off hidden Nix instantiations in the routine operation of flox is a bad idea IMO.

**Comment by aakropotkin** [comment]
> > ```shell
> >   : "${EDITOR:=nix run 'nixpkgs#emacs' --}";
> > ```
> 
> Kicking off hidden Nix instantiations in the routine operation of flox is a bad idea IMO.

This was more of a lighthearted joke about _emacs being the best text editor_ than a serious technical recommendation.

Among software developers there's a long running joke about _which text editor is the best_, especially between `emacs` and `vim`. This was me riffing on that.

**Comment by ghudgins** [comment]
verified 🎉

**Comment by ghudgins** [comment]
this issue persists on debian `Version: 0.3.7-r830`

```
flox [default] [ec2-user@ip-172-31-84-51 ~]$ flox edit
ERROR: no editor found; neither EDITOR nor VISUAL are set
    
    Caused by:
        environment variable not found
```

**Comment by stahnma** [comment]
Moving to Backlog due to last comment.

**Comment by ysndr** [comment]
@ghudgins that must be an old(er) version without the changes from ~10 days ago.
That error message was replaced from flox 0.3.7-r780.

we merged https://github.com/flox/flox/pull/501 on Dec 1 as https://github.com/flox/flox/commit/2100c831a731144277169dc583e279dc2e7646a4

<details>
<summary>version and output running that commit:</summary>

```
$ unset EDITOR
$ unset VISUAL

$ nix run 'git+https://github.com/flox/flox?rev=2100c831a731144277169dc583e279dc2e7646a4#flox' -- --version

Version: 0.3.7-r780

$ nix run 'git+https://github.com/flox/flox?rev=2100c831a731144277169dc583e279dc2e7646a4#flox' -- edit -vv
[...]
Using editor "vim" from "/usr/bin"
[...]

<vim opens>
```

</details>


<details>
<summary>version and output of the parent commit:</summary>

```
$ unset EDITOR
$ unset VISUAL

$ nix run 'git+https://github.com/flox/flox?rev=5f9d59ed9cc40f5e2ab2c5f84bf42663950a91f3#flox' -- --version

Version: 0.3.7-r779

$ nix run 'git+https://github.com/flox/flox?rev=5f9d59ed9cc40f5e2ab2c5f84bf42663950a91f3#flox' -- edit -vv
[...]
ERROR: no editor found; neither EDITOR nor VISUAL are set
    
    Caused by:
        environment variable not found
```

</details>

**Comment by ghudgins** [comment]
thanks. yes, my apologies
