### ISSUE TITLE
Most recently activated environment not most recent in PATH

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2456]
**Describe the bug:**

A default environment activated in .zshrc is currently in PATH before a more recently activated environment

**Steps to reproduce:**
1. Put `eval "$(flox activate -d ~ --mode run)"` in .zshrc
2. `flox init -d /tmp && flox activate -d /tmp`
3. `echo $PATH`

Result:
`/Users/matthew/.flox/run/aarch64-darwin.default.run/bin:/Users/matthew/.flox/run/aarch64-darwin.default.run/sbin:/private/tmp/.flox/run/aarch64-darwin.tmp.dev/bin:/private/tmp/.flox/run/aarch64-darwin.tmp.dev/sbin...`

Expected:
`tmp` should come before `default` in PATH

**Flox Version (run `flox --version` if possible):**
`1.3.4`

**`uname -a` output:**
`Darwin Matthews-MacBook-Pro-2.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64`

**Comment by zmitchell** [comment]
Addressed by #2476
