### ISSUE TITLE
Recommend `.profile` for default env activation on macOS for Bash

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2467]
We currently recommend sourcing the default environment in `.bashrc`, but on macOS, most Terminal emulators start a login shell (I just checked and this is not the case on Debian). For login shells, Bash sources `.profile` but not `.bashrc`, so we should recommend `.profile` on macOS.

We also need to update the docs accordingly.

**Comment by mkenigs** [comment]
We could consider always recommending `.profile` instead of `.bashrc`, not just on macOS. `flox activate` modifies PS1 so I'm not sure if that's technically correct. Although counterpoint would be something like ssh which doesn't source `.bashrc`

**Comment by limeytexan** [comment]
Actually we need to recommend both. The litmus test is that both a login shell and a non login shell should both have access to the default environment. I usually test the latter with `ssh localhost command` where the command can only come from the default env.

**Comment by mkenigs** [comment]
We'll recommend both on both Linux and macOS
