### ISSUE TITLE
publish: fix inconsistent use of outputs

### ISSUE THREAD

**Issue by billlevine** [flox/flox#2479]
Currently we are taking the realpath of the build output as both the `drv_path` and `store_path` for the single assumed output.  And we are copying to the cache the `drv_path`.  We need to be copying the outputs during the publish phase, and fix the population of the `drv_path` field in the metadata.

On the consumption side, ensure we are copying the outputs, and not trying to copy via the `drv_path` field.

**Comment by billlevine** [comment]
Discussing approach to take w.r.t. metadata from the manifest vs built derivation...

**Comment by limeytexan** [comment]
> Discussing approach to take w.r.t. metadata from the manifest vs built derivation...

Where is that discussion? The `nix build` invocation returns the JSON blob detailing the drv path and all outputs. Also note that we will soon be adding the "log" output to that list of outputs to be uploaded, and in general we need to add support for multi-output builds in future. So .. I think the only viable option is parsing that JSON blob returned by `nix build`.
