### ISSUE TITLE
Broken in-place activation in zshenv

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2503]
Initially reported by @brendaneamon 

Symptoms:
- Put the `eval "$(flox activate -d ~ -m run)"` line in `.zshenv`, ensuring that it's the last line.
- Ensure that the line is no longer in `.zshrc`
- Start a new shell
- See a line that says `command not found: flox`
- The commands in the default environment are not in `PATH`
- `flox` is somehow still in `PATH`

I was unable to reproduce on my system, but I have nothing else in my `.zshrc` or `.zshenv`, and @brendaneamon is using oh-my-zsh.

**Comment by mkenigs** [comment]
Closed by https://github.com/flox/flox/pull/2505
