### ISSUE TITLE
--verbose option does not do anything for flox install

### ISSUE THREAD

**Issue by louy2** [flox/flox#2555]
**Describe the bug:**
`flox install --verbose` shows the same output as `flox install`

**Steps to reproduce:**
1. Run `flox install hello`, observe output 1
2. Run `flox uninstall hello`
3. Run `flox install --verbose hello`, observe output 3

Result: output 1 and 3 looks exactly the same

Expected: output 3 is much more detailed than output 1

**Screenshots/terminal output (if relevant):** 
`⠉ Installing packages to environment 'default'...`

**Flox Version (run `flox --version` if possible):** `1.3.8-gf572178`

**`uname -a` output:**
```
Darwin macbook-pro-2.local 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 18:40:14 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8103 arm64
```

I discovered `flox` today, and I am evaluating it as an alternative to `brew` and `nix-darwin`.

So far `flox install` is way slower than both `brew` and `nix-darwin`.

It is not helping that `flox install` gives no information at all.

In comparison, `brew install` shows me a comprehensive log: auto-updating `brew`, downloading manifests, downloading artifacts, downloading attestation, then success.

`nix-darwin` gives a rolling indicator: downloading from cache, evaluating derivation, then success.

I am in a situation where I need to sometimes Ctrl-C, tweak my network a bit, and retry. Both `brew` and `nix-darwin` shows me enough so I know whether it is worthwhile to wait for completion or Ctrl-C. `flox install` does not.

**Comment by louy2** [comment]
To whoever is similarly confused:

`flox -vv install` will show `DEBUG` level log, and `flox -vvv` will show `TRACE` level log.

I guess `flox -v install` is supposed to show `INFO` level log, but I do not see any, which explains the lack of log.

**Comment by louy2** [comment]
Unfortunately even with `flox -vvv install`, there are no log related to the internals of the installation spinner:

```
⠉ Installing packages to environment 'default'...
```

**Comment by ysndr** [comment]
Just be sure, you are using the current stable version of flox correct?

The next release of flox will include https://github.com/flox/flox/pull/2515 which should make the output of flox more granular.

Multiple -v should increasingly add information to the logs.
The rules will be adjusted a little bit as well in the wake of the above pr, but `-vv` should get you debug details for internals.

**Comment by louy2** [comment]
```
flox --version
1.3.8-gf572178
```

Thank you for working to make the output more granular. With that PR already merged, I don't have any more questions about this issue.
