### ISSUE TITLE
homebrew cask

### ISSUE THREAD

**Issue by tnxz** [flox/flox#274]
**Describe the feature:**
would be great to have a homebrew cask to install

**Describe a use case of this feature:**
can `brew install --cask flox`

**Acceptance criteria:**
1. as many macOS users use homebrew (that I know of)

**Comment by robinbrantley** [comment]
Hi @tnxz - thanks for your interest in flox! flox has its own installer and can sit along side homebrew. There are overlapping features between them but flox goes a bit further - for example we support distinct environments that can be activated independently and we track environment generations. I have added your suggestion to our internal list for prioritisation. thanks!

**Comment by stahnma** [comment]
I've put together an initial formula, but we still have several issues with the uninstaller which need to be resolved before submission to homebrew as our own cask. 


```
cask "flox" do
  arch arm: "aarch64", intel: "x86_64"

  version "1.0.1"

  sha256 arm: "a7c4f75706fa7bbd9631478ac60d5c631cce475b88e49ae7b93fea04be9e836d",
       intel: "4edf58afc1556348b0ac05868d1488434d02b1e4e4dfd9e122be6e440aebffc3"

  url "https://downloads.flox.dev/by-env/stable/osx/flox-#{version}.#{arch}-darwin.pkg"
  name "flox"
  desc "Flox manages environments across the software lifecycle"
  homepage "https://flox.dev/"

  livecheck do
    url "https://downloads.flox.dev/by-env/stable/osx/flox-#{version}.#{arch}-darwin.pkg"
    strategy :header_match
  end

  auto_updates true
  depends_on macos: ">= :catalina"

  pkg "flox-#{version}.#{arch}-darwin.pkg"

  uninstall launchctl: [
              "org.nixos.darwin-store",
              "org.nixos.nix-daemon",
            ],
            quit:      [
              "org.nixos.darwin-store",
              "org.nixos.nix-daemon",
            ],
            delete: [
              "/opt/homebrew/Caskroom/flox",
              "~/.cache/flox",
            ],
            script:    {
              executable: "/usr/local/share/flox/scripts/uninstall",
              sudo:       true,
            },
            pkgutil:   "com.floxdev.flox"

  zap trash: [
    "/opt/homebrew/Caskroom/flox",
    "~/.cache/flox",
    "~/.config/flox",
  ]
end
```

**Comment by stahnma** [comment]
https://github.com/Homebrew/homebrew-cask/pull/170971 is up.

**Comment by stahnma** [comment]
This is now readily available.
