### ISSUE TITLE
Break down into tasks: Implement GitHub "device flow" for login in Rust

### ISSUE THREAD

**Issue by nicklewis** [flox/flox#294]
Currently this behavior is implemented by calling out to a _heavily_ patched copy of `gh`. In order to migrate away from GitHub OAuth, we need to implement the client side of this protocol directly in the Rust code.

Follow the example set by [cli/oauth](https://github.com/cli/oauth) to implement the [device flow](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow).

This may require changes to where we store the token since `gh` currently puts it in the keyring, and supporting that may be beyond the scope of this issue.

**Comment by samrose** [comment]
This issue needs to be broken down into discrete tasks

I am working on doing that now before diving into the implementation

**Comment by samrose** [comment]
@ghudgins mentioned that @jennymahmoudi is still working on the design of this, so whatever I do in the short term wrt to user experience could be subject to change

**Comment by jennymahmoudi** [comment]
This is where I'm capturing the signup workflows: https://www.figma.com/file/i7YrJb7YuqMO8Au4jPNLPb/Sharing-workflow?type=whiteboard&node-id=177%3A354&t=yHsrxitHbEF3xyWE-1

I will set up some time to work on this with you.

**Comment by samrose** [comment]
@jennymahmoudi I am going to respect your design, so I will plan on refactoring whatever I do now so that it will adhere to your design, but still be able to move the work forward

**Comment by robinbrantley** [comment]
@jennymahmoudi - May I please have access to this figma link so I can be sure to help coordinate?
