### ISSUE TITLE
Failed to install packages because of an conflicting priority

### ISSUE THREAD

**Issue by OhMyMndy** [flox/flox#3]
Hi there!

Awesome project, I am really enjoying it so far!

I ran into an error while installing `tree-sitter-grammars.tree-sitter-markdown` and `tree-sitter-grammars.tree-sitter-bash` with `flox install tree-sitter-grammars.tree-sitter-markdown tree-sitter-grammars.tree-sitter-bash` in the Docker container (`docker run --pull always --rm -it ghcr.io/flox/flox`).

The following error occurs:

```
error: builder for '/nix/store/j11rij6k1ay8nmkrin27svlzaqdzd1dc-profile.drv' failed with exit code 1;
       last 1 log lines:
       > error: files '/nix/store/6ph2v8vlwqya00hjkdv33hr9mih7p7yn-tree-sitter-bash-grammar-0.20.6/parser' and '/nix/store/67placg5imrr73h11dinpa0qij0gv212-tree-sitter-markdown-grammar-0.20.6/parser' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' or type 'nix profile install --help' if using 'nix profile' to find out howto change the priority of one of the conflicting packages (0 being the highest priority)
       For full logs, run 'nix log /nix/store/j11rij6k1ay8nmkrin27svlzaqdzd1dc-profile.drv'.
error: 1 dependencies of derivation '/nix/store/4zq5kzyjh8dcq3l7c07llzbarlvg03p8-profile.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6is738b12kzi6a53pw61cnwkpwrazgh2-wrapper.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bcjqj6zk8sayfgmpc5zdq79fhq4sc4ri-floxShell.drv' failed to build

ERROR: failed to install packages: flake:nixpkgs-flox#evalCatalog.x86_64-linux.stable.tree-sitter-grammars.tree-sitter-markdown flake:nixpkgs-flox#evalCatalog.x86_64-linux.stable.tree-sitter-grammars.tree-sitter-bash
```

**Comment by mkenigs** [comment]
Hi! Thanks for flagging! We have a fix in the works that hasn't been released yet. As a temporary workaround, does it work to install into two separate environments?
```
flox install tree-sitter-grammars.tree-sitter-markdown
flox install -e tree-sitter-bash tree-sitter-grammars.tree-sitter-bash
flox activate -e default -e tree-sitter-bash
```

**Comment by mkenigs** [comment]
A newer container should be released with a fix that allows avoiding the conflict. To explain the error, both packages are providing a file `parser`, and there's no way to determine which of those should take precedence in the environment. You can set `tree-sitter-bash` to have a higher priority by:
```
flox install tree-sitter-grammars.tree-sitter-markdown
flox edit
# add the line: packages.nixpkgs-flox.tree-sitter-grammars.tree-sitter-bash = { meta.priority = 4; }; # the default priority is 5
```

If the `parser` file isn't important or shouldn't be conflicting, you could open an issue in nixos/nixpkgs.

**Comment by robinbrantley** [comment]
Hi @OhMyMndy - please give the new release a try and if you have any issues, please let us know. :-)
