### ISSUE TITLE
Make git methods sync

### ISSUE THREAD

**Issue by ysndr** [flox/flox#304]
Following the decision to consume git in a synchronous way what remains is consitently provide sync methods by the git provider.

- [ ] replace async tokio::command with sync process::command
- [ ] remove `async` color from git methods
- [ ] remove `await` from consumers
- [ ] remove `async` color from consumers if possible (i.e. no other async methods used

**Comment by stahnma** [comment]
@ysndr should this be in review? I am confused.

**Comment by ysndr** [comment]
No this shouldn't, if it land in review that's an accident
