### ISSUE TITLE
Split git executable wrapper from git repo abstraction

### ISSUE THREAD

**Issue by ysndr** [flox/flox#305]
Currently our git instance does not allow for any customization of the git command call, e.g. the raw `Command` struct.
We would like configurability in order to call git with or without access to user/system configuration, set user/email config values and authentication providers.

The config can't live on the current `GitCommandProvider` struct as the latter is only created by _calling_ git. This initial git command is not configurable.

Instead, to keep the API as  close to the current as possible, its proposed to use a `CommandAbstraction` that iwill be wrapped by the existing `GitCmmandProvider`

**Comment by stahnma** [comment]
@ysndr should this be in review? I don't see a PR.

**Comment by stahnma** [comment]
@ysndr should this be in review? I don't see a PR.

**Comment by ysndr** [comment]
We need some changes in this direction for authentication of floxmeta. It's not meant as a complete redoing of the git wrapper just giving us a bit more control. I pulled this to prepare for integrating sams work and facilitate push/pull as we have ongoing work on install switching to manifest already.

**Comment by mkenigs** [comment]
Would it be faster to just pass config flags manually in the few places we need to do it for now or split out `CommandAbstraction`?
