### ISSUE TITLE
Consolidate environment errors

### ISSUE THREAD

**Issue by ysndr** [flox/flox#316]
Our `EnvironmentError2` enum has grown to 32 error variants (not including the new nested ones for managed envs).
Many of the variants have just been piling up due to the sped up development of environments and are now either unused, ambiguous or with overlapping meaning.

While not mission critical, this issue is to recognize the need to address these code smells.

**Comment by ghudgins** [comment]
closing in lieu of https://github.com/flox/flox/issues/375
