### ISSUE TITLE
`flox edit` manipulates `manifest.toml`

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#338]
`flox edit` previously relied on `nix-editor` to programmatically edit the manifest as a non-interactive `EDITOR`. We need a similar functionality based on TOML. We can build a similar script around [toml-cli](https://github.com/gnprice/toml-cli).

Acceptance criteria:
- We have a non-interactive `EDITOR` that can edit TOML files.
- All of the tests in `environment-edit.bats` that were marked as `FIXME: broken migrating to manifest.toml` now pass.

**Comment by ghudgins** [comment]
can we knock out https://github.com/flox/flox/issues/245 when we do this?
