### ISSUE TITLE
flox activate with linkFarm

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#346]
EDIT:
This is a parent ticket that will be closed when the following are closed:

- [x] https://github.com/flox/flox/issues/405
- [x] https://github.com/flox/flox/issues/406

Build initial activate script inspired by existing activate script using `linkFarm` instead of `buildEnv` (Take what we have today). 

* Port logic from https://github.com/flox/phlox/blob/main/src/tasks/env/activate.sh for a simple activation.
* By default include profile and profile.d/0100_common-paths.sh scripts
   * Sets common environment variables such as PATH, PKG_CONFIG_PATH, etc ( see https://github.com/flox/etc-profiles/blob/main/profile and https://github.com/flox/etc-profiles/blob/main/profile.d/0100_common-paths.sh )
* Prompt logic in activate - pull parts of existing flox-bash routines. [Existing bash script](https://github.com/flox/flox/blob/668a80a40ba19d50f8ca304ff351f4b27a886e21/flox-bash/lib/commands/activate.sh). Rust is currently setting `FLOX_PROMPT_ENVIRONMENTS` but the rest of the logic needs to be in a shell script
* The only input is the lockfile.

TODO:
- [ ] Change lockfile format to include locked URLs in addition to or instead of the exploded flake references.

# Acceptance Criteria

**When** I install tool chain and its package manager (i.e. `flox install pip, python3 && flox activate && pip install requests && python3`)
**And** I use the tool chain
**Then** language can find packages installed via toolchain-specific package manager

**Comment by ghudgins** [comment]
can we put in the scope of this task cleaning up `flox activate --help` - there seems to be an odd `ARGUMENTS` word...is this right? 

```
Activate environment

Usage: flox activate [-s=SYSTEM] [-d=<path> | -r=<owner/name>] [-- COMMAND [ARGUMENTS]...]

Activate environment
  Modes:
  * in current shell: eval "$(flox activate)"
  * in subshell: flox activate
  * for command: flox activate -- <command> <args>
    -s, --system=SYSTEM
    -d, --dir=<path>     Path containing a .flox/ directory
    -r, --remote=<owner/name>  A remote environment on floxhub
    ARGUMENTS

Available options:
    -h, --help           Prints help information
```

**Comment by zmitchell** [comment]
Building the environment is done. I can either pick up the remaining work tomorrow or someone else can pick it up if they're looking for things to do.

**Comment by mkenigs** [comment]
@ghudgins can we revisit the AC for this ticket? Upstream nixpkgs explicitly disables the behavior you're asking for in pip (https://github.com/NixOS/nixpkgs/blob/9975ea9c3797c2aaa93f3abe7907cf0a95151f7b/pkgs/development/interpreters/python/cpython/default.nix#L526)

```
flox init && flox install python && flox install pip
✨ created environment debug (aarch64-darwin)

Enter the environment with "flox activate"
Search and install packages with "flox search {packagename}" and "flox install {packagename}"

✅ 'python' installed to environment
✅ 'pip' installed to environment
~/debug  > SHELL=bash flox activate
Building environment...
flox [debug] Matthews-MacBook-Pro-2:debug matthew$ pip install requests
error: externally-managed-environment

× This environment is externally managed
╰─> This command has been disabled as it tries to modify the immutable
    `/nix/store` filesystem.

    To use Python with Nix and nixpkgs, have a look at the online documentation:
    <https://nixos.org/manual/nixpkgs/stable/#python>.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python3.10 -m pip install --upgrade pip
```

**Comment by aakropotkin** [comment]
There's a fix for that we have handled in the python3 etc-profiles script IIRC

**Comment by mkenigs** [comment]
Hmm doesn't look like it:
```
flox [default] Matthews-MacBook-Pro-2:~ matthew$ source ~/etc-profiles/profile.d/0500_python3.sh
flox [default] Matthews-MacBook-Pro-2:~ matthew$ pip install requests
error: externally-managed-environment

× This environment is externally managed
╰─> This command has been disabled as it tries to modify the immutable
    `/nix/store` filesystem.

    To use Python with Nix and nixpkgs, have a look at the online documentation:
    <https://nixos.org/manual/nixpkgs/stable/#python>.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python3.10 -m pip install --upgrade pip
```

**Comment by aakropotkin** [comment]
Take to put on the ol' _problem solving hat_ tomorrow.

We need Python 🖤

**Comment by aakropotkin** [comment]
@mkenigs this follow up ticket has been created : https://github.com/flox/flox/issues/405

**Comment by limeytexan** [comment]
Not sure if I'm missing something obvious here but in all my previous demos involving `etc-profiles` I always started a `venv` in order to use `pip`. I never expected to be able to `pip install` without first launching the `venv`. Relevant?

```
flox [flox/prerelease default] Michaels-MBP% flox init
✨ created environment tmp.bZx5p2PABD (aarch64-darwin)

Enter the environment with "flox activate"
Search and install packages with "flox search {packagename}" and "flox install {packagename}"

flox [flox/prerelease default] Michaels-MBP% flox install python
✅ 'python' installed to environment tmp.bZx5p2PABD at ./.flox
flox [flox/prerelease default] Michaels-MBP% flox install pip
✅ 'pip' installed to environment tmp.bZx5p2PABD at ./.flox
flox [flox/prerelease default] Michaels-MBP% SHELL=bash flox activate
Building environment...
flox [flox/prerelease default tmp.bZx5p2PABD] %m%# python -m venv floxdemo
flox [flox/prerelease default tmp.bZx5p2PABD] %m%# . floxdemo/bin/activate
(floxdemo) flox [flox/prerelease default tmp.bZx5p2PABD] %m%# python -c 'import requests'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
(floxdemo) flox [flox/prerelease default tmp.bZx5p2PABD] %m%# pip install requests
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-macosx_11_0_arm64.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.4/120.4 kB 7.7 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.7-py3-none-any.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 10.0 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 11.7 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2023.7.22 charset-normalizer-3.3.2 idna-3.4 requests-2.31.0 urllib3-2.0.7

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
(floxdemo) flox [flox/prerelease default tmp.bZx5p2PABD] %m%# python -c 'import requests'
(floxdemo) flox [flox/prerelease default tmp.bZx5p2PABD] %m%# 
```

**Comment by ghudgins** [comment]
it could be a false AC...but whenever I use python I never use a venv. that could be because i'm a cosplay developer (i.e. I dabble but I don't python for a living). however if we have something that provides isolation then why do I have to use python's way of providing isolation? feels like this is the nixpkgs maintainers trying to keep nixpkgs "pure" (thou shall not use nix in conjunction with things that nix can do)

**Comment by zmitchell** [comment]
This should absolutely be an acceptance criteria. People are going to use flox thinking that it’s a replacement for virtual environments.

**Comment by mkenigs** [comment]
Closing per discussion in standup. Followup tickets:
- [ ] https://github.com/flox/flox/issues/396
- [ ] https://github.com/flox/flox/issues/404
- [ ] https://github.com/flox/flox/issues/405
- [ ] https://github.com/flox/flox/issues/406

**Comment by ghudgins** [comment]
@mkenigs this doesn't work yet for me. still getting the shell issue on mac

**Comment by mkenigs** [comment]
An issue for that is linked in the comment I closed this with. I don't really care if we keep this open as a parent ticket but @stahnma asked to close

**Comment by mkenigs** [comment]
Okay I'm moving to backlog then

**Comment by ghudgins** [comment]
resolved as of r757
