### ISSUE TITLE
flox activate command dispatcher

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#347]
Rust command dispatcher for flox activate

* Set FLOX_ENV
* Call profile script
* prompt (edit: It's not possible to set prompt in Rust so instead just set `FLOX_PROMPT_ENVIRONMENTS` and we can set PS1 as part of #346)

Related to #346 

# Acceptance Criteria

See AC from #346 
See active flox environment in prompt

**Comment by mkenigs** [comment]
Need to revisit whether this is done or not after https://github.com/flox/flox/issues/346 is closed
