### ISSUE TITLE
flox detects changes that require (re) activation

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#348]
# Acceptance Criteria

_detect changes for shell hooks or environment variables_
**Given** I am activated in an environment
**When** I `flox edit` the shell hook for my environment
**Or** I `flox edit` the environment variables
**Then** I see a warning: 
```
Your manifest has changes that cannot be automatically applied to your current environment. 

Please `exit` the environment and run `flox activate` to see these changes.
```

**Comment by ghudgins** [comment]
depends on #347

**Comment by mkenigs** [comment]
Are we going to do the shell hooks part of https://github.com/flox/flox/issues/436? If so, we should probably set environment variables when they are modified.

**Comment by ghudgins** [comment]
LGTM

<img width="660" alt="image" src="https://github.com/flox/flox/assets/5465514/296112ec-66df-4572-b9cc-31ca32b34e1b">
