### ISSUE TITLE
Write data package returned from successful deveice flow login to dynamic conf/update dynamic conf

### ISSUE THREAD

**Issue by samrose** [flox/flox#354]
## Acceptance criteria

- Upon success of `flox auth2 login`, the cli will have polled the device flow endpoint, and received a response with the token, expiry, and refresh token. The value of the token need to be dynamically written or updated to the flox conf
- implement a logout command that removes the token from the configuration.

**Comment by ysndr** [comment]
closed in [flox/flox#358](https://github.com/flox/flox/issues/358)
