### ISSUE TITLE
[oauth2]: check token validity

### ISSUE THREAD

**Issue by ysndr** [flox/flox#357]
- [ ] add a method that returns the current authentication state
- [ ] expose as `flox auth status`

-- out of scope --

- [ ] `flox auth login` could validate, exit early?
- [ ] refresh token proactively https://github.com/flox/product/issues/557

Note: both token actions would be more efficient using the `oauth2` crate #352

**Comment by ysndr** [comment]
@samrose

**Comment by mkenigs** [comment]
Dup of https://github.com/flox/flox/issues/837
