### ISSUE TITLE
flox installs/uninstall/edit/search to last activated environment automatically

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#359]
# Acceptance Criteria

_Installs to the last active shell when there is no .flox_
**Given** I have an environment in `~/projectA`
**And** i have an environment in `~`
**And** I have activated, this this order my home environment `~` and then `~projectA` (`projectA` is last activated)
**And** I have `cd` to a different directory that doesn't contain a .flox
**When** I `flox install curl` 
**Then** I see flox has installed `curl` to `projectA` _<-- no .flox, takes last active shell_

_Ask the user if install has more than one possible destination_
**Given** I have an environment in `~/projectA`
**And** i have an environment in `~`
**And** I have activated the home environment in `~`
**And** I have `cd` to the `~/projectA` directory
**When** I `flox install curl` 
**Then** I see a choice of where to install the package between the active and local environment _<-- needs a design pass_
**And When** I pick projectA's enviornment
**Then** I see flox has installed `curl` to `projectA` 

_install/uninstall/edit/search prompts for git repo boundary_
**Given** I have an environment in `~/projectA`
**And** I have an env in `~/projectA/subdir`
**And** I am in `~/projectA/subdir`
**When** I `flox install curl`
**Then** I see prompt

```Do you want to install to the flox environment detected in a git repo or the current active flox environment?
  upper level directory's flox environment [env-name]
  current active flox environment [env-name] 
```

Depends on #347
CC @jennymahmoudi to make sure this interaction sounds good.

**Comment by mkenigs** [comment]
As far as implementation work goes this does not depend on #346. It has some intersection with #347 but can probably still be done in parallel

**Comment by mkenigs** [comment]
@ghudgins @jennymahmoudi I'm starting to look at this even though it says it needs a design pass. Let me know if there are any changes from what we have written

**Comment by mkenigs** [comment]
It's also unclear how searching upwards should work. Currently search/show look upwards from the current directory for a `.flox`, but `activate/install/etc` do not. If there's a `.flox` in the directory above current directory and I have a separate activated environment, which one does `install` use? Does activate use the directory above cwd?

See also https://github.com/flox/flox/issues/444

**Comment by mkenigs** [comment]
I've done a good chunk of this in #498, but I think we could use some more design at this point. One other thing related thing we haven't decided is i2.a or i2.b in the unify spec.

@ghudgins @jennymahmoudi let me know how to proceed - I can just make some decisions and implement what I think is best, or I can wait for more clarification

**Comment by ghudgins** [comment]
lets do `i2.a` for now. we can evaluate the default environment case holistically post GA

**Comment by jennymahmoudi** [comment]
1. `i2.a` says:
> `flox install` without specifying a name should install to an environment found in the user's **current** directory. if no environment is found, install should return an error

does this mean we're not doing the first item in this ticket? 
> Installs to the last active shell when there is no .flox

2. For the choice of where to install when you've activated an environment, then moved to a directory where there is a different flox environment that's not active (choose local vs active shell), let's say:
```
$ flox install curl
Do you want to install to the current directory's flox environment or the current active flox environment? Use arrows to select:
  current directory's flox environment [env-name]
  current active flox environment [env-name] 
  
```

**Comment by mkenigs** [comment]
Search currently looks for `.flox` in parent directories, e.g. if current dir is /path/in/project and there's a /path/.flox, that environment will be used. I'm thinking we should make that behavior consistent, so if I `flox install` while in `/path/in/project`, `/path/.flox` is used, and if a second directory is activated, I get prompted with:
```
Do you want to install to the ancestor directory's flox environment or the current active flox environment?
  ancestor directory's flox environment [env-name]
  current active flox environment [env-name] 
```

Or should we only detect upwards for search? Or should we drop the detecting upwards for search?

**Comment by jennymahmoudi** [comment]
Given we decided on this:
> if no environment is found, install should return an error

I would say either we leave it inconsistent or drop detecting upwards for search.

I don't understand why search needs to look for a flox directory, so I don't have the context to make the decision on how that should work (detecting upwards or not). Can you explain this? Tagging @ghudgins in case he can help without additional explanation.

**Comment by mkenigs** [comment]
If search finds an environment, it uses the inputs defined in the environment to look for packages. This can be helpful, for example, because an environment could have an older version of nixpkgs, so if search doesn't detect that, it might return a package that is in the latest update to nixpkgs. The user might then try to `flox install` the package, and they would get an error saying the package couldn't be found. So in general I think we should try to keep things as consistent as possible.

**Comment by jennymahmoudi** [comment]
Thanks for clarifying. I understand your proposal now and think you should go ahead with it.

Not holding this up but I wonder if we can avoid using the term ancestor because it just feels slightly less approachable, even though it's perfectly correct. 

If this works, great, but if not go on ahead:
```
Do you want to install to the flox environment detected in an upper level directory or the current active flox environment?
  upper level directory's flox environment [env-name]
  current active flox environment [env-name] 
```

**Comment by ghudgins** [comment]
would be good to make all 'resolve upward' logic stop at the git boundary

**Comment by mkenigs** [comment]
If we aren't in a git repo at all, does that mean to resolving upwards?

**Comment by ghudgins** [comment]
correct. at least for now

**Comment by mkenigs** [comment]
@jennymahmoudi should we say something like `flox environment detected in git repo` then?

**Comment by mkenigs** [comment]
@ghudgins @jennymahmoudi ready for review
