### ISSUE TITLE
Allow configuration of the git command

### ISSUE THREAD

**Issue by ysndr** [flox/flox#362]
This was the main ask for #305, i.e. being able to provide configuration for _all_ commands in the context of a git repo wrapped by `GitCommandProvider`.

Configuration should be passed in at construction time and stored during the lifetime of the object.

We did consider configuring `GitCommandProvider` constantly to its usage in floxmeta, essentially making every instance a `FloxMetaGitProvider`.
In this case we _still_ have an API change if tokens have to be inserted along the initialization by `git clone`.

AC:

- [x] be able to configure `GitCommandProvider` instances at creation time
- [x] do not change the semantics or signatures of any instance methods (to keep the change confined to the constructors)

**Comment by mkenigs** [comment]
Closed by https://github.com/flox/flox/pull/363
