### ISSUE TITLE
flox semver search doesn't work with wildcards

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#378]
STR:

* observe that nodejs has semver @ 18 with `flox show nodejs --all`
* `flox search nodejs@18*`

Expected: results
Actual: no results

**Comment by aakropotkin** [comment]
This is an issue in `pkgdb`.
We get 0 results with `pkgdb search` with the same query.

This needs debugging surrounding the `semver` handling in `PkgQuery`.

**Comment by aakropotkin** [comment]
A PR to `pkgdb` ( merging soon ) fixes this issue.
We need to push that change down the pipes to `github:flox/flox` after that.

**Comment by aakropotkin** [comment]
Blocked by integration with other `pkgdb` schema changes.

@zmitchell please close when you wrap your work.
