### ISSUE TITLE
flox search lists packages by search relevence

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#383]
**When** I am searching for packages to install
**I need** to see results that more closely match my search term at the top
**So I can** avoid hunting through an alphabetized list

# Acceptance Criteria

* exact term match should be at the top of results

**Comment by aakropotkin** [comment]
This is the existing behavior when results are taken directly from `pkgdb`.

If there is any re-ordering of results happening in Rust that should be fixed.
Coming out of `pkgdb` results are ranked such that "the first thing printed is the best match", and "the last thing printed is the worst match".
Be sure to maintain that ordering when you consume the output.

**Comment by mkenigs** [comment]
@ghudgins this looks stale to me
