### ISSUE TITLE
improve command spacing and readability 

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#386]
# Problem

**When** I am using flox --help, init, search, show, install, uninstall, activate in a string of activity
**I need** to visually be able to distinguish the commands from each other
**So I can** more easily see the different commands when scrolling my terminal

# Design

This needs design. @jennymahmoudi and I will update this issue with specifications after giving the command output a comprehensive audit

**Comment by ysndr** [comment]
just a note before you go wild with designing a help output,.. we don't have a lot of control over the _exact_ layout of the usage.

1. We can fork and maintain a fork of the argument parser
2. There might be an interface to build usages ourselve from the ground up, or can be exposed, I need to research that.
3. We can migrate to a different argument parser that might have more stable (and thus exposed) internals (making 2 easier). That parser is however lacking some features we currently have.
4. We write and maintain usage entirely by hand (easy to break, but if equal to manpages at least - well - equal to the manpages)

There is another discussion on building manpages from the usage using either parser, basically have a single source of truth for command documentation.
We've been discussing that pre steal thread days and had this fall under the table.

**Comment by ghudgins** [comment]
addressed in separate issues
