### ISSUE TITLE
flox language support: search, init reads .nvmrc, template

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#388]
**When** using a project configured with node version manager
**I need** flox to suggest packages installed at the right version
**So I can** easily adopt flox on an .nvmrc project without having to search / find appropriate nodejs versions

@jennymahmoudi and @ghudgins to add design and AC 

# Acceptance Criteria

* `flox search npm` functions
* `flox init` reads `.nvmrc`
*  add node template to `flox init` for node
* docs for node example

**Comment by jennymahmoudi** [comment]
+1 from yesterday's research session. the participant wondered if flox could just read the package.json file

**Comment by ghudgins** [comment]
+1 from research today read package.json node version / or .nvmrc

**Comment by ghudgins** [comment]
closing this as we'll track the constituent pieces
