### ISSUE TITLE
flox delete with confirmation

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#393]
# Acceptance Criteria

this will be split along remote / path lines but putting the AC in here for now

_Delete confirmation for path environment_
**Given** my environment is a local path environment
**And** I am in the directory with the .flox 
**When** I `flox delete` my environment
**Then** I see a confirmation "WARNING: you are about to delete {environment name} located at {environment path}
Are you sure? (Y)es / (N)o"
**And When** I input `Y`, `y`, or `yes` 
**Then** I see an environment deleted confirmation
**And** the .flox is removed
**And** the local flox meta has been removed (user does not need to see in the CLI that this has happened)

_Delete confirmation for remotely managed environment_
**Given** my environment is a remotely managed environment
**And** I am in the directory with a .flox pointed to that environment
**When** I `flox delete` my environment
**Then** I see a confirmation "You are about to delete {environment name} at {environment location}. 
Do you want to proceed? (Y)es / (N)o"
**And When** I input `Y`, `y`, or `yes` 
**Then** I see an environment deleted confirmation
**And** the .flox is removed
**And** the local flox meta has been removed (user does not need to see in the CLI that this has happened)
_Also offer upstream delete_
**And** "Do you also want to delete the upstream environment at owner/envname? (Y)es / (N)o"
**And When** I input `Y`, `y`, or `yes` 
**Then** I see an environment deleted confirmation
**And** the remote environment is no longer in flox hub

_Pure remote delete_
**Given** my environment is a remotely managed environment
**When** I `flox delete -r owner/envname` 
**And** "Do you want to delete the upstream environment at owner/envname? (Y)es / (N)o"
**And When** I input `Y`, `y`, or `yes` 
**Then** I see an environment deleted confirmation
**And** the remote environment is no longer in flox hub
**And** the local flox meta has been removed (user does not need to see in the CLI that this has happened)

**Comment by ysndr** [comment]
What behaviour do you expect in non interactive cases, i.e in a script.
Having to add a `-f` to every delete call in a script feels a bit weird to me..

**Comment by ghudgins** [comment]
sounds good. can we leave it off in non interactive without the option?

**Comment by ysndr** [comment]
yes, that's the conditional now (IF interactive AND NOT force)

**Comment by ghudgins** [comment]
@ysndr gave this a test can you check the strings to make sure they follow the AC

example from above - 
>You are about to delete {environment name} located at {environment path}. Are you sure? (Y)es / (N)o"

found in main 
```
? You are about to delete your environment cli at /Users/ghudgins/flox/cli (y/N) y
[Use `-f` to force deletion]
```

can you replace the ✅ with a 🗑️ on the confirmation that env was deleted
