### ISSUE TITLE
activate improvements: zsh support, environment variables

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#396]
- support zsh activation. See https://github.com/flox/flox/blob/668a80a40ba19d50f8ca304ff351f4b27a886e21/flox-bash/lib/commands/activate.sh#L371 and https://github.com/flox/flox/tree/668a80a40ba19d50f8ca304ff351f4b27a886e21/flox-bash/etc/flox.zdotdir for a possible approach
- use the `manifest.vars` section of the lockfile to set env vars in the environment

**Comment by ghudgins** [comment]
related issue
- [ ] https://github.com/flox/flox/issues/404
