### ISSUE TITLE
flox upgrade

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#398]
_this issue is placeholding. WIP_

# Acceptance Criteria

* `flox upgrade` advances lock file to latest available upstream 

# Notes / discussion points
* for remote and managed environments, the env must first build before the new generation can be recorded for the environment
* you need to be able to pause upgrades for certain packages
* you need to be able to upgrade individual packages within an environment

**Comment by mkenigs** [comment]
@ghudgins @aakropotkin here's a few cases I've thought through for initial implementation. Let me know if there's anything to change before I start implementing it this way.
```
No active environment, no environment in current directory or git repo:
flox upgrade
ERROR: No environment found

flox upgrade --global
# Upgrade global manifest's lockfile

flox upgrade # no args
# Upgrade all packages. There's no way to skip a single package or group.

flox upgrade PACKAGE ID|GROUP NAME...
# upgrades package IDs if not in groups, upgrades groups

flox upgrade toplevel
# upgrade all packages without a group when using the grouping strategy that puts them all in one group
ERROR: No group toplevel # when using the grouping strategy that puts packages without a group in their own group

flox upgrade package-in-group
ERROR: Can't upgrade a single package in a group; run flox upgrade group-name
```

**Comment by ghudgins** [comment]
this looks directly in line with what I was expecting (a naked upgrade upgrades everything in the environment. there's an option for package). I like the addition of a packageGroup. I'm not sure what a global manifest is at this point...the one in the home directory? this design LGTM

**Comment by mkenigs** [comment]
Yeah the global manifest is in the home directory what we search when we're not in an environment. (Thought: I wonder if we could drop that and have `search` only work in the context of an environment 🤔 )

**Comment by mkenigs** [comment]
Whoops I meant to add `--global` only for `flox update` as it only makes sense then https://github.com/flox/flox/issues/502, edited the comment above

**Comment by ghudgins** [comment]
LGTM
