### ISSUE TITLE
ERROR: missing field `channels` at line 5 column 1

### ISSUE THREAD

**Issue by tmrsgl** [flox/flox#4]
After reinstalling flox on MacOs M2 Monterey.

Installed version is:

```
tamir@Rons-MacBook-Air Downloads % flox --version
Version: 0.1.1-r404-0.0.10-r204 
```
I constantly getting errors when I am running flox commanfs:
```
tamir@Rons-MacBook-Air Downloads % flox search ripgrep
ERROR: missing field `channels` at line 5 column 1
tamir@Rons-MacBook-Air Downloads % flox search ripgrep
ERROR: missing field `channels` at line 5 column 1
```

Note: after the old version on my local machine stopped working (I did not captured the issue), I downloaded the latest flox for MacOs M1/M2 and installed it on my machine.

**Comment by robinbrantley** [comment]
Hi @tmrsgl - thank you for the feedback. 
Could you please run the command `flox --debug search ripgrep` and append the output?

**Comment by tmrsgl** [comment]
Here you go:

***@***.*** Downloads % flox --debug search ripgrep

[DEBUG] [*flox::config*] *`$FLOX_CONFIG_HOME` not set, using
"/Users/tamir/.config/flox/"*

[DEBUG] [*flox::config*] *`FLOX_CONFIG_HOME` not set, using
"/Users/tamir/.config/flox/"*

[ERROR] [*flox*] *missing field `channels` at line 5 column 1*

**Comment by robinbrantley** [comment]
All sorted offline, the error was related to a very old version of flox.
