### ISSUE TITLE
[mkEnv/activate]: test: ensure Node.js KRB5 test flow works

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#404]
Ensure that Node.js has access to other environment members in order to perform `node-gyp` compilations.

This test from the previous iteration targets `krb5` and `pkg-config` to perform `node-gyp` compilation: 
https://github.com/flox/floxpkgs/blob/c5f7a990a1526b9ba290ab1e56b3bba339e6b605/.github/workflows/etc-profiles.yml

## Acceptance Criteria
- [ ] Port legacy test case into a `bats` test.
- [ ] Make any necessary changes to `flox activate` or `mkEnv` until this flow works.

You may need to adjust the estimate on this ticket or create new follow up tickets.
More important than ticket management is doing whatever is necessary to ensure this flow works before GA.

**Comment by ghudgins** [comment]
there's a branch from when @garbas took a look for us to pick up with
