### ISSUE TITLE
flox install/uninstall builds environment

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#409]
# Acceptance Criteria

**Given** I have `flox init` an environment (it's empty)
**When** I `flox install curl` 
**Then** I see "Installing package..." (which builds the environment)
**And When** I `flox activate`
**Then** I do not have to wait for the environment to build

**And When** I `flox uninstall curl` 
**Then** I see "Uninstalling package..." (which builds the environment)
**And When** I `flox activate`
**Then** I do not have to wait for the environment to build

**Comment by stahnma** [comment]
A secondary benefit here is that it should validate the package name (as in it's real).  Right now i can do `flox install athingimadeupandisnotreal` and that appears to work (but then fails on activate, without a helpful error). We'll need a helpful error there on activate as well, in case somebody hand edits the manifest.toml.

**Comment by zmitchell** [comment]
Trying to install a package that doesn't exist now gives this error message:
```
chonker:build-envs zmitchell$ target/debug/flox install doesnt_exist
ERROR: locking manifest failed

    Caused by:
        0: resolution failure
        1: failed to resolve some packages(s):
             one of the following failed to resolve: doesnt_exist, ripgrep
```

@mkenigs has a PR up (https://github.com/flox/pkgdb/pull/166) that will improve the error message here to not list every single package
