### ISSUE TITLE
Call `pkgdb` with `--ga-registry` flag

### ISSUE THREAD

**Issue by ysndr** [flox/flox#414]
Modify `flox` CLI wrappers to use the `--ga-registry` flag.
You can preserve existing Rust unit tests that run without the `--ga-registry` flag.
Add new tests using `--ga-registry` which remove `registry` fields from manifests.

**Comment by zmitchell** [comment]
This will be included in https://github.com/flox/flox/pull/433

**Comment by zmitchell** [comment]
Closed by flox#433

**Comment by mkenigs** [comment]
Reopening as #433 didn't add `--ga-registry` here:
https://github.com/flox/flox/blob/db65051534d33dadfbf0df098c24866de37614b4/crates/flox-rust-sdk/src/models/environment/mod.rs#L387
And it disabled tests which should be renabled. @zmitchell feel free to close again if those will get fixed as part of some other ticket
