### ISSUE TITLE
flox search is faster first time

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#420]
**When** I am using `flox search` for the first time
**I need** it to not take 30s (fast connections) or > 60 seconds (slow connections)
**And** to see what it's doing when it's working
**So I can** see that flox is responsive and easy to use

# Acceptance criteria
* takes less than 5 seconds (fast connections) and 15 (slow connections)
* Change update cadence to daily
* add building/fetching the database to the installer (async)
* Definitely notify the user.

**Comment by ghudgins** [comment]
we could also consider `flox update` but need to create a separate issue for it

**Comment by zmitchell** [comment]
* Bundle a database with the installer
   * Pros:
      * Installation is already slow, building a database during installation will just make it slower. This way you can run searches right out of the box.
   * Cons:
      * The bundled database will be out of date.
         * The nixpkgs stable branches don’t change that fast. The packages that exist are likely to be the same. You may get packages with different hashes, but the package versions themselves are likely to be identical with a database that’s at most 2 weeks old.
         * Mitigation
            * A database daemon that kicks off a database build in the background immediately after installation.
* Database daemon that builds databases on a schedule.
   * Right now it would just track the nixpkgs stable branch, but in the future with multiple catalogs you could have `flox init` register new inputs with the daemon. The daemon would also be in charge of garbage collection.
   * Pros:
      * The user will always have fast searches.
      * The user doesn’t have to worry about whether their search index is up to date (e.g. we don’t need to search existing databases by default and have the user call something like `flox update-index` or pass a flag like `flox search --update-index` to get the latest results).
   * Cons:
      * Operational complexity. This is a new binary we have to support, install somewhere, manage the lifecycle of, etc.
      * Unclear when you no longer need to scrape a certain input.
         * Somehow we register with the daemon that a certain input needs to be scraped.
         * At what point do we no longer scrape that input? When the user deletes that project? What if they forget about it and we just end up wasting resources scraping that input.
         * Mitigation
            * When we register an input to scrape we could keep a record of which project/env it came from, provide a command to list the inputs that are being scraped, display the inputs that are being scraped along with the source project. This way a user can realize “hey, I no longer care about that project, let me unregister these inputs”.
            * By default we would unregister inputs when we call something like `flox delete` to delete an environment, so this user-facing command would be a last resort for cleanup.
* Change the nixpkgs update frequency
   * Pros:
      * User-visible database rebuilds are less frequent.
      * Easy change to make.
   * Cons:
      * The user still witnesses a database rebuild.
* Display a progress message
   * Pros:
      * Easy change to make
      * The user has a visual indicator that the software isn’t broken.
   * Cons:
      * Doesn’t actually make the software any faster
* Search existing databases by default, only update databases when the user passes a flag.
   * Pros:
      * The `flox search` command will always be fast.
      * Not very involved to implement.
   * Cons:
      * The user has to know about the search index potentially being out of date.
      * The user has to know which flag to use to update the search index.
      * The user has to watch the database update.

**Comment by zmitchell** [comment]
My vote is for the daemon and bundling a pre-built database. The first iteration of the daemon can just be a cron job.

**Comment by mkenigs** [comment]
- download a database instead of a flake that needs to be scraped
  - pros
    - cpu time is spent serverside once rather than clientside every time
    - the search itself is still performed clientside
  - cons
    - still have to spend network time waiting to download the database
- search serverside
  - pros
    - clients get only what they need
  - cons
    - clients can't search when offline

**Comment by aakropotkin** [comment]
- Update cadence is the easiest to implement and will have a large impact.
- Making updates to inputs explicit in projects will have a large impact.
- Fetching/serving pre-built databases is a great improvement.

**Comment by tomberek** [comment]
Idea:
- eval + build the DB in a proper nix build
- store it in S3
- substitute it via standard S3 cache mechanisms

**Comment by mkenigs** [comment]
> Idea:
> 
>     * eval + build the DB in a proper nix build
> 
>     * store it in S3
> 
>     * substitute it via standard S3 cache mechanisms
> 
> 
> Note: this was not done with the previous Catalog due to the requirement for it to have many impure facts in it.

I'm not sure if we should use Nix mechanisms, but if we do, we could also just use a `file+https` flake input. I think that fits better with some of the manifest.toml to flake.nix parallels, although it wouldn't support evaling clientside.

**Comment by ghudgins** [comment]
@aakropotkin can you add what we should do first to the top of this ticket and split the remainder into other tickets given the ideas above? then we can estimate

**Comment by tomberek** [comment]
Here's an approach leveraging Nix features to make it easier.

One can only build this way for each nixpkgs we suport in CI and include in installers. Or distribute this way as well. Or do something like this to populate it the cache instead of shelling to pkgdb directly:
```
nix build db-builder#full-eval --extra-substituters s3://our-pre-build-dbs --override-input target-flake some-target/ref/rev --out-link $HOME/.cache/flox/pkgdb-v3/FINGERPRINT.sqlite
# or use a cp --no-preserve=mode if we want the sqlite to be mutable
```

If we can do it with Nix and leverage it, we get things like caching, naming, distribution for first-use, etc....

```
{
  inputs.pkgdb.url = "github:flox/pkgdb";
  inputs.nixpkgs.url = "nixpkgs";

  inputs.target.url = "nixpkgs";

  outputs = inputs: {
    packages =
      builtins.mapAttrs (system: pkgs: {
        default =
          pkgs.runCommand "pkgdb-build.sqlite" {
            nativeBuildInputs = [
              inputs.pkgdb.packages.${system}.default
              # nixUnstable
              # jq
              # args.nix-eval-jobs.defaultPackage.${system}
            ];
          } ''
            export HOME=$PWD
            export GC_DONT_GC=1
            export NIX_CONFIG="experimental-features = flakes nix-command
            store = $PWD/temp"
            mkdir temp gc

            echo evaluating "${"path://${inputs.target.sourceInfo.outPath}?narHash=${inputs.target.sourceInfo.narHash}"}"
            pkgdb scrape "${builtins.unsafeDiscardStringContext "${inputs.target.sourceInfo.outPath}?narHash=${inputs.target.sourceInfo.narHash}"}" --database $out legacyPackages ${system}
          '';
      })
      inputs.nixpkgs.legacyPackages;
  };
}
```
usage:
```
nix build && sqlite3 ./result 'SELECT * FROM Packages LIMIT 10'
1|2|AMB-plugins|AMB-plugins-0.8.1|AMB-plugins|0.8.1|0.8.1|GPL-2.0-or-later|["out"]|["out"]|0|0|1
2|2|ArchiSteamFarm|ArchiSteamFarm-5.4.12.5|ArchiSteamFarm|5.4.12.5||Apache-2.0|["out"]|["out"]|0|0|2
3|2|AusweisApp2|AusweisApp2-1.26.7|AusweisApp2|1.26.7|1.26.7|EUPL-1.2|["out"]|["out"]|0|0|3
4|2|BeatSaberModManager|BeatSaberModManager-0.0.5|BeatSaberModManager|0.0.5|0.0.5|MIT|["out"]|["out"]|0|0|4
5|2|CHOWTapeModel|CHOWTapeModel-2.10.0|CHOWTapeModel|2.10.0|2.10.0||["out"]|["out"]|0|0|5
6|2|ChowCentaur|ChowCentaur-1.4.0|ChowCentaur|1.4.0|1.4.0|BSD-3-Clause|["out"]|["out"]|0|0|6
7|2|ChowKick|ChowKick-1.1.1|ChowKick|1.1.1|1.1.1||["out"]|["out"]|0|0|7
8|2|ChowPhaser|ChowPhaser-1.1.1|ChowPhaser|1.1.1|1.1.1||["out"]|["out"]|0|0|8
9|2|CoinMP|CoinMP-1.8.4|CoinMP|1.8.4|1.8.4|EPL-1.0|["out"]|["out"]|0|0|9
10|2|DisnixWebService|DisnixWebService-0.10.1|DisnixWebService|0.10.1|0.10.1|MIT|["out"]|["out"]|0|0|10
```

**Comment by samrose** [comment]
Did we decide to move forward with @tomberek solution on at https://github.com/flox/flox/issues/420#issuecomment-1823211255 ?

**Comment by aakropotkin** [comment]
Ranked steps
1. Notify user when databases are being built with a spinner or loading bar.
2. lower the frequency that the _Global Registry_ ( used outside of projects ) is refreshed ( currently hourly ).
3. Make _update_ operations explicit in projects ( `flox update`? ).
4. Improve database locking.
5. Kick off creation of global registry DB during install as a background task.
6. Create client/server model that serves SQLite3 databases. Or something similar to Tom's approach which can reuse existing cache push/pull features.

**Comment by ghudgins** [comment]
will resolve 1. via https://github.com/flox/flox/issues/526
will resolve 2 via https://github.com/flox/flox/issues/551

**Comment by ghudgins** [comment]
+1 via research today

**Comment by ysndr** [comment]
with the initial scrape at install time, and explicit updates, isn't this implemented now?

**Comment by ghudgins** [comment]
agreed. we can close this
