### ISSUE TITLE
flox install allows invalid package into manifest

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#427]
STR:
* `flox install python 310`

Results: both python and 310 are installed
Expected: fail to install both

STRx2:
* `flox install totallyMadeUpPackage`

Results: installed
Expected: failed to install

<img width="668" alt="image" src="https://github.com/flox/flox/assets/5465514/c49e1ce1-f03c-46e5-a044-f3b96f48e4c9">

**Comment by mkenigs** [comment]
I would expect this to fail and not install either package. See `apt` for comparison:
```
$ sudo apt install neovim not-a-package
[sudo] password for floxfan: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package not-a-package
```

This would be closed for managed environments by https://github.com/flox/product/issues/463

**Comment by ghudgins** [comment]
@stahnma found that you can also install nonsense

```
[0] stahnma@floxbox01 ~/testingarea № flox install packageNameItotallyMadeUp
:white_check_mark: 'packageNameItotallyMadeUp' installed to environment testingarea at ./.flox
```

**Comment by mkenigs** [comment]
This will all get fixed together

**Comment by jennymahmoudi** [comment]
+1 research participant experienced this today and didn't realize the package didn't actually install (npm)

**Comment by ghudgins** [comment]
`flox install npm` resolves to emacs npm package

**Comment by mkenigs** [comment]
Is this still an issue? On main:
```
> ./target/debug/flox install --dir ~/debug python 310
ERROR: locking manifest failed

    Caused by:
        0: resolution failure
        1: failed to resolve some package(s):
             in default group:
               failed to resolve `310' in input `github:NixOS/nixpkgs/e922e146779e250fae512da343cfb798c758509d'
> ./target/debug/flox install --dir ~/debug totallyMadeUpPackage
ERROR: locking manifest failed

    Caused by:
        0: resolution failure
        1: failed to resolve some package(s):
             in default group:
               failed to resolve `totallyMadeUpPackage' in input `github:NixOS/nixpkgs/e922e146779e250fae512da343cfb798c758509d'
```

**Comment by ghudgins** [comment]
you're right. original issue looks resolved. i'll log the `npm` issue separately

**Comment by ghudgins** [comment]
https://github.com/flox/flox/issues/486
