### ISSUE TITLE
flox activate uses relative paths causing issues

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#428]
STR:
* `mkdir test`
* `cd test`
* `flox init`
* `flox install nodejs`
* `flox activate`
* `node --version` (see a version number)
* `cd ..`
* `node --version`

Expected: a version number
Actual: "no such file or directory"

**Comment by stahnma** [comment]
I could really use this for the RE:invent demo, can we prioritize?

**Comment by mkenigs** [comment]
Can't confirm this is working now because there's other activate breakage at the moment, but I think it should be fixed. Reopen if not

**Comment by ghudgins** [comment]
verified 
<img width="496" alt="image" src="https://github.com/flox/flox/assets/5465514/68848d91-ece9-4f95-8f45-f84192178b06">
