### ISSUE TITLE
don't display telemetry errors in production builds

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#432]
# Acceptance Criteria

* This is tough to reproduce. If there is an issue with dependent telemetry system we should not display errors in production versions of flox. 

![image](https://github.com/flox/flox/assets/5465514/02e0cdb4-60a2-48e3-aac3-be70d7adf22b)

**Comment by ghudgins** [comment]
i've seen this on two colleagues' machines

**Comment by ghudgins** [comment]
+1 from research session today

**Comment by ysndr** [comment]
hiding these errors for now.

Shall we spend the time digging into what these are? @stahnma @ghudgins

**Comment by ghudgins** [comment]
let’s create the follow on ticket and we can work on it in the polish step
