### ISSUE TITLE
Activation of same environment just keeps adding it to PS1

### ISSUE THREAD

**Issue by stahnma** [flox/flox#441]
I found myself activating default accidentally a few times. Do we expect the behavior here to be 3x default or just once? 

`flox [default default default] [0] stahnma@floxbox01 ~ $`

**Comment by ghudgins** [comment]
<img width="697" alt="image" src="https://github.com/flox/flox/assets/5465514/e3a6891f-9218-4ce9-9a28-d2a32e56728b">
we now show an error
