### ISSUE TITLE
flox locks the wrong package

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#442]
STR:
* `flox install go`
* `flox activate`

Expected: `go - the go programming language` is installed
Actual: 

<img width="369" alt="image" src="https://github.com/flox/flox/assets/5465514/0872d950-5611-4bfc-9d4b-9936511ef885">

**Comment by aakropotkin** [comment]
A fix was added to `pkgdb` : https://github.com/flox/pkgdb/pull/160
Once we update `github:flox/flox` this should be fixed.

**Comment by ghudgins** [comment]
LGTM 

r750
<img width="221" alt="image" src="https://github.com/flox/flox/assets/5465514/9123dedb-49e6-4994-9351-4cc8a4c166ab">
