### ISSUE TITLE
flox activate doesn't flood history with setup commands

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#480]
**Given** I have created an environment
**When** I `flox activate` 
**And** within the shell I run `history`
**Then** I do not see flox's activate commands (see list)

<img width="375" alt="image" src="https://github.com/flox/flox/assets/5465514/c13d59c0-a9d0-485c-bd46-5edf6fa474bf">

**Comment by ghudgins** [comment]
+1 from research participant today (he was looking to see what `flox activate` did)

**Comment by limeytexan** [comment]
It's essential that activate honors a verbose flag that tells the user exactly what it is doing. A good litmus test for this is if a user has to resort to the use of strace to figure out what's happening then we will have missed the mark.

**Comment by ghudgins** [comment]
same. closing
