### ISSUE TITLE
flox install fuzzy matched package

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#486]
STR:
* `flox install npm`
result: `emacsPackages.npm` is installed
expected: nothing is installed

* `flox install gcc`
result: `gcc-unwrapped` is installed
expected: gcc is installed

* `flox install rails`
result: `rubyPackages_2_7.rails` is installed
expected: nothing is installed

* `flox install dotnet`
result: `emacsPackages.dotnet` is installed
expected: nothing is installed

**Comment by ghudgins** [comment]
`flox install dotnet` does the same thing

**Comment by aakropotkin** [comment]
We talked on Slack a bit.
Changing to align with the behavior you're describing conflicts with our existing specs for `flox search` and `flox install`.

We _can_ change the behavior but I'd like to sync to make sure we have alignment on the behaviors we want.

**Comment by aakropotkin** [comment]
I've moved this to be a product ticket, I'll be creating related ENG tickets to be completed next sprint.

**Comment by ghudgins** [comment]
verified 🎉
