### ISSUE TITLE
Can't show/install package output by search

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#494]
```
> flox search rails
...
rubyPackages_3_2.rails                   <no description provided>
...
> flox install rubyPackages_3_2.rails
ERROR: locking manifest failed

    Caused by:
        0: resolution failure
        1: failed to resolve some package(s):
             in default group:
               failed to resolve `rubyPackages_3_2.rails' in input `github:NixOS/nixpkgs/67be70a859530f6f7c358568eaa6ab0d84b36b01'
> flox show rubyPackages_3_2.rails
ERROR: no packages matched this search term: rubyPackages_3_2.rails
```

We're putting `"rubyPackages_3_2.rails" = {}` in the manifest instead of `rails = {path = "rubyPackages_3_2.rails"}`

**Comment by mkenigs** [comment]
@ghudgins pointed out that we could instead have the package identifier match against relPath as well as pname and attrName. That would mean changing this https://github.com/flox/pkgdb/blob/00b57be08a90531b606c5ea1247fc6fb2b05c85a/src/resolver/descriptor.cc#L552

**Comment by ghudgins** [comment]
will use solution identified in https://github.com/flox/flox/issues/486 to track fix
