### ISSUE TITLE
AWS t2.micro instance dies after installing flox

### ISSUE THREAD

**Issue by tmrsgl** [flox/flox#5]
I installed flox on a t2.micro instance, with 1G memory and 8Gb of storage (I also tried with 32G).
Looks like after installing at the first time I run flox search <pkg> the machine will halt and become unresponsive. a reboot to the machine does not solve the problem.

Please add checks of the minimum requirements of a machine at the first time flox is used on any machine.

**Comment by tmrsgl** [comment]
I tried on the same machine with 4Gb and things works as expected.

As FYI this was on ubuntu based Linux.

**Comment by robinbrantley** [comment]
thank you @tmrsgl for the feedback and we are investigating further.  :-)

**Comment by robinbrantley** [comment]
Hi @tmrsgl - we have added a section on the recommended minimum requirements on https://floxdev.com/docs/
thanks for the suggestion!
