### ISSUE TITLE
[flox/install]: Use `install.<IID>.path = ...` not `install.<IID>.name = ...`

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#503]
We are changing the interpretation of `flox install ...` to ask users to pass in a relative attribute path instead of a `match-name` term.

This means that when writing `manifest.toml` we should use the `path = <REL-PATH>` field, instead of `name = <MATCH>`.

Additionally, we will not use the provided _relative path_ argument as the `<ID>` ( _install identifier_ ); instead we will use the last element of the provided _relative path_, or allow users to set the ID explicitly with `flox install [{--id,-i}[=]<ID>] [<INPUT>:]<REL-PATH>`.

XXX: The `REL-PATH` argument should be written to `manifest.toml` AS IS.
XXX: **No quotes should be removed from the provided arguments.**
XXX: **No quotes should be removed from the provided arguments.**

Related Product Ticket: https://github.com/flox/flox/issues/486

## Acceptance Criteria
- [x] Add test cases that cover the examples below ( at a minimum ).
- [x] Add a test case for a package which requires quotes in its attribute path ( e.g. `foo."1.2.0".bar` ).
- [x] Add `-i,--id <IID>` option to `flox install`.
- [x] Manifest descriptors should use `path` field not `name` field from provided arguments.
- [x] Detect name conflicts and emit helpful error ( see below ).

## Example

```console
$ flox install hello;
$ cat ./.flox/manifest.toml;
[install]
hello.path = hello

$ rm ./.flox/manifest.toml;
$ flox install -i foo hello;
$ cat ./.flox/manifest.toml;
[install]
foo.path = hello

$ rm ./.flox/manifest.toml;
$ flox install -i=foo hello;
$ cat ./.flox/manifest.toml;
[install]
foo.path = hello

$ rm ./.flox/manifest.toml;
$ flox install --id foo hello;
$ cat ./.flox/manifest.toml;
[install]
foo.path = hello

$ rm ./.flox/manifest.toml;
$ flox install --id=cowsay hello;
$ cat ./.flox/manifest.toml;
[install]
cowsay.path = hello
$ flox install cowsay;
error: failed to install package
  A package with the id `cowsay' already exists in the environment.
  Use a unique id with:  flox install --id <ID> cowsay

$ rm ./.flox/manifest.toml;
$ flox install nodePackages.npm;
$ cat ./.flox/manifest.toml;
[install]
npm.path = nodePackages.npm

$ rm ./.flox/manifest.toml;
$ flox install 'nodePackages.npm@^18';
$ cat ./.flox/manifest.toml;
[install]
npm.path = nodePackages.npm
npm.version = '^18'
```

**Comment by ghudgins** [comment]
this proposal changes what it's in design for the manifest. I've reviewed these changes and approve of them.

**Comment by zmitchell** [comment]
@aakropotkin If you're aware of a package in `nixpkgs` of the form `foo."1.2.0".bar` please let me know. We currently can't check that exact case because you can't install a package that doesn't exist. We're also prevented from testing the `nodePackages.npm` case for the same reason (`nodePackages` isn't scraped at the moment for some reason).

**Comment by zmitchell** [comment]
I also don't think we can do both `-i foo bar` and `-i=foo bar`, which looks weird to me anyway.

**Comment by zmitchell** [comment]
```
$ flox install 'nodePackages.npm@^18'
```
```
[install]
npm.path = nodePackages.npm
npm.version = '^18'
```
This case means that we'll have to call `pkdb parse descriptor` from `flox` and parse the output, which is a bad idea long term. It's what I'll do for the sake of time but implementing the descriptor parser in `flox` will be high on the list of priorities for me after GA because `flox` is responsible for editing manifests and should know how to write the provided input to them. 

Was the plan originally to do something like
```
[install]
foo = "myinput:nodePackages.npm@^18"
```
and have `pkgdb` parse it?

**Comment by aakropotkin** [comment]
Node Package being skipped is a bug that we need to pull into the sprint.
This was a good reminder.

**Comment by aakropotkin** [comment]
My expectation is for you to write test cases that perform the equivalent checks against real packages. 

You can find packages that align with the draft, or unit test with arbitrary inputs without invoking the full CLI.
