### ISSUE TITLE
`gitCheckout` fails in bare floxmeta repo

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#51]
Reproducer:
```
> docker run --rm -it ghcr.io/flox/flox
bash-5.2# flox create
Updating git config "/root/.config/flox/gitconfig"
> Do you consent to the collection of basic usage metrics? No
> Can we log your refusal? No

    Understood. If you change your mind you can change your election
    at any time with the following command: flox reset-metrics

Updating /root/.config/flox/nix.conf

flox collects basic usage metrics in order to improve the user experience,
including a record of the subcommand invoked along with a unique token.
It does not collect any personal information.

Do you consent to the collection of basic usage metrics? (Y/n) n
warning: remote HEAD refers to nonexistent ref, unable to checkout

Understood. If you change your mind you can change your election
at any time with the following command: flox config --reset

warning: remote HEAD refers to nonexistent ref, unable to checkout
warning: remote HEAD refers to nonexistent ref, unable to checkout
created environment default (aarch64-linux)
bash-5.2# flox export > /dev/null
fatal: this operation must be run in a work tree
```

I believe the error is coming from https://github.com/flox/flox/blob/e3f71c34046e7b71a2cf264cb09a8f95514975de/flox-bash/lib/metadata.sh#L380

Since moving to bare repos, we shouldn't be performing `git checkout`

@zmitchell I believe you ran into this in another context, could you append anything relevant?

**Comment by zmitchell** [comment]
The only other thing I would mention is that you were able to pull my environment just fine even when I wasn't.

**Comment by limeytexan** [comment]
> Since moving to bare repos, we shouldn't be performing git checkout

Agree @mkenigs - this is probably the last vestige of the old way of having git checkouts of the floxmeta repo, and the subsequent `git archive` invocation doesn't even depend on the branch being checked out. Patch forthcoming in a moment ...

**Comment by mkenigs** [comment]
> The only other thing I would mention is that you were able to pull my environment just fine even when I wasn't.

Maybe I already had a non-bare repo, so performing git operations didn't change that? Not sure. Are there any other bugs you can reproduce after this change?
