### ISSUE TITLE
[pkgdb] Different results when search term contains special characters

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#521]
If you do a search query with `match="hello"` you get 11 results on `x86_64-linux`. This is the expected behavior. If you perform a search with `match="hello%"` instead, you get the same results. However, if you do a search with any of the following, you get no results back:
- `hello'`
- `hello"`
- `hello[`
- `hello]`
- `hello*`

It's unclear whether this is the intended behavior, but it seems unlikely that `hello%` should return the same results as `hello` but `hello[`, etc shouldn't.

**Comment by billlevine** [comment]
Given that I don't know what could be present in `attrName`, it seems reasonable that we just bail on any non `[.-+a-zA-Z0-9_]` character in the search term (seems like that's what is allowed in those fields by nix).  ...and only the `_` needs to be escaped (SQLlite only gives `%` and `_` as pattern wildcards).  This makes the assumption that we are not trying to do (or allow) any pattern matching via the query and we're only interested in *matching* exact sub-strings.

From the docs in `pkgdb`:
| - `match-name`: Partially match a package's `name` or `pname` fields as well as on a calculated column `attrName`.

Looking for a reference on nix package names and found this (is there a more definitive reference?): https://discourse.nixos.org/t/clarification-on-package-names-and-versions/9819
- Seems like `[a-zA-Z0-9_][.-+a-zA-Z0-9_]` is the regex for `pname`.
- And `[.-+a-zA-Z0-9_]` for `version`.

@zmitchell, @aakropotkin , anyone else? - Does this sound reasonable?

**Comment by billlevine** [comment]
Revising my suggestion... so as to not shoot ourselves in the foot... `%` and `_` for sqllite must be escaped, so at the query level, I'll do that.  If we choose to sanity check the terms later, that's a separate discussion and can happen at higher levels independent of this.  Here, we'll just make sure the query given... works.

We are making the assumption that we are doing a strict sub-string search here and no pattern matching.  It would be good to confirm that.

**Comment by mkenigs** [comment]
Currently we're doing a strict sub-string search with no pattern matching

Regex for `attrName` is here: https://nixos.org/manual/nix/stable/language/values#attribute-set

I think there's convention for pname and version, but I think under the hood there strings so I'm not sure what's enforced. I found some `=` in versions:
```
sqlite> select version from Packages where version like '%=%' limit 5;
unstable=2021-05-10
0.pre+date=2021-10-09
0.2.0+date=2021-10-16
0.2.0+date=2021-10-16
1.0+unstable=2020-11-16
```
