### ISSUE TITLE
[pkgdb] Improve ordering for nested packages

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#522]
search currently ranks older versions of rails higher than newer ones:
```
pkgdb search --quiet --ga-registry '{"query":{"match-name":"rails"}}' | jq -r '. as $pkg | ($pkg.relPath | join(".")) + "      " + $pkg.version'
rubyPackages_2_7.rails      7.0.4.3
rubyPackages_3_0.rails      7.0.4.3
rubyPackages.rails      7.0.4.3
rubyPackages_3_1.rails      7.0.4.3
rubyPackages_3_2.rails      7.0.4.3
...
```

Interestingly, the version is the same for all packages, but the newer ones can be successfully installed (e.g. with `rails = {"path" = "rubyPackages.rails"}`, but `flox install rails` fails, because it uses such an old version:
```
> flox install rails
...
           error: Package ‘ruby-2.7.8’ in /nix/store/l45hwj0x8rpmz64qli38m2j831n82zkw-source/pkgs/development/interpreters/ruby/default.nix:297 is marked as insecure, refusing to evaluate.
...
```

We may need to sort using the first element of relPath

AC:
`flox search rails` starts with the output:
```
rubyPackages.rails
rubyPackages_3_2.rails
rubyPackages_3_1.rails
rubyPackages_3_0.rails
rubyPackages_2_7.rails
```

**Comment by ghudgins** [comment]
@mkenigs does it make sense to fold this consideration into the catalog plans?

**Comment by mkenigs** [comment]
I wouldn't necessarily expect this edge case will be covered by the initial implementation, but it's probably a decent edge case to keep in mind at some point in the future. I don't know if we want tickets hanging around that long though 🤷

**Comment by ghudgins** [comment]
lets keep it in the epic for catalog so you can see it and we can try this case when we have a search interface. I'm really hoping we can pick a search implementation that we trust and can modify sane-ly. one thing about the first version we have had in the CLI is it took awhile to dial that in and it felt like re-inventing the wheel a bit.

**Comment by limeytexan** [comment]
A mix of prioritized field matching and shortest results first deliver a pretty good 90% result for 10% effort. FYI [this query](https://github.com/flox/catalog-server/blob/main/catalog_server/packages.py#L44-L70) does that and it works well.

**Comment by billlevine** [comment]
Current catalog based response looks like the following which I think meets the criteria.

```
grails                  Full stack, web application framework for the JVM
rubyPackages.rails      <no description provided>
vimPlugins.vim-rails    <no description provided>
emacsPackages.grails    <no description provided>
rubyPackages_3_3.rails  <no description provided>
rubyPackages_3_2.rails  <no description provided>
rubyPackages_3_1.rails  <no description provided>
rubyPackages_3_0.rails  <no description provided>
rubyPackages_2_7.rails  <no description provided>
rubyPackages_2_6.rails  <no description provided>
```
