### ISSUE TITLE
[flox/pkgdb]: `nodePackages.npm` missing from `pkgdb`

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#524]
Cannot find `nodePackages.npm` with `pkgdb`.

Context ( this package exists ):
`nix eval 'nixpkgs#nodePackages.npm';`

**Comment by ghudgins** [comment]
this gets solved with rules engine - adding to sprint. @zmitchell FYI

**Comment by ghudgins** [comment]
this is also solved already by the suggestion
