### ISSUE TITLE
[flox/pkgdb]: Notify user when `pkgdb` is generating a DB

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#526]
When `pkgdb` is invoked notify the user when it is generating a DB.

A simple path is to simply start a spinner with `pkgdb is creating indexes` if `pkgdb` runs for more than 0.5s.
This elides any need for message passing or IPC.

**Comment by zmitchell** [comment]
I briefly discussed this with @aakropotkin the other day and I mentioned that it would probably be easiest to do this on the `flox` side by doing this procedure for any time we call `pkgdb` or the `flox-build-env`.

Create a wrapper function like this and call it wherever a call could take a long time. This means you can handle spinners the same way in most cases and you don't need to edit the subsystems.
```rust
// pseudo-code, will not compile
const SPINNER_AFTER_DURATION: Duration = Duration::from_millis(100);
fn spinner_for_long_running_cmd(msg: &str, cmd: Command) -> Result<(stdout, stderr), std::io::Error> {
    let start = Instant::now();
    let proc = cmd.spawn();
    let stdout = proc.stdout.take(); // probably buffer these
    let stderr = proc.stderr.take();  // probably buffer these
    let mut spinning = false;
    loop {
        if (Instant::now().duration_since(start) > SPINNER_AFTER_DURATION) && !spinning {
            spinning = true;
            // Start a spinner from the `indicatif` library
        }
        let maybe_ready = proc.try_wait();
        // If it's not ready, collect stdout/stderr, if it is ready, break and stop the spinner
        std::thread::sleep(Duration::from_millis(100));
    }
}
```
