### ISSUE TITLE
install and use gcc

### ISSUE THREAD

**Issue by samrose** [flox/flox#532]
Installing and using gcc in a flox env produces errors

![image](https://github.com/flox/flox/assets/115821/fd60b9e1-7e73-453a-b1c3-c79d4d596006)

A similar exercise with nix did not fail

```
nix --version
nix (Nix) 2.18.1
sam@samrose-flox:~$ mkdir gcc-test
sam@samrose-flox:~$ cd gcc-test
sam@samrose-flox:~/gcc-test$ nix shell nixpkgs#gcc
sam@samrose-flox:~/gcc-test$ nano foo.c
sam@samrose-flox:~/gcc-test$ gcc foo.c
sam@samrose-flox:~/gcc-test$ ls
a.out  foo.c
sam@samrose-flox:~/gcc-test$ ./a.out 
Enter an integer: 1
You entered: 1sam@samrose-flox:~/gcc-test$ bat foo.c 
───────┬────────────────────────────────────────────────────────────────────────
       │ File: foo.c
───────┼────────────────────────────────────────────────────────────────────────
   1   │ #include <stdio.h>
   2   │ 
   3   │ int main() {
   4   │   int number;
   5   │ 
   6   │   printf("Enter an integer: ");
   7   │ 
   8   │   scanf("%d", &number);
   9   │ 
  10   │   printf("You entered: %d", number);
  11   │ 
  12   │ 
  13   │   return 0;
  14   │ 
  15   │ }
───────┴────────────────────────────────────────────────────────────────────────
```
(will follow up with flox version, operating system)

**Comment by ghudgins** [comment]
I think this is going to get fixed when we fix https://github.com/flox/flox/issues/435 @aakropotkin - do you agree?


```
$ flox show gcc
gcc-unwrapped - GNU Compiler Collection, version 12.2.0
    gcc-unwrapped - gcc-unwrapped@12.2.0
```

**Comment by aakropotkin** [comment]
We can hide `gcc` to prefer `gccUnwrapped` when you wrap that "allow/disallow list" PR.

**Comment by ysndr** [comment]
I tried this today and it.. worked?
This is not conclusive, just a splash of experience

**Comment by ghudgins** [comment]
there is not ideal behavior on some distributions. we're working on this "resolution engine" thing to address those

**Comment by ghudgins** [comment]
we can close this when https://github.com/flox/product/issues/607 resolves
