### ISSUE TITLE
[BUG]: flox prompts user for metrics twice when first getting started

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#54]
@limeytexan commented on [Thu May 18 2023](https://github.com/flox/product/issues/232)

The first experience a user will have following the onboarding doc will prompt them to answer the metrics question twice if they answer "no" (not sure what happens when they say "yes").

<img width="954" alt="image" src="https://github.com/flox/product/assets/36448130/72ec78da-8854-4b0d-8b22-babbcc2f03a2">

---

@limeytexan commented on [Fri May 19 2023](https://github.com/flox/product/issues/232#issuecomment-1555008803)

Spoke to Mika about this. The double logging resulted from recent-ish changes in the handling of `floxUserMeta.json` as it moved from `XDG_DATA_DIRS` to the `floxmeta` repository, but bottom line is this is best solved by removing all metrics reporting from the flox-bash code. This will require:

* add subcommand events for the bash-handled paths, currently intentionally omitted to avoid double-logging
* remove metrics support from the bash side

Mika and I will log a single PR in the flox/flox repo to work on this.

**Comment by stahnma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/flox-Engineering-6380b504813d442db8cea674/issues/flox/flox/54?planning-poker) with Zenhub @ysndr

**Comment by stahnma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/flox-Engineering-6380b504813d442db8cea674/issues/flox/flox/54?planning-poker) with Zenhub @limeytexan
