### ISSUE TITLE
flox pull

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#540]
# Acceptance Criteria

_pull existing anonymously_
**Given** I have `flox push` an environment called `ghudgins/material-ui` that contains a single package, `yarn`
**And** I am not authenticated with flox
**When** I `flox pull ghudgins/material-ui`
**Then** I see output:

```
⬇️ remote: pulling and preparing ghudgins/material-ui from https://{dev / staging / production}hub.flox.dev
```
**And When** the environment is pulled and built
**Then** I see additional output:

```
✨ pulled ghudgins/material-ui from https://{dev / staging / production}hub.flox.dev

You can activate this environment with `flox activate`
```
**And** I see a .flox is in my current directory 

Depends on flox push - https://github.com/flox/product/issues/589

**Comment by ghudgins** [comment]
related to https://github.com/flox/product/issues/570 and https://github.com/flox/product/issues/464

**Comment by ghudgins** [comment]
@ysndr - I checked out main. it's really close. can we make sure messages are done and that 1/ the user can use the `-r` option as well as submit the command 'naked' like it's written in the AC? 

thanks!

**Comment by ysndr** [comment]
with https://github.com/flox/flox/pull/646 in can this be closed?

**Comment by ghudgins** [comment]
LGTM!

**Comment by ghudgins** [comment]
@ysndr on trying it, the line about `pulling and preparing` isn't necessary since we're not pre-building the env. either we drop it and keep the implementation as it is or we keep it and kick off the env builder for the new env. 

If we keep it, can we space the down arrow away from the word `remote`. Also my english wasn't so good on this one - can we update the text to "remote: pulling {owner/env} from {floxhuburl} to current directory"

would love to hear what you think about keeping or not

**Comment by ysndr** [comment]
I think we planned to run the builder after pulling so the activate afterwards is quick

There was a bullet on that in the engineering ticket

**Comment by ghudgins** [comment]
I created https://github.com/flox/flox/issues/663 because `flox pull` doesn't currently work anonymously. FYI
