### ISSUE TITLE
flox providing some type of debug output on first activate but unclear why

### ISSUE THREAD

**Issue by stahnma** [flox/flox#557]
**Describe the bug:**

On a brand new install flox (and nix included) when you activate, you get an `[INFO]` log message. It doesn't seem helpful to a user. Maybe it should be at the `[DEBUG]` level? 
**Steps to reproduce:**
1. Install flox onto a brand new machine (no nix, no flox). 
2. clone a project that has a `.flox` directory
3. `flox activate`

Result: 

```
[stahnma@ip-172-31-83-74 goldiflox]$ flox activate
[INFO] [flox_rust_sdk::flox] Updating nix.conf: "/home/stahnma/.config/flox/nix.conf"
Building environment...
```

Expected: 
```

[stahnma@ip-172-31-83-74 goldiflox]$ flox activate
Building environment...
```

Flox version: 0.3.7-r796

**Comment by ghudgins** [comment]
will use 838
