### ISSUE TITLE
The suggestions on a typo seem...odd and frustrating. 

### ISSUE THREAD

**Issue by stahnma** [flox/flox#561]
**Describe the bug:**

When type `flox help` the suggest is `did you mean pull`? I did not. 

**Steps to reproduce:**
1. `flox help`
2. `flox version`

Result: 

`flox help`

`ERROR: no such command or positional: `help`, did you mean `pull`?
`

`flox version`

`ERROR: no such command or positional: `version`, did you mean `--version`?
`
⚠️  What is a positional? Should a user know that?  My experience is that positional is an adjective such as a "positional argument", not a noun in that a thing is a positional.  

#### Expected: 

display the help menu. 

Alternatively (and less preferred) "Did you mean --help?" 

Also, if we can figure out what the user meant, why ask and not just do it? 

**flox version:**  0.3.7-r796 commit 3766d1a

**Comment by ghudgins** [comment]
we implemented `flox help`
