### ISSUE TITLE
Devshell sets `PKGDB_BIN` and `ENV_BUILDER_BIN` to ""

### ISSUE THREAD

**Issue by ysndr** [flox/flox#591]
Setting `PKGDB_BIN` and `ENV_BUILDER_BIN` in the nix develop shell means setting these variables prior to entering the devshell is not possible:

```
PKGDB_BIN=$(pwd)/pkgdb/bin ENV_BUILDER_BIN=/Volumes/Projects/Flox/flox/flox/env-builder/bin nix develop -c code . 

# can't build rust code :/
```
instead I have to reset envs from _within_ the devshell:

```
$ nix develop
$ PKGDB_BIN=$(pwd)/pkgdb/bin
$ ENV_BUILDER_BIN=/Volumes/Projects/Flox/flox/flox/env-builder/bin
$ code .
```

**Comment by aakropotkin** [comment]
Closed by: https://github.com/flox/flox/pull/585
