### ISSUE TITLE
Create an integration test for pkgdb scrape --rules implementation

### ISSUE THREAD

**Issue by samrose** [flox/flox#593]
This test should cover a set of rules like this

```
{
  "allowRecursive": [
    ["legacyPackages", null, "darwin"],
  ],
  "allowPackage": [
    ["legacyPackages", null, "python310Packages", "pip"],
    ["legacyPackages", null, "python310Packages", "django"],
  ],
  "disallowRecursive": [
    ["legacyPackages", null, "python310Packages"],
    ["legacyPackages", null, "emacsPackages"],
    ["legacyPackages", null, "vimPlugins"]
  ],
  "disallowPackage": [
    ["legacyPackages", null, "sqlite"]
  ]
}
```
`allowPackage` takes priority over `disallowRecursive.`

that lets us "disable all python310Packages except for ____"

This ticket contributes toward #547

**Comment by aakropotkin** [comment]
this is partially completed on https://github.com/flox/flox/pull/689 but those tests need to be cherry picked out from the actual implementation of the rules engine here

**Comment by mkenigs** [comment]
Moving to backlog as this is blocked by https://github.com/flox/flox/issues/763

**Comment by ghudgins** [comment]
tests we will need:
 - include list (scrape, for example, nodepackages)
 - filter out

**Comment by mkenigs** [comment]
@billlevine do we still need coverage for this?

**Comment by billlevine** [comment]
> @billlevine do we still need coverage for this?

I think we're covered *OK* for now.  We check for the `nodePackages.npm` which is based on the rules, and unit test the rules themselves.  Considering we hope to have this offloaded to the catalog server and will likely be revisiting this code, I think the testing is adequate for the current state of affairs.
