### ISSUE TITLE
runtime flox environment issues

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#595]
# Motivation

On RHEL, the following issue can put the user in a bad state:

```
$ flox list
git

$ flox activate
Building environment...

flox [default] $ which git
~/.flox/run/x86_64-linux.default/bin/git

flox [default] $ ls
example.c  foo

flox [default] $ flox install glibc
✅ 'glibc' installed to environment default at /home/ec2-user

flox [default] $ ls
ls: relocation error: /home/ec2-user/.flox/run/x86_64-linux.default/lib/libc.so.6: symbol _dl_find_dso_for_object, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

# Acceptance Criteria

**Given** I am on RHEL
**When** I `flox install glibc`
**And** `flox activate`
**And** `ls` 
**Then** I do not see an error

**Comment by mkenigs** [comment]
This also happens on Debian 5

**Comment by ghudgins** [comment]
@stahnma to hold a discussion to come up with a solution. include me as a product stakeholder. implementers choice
