### ISSUE TITLE
`flox activate` supports managed environments

### ISSUE THREAD

**Issue by ysndr** [flox/flox#603]
- [x] a managed environment in a repo is automatically fetched and built \*
- [x] multiple instances of the same environment on the same machine have unique activations if their content differs
- [x] integration tests exist to prove activation of managed environments works

\* skipping builds is going to be implemented separately

**Comment by mkenigs** [comment]
Done except for tests

**Comment by ysndr** [comment]
tests are implemented in #620 (i cant add this issue to the PR for some reason :/)

**Comment by zmitchell** [comment]
Can this be closed if the tests are implemented?
