### ISSUE TITLE
Create a documentation page for `flox rollback`

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#61]
The `flox rollback` command is used to switch to the previous generation of an environment. This command is nice to have, but we don't have a command reference page. I'd like to use this command in the "flox in 5 minutes" tutorial, so getting this done is a high priority to me.

**Comment by aakropotkin** [comment]
Hey thanks for the recommendation.
We've got a member of our team working on some docs for this.
We'll let you know when they're available.
