### ISSUE TITLE
flox activate shows progress when building an environment

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#611]
# Acceptance Criteria

**Given** a fresh install of flox
**When** I `git clone` a project with an existing .flox
**And** I `flox activate`
**Then** I see interactive progress of an environment being prepared for first use
**And** I see a displayed message when the environment is built successfully 
**And** I see a hint about how to exit

Nice to have: configuration to disable the message

CC @jennymahmoudi if you have thoughts on what we should display

**Comment by jennymahmoudi** [comment]
1. It could be helpful to display a list of the packages that are available in the environment, so that when someone activates a shared or remote environment, they won't duplicate efforts by installing things that are already there.
2. The last message should let them know to use "exit" to leave the environment.

**Comment by ghudgins** [comment]
see this comment for a potential approach for the message: https://github.com/flox/flox/issues/526#issuecomment-1841856962

another idea: skip the build if we don't need to do it by adding the lock file to the built environment and diffing a lockfile

**Comment by aakropotkin** [comment]
`pkgdb diff` is useful if you want to generate a changelog or describe changes to an env.

I mightve misunderstood the context that y'all were discussing change detection in.

**Comment by ghudgins** [comment]
+1 on needing to see a message about having to exit from research today

**Comment by ghudgins** [comment]
LGTM
