### ISSUE TITLE
Interaction between [vars] should be predictable

### ISSUE THREAD

**Issue by nicklewis** [flox/flox#617]
# Acceptance Criteria

 - vars no longer use the shell interpolation
 - treat vars as plain string values. 

**Describe the bug:**

Currently, vars are included as shell expressions in the activation script and can therefore interpolate values. In general, they can properly reference env vars set _outside_ the context of the flox environment. In _some cases_, they can reference other vars defined in the `[vars]` list, but the behavior is unpredictable.

For instance:

```toml
[vars]
FOO="/foo"
BAR="/foo/${BAR}"
BAZ="${BAR}/BAZ"
```

The intuitive behavior here is that the resulting values will be `/foo`, `/foo/bar` and `/foo/bar/baz`. In practice, the result depends on the order in which the variable assignments are executed.

The trouble stems from the fact that we use a TOML table to define vars. Tables don't guarantee any ordering of elements.

**Desired behavior**

The critical requirement is that the behavior must be predictable and consistent. Ultimately, any behavior the user wants from vars can be implemented using `export` expressions in the shell hook, so whatever we choose doesn't actually restrict what the user can accomplish in their environment.

A few options involve changing either how we represent these fields in the manifest or how we format them. One is to parse the table using an order preserving map, which has the significant drawback of not conforming with the TOML spec. Another is to represent this data in the manifest using an array rather than a table, which has the significant drawback that TOML arrays are very user-hostile.

Other options involve changing the semantics of the vars themselves. Today, the value of the var is an arbitrary shell expression and vars are assigned serially.

We could assign vars in parallel (ie. `export <var>=<value> <var>=<value> <var>=<value>`) which strictly prevents vars from referencing each other's values but still lets them reference env vars.

We could also restrict the semantics of the value to something we define. This type of solution has the benefit of being well defined and portable (both between shells as well as to outside tools like flox hub).

The simplest such option would be to specify that vars can only be assigned literal values (so `foo="$bar"` would result in the literal value `$bar`). This has the benefit of being easy to understand and the drawback of providing very limited utility.

Another such option would be to parse the value and implement interpolation ourselves in a format we specify, rather than leaving it to the shell. This has the benefit that we could order vars based on dependency order and allow them to reference one another. It has the drawback of being somewhat complex to implement and potentially unintuitive if it _looks_ like shell interpolation but isn't. It also means we would either lack or have to implement additional functionality like setting a default value (`FOO="${FOO:-hello}"`).

**Comment by nicklewis** [comment]
While I wrote a number of options, in retrospect it's clear to me that the ideal solution is the last one: fully define the semantics of variable definitions, implementing interpolation ourselves if we want it. The _only_ reason to leave this up to the shell is for simplicity of implementation. There is no real user benefit.

Of course, implementing interpolation is probably prohibitively expensive in the short term. In that case, we should support a strict _subset_ of that functionality. My proposal is therefore that we drop interpolation entirely and make these vars literal values. Layering interpolation on top of that later will be purely additive and won't break any existing uses. Shipping with shell interpolation for now paring back to our own interpolation later, on the other hand, would constitute a breaking _removal_ of functionality.

**Comment by zmitchell** [comment]
I'd like to clarify the TOML array point. TOML [arrays](https://toml.io/en/v1.0.0#array) aren't user hostile, but a TOML [array of tables](https://toml.io/en/v1.0.0#array-of-tables) are ugly.

You could have an array like this using TOML "inline tables":
```toml
vars = [
  {name = "FOO", value = "/foo"},
  {name = "BAR", value = "/foo/${BAR}",
  ...
]
```
or some other format for defining variables inside of the array e.g. `"FOO=/foo"`, `"BAR=/foo/${BAR}"`, etc. This way you get order preservation.

**Comment by nicklewis** [comment]
Ah yes good point. I was thinking of the array of tables which is verbose and obscure. A regular array could work. A benefit is that it gives us a place to put metadata/parameters (though we could maybe do that with a regular table as well? `<var>.<param> = ...`?).

```toml
vars = [
  # simple assignment
  "FOO=/foo",
  # only set the var if it's not already set as an env var
  {name = "BAR", value = "/bar", override = false}, 
  # don't set the var in the resulting env, only while running the shell hook
  {name = "BAZ", value = "/baz", activate_only = true}
]
```

**Comment by tomberek** [comment]
There is some prior art to examine: https://github.com/numtide/devshell/blob/main/modules/env.nix#L62-L70 , namely being explicit if one wants an eval or not to occur, or to capture common patterns such as prefixing

To avoid accidental order-sensitive evaluation one needs to use shellEscaping equivalent to: https://github.com/NixOS/nixpkgs/blob/master/lib/strings.nix#L443

**Comment by ysndr** [comment]
When discussing this the other day, the conclusion was: `vars` will be documented/implemented as literals and do not allow substitution. The ability to add substitution using shell independent escapes may be added post-GA.

(please correct if this is wrong information, I just wanted to have the decision on the record)

**Comment by zmitchell** [comment]
That decision was captured as acceptance criteria  above

**Comment by ysndr** [comment]
Huh read right past it 🫥

**Comment by ysndr** [comment]
Huh read right past it 🫥
