### ISSUE TITLE
flox init adds runtime to .gitignore

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#625]
# Acceptance Criteria

**When** I `flox init`
**Then** I see a `.gitignore` has been added to the `.flox` folder 
**And When** I `cat` the `.gitignore`
**Then**  `.flox/run` at the end of my `.gitignore`

**Comment by ysndr** [comment]
@ghudgins this changes was merged
please reopen if this needs further attention

**Comment by ghudgins** [comment]
verified, LGTM
