### ISSUE TITLE
Test failure due to leaking USER/HOME

### ISSUE THREAD

**Issue by tomberek** [flox/flox#628]
**Describe the bug:**

Running tests with a logged in real user on a Mac failes tests that expect the testing user to be not logged in. (@stahnma )

**Steps to reproduce:**
1. Be on a Mac
2. flox auth login
3. nix run .#flox-cli-test

Result: 
h1 and l1 tests fail

Expected: 
success

Likely related:
- https://github.com/flox/flox/blob/main/cli/flox/src/main.rs#L125-L131
- https://github.com/flox/flox/blob/main/cli/tests/setup_suite.bash#L23-L35
- https://github.com/flox/flox/blob/main/cli/tests/setup_suite.bash#L399

**Comment by ysndr** [comment]
Another one, when updating the global lockfile:

**Steps to reproduce:**

1. (be on a mac?)
2. flox update --global
3. nix run .#flox-cli-test

Result: 

```
 ✗ 'flox show' uses '_PKGDB_GA_REGISTRY_REF_OR_REV' revision [5302]
   (from function `assert_output' in file /nix/store/2migbgfk5h02270zh8miv398qkv59p55-bats-with-libraries-1.9.0/share/bats/bats-assert/src/assert_output.bash, line 194,
    in test file package-show.bats, line 183)
     `assert_output '    nodejs - nodejs@18.16.0'' failed
   ✨ Created environment test (aarch64-darwin)
   
   Next:
     $ flox search <package>    <- Search for a package
     $ flox install <package>   <- Install a package into an environment
     $ flox activate            <- Enter the environment
   18.16.0
       nodejs - nodejs@18.17.1
   
   -- output differs --
   expected :     nodejs - nodejs@18.16.0
   actual   :     nodejs - nodejs@18.17.1
   --
   
   Last output:
       nodejs - nodejs@18.17.1
```

**Comment by mkenigs** [comment]
> Another one, when updating the global lockfile

I may have fixed that particular issue with https://github.com/flox/flox/pull/828/files#diff-4201466466709fc33beaedf4767a41986ea75b011db9a6c0d738b365c9ee8d2dR165

**Comment by mkenigs** [comment]
This may have been addressed by https://github.com/flox/flox/pull/1045 and the reproducer no longer fails, so closing
