### ISSUE TITLE
flox commands other than `update` don't generate a pkgdb database

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#635]
Currently, any flox command may run into a pretty large slowdown if it has to generate a pkgdb database. We should instead only generate databases during a `flox update`, when users will understand the slowdown.

- Trigger db generation in `update`
- Start a background `flox update` in the installer
- Unlocked environments use the global lock. Currently, if e.g. the global lock has a nixpkgs with nodejs@18.16, if a user runs `flox init && flox install nodejs`, they'll get a nodejs newer than 18.16. Instead, 18.16 should be installed from the nixpkgs in the global lock.
- `show`/`search` use the global lock when outside of an environment

**Comment by mkenigs** [comment]
Ready for product review. It's worth noting that we don't trigger db generation on Linux unless the user invokes `sudo`. This may not be the case if running in e.g. a container.

**Comment by ghudgins** [comment]
verified
