### ISSUE TITLE
flox list shows additional metadata

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#636]
# Acceptance Criteria

**Given** I have `curl` installed at version 8.1.1 and `python311Packages.pip` installed at 3.6.8 in an environment
**When** I `flox list` my environment
**Then** I see listed packages and installed versions

```
curl: curl (8.1.1)
pip: python311Packages.pip (3.6.8)
```

_--name option_
**Given** I have `curl` installed at version 8.1.1 and `python311Packages.pip` installed at 3.6.8 in an environment
**When** I `flox list --name` my environment
**Then** I see a list of IDs

```
curl
pip
```

_--detail option_
**When** I `flox list --detail` my environment
**Then** I see a list including all available metadata organized roughly into columns

Design is implementer's discretion based on available data

**Comment by ghudgins** [comment]
other metadata to consider:
- has package number
- has package name
- shows version
- shows system
- shows path (or remote)

**Comment by rossturk** [comment]
I wonder if we should show the package's `attr name` here - e.g. if you install gcc on Mac this will be `gcc-unwrapped`? Might this help folks know if there's a mapping going on underneath?

**Comment by stahnma** [comment]
I'd be interested in list with versions and list without versions given a flag. Like
 
 `flox list -n` is names only.

**Comment by ghudgins** [comment]
>I wonder if we should show the package's attr name here - e.g. if you install gcc on Mac this will be gcc-unwrapped? Might this help folks know if there's a mapping going on underneath?

@rossturk we have closed the bug that made it so `flox install gcc` was installing another package called `gcc-unwrapped`. The install experience is back to being deterministic against what you literally pass to install, which is a good thing. we are considering a resolution engine feature that will allow us to alias commands and substitute other packages in specific cases and, as part of that requirements spec, communicating what is happening to the user is in scope. 

>If so, I propose lines like:
>gcc: gcc-unwrapped (12.2.0)

we should show additional metadata now that we have it. We have the following pieces and I like the idea that we display the path in addition to the ID to make it clear what you have installed (and what the ID's are since we have gone that way with #503 ) 

here are the parts we can work with ID (pip), path (python311Packages.pip), version (3.4.5), system (aarch64-darwin), name (pip), description (The PyPA recommended tool for installing Python packages)

with that in mind and your suggestion I think we should amend the list command as follows

`ID: path (version)` i.e. `pip: python311Packages.pip (3.4.5)`

this does mean we will repeat ourselves for some packages `hello: hello (4.5.6)` but I don't think that's too bad.

cc @stahnma what do you think too?

**Comment by rossturk** [comment]
> with that in mind and your suggestion I think we should amend the list command as follows
> 
> `ID: path (version)` i.e. `pip: python311Packages.pip (3.4.5)`

I played with this for a bunch last night, and (avoiding the `gcc` example), if you install `mysql` you get a result like this:

```
      "mysql": {
        "attr-path": [
          "legacyPackages",
          "x86_64-linux",
          "mysql"
        ],
        "info": {
          "broken": false,
          "license": "GPL-2.0",
          "pname": "mariadb-server",
          "unfree": false,
          "version": "10.6.15"
        },
```

In this case, the fact that it’s not actually MySQL from Sun cannot be found in the ID or the path, it can only be seen in the `pname`.

**Comment by ghudgins** [comment]
really cool comparison. now we're dipping into how nixpkgs maintainers have organized things. I feel we'll need to curate that experience. there's a design doc in the works around that topic. I think the challenge with pname is we are currently centering search and install around paths as that's the best lookup for the catalog. while we are still exposing nixpkgs directly, it is surfacing how the nixpkgs maintainers have organized things and have made calls on resolution. as soon as we start creating resolution rules and curating it (that separate spec mentioned above), the sky is the limit. for now I think the proposed changes to list can proceed....what do you think, do you agree?

**Comment by rossturk** [comment]
> I think the challenge with pname is we are currently centering search and install around paths as that's the best lookup for the catalog.

That is true, but in the list command I think what the user wants to know is:
* what did I ask for (which I believe we call the “package id”)
* what is the actual software package that got installed (like, if I look in my `.flox/run` directory for links into `/nix/store/` what is the name of the directory I will find it linking to)

My current set of experiences suggest that the second bullet is `pname` - that’s what would tell a user that `mariadb` is what was actually installed.

If we do as you proposed, I think users will have to look through JSON or symlink trees to find that answer.

**Comment by ghudgins** [comment]
I don't know I want to expose the added complexity of "what nixpkgs actually did" to users with the pname because we can fix wrong behaviors with a "resolution engine" in flox or in nixpkgs directly allowing us to rely/curate the packages that are doing the right things vs. exposing something you can't search or install in the list command. If we center the search/install around pnames then we would be missing extra metadata stored in the path name by nixpkgs maintainers...would think it's better to lean in on how nixpkgs organizers have set things up. This would allow us to solve that `mysql` issue or any other issue we find by either upstream changes we need or address them via resolution engine rules that overlay nixpkgs. As a user you get to trust that we'll do the right thing between search and install without having to worry about it. And, for us, we get the manifest.lock to allow us to debug. CC @aakropotkin because he may have thoughts to but what do you think, @rossturk?

**Comment by rossturk** [comment]
> I don't know I want to expose the added complexity of "what nixpkgs actually did" to users with the pname because we can fix wrong behaviors with a "resolution engine" in flox or in nixpkgs directly allowing us to rely/curate the packages that are doing the right things vs. exposing something you can't search or install in the list command. 

Again going back to the example of `mysql`, I don't feel like it's a good experience for there to be no sign whatsoever in flox that it actually installed `mariadb`.

This isn't an unimportant packaging detail that only matters when you are operating within the bowels of Nix; MariaDB is a different project with a completely different license.

**Comment by ghudgins** [comment]
>This isn't an unimportant packaging detail that only matters when you are operating within the bowels of Nix; MariaDB is a different project with a completely different license.

yeah - agree, didn't say the issue was unimportant - would want to fix that in either nixpkgs or via the "resolution engine" with what I propose in my previous comment

**Comment by ghudgins** [comment]
no that's the default list. `--detail` should show everything we have in pkgdb

**Comment by ghudgins** [comment]
looks good from my end. tested all new options
