### ISSUE TITLE
Unable to activate in flox in a .bashrc or .zshrc

### ISSUE THREAD

**Issue by stahnma** [flox/flox#641]
**Describe the bug:**

I might be using the wrong incantation, but using the one I used to use for flox back in the day, it just hangs. 

**Steps to reproduce:**
1. edit .bashrc or .zshrc 
2. add `eval "$( flox activate; )"` to your .bashrc or .zshrc # note probably have another terminal window open when you do this so you don't lock yourself out.
3. attempt to login 

Result: 

```
[0] stahnma@floxbox01 ~ № ssh 192.168.1.36
Last login: Thu Dec 14 22:24:34 2023 from 192.168.1.227 # hangs for 30+ seconds

^C
%
[stahnma@fedora]~% clear
[stahnma@fedora]~%
(eval):1: command not found: ^[7Building
(eval):2: bad pattern: ^[8^[[H^[[2J^[[3J
flox [default default default default default default default default default default default default default default] [stahnma@fedora]~% cat .zshrc
flox [default default default default default default default default default default default default default default] [stahnma@fedora]~%
```

It appears that the "Building environment..." string is part of what's causing issues, but it could be other things as well. 

Expected: 

I have an active env based in my home dir with my favorite tools in it. 

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **
Version: 0.3.7-r830

**Comment by mkenigs** [comment]
This isn't really a bug, we just haven't gotten to that feature yet. Old flox would check for a tty and print an activation script in the non-interactive case. We decided to not support that in the initial iteration of activate

**Comment by ghudgins** [comment]
verified!
