### ISSUE TITLE
Search performance investigation

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#659]
This is going to be a running note as I investigate the current state of search performance.

**Comment by zmitchell** [comment]
The first thing I want to know is where time is spent when I `flox search`.

Let's start by assuming we've already downloaded the tarball for the `nixpkgs` revision we're searching against. You can do this warm up step by simply calling `pkgdb search --ga-registry --match-name hello`. The current TTL on tarballs we've set is 24 hours, so you basically don't have to worry about getting a test run that needs to download the next latest revision, and if you do end up downloading another tarball, you'll notice. I think this also means that evaluation of the flake is cached, but I'm not sure how that works.

After that I wrote a script that uses DTrace to profile `pkgdb search --ga-registry --match-name hello` and uses some [other tools](https://github.com/jonhoo/inferno) to turn the samples into a flamegraph.
![flamegraph](https://github.com/flox/flox/assets/10246891/df0a17f7-fcc7-4b58-90ec-e8f7c89a8ecc)

As expected, about 95% of the time is spent in `PkgDbInput::scrape`, however, there's a couple of interesting things:
- 27.4% of the time is spent simply initializing packages
- Another 20.3% of the time is spent getting package attributes (name, description, etc)
- 11.8% is spent inserting descriptions if they don't exist (which requires a query to see if one exists)
- Only 26.6% of the execution time is `pkgdb` talking to SQLite (there are some times where `nix` is talking to SQLite because it's looking at the eval-cache). Note that this includes the getting/setting descriptions mentioned in the previous bullet.
- The largest chunk of time is spent in `nix` in one way or another (mostly evaluation).
- 10.4% of the time is spent in `versions::coerceSemver`

What this tells me is that if we were to magically make the database transactions instantaneous, we would only speed up a search with a warm eval-cache by about 25%, which isn't the order of magnitude (at least) improvement that we want in order to provide a better experience for users. The _bigger_ issue is that doing this search and building this database takes 1.8s on my machine (M1 Max Macbook Pro), which is only a fraction of the time it takes for a user to do their first search.

Later posts will dissect where that time is spent.

**Comment by zmitchell** [comment]
Downloading `nixpkgs` on my home internet (1200mpbs down) takes about 6 seconds using this command:
```
$ time curl -L "https://api.github.com/repos/NixOS/nixpkgs/tarball/release-23.11" -o nixpkgs.tar.gz
```
The bottleneck isn't my home internet speed, it's GitHub. If I limit the download speed using `--limit-rate 6250k` (50mbps, which is a reasonably common download speed) the time to download is essentially identical.

**Comment by zmitchell** [comment]
Extracting `nixpkgs` to another directory takes about 4.5-5s on my machine (M1 Max Macbook Pro):
```
$ time tar -xzf nixpkgs.tar.gz --directory=extracted
```
This is a relatively beefy machine with very good single-threaded performance, so I suspect most users would experience something slower. Allegedly the deflate format doesn't lend itself well to utilizing multiple cores, so it appears standard `gzip` doesn't even bother. That could be completely wrong, but the timing is still accurate.

**Comment by zmitchell** [comment]
The upshot of all of this is that eliminating the database transactions would save us about 0.5s out of a 10+s operation, so it's truly a waste of time trying to make that much faster, even though I'm very, very confident there's low-hanging fruit in terms of optimizing the database operations.

**Comment by ghudgins** [comment]
we should review this today to make sure we have everything accounted for

**Comment by zmitchell** [comment]
I'm traveling today. I should have time in the airport or after I've made it to my destination.

**Comment by ghudgins** [comment]
thanks for doing this @zmitchell - resolving this issue. trusting we'll address this issue's findings when we do the upcoming catalog work
