### ISSUE TITLE
More consistent use of spinners

### ISSUE THREAD

**Issue by ysndr** [flox/flox#660]
Instead of adhoc messaging, for tasks that we know will take a _some time_ (e.g. commands that kick of a build in the background) should use the `Spinner` dialog.

Tbd: pass a spinner handle into the library layer to provide more detailed information retrieved from pkgdb.
That by itself is a somewhat larger task with some unknowns so is *not* covered by this issue.

**Comment by ghudgins** [comment]
LGTM
