### ISSUE TITLE
`flox pull` & `flox activate -r` allows anonymous users

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#663]
# Acceptance Criteria

**Given** I have not `flox auth login`
**When** I `flox activate -r ghudgins/cli`
**Then** I am taken to an interactive shell for the env (today it errors)
**And When** I `flox pull ghudgins/cli` 
**Then** I pull successfully (today it errors)

Note: the API already allows this behavior.

**Comment by ysndr** [comment]
@nicklewis does the api also allow for checking if I will need auth?

@ghudgins do _all_ pulls work anonymously? I.e. do we laugh without private environments?

**Comment by ghudgins** [comment]
@nicklewis confirmed this for me earlier. it does

eventually, no. all won't work. we will get unauthorized back from the backend at some point. just not initially

**Comment by nicklewis** [comment]
We don't currently have an API to check auth and we don't exactly have anywhere to _put_ such an API. We need something akin to flox-api, like a dedicated API service for the CLI to talk to.

The trouble here is that if authentication _is_ required but you aren't logged in, we don't have a good way to prevent git from trying to query the user for their login info. One option we discussed was to have a well-known user/"password" combination that the server will interpret as "anonymous". In that case, if you aren't logged in but try to perform an operation that requires authentication, git will 1) try the request anonymously and fail, 2) retry the request "authenticate" (as the anonymous user) and fail, and then report a hopefully intelligible failure.

I think ultimately we aren't going to be able to rely on git to tell us what happened, so we will need an API that we can query to find out whether we _expect_ the git operation to succeed before we actually try it. In that case, any git failure can just be 
treated as an unexpected error.

**Comment by ysndr** [comment]
My take away:

* initially all environments are public -> ill remove the "guard"
* we will add some sort of preflight ability (or find arcane git magic) to tell us whether we _need_ authentication when we work towards introducing private environments
