### ISSUE TITLE
`flox i <package>` shortcut

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#664]
# Acceptance Criteria

**Given** I have `flox init` an environment
**When** I `flox i ruby`
**Then** I see ruby is installed
**And When** I `flox --help`
**Then** I see

```
...
install, i     Install a package into an environment
...
```

**Comment by ysndr** [comment]
- We just need to know which to provide shorthands for
  - some are obvious
  - some are ambiguous
- Do all commands have a shortcut (obv, not all can but if they are unambiguous, should they get a shortcut now?)
- do "Additional Commands" get a shortcut?

**Comment by ghudgins** [comment]
@jennymahmoudi strong feelings about others? this one was so we could have muscle memory similar to npm

**Comment by jennymahmoudi** [comment]
nope, not yet

**Comment by ysndr** [comment]
@ghudgins @jennymahmoudi 
implemented in https://github.com/flox/flox/pull/687

**Comment by ysndr** [comment]
let me know when you want more

**Comment by ghudgins** [comment]
verified. resolve this once it's merged
