### ISSUE TITLE
Allow `flox` to update spinners during long running operations

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#665]
Seeing a spinner gives the user some indication that an operation is taking place. Seeing the same message on the spinner for the duration of the operation can give the false impression that the operation has stalled. Being able to update the spinner during long running operations will give the user confidence that the operation is proceeding as intended.

In order to accomplish this, `pkgdb` can send JSON records over `stdout` that have a "progress message" structure. We already do something similar for search results, where `pkgdb` emits a stream of JSON records that are currently either
1. The total number of search results
2. A single search result
3. An error

Adding this record type would be trivial now that `flox` and `pkgdb` live in the same repository.

**Acceptance criteria**
- There is a new `ProgressMessage` class that holds a message intended to be displayed to the user in a spinner.
- The `ProgressMessage` class is serialized to JSON and sent back to `flox` over `stdout`.
- `flox` deserializes the progress message and updates the spinner with the message.
- `pkgdb` emits these progress message records while building environments

**Comment by mkenigs** [comment]
I think we're going to use tracing for this in https://github.com/flox/flox/issues/2219, can we close this ticket in favor of that approach @zmitchell ?

**Comment by zmitchell** [comment]
Yep
