### ISSUE TITLE
Non-interactive `activate` invokes interactive shell

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#666]
`flox activate -- COMMAND` currently runs interactive rc scripts, which is surprising behavior as the user cannot interact with the shell.
We should drop the `-i` here, but doing so would require changing our initialization scripts:
https://github.com/flox/flox/blob/866b5fde83c455b026f8af78bfd333e6a04fc91d/cli/flox/src/commands/environment.rs#L406

**Comment by ysndr** [comment]
to clarify, our activation hook and environment setup in interactive shells is exectured through a custom `.{bash,zsh}rc` which itself sources the original rc files for the shell.
Changes would need to be made to execute the shell setup only and _then_ exec the requested command.

**Comment by mkenigs** [comment]
Yeah we would probably need to use zshenv instead of zshrc. But we don't necessarily want to do that for interactive shells, because we want our initializations to run as late as possible

**Comment by ysndr** [comment]
Do we need to go through the zshenv/bashrcs at all for this kind of activation, or can we just use the in-place activate script? The shell specific setup for prompts and such is not relevant for a non-interactive `flox activate --` or am i missing something?

```
exec bash -c {in-place activation script}; exec {provided arguments}
```

**Comment by mkenigs** [comment]
> ```
> exec bash -c {in-place activation script}; exec {provided arguments}
> ```

(I think you mean to have that command quoted)

I think you're probably right that we can skip RCs for `flox activate --`. That does introduce a little bit of divergence in behavior (it could be confusing for `flox activate -- cmd` and `flox activate\n cmd` to behave differently), but I think that's probably desirable.

Shouldn't the in-place activate script be settings prompts though? Looks like it isn't currently. Is that deliberate because of activating environments in rc files?

**Comment by ysndr** [comment]
the in-place variant is setting the prompt (or should be)

```
$ flox activate --in-place
...
source /Volumes/Projects/Flox/flox/flox/cli/.flox/run/aarch64-darwin.cli/activate/zsh

$ cat /Volumes/Projects/Flox/flox/flox/cli/.flox/run/aarch64-darwin.cli/activate/zsh


if [ -d "$FLOX_ENV/etc/profile.d" ]; then
  declare -a _prof_scripts;
  _prof_scripts=( $(
    echo "$FLOX_ENV/etc/profile.d"/*.sh;
  ) );
  for p in "${_prof_scripts[@]}"; do . "$p"; done
  unset _prof_scripts;
fi

$ source /nix/store/b63zswm4vni8r6cjbbfdflll0r0mpvlp-set-prompt.zsh.sh
if [ -d "$FLOX_ENV/etc/profile.d" ]; then
  declare -a _prof_scripts;
  _prof_scripts=( $(
    echo "$FLOX_ENV/etc/profile.d"/*.sh;
  ) );
  for p in "${_prof_scripts[@]}"; do . "$p"; done
  unset _prof_scripts;
fi

source /nix/store/b63zswm4vni8r6cjbbfdflll0r0mpvlp-set-prompt.zsh.sh
```

**Comment by mkenigs** [comment]
Oh nvm it is working, I had forgotten to quote `$(flox activate)` 😳
