### ISSUE TITLE
flox search unixtools wrongly returns no packages

### ISSUE THREAD

**Issue by stahnma** [flox/flox#677]
**Describe the bug:**

I can see `unixtools.` packages showing up when I search certain strings, but I can't search for that string.

**Steps to reproduce:**
1. `flox search glibc --all` # Notice the last 3 lines
2.  `flox search unixtools` # nothing
3. `flox search unixtools.getent` # something is returned, but i have to know the package name exactly

Result: 

I can't really search for unixtools.

Expected: 

I can search for unixtools. 

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

Version: 0.3.6-168-g2d8d41c

**Comment by ghudgins** [comment]
lets start by prototyping the queries before committing to the full text search solution. let's have a discussion before we commit to the solution

**Comment by mkenigs** [comment]
I remember this coming up in the CLI meeting, but I can't quite remember what we decided. Did we say we'd just check for the search term in any component of the attribute path? @zmitchell @ghudgins

**Comment by ghudgins** [comment]
yes, I think so. and  we wanted to see some example queries in a prototype before we committed to how we would address this use case.

**Comment by mkenigs** [comment]
Could you see what you think of this branch? https://github.com/flox/flox/tree/match-relPath Stuff like ordering isn't polished, but I think it might be the gist of the behavior

**Comment by ghudgins** [comment]
looks a lot closer to what I was expecting. any reason `flox search unixtools.ge` doesn't work? 
<img width="577" alt="image" src="https://github.com/flox/flox/assets/5465514/ff6c8b8c-d432-4bc8-8d67-3c2c57af62e9">

**Comment by mkenigs** [comment]
Good point, I'll change that

**Comment by mkenigs** [comment]
Pushed another commit, how's it look now?

**Comment by ghudgins** [comment]
much better. resolves my prior issue.

**Comment by mkenigs** [comment]
Ready for review

**Comment by ghudgins** [comment]
not able to do `flox search unixtools.ge` on main

**Comment by mkenigs** [comment]
Is it returning no results?
```
> git pull origin main
From github.com:flox/flox
 * branch              main       -> FETCH_HEAD
Already up to date.
> just build-cli
make: Entering directory '/Users/matthew/flox/main/pkgdb'
mkdir -p tests;
Generating tests/.gitignore
make: Leaving directory '/Users/matthew/flox/main/pkgdb'
~/flox/main/cli ~/flox/main
~/flox/main
> flox search unixtools.ge
unixtools.getconf  <no description provided>
unixtools.getent   <no description provided>
unixtools.getopt   <no description provided>

Use `flox show <package>` to see available versions
```
