### ISSUE TITLE
flox prompts me for what env I want to search...but I'm just searching

### ISSUE THREAD

**Issue by stahnma** [flox/flox#678]
**Describe the bug:**

Flox needs to know what environment i want to search in. Search feels like it should be read-only so it won't need to know what env I am in. At least, if it does, that feels odd to me. 

**Steps to reproduce:**
1.  Have an environment in $HOME. Have another one somewhere. Activate that other one. 
2. `flox search glibc`
3. Get prompted to see if you want to search in $HOME/.flox or active env. 

Result: 

Asking for input. 

Expected: 

It does the search without more instructions. 

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

Version: 0.3.6-168-g2d8d41c

**Comment by ghudgins** [comment]
it does because we have `flox update` so the catalog it's searching can advance. this is as specified.

**Comment by mkenigs** [comment]
You can also search outside an environment if you don't have one activated or in the current dir

**Comment by ghudgins** [comment]
discussed offline. can close this for now. ideas to consider in the backlog: 
 - config to always handle this choice a specific way so you don't have to get prompted. 
 - maybe a reminder about `-d` so you can avoid the interactive
