### ISSUE TITLE
Setting MANPATH on activation removes ability to see man pages for system tools

### ISSUE THREAD

**Issue by stahnma** [flox/flox#684]
**Describe the bug:**

I can't `man` things that are system provided when I have an activated environment. 

**Steps to reproduce:**
1. `echo $MANPATH`
1. `man uptime` # note this works
1. `flox activate` 
1. `man uptime` # no manual entry found for uptime
1. `echo $MANPATH`

Result: 

```
flox [default] [0] stahnma@floxbox01 ~ № man uptime
No manual entry for uptime
```

Expected: 

The man page is displayed. 

**Screenshots/terminal output (if relevant):**

```
[0] stahnma@floxbox01 ~ № echo $MANPATH

[0] stahnma@floxbox01 ~ № man uptime
[0] stahnma@floxbox01 ~ № flox activate
Welcome to your flox environment!
flox [default] [0] stahnma@floxbox01 ~ № man uptime
No manual entry for uptime
flox [default] [1] stahnma@floxbox01 ~ №
```

** flox Version (run `flox --version` if possible): **

Version: 0.3.6-168-g2d8d41c 

On Darwin, with system provided bash as shell. 

![Cursor_and_floxbox01](https://github.com/flox/flox/assets/6961/8c3e0bdc-434c-48a1-b80f-600705e7957d)

**Comment by ghudgins** [comment]
need to introspect the OS, figure out defaults, and append

**Comment by aakropotkin** [comment]
I'd do
```
MANPATH="${MANPATH:+$MANPATH:}:/share/man:/usr/share/man";
MANPATH="$MANPATH:/usr/local/share/man:$FLOX_ENV/share/man";
export MANPATH;
```

**Comment by aakropotkin** [comment]
Good tip from @nicklewis ( handled in my snippet above ):

> If MANPATH begins with a colon, it is appended to the default list; if it ends with a colon, it is prepended to the default list; or if it contains two adjacent colons, the standard search path is inserted between the colons. If none of these conditions are met, it overrides the standard search path.
