### ISSUE TITLE
flox edit with systems

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#701]
STR:
* `flox init`
* `flox edit`

paste the below

```
[install]
curl.path = "curl"
curl.package-group = "green"
curl.systems = ["aarch64-linux"]
curl.optional = true

[options]
systems = ["x86_64-darwin", "aarch64-darwin", "aarch64-linux"]
```

Result: error
Expected: success
<img width="644" alt="image" src="https://github.com/flox/flox/assets/5465514/8d306035-9554-418c-bae5-418a3f3baa39">

**Comment by ghudgins** [comment]
same issue for `curl.systems = ["aarch64-darwin", "x86_64-darwin"]`

**Comment by ghudgins** [comment]
okay the issue is it's `package-group` not `packageGroup`. also the error from pkgdb is being suppressed

**Comment by ghudgins** [comment]
we reviewed - the `flox edit` command appears to have the bug as you can edit the manifest directly and generate a lockfile with `~/flox/pkgdb/bin/pkgdb manifest lock --ga-registry --manifest .flox/env/manifest.toml --lockfile .flox/env/manifest.lock`

**Comment by aakropotkin** [comment]
#730 fixes the `null` parse failure.
Other issues are not addressed in #730.

**Comment by mkenigs** [comment]
Can we close or update this ticket? You mention other issues @aakropotkin but the reproducer above seems to work on `main` now

**Comment by ghudgins** [comment]
verified
