### ISSUE TITLE
flox containerize (experimental)

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#718]
# Acceptance Criteria

* fail early with an error on macos (mitigations and maybe polish left for another PR/issue)
* write to stdout if stdout is mapped to a file `flox containerize | docker load`
* write to a file `<env name>-container.tar.gz`
* allow to override file with `(--output|-o) <file>` where `-` is stdout again

**Comment by ysndr** [comment]
a fix for zsh activation is in flight in #747

**Comment by ghudgins** [comment]
verified. will capture follow-ons in new issues
