### ISSUE TITLE
flox push login prompt should allow users to press enter to open the URL 

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#719]
**Describe the bug:**
When I am not authenticated, and I flox push, the message I receive doesn't match the design.

Results:
```
You are not logged in to floxhub. Logging in...
Please visit https://[redacted].com/activate in your browser
And enter code: KMKP-JQBL
```

Expected:
```
You are not logged in to flox. 

First copy your one-time code: [8-digit code]
Press enter to open [vanity URL] in your browser... 
```
where [vanity URL] is the base url of floxhub: `hub.flox.dev`

When a user's system does not have an `open` command to allow them to press enter to open the URL, then the message should be: 
```
You are not logged in to flox. 

Go to [activation URL] in your browser
Then enter your one-time code: [8-digit code]
```
where [activation URL] is the full URL for the device auth activation 

**flox Version: 0.3.6-192-g3ef8037**

**Comment by ghudgins** [comment]
missed details when I wrote https://github.com/flox/flox/issues/539 and https://github.com/flox/product/issues/589. would be good to correct!

**Comment by jennymahmoudi** [comment]
A few additional changes needed to match the design, particularly after successful login:
* clickable prototype here: https://www.figma.com/proto/eWhJ1u51TGKjAhoFtYyRK0/Sign-up?page-id=0%3A1&type=design&node-id=167-7367&viewport=1339%2C-19410%2C0.87&t=2y45D7tiC9zSovBr-1&scaling=min-zoom&starting-point-node-id=167%3A7367&mode=design
* Direct to the figma file here: https://www.figma.com/file/eWhJ1u51TGKjAhoFtYyRK0/Sign-up?type=design&node-id=62%3A423&mode=design&t=8wJvETtIxzxKPPWX-1

**Comment by zmitchell** [comment]
I'm thinking for this one that you detect the presence of one of the `open` commands first, then only if you detect them you show this message about pressing `Enter`. If we can't detect one of the open commands then it doesn't make sense to suggest a user try it.

These commands open a browser when passed a URL:
- Linux: `xdg-open`, and maybe `gnome-open`
- macOS: `open` (should be there by default)

**Comment by zmitchell** [comment]
Down the line we can also try to automatically copy the code to the clipboard as well.

**Comment by jennymahmoudi** [comment]
> If we can't detect one of the open commands then it doesn't make sense to suggest a user try it.
TIL. :)

If they don't have an `open` command, we can show an alternate version of this message? adding that to the ticket description.

**Comment by ysndr** [comment]
For reference, `gh` **does not print the full url** (likely unless no opener is found but i'd need to dig for that),
Pressing <kbd>enter</kbd> is thus _the only_ way to open the correct url.

```
...

! First copy your one-time code: 2169-EA22
Press Enter to open github.com in your browser...
```

The code to make _both_ copy pasting the url and pressing enter work is a bit awkward.
I agree with zach that we should likely look for an opener and if present, only provide the <kbd>enter</kbd> method.
If the opening fails, or no opener is present we can fall back to manual entry.

```
You are not logged in to flox. 

First copy your one-time code: [8-digit code]
Press Enter to open hub.flox.dev in your browser...
<Enter>
Could not open browser!

Please visit https://hub.flox.dev/auth/device in your browser to continue... 
```

**Comment by ysndr** [comment]
Please also note that we _can_ construct urls with the token pre-applied.

I.e. when we are in the opener flow, we don't need to let the user copy the code.
Auth0 will (in either case) ask the user to verify that the code they see is the same as printed in the browser.

We could reword our messaging accordingly (It can be weird to copy from the terminal and frustrating if in the next step you notice you wouldn't have to).

Non blocking but i think an improvement of usability

**Comment by jennymahmoudi** [comment]
> Do we wan't "copy paste to browser" and "open browser on enter" to both work?

When you say "copy paste to browser" do you mean showing the full URL? Or something additional happening besides that?

> Please also note that we can construct urls with the token pre-applied.
> I.e. when we are in the opener flow, we don't need to let the user copy the code.

Good to know! Let's stay with the current manual copy method for now. Happy to revisit/iterate after GA.

**Comment by ysndr** [comment]
> When you say "copy paste to browser" do you mean showing the full URL? Or something additional happening besides that?

Yeah that's what I mean 
copy the url -> open browser -> copy code -> enter code -> go back to the terminal.

Some terminals will allow to open links directly so you just copy the code. If your terminal doesn't it's just getting a bit frustrating.

What I meant to say is, we should only display the full url to manually go there if we can't open a browser. Juggling both options is rather awkward.

**Comment by ysndr** [comment]
> Good to know! Let's stay with the current manual copy method for now. Happy to revisit/iterate after GA.

Manual code entry it shall be, happy to show/discuss other options later.
