### ISSUE TITLE
Update error message for login timeout

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#721]
**Describe the bug:**
When I log in to flox from the CLI (in this case, when I am prompted via flox push), the CLI timeout error is not great.

**Steps to reproduce:**
1. On the CLI, when unauthenticated, do `flox push`
2. Take more than the timeout length (currently 30 seconds due to a bug, but will be 15 minutes when fixed) to enter 8-digit code on the web

Result: 
* the auth0 web flow reports that the device is successfully connected
* the CLI reports an error:
`ERROR: Could not authorize via oauth: Could not authorize via oauth: Server returned error response`

Expected: 
* the auth0 web flow should report an error
* the CLI error should be:
`ERROR: failed to authenticate before the device code expired. Please retry to get a new code.`

^^ Not sure if we can/should be specific about retrying `flox auth login` or `flox push` depending on what triggered the login attempt, so I kept it vague with "Please retry". If we can be more specific we can rewrite this.

**flox Version (run `flox --version` if possible): 0.3.6-192-g3ef8037**

**Comment by ysndr** [comment]
closed with #842
