### ISSUE TITLE
flox activate tells you how to exit

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#724]
# Acceptance Criteria
**Given** I have an environment in my current directory
**When** I `flox activate`
**Then** I see a loading message with a spinner:
```
:. Getting ready to use environment project1 at /path/to/env/project1
```
**And then** when it is completed I see the loading message is replaced with a confirmation message:
```
✅ You are now using the environment ‘project1’ at /path/to/env/project1 
To stop using this environment, type ‘exit’
```

**Comment by ghudgins** [comment]
related to proposal in https://github.com/flox/flox/issues/611

**Comment by jennymahmoudi** [comment]
### Current behavior

Loading...
```
$ flox activate
:. Building environment project1 at /path/to/env/project1
```
Completed...
```
$ flox activate 
flox [project 1] $
```

### Proposal 1 (activate)

Loading...
```
$ flox activate
:. Activating environment project1 at /path/to/env/project1
```
Completed...
```
$ flox activate 
✅ Activated environment project1 at /path/to/env/project1
To deactivate this environment, type ‘exit’
flox [project 1] $
```


### Proposal 2 (use)

Loading...
```
$ flox activate
:. Getting ready to use environment project1 at /path/to/env/project1
```
Completed...
```
$ flox activate 
✅ You are now using the environment ‘project1’ at /path/to/env/project1 
To stop using this environment, type ‘exit’
flox [project 1] $
```


### Proposal 3 (use config with details - if we can show a simplified list)

Loading...
```
$ flox activate
:. Getting ready to use environment config for project1 at /path/to/env/project1
```
Completed...
```
$ flox activate 
✅ You are now using the environment config for ‘project1’ at /path/to/env/project1
Packages:
  hello
  python
  requests
Environment variables:      # only shown if there are any variables OR just show a count of env vars?
  message                           # only show the variable name? 
Activation hooks:               # only shown if there are any hooks OR just show a count of hooks?
  script                                 # only show the hook name?

To stop using this environment config, type ‘exit’
flox [project 1] $
```

**Comment by ghudgins** [comment]
I think, for now, option 2 is probably good to start. can always do parts of 3 later.

**Comment by mkenigs** [comment]
I guess most developers will know and do it anyways, but I prefer `CTRL + D` to `exit`. 2 vs 5 keystrokes 😛

**Comment by ghudgins** [comment]
we've seen enough developers in research to include it

**Comment by mkenigs** [comment]
I was suggesting we consider saying `To stop using this environment, type 'CTRL + D' or 'exit'`

**Comment by jennymahmoudi** [comment]
Thanks for clarifying. Let's just give one way for now (exit). Less to read/scan.

Good to know the shortcut though. We could add this in to the web docs, and/or help. 

For the general --help, I'm not sure if there is a way to add in a message about how to exit, not tied to another command, though. Do you know if that's possible?

**Comment by mkenigs** [comment]
I don't completely understand what you mean, could you maybe paste what output you would want?

**Comment by jennymahmoudi** [comment]
Since I have seen people scanning the help trying to figure out how to leave an environment, I was thinking of adding something in there, although we can wait to see if the activate confirmation message is enough. 

Something like this under additional commands (even though it's not a flox command)...

```
flox is a virtual environment and package manager all in one.

With flox you create development environments that layer and replace dependencies just where it matters,
making them portable across the full software lifecycle.

Usage: flox [[-v]... | -q] [--debug]... [--version] [COMMAND ...]

Local Development Commands
    init           Create an environment in the current directory
    activate       Enter the environment
    search         Search for system or library packages to install
    show           Show details about a single package
    install, i     Install a package into an environment
    uninstall      Uninstall installed packages from an environment
    edit           Edit declarative environment configuration file
    list           List packages installed in an environment
    delete         Delete an environment

Sharing Commands
    push           Send environment to flox hub
    pull           Pull environment from flox hub

Additional Commands
    update, upgrade, config, wipe-history, history, auth 
    Use 'flox COMMAND --help' for more info
    Use 'exit' to leave an activated environment

Available options:
    -v, --verbose  Verbose mode.
                   Invoke multiple times for increasing detail.
    -q, --quiet
        --debug    Debug mode.
        --version  Print the version of the program
    -h, --help     Prints help information

```

**Comment by mkenigs** [comment]
We could add it there! I agree it's a little odd to put it there since it's not really an additional command though

**Comment by ghudgins** [comment]
+1 from user research today

**Comment by ysndr** [comment]
we should add it as a note in the help of `flox activate` rahter than the `flox` help but we can start with the message.

**Comment by ghudgins** [comment]
+1 from research today

@ysndr - we amended the top to be from activate

**Comment by ghudgins** [comment]
+1 from _another_ research participant today

**Comment by ghudgins** [comment]
looks good from the product side. mergable once the PR comes in
