### ISSUE TITLE
flox init injects current system to manifest

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#739]
We would like to eagerly lock all systems in the manifest so that the lockfile is never in a dirty state and can be pulled on a system other than the system the lockfile was created on. Eagerly locking all systems includes a performance penalty, so we would like to include systems in the "to be resolved" list on an opt-in basis, so we'll use the existing `option.systems` field as the explicit list of systems to resolve on.

**Comment by ghudgins** [comment]
can we assume that no system injected means the env will build for all systems? I'm worried about doing this as restriction should be opt in and not by default.

**Comment by zmitchell** [comment]
Discussed offline, for now we're just going to inject the current system. We can revisit this later when there's less of a performance hit to creating package databases.
