### ISSUE TITLE
Add a top-level 'cache' field to the lockfile

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#743]
It can be useful to know that an environment is guaranteed to build on systems other than the current one. Knowing that individual packages build isn't enough to guarantee this, as file conflicts between packages can cause a build failure.

**Acceptance criteria:**
- The lockfile has a top-level field called `cache` that `pkgdb buildenv` fills out when building an environment.
- The `cache` field contains `system.outpath: path` key value pairs corresponding to the outpath for the built environment.

**Comment by mkenigs** [comment]
I suggested keeping the cache block clearly separated from the rest of the lockfile because a functional representation of what you're saying sounds to me like:
```
fn buildenv(fields: LockfileExceptCache, _please_do_not_use: Cache) -> StorePath {
  # if I accidentally use _please_do_not_use, I invalidate the build and force a useless rebuild
}
```

When we could just keep things clearly separated and do
```
fn buildenv(fields: Lockfile) -> StorePath {
  # I can use any field from the lockfile
}
```

**Comment by mkenigs** [comment]
This isn't consistent with our current design for multi-system environments. If we need to store guarantees about building, we'll do it outside of the lock.

**Comment by ghudgins** [comment]
@zmitchell can we close or refine this issue?
