### ISSUE TITLE
"no change made" flox edit message returns after trying to build the environment 

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#751]
STR:
* have an environment with multiple packages installed
* flox edit it
* quit without saving

Result: you wait for the environment to build
Expected: the "no changes made happens" immediately

+1 from user research today

**Comment by ysndr** [comment]
- "edit" is also performing a build which may result in a new|updated lockfile even if the manifest didn't change.
- could rely on modify time but that seems kinda fragile
- this would work because the initial creation of the edited file happens just before its opened with the editor

**Comment by mkenigs** [comment]
We could diff the manifest against the manifest in the lockfile

**Comment by ghudgins** [comment]
tested the product side on the branch. works as I would expect
