### ISSUE TITLE
flox displays active environment // flox envs

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#752]
# Motivation

**When** my terminal preferences are overriding flox's prompt (https://github.com/flox/flox/issues/637) 
**I need** flox to display the active environment(s) in its commands
**So I can** know where I am

# Acceptance Criteria

* Print active environment info in `flox` 
* `flox` : when at least one env is present, the help text to use flox init is replaced with a list of active envs (or “no active envs”)
Design details in https://www.notion.so/floxdev/View-environments-CLI-design-8f68c6465e944cba8f3ab474b1785ca4?pvs=4

Also covered with `flox envs --active`, implemented in https://github.com/flox/flox/issues/934

**Comment by ghudgins** [comment]
+1 from research. person had #678 issue and wanted `flox status`

**Comment by ghudgins** [comment]
questions flox status could help answer (from @rossturk ) 
* am I in an environment or not?
* am I in more than one environment? in what order are they layered?
* what's my sync status? do I need to run a pull?
* what's my freshness status? would things change if I ran an upgrade?
* do I have known security issues (dun dun DUN)

**Comment by ysndr** [comment]
TBF those questions could also be answered by inspecting `$FLOX_ACTIVE_ENVIRONMENTS` which also provides a bit more information on what type of environment is active:

```
❯ flox activate --                                         
flox [cli] 
❯ echo $FLOX_ACTIVE_ENVIRONMENTS 
[{"type":"dot-flox","path":"/Volumes/Projects/Flox/flox/flox/cli","pointer":{"name":"cli","version":1}}]
```

I guess a `flox status` command should be not more than a pretty printer for that variable

**Comment by ghudgins** [comment]
+1 user research

**Comment by ghudgins** [comment]
consider adding a tip about exiting if we do `flox status`

**Comment by ghudgins** [comment]
+1 from research today

**Comment by ghudgins** [comment]
duplicate of https://github.com/flox/flox/issues/934
