### ISSUE TITLE
flox push design match

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#755]
**Describe the feature:**
Success message after flox push should be updated to match the design. 

**Acceptance criteria:**
When a user successfully pushes a flox environment and completes login at the same time, the message should be:
```
✓ Authentication complete
✓ Logged in as **jennymahmoudi**
✓ **myenvironment** successfully pushed to floxhub

Use ‘flox pull jennymahmoudi/myenvironment’ to get this environment in any other location.
```
![image](https://github.com/flox/flox/assets/2687382/1d49cd17-7b3a-43fd-8867-ec22e1d3c68f)

And when a user successfully pushes a flox environment (while already logged in), the message should be:
```
✓ **myenvironment** successfully pushed to floxhub

Use ‘flox pull jennymahmoudi/myenvironment’ to get this environment in any other location.
```

clickable prototype here: https://www.figma.com/proto/eWhJ1u51TGKjAhoFtYyRK0/Sign-up?page-id=0%3A1&type=design&node-id=167-7367&viewport=1339%2C-19410%2C0.87&t=2y45D7tiC9zSovBr-1&scaling=min-zoom&starting-point-node-id=167%3A7367&mode=design

Direct to the figma file here: https://www.figma.com/file/eWhJ1u51TGKjAhoFtYyRK0/Sign-up?type=design&node-id=62%3A423&mode=design&t=8wJvETtIxzxKPPWX-1

**Comment by ysndr** [comment]
we currently print 
```
✅  updated -> {owner}/{name}{suffix}

Pull this environment with 'flox pull {owner}/{name}'.
You can see this environment at {web_url}{owner}/{name}.
```

at @ghudgins request

is the change to 

```
Use ‘flox pull jennymahmoudi/myenvironment’ to get this environment in any other location.
```
intentional?

**Comment by jennymahmoudi** [comment]
Sorry for the miscommunication here when you first built it. 

The message I used is intentional for a few reasons: 
1. It's the same language used in floxhub to describe the flox pull command
2. "get this environment in any other location" is a reminder that this is publicly accessible without needing to use a warning or scary messaging about it.
3. dropping the reference to view it in floxhub so that we don't overshadow the message about using the pull command.

**Comment by ysndr** [comment]
Ok.

Just to confirm, we also use _the same_ message now for both updating an existing env on floxhub and pushing a new one?
Currently its:
```
✅  updated -> {owner}/{name}{suffix}
✅  created -> {owner}/{name}{suffix}
```

**Comment by ysndr** [comment]
Ok.

Just to confirm, we also use _the same_ message now for both updating an existing env on floxhub and pushing a new one?
Currently its:
```
✅  updated -> {owner}/{name}{suffix}
✅  created -> {owner}/{name}{suffix}
```

**Comment by jennymahmoudi** [comment]
Yep, let's have a different message for subsequent pushes.

I propose
`✓ Updates to <environmentname> successfully pushed to floxhub`

**Comment by ysndr** [comment]
Do we also want to mention when we pushed with --force?

Currently we append (forced) to the message if the flag was provided

**Comment by jennymahmoudi** [comment]
Yes let's keep that as is. Append `(forced)`.

**Comment by ysndr** [comment]
amended the message for update

**Comment by ghudgins** [comment]
LGTM
