### ISSUE TITLE
`flox list` fails if environment contains packages that are excluded for the current system

### ISSUE THREAD

**Issue by ysndr** [flox/flox#761]
a manifest with `install` items that specify specific systems such as

```toml
# manifest.toml
[install.gcc]
path    = ["gcc-unwrapped"]
systems = ["x86_64-linux", "aarch64-linux"]
```

will produce a lockfile where the locked package for systems other than the stated ones, will be `null`:

```json5
# manifest.lock
...
"packages": {
	"aarch64-darwin": {
		"gcc": null
	}
}
...
```

We parse the lockfile assuming a locked package and fail with 

```
ERROR: failed to parse contents of locked manifest: invalid type: null, expected struct LockedPackage
```

due to the element being `null`.

The relevant change to **ignore** packages not installed for your system (and minimal change to fix resolve this issue) would be 

```diff
diff --git a/cli/flox-rust-sdk/src/models/lockfile.rs b/cli/flox-rust-sdk/src/models/lockfile.rs
index ca8bfd85..0e8f25e6 100644
--- a/cli/flox-rust-sdk/src/models/lockfile.rs
+++ b/cli/flox-rust-sdk/src/models/lockfile.rs
@@ -1,3 +1,4 @@
+use futures::lock;
 use serde::{Deserialize, Serialize};
 use serde_json::Value;
 
@@ -123,7 +124,7 @@ impl ToString for LockedManifest {
 pub struct TypedLockedManifest {
     #[serde(rename = "lockfile-version")]
     lockfile_version: Version<0>,
-    packages: BTreeMap<System, BTreeMap<String, LockedPackage>>,
+    packages: BTreeMap<System, BTreeMap<String, Option<LockedPackage>>>,
     registry: Registry,
 }
 
@@ -174,12 +175,14 @@ impl TypedLockedManifest {
         let mut packages = vec![];
         if let Some(system_packages) = self.packages.get(system) {
             for (name, locked_package) in system_packages {
-                packages.push(InstalledPackage {
-                    name: name.clone(),
-                    rel_path: locked_package.rel_path(),
-                    info: locked_package.info.clone(),
-                    priority: locked_package.priority,
-                });
+                if let Some(locked_package) = locked_package {
+                    packages.push(InstalledPackage {
+                        name: name.clone(),
+                        rel_path: locked_package.rel_path(),
+                        info: locked_package.info.clone(),
+                        priority: locked_package.priority,
+                    });
+                };
             }
         }
         packages
```

**Comment by mkenigs** [comment]
- We should make sure the Rust schema isn't inconsistent with the C++ one
- Should we be adding that package in `pkgdb lock`?

**Comment by ysndr** [comment]
> We should make sure the Rust schema isn't inconsistent with the C++ one

That's what this diff is trying to do, taking the pkgdb schema as authoritative
Better would be a common schema definition... but that seems outside of the scope of this bug

> Should we be adding that package in `pkgdb lock`?

I'm not sure how you mean that? the pacakge is there, just it's value is `null`. The value is `null` either because it was marked `optional` and failed to evaluate, or because it was explicitly excluded from evaluation on a specific platform.
Instead of writing null we could write an object describing the reason.
If we want that, that should be done before GA and stability guarantees reg. the lockfile set in.

**Comment by mkenigs** [comment]
> > Should we be adding that package in `pkgdb lock`?
> 
> I'm not sure how you mean that? the pacakge is there, just it's value is `null`. The value is `null` either because it was marked `optional` and failed to evaluate, or because it was explicitly excluded from evaluation on a specific platform. Instead of writing null we could write an object describing the reason. If we want that, that should be done before GA and stability guarantees reg. the lockfile set in.

Oh I misread the ticket sorry, I was thinking `aarch64-darwin` was `aarch64-linux`

**Comment by ghudgins** [comment]
tested the product side on the branch and it looks like it fixes the issue. I tested with the manifest on https://github.com/flox/flox/issues/701
