### ISSUE TITLE
flox activate -r is slower than path envs on subsequent activations

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#769]
suggested AC: 

* repeated activation of a remote environment doesn't perform a rebuild

STR:
* do a `time | flox activate -r ghudgins/default -- true`
* do a `time | flox activate -r ghudgins/default -- true` again

Result: 
consistent slower performance
```
shell  0.00s user 0.00s system 0% cpu 2:11.48 total
children  0.00s user 0.00s system 0% cpu 2:11.48 total
```

Compare to doing repeat activation with a path env with the same contents

* `time | flox activate -d /Users/ghudgins`

```
shell  0.00s user 0.00s system 0% cpu 13.496 total
children  0.00s user 0.00s system 0% cpu 13.496 total
```

Expected: remote path activations match path env performance on repeat activations

**Comment by ghudgins** [comment]
visual comparison:

remote env
![Large GIF (856x508)](https://github.com/flox/flox/assets/5465514/0d1b111d-c63d-4fc9-aff6-c25637007835)

path env
![Large GIF (640x436)](https://github.com/flox/flox/assets/5465514/41df1164-9cf7-4bf5-943f-3c1b723b1bb1)

**Comment by ghudgins** [comment]
+1 from an early pog-making user

**Comment by mkenigs** [comment]
We're building the environment twice even if we've already built it. We should have a gcroot for the environment, so we can at least skip that slowdown. From watching the logs for `flox --debug activate -r ghudgins/default -- true`, both of the builds seem slower than the git operations

**Comment by mkenigs** [comment]
I would update the AC to "repeated activation of a remote environment doesn't perform a rebuild"

**Comment by ysndr** [comment]
we're *evaluating* it again, _because we have a new clone_ and there is no _outlink_.
but then again it _could_ also be a whole new outlink anyway because the environment was updated.

the issue would also need an AC for
1) how long after the first activation, the second activation _should not_ rebuild
2) whether _all activations_ of the environment shall be affected by an update/rebuild after that phase

IMO if you want caching, and predictable performance you should `flox pull` an environment and then activate it with locally with `flox activate -d ...`

**Comment by mkenigs** [comment]
Until a different generation is pushed to the remote, we shouldn't do a rebuild. As soon as a different generation is pushed, we should do a rebuild.

**Comment by ysndr** [comment]
What if it's pushed somewhere else?

But we can treat them as basically syntax sugar to `flox pull --force -d <flox provided dir> && flox activate -d <flox provided dir>` and possibly a different heuristic for detecting the need to (re)build

**Comment by mkenigs** [comment]
I meant rebuild if it's pushed anywhere. We still need to do the underlying git operation, but if the environment hasn't changed at all, we shouldn't rebuild

**Comment by ysndr** [comment]
Ok then we're saying the same thing I guess
The only quirk is that activating an environment may update existing activations

Which could be a feature or not

**Comment by mkenigs** [comment]
Hmm yeah that's a good catch. Maybe call it a feature for now 😆 I guess we have a similar problem for path envs:
```
term1$ flox init
term1$ flox activate
term2$ flox edit # add hello and an env var
term1$ # I have hello but not the env var
```

**Comment by ghudgins** [comment]
seems reasonable to require a new window to get changes made in other windows for now

**Comment by ghudgins** [comment]
also, an aside. it's much slower now than it was when this was opened

this is `Version: 0.3.6-269-g8a69e2d`
![Large GIF (860x548)](https://github.com/flox/flox/assets/5465514/ae1fbe78-c6b9-47bc-adfb-7af5d4554035)

**Comment by ghudgins** [comment]
verified 🔥 
![Large GIF (946x614)](https://github.com/flox/flox/assets/5465514/1cf92675-2ba3-43cb-a4fa-cd8fc9f8a796)
