### ISSUE TITLE
`flox list` should have some sort of output when the environment contains no packages

### ISSUE THREAD

**Issue by nicklewis** [flox/flox#780]
**Describe the bug:**

**Steps to reproduce:**
1. `flox init`
2. `flox list`

Result:

```
$ flox init
✨ Created environment foobar (aarch64-darwin)

Next:
  $ flox search <package>    <- Search for a package
  $ flox install <package>   <- Install a package into an environment
  $ flox activate            <- Enter the environment
$ flox list
$ 
```

Expected: 

Some sort of message indicating the environment has no packages, maybe a call-to-action.

```
$ flox init
✨ Created environment foobar (aarch64-darwin)

Next:
  $ flox search <package>    <- Search for a package
  $ flox install <package>   <- Install a package into an environment
  $ flox activate            <- Enter the environment
$ flox list
No packages installed.
$
```

**Comment by ysndr** [comment]
For context, `list` was supposed to _not_ print a message like that for use in scripts -- i.e. it should behave like `git remote` without remotes...
That was when the `--names-only`  option was the only available/default option.
We can add a more error'y output going to stderr in either case i guess

**Comment by mkenigs** [comment]
Dup of https://github.com/flox/flox/issues/930
