### ISSUE TITLE
update formatting on flox install help message

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#792]
The help message for `flox install` uses two ways of formatting for optional arguments: a space or `=`. Both ways are valid, but we should be consistent. 

Current help output:
```
flox install --help
Install a package into an environment

Usage: flox install [-s=SYSTEM] [-d=<path> | -r=<owner/name>] [-i <id> <package>]... [<packages>]...

Install a package into an environment
    -s, --system=SYSTEM
    -d, --dir=<path>     Path containing a .flox/ directory
    -r, --remote=<owner/name>  A remote environment on floxhub
  -i <id> <package>
    -i, --id             Install a package and assign an explicit ID
    <id>                 ID of the package to install
    <package>            Path to the package to install as shown by `flox search`

Available options:
    -h, --help           Prints help information
```

Additional context 
> it's two different kind of parsers
> the "two args option" we use for id is contructed differently (parses -i id, package indivvidually) while the -r=<owner/name> parser is a provided parser that parses "an option with a value" as one.
> since the latter is a built in parser there is a special syntax for that for usages.

**Comment by ysndr** [comment]
as some sort of data point, `git` i actually using the same formatting, `--option=value` for single value options and `--option value value` for multi value options:

```
$ git config --help
...
git config [<file-option>] [--type=<type>] [-z|--null] --get-urlmatch <name> <URL>
...
```

**Comment by jennymahmoudi** [comment]
Bummer but I understand. I'll close/won't fix.
