### ISSUE TITLE
terminal reset needed after CTRL+C'ing out of flox edit

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#793]
STR:
* `flox edit`
* CTRL+C out of the editor
* do any other flox command like just `flox`

Result: misaligned terminal that requires `reset` to fix
Expected: happy terminal on CTRL+C

<img width="966" alt="image" src="https://github.com/flox/flox/assets/5465514/e1813b88-92c4-4174-8a69-4c54d4190207">

**Comment by ghudgins** [comment]
@rossturk I can't repro this one now. can you?

**Comment by rossturk** [comment]
> @rossturk I can't repro this one now. can you?

Not using my previous method, no!
