### ISSUE TITLE
question: flox wipe-history is not implemented, how to do nix garbage collection

### ISSUE THREAD

**Issue by networkhermit** [flox/flox#8]
```text
$ flox --version
Version: 0.1.1-r404-0.0.10-r204
```

I see `flox wipe-history` prompts `ERROR: not implemented` and there are no flox command to do garbage collection.

I find a workaround by first backing up the flox.nix and running `flox destroy` together with `flox edit`, after that `nix-collect-garbage -d` can be used to do the cleanup.

I'm relatively new to nix and flox. Are there better ways to do garbage collection that follow nix/flox best practices?

**Comment by robinbrantley** [comment]
Hi @networkhermit - thank you for the feedback! You are right and we need to improve this part of the UX. I have added it to our list to prioritise.
