### ISSUE TITLE
When activating second env, getting an error that an env is already active (but it appears to work) 

### ISSUE THREAD

**Issue by stahnma** [flox/flox#806]
**Describe the bug:**

When activating a second env, an error is given -- however the activation appears to work. 

**Steps to reproduce:**
1.  `flox activate` your `$HOME` environment.
2.  Go into another directly and `flox init`, `flox install` some stuff
3.  `flox activate` 

Result: 

```
flox [default] [0] stahnma@floxbox01 ~/development/nixpkgs [master] $ flox activate
ERROR: Environment 'default at /Users/stahnma' is already active
flox [nixpkgs default] [0] stahnma@floxbox01 ~/development/nixpkgs [master] $
```

Expected: 

No `ERROR` message. 

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

0.3.6-209-gf481196

**Comment by ghudgins** [comment]
can't reproduce on 0.3.6-235-gdf37997

**Comment by stahnma** [comment]
able to reproduce on 0.3.6-236-g6111fe0 

I'm wondering if it's because my $HOME environment is done through `eval $(flox activate -d $HOME)` ?

**Comment by ghudgins** [comment]
yes - we have that covered in https://github.com/flox/flox/issues/812
