### ISSUE TITLE
`flox activate` issues spurious warning when activating already-active **default** environment

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#812]
**Describe the bug:**

When activating your default environment in `.zlogin`, any subsequent "login" shells will issue a warning to tell you that your default environment is already active. This is particularly annoying when using `tmux` because it enforces a new "login" shell for every new pane. The previous flox handled this by maintaining that the "default" environment was special, and thus did not warn about double-activations for this environment.

**Steps to reproduce:**
1. create "default" environment in your home directory
2. `flox install tmux` to the environment
3. add following text to your `.zlogin`
    ```
    echo "Activating flox from .zlogin ..." 1>&2
    eval "$(flox activate -d ~/.)"
    ```
4. start a new terminal window with `<command>-n`
5. launch `tmux`

Result: 

```
Activating flox from .zlogin ...
ERROR: Environment 'default at /Users/brantley' is already active
brantley@Michaels-MacBook-Pro ~ % 
```

Expected: 

```
Activating flox from .zlogin ...
brantley@Michaels-MacBook-Pro ~ % 
```

**flox Version (run `flox --version` if possible):**

```
brantley@Michaels-MacBook-Pro ~ % flox --version
Version: 0.3.6-244-g7777245
brantley@Michaels-MacBook-Pro ~ % 
```

**Comment by ghudgins** [comment]
I think we regressed https://github.com/flox/flox/issues/641

**Comment by ysndr** [comment]
kind of expected IMO, flox activate will error if the env is already active..

Shall we add "... except when doung the _eval activation in an rcfile, then just ignore and do (activate silently|nothing (print `true`))"?

**Comment by ghudgins** [comment]
I can no longer add an env to my RC file. the prompt doesn't update, the env doesn't seem activated, and flox thinks it's activated. something is wrong

**Comment by ghudgins** [comment]
my comment is separate from this issue. i'll file it elsewhere

**Comment by ghudgins** [comment]
I suppose the question here is should we show this error message at all...i'm thinking we suppress it to address this case. what do you think @jennymahmoudi?

**Comment by mkenigs** [comment]
I don't think hardcoding $HOME/.flox is the best solution because someone might want to put some other environment in their RC files. Adding a `flox activate --okay-if-activated` or checking if we have a tty would be more general solutions

**Comment by ysndr** [comment]
Yeah I meant (re-)activating if it's going to a tty and is already active or do nothing e.g do an `eval "true"`

**Comment by mkenigs** [comment]
> Yeah I meant (re-)activating if it's going to a tty and is already active or do nothing e.g do an `eval "true"`

I was agreeing! I was responding to:

> The previous flox handled this by maintaining that the "default" environment was special, and thus did not warn about double-activations for this environment.

**Comment by limeytexan** [comment]
Matthew and I spoke about this earlier. A reasonable heuristic might be:

* if activating an environment interactively [with a controlling terminal] then warn about activating an already-active environment (without regard to how it was activated)
* if activating an environment non-interactively [without a controlling terminal] then do not warn about environments that were previously activated non-interactively
    * the thinking here is that if someone activates an env in their dotfiles then subshells will attempt to re-activate that env, and this is not an error
    * but ... if someone activates an env in their dotfiles that was previously activated interactively, then that's probably an exception worth noting

One other comment would be that even when an environment has already been activated there's may still be work to be done by `flox activate`. One example would be the path reordering as required by the Darwin `path_helper` (see https://github.com/flox/flox/issues/811), or setting cacert or locale environment variables required by Nix packaged applications. I don't 100% know that these will be required, but we should keep open the possibility that we will need to do _something_ for this case.

**Comment by mkenigs** [comment]
Discussed in CLI meeting and we'll only print the message if activate is interactive.

**Comment by ysndr** [comment]
@mkenigs to disambiguate "interactive"

* i guess we mean (at least) the definition of "non-interactive" as in `eval "$(flox activate)"` -- non-controlling tty on stdout AND no arguments
* do we broaden this to "any flox activate without controlling tty"  -- "flox activate -- something"?

**Comment by mkenigs** [comment]
I could go either way on the `flox activate -- command`. I don't think @ghudgins cares much on this one so I'd say implementers choice.

**Comment by ysndr** [comment]
and we said no new activation, e.g. no duplicate layers or no duplicate layers if the last layer is already the activated env?

**Comment by mkenigs** [comment]
Yeah I think for now the simplest thing is probably to do nothing. And we can add a `TODO` to re-order PATH and anything else

**Comment by ghudgins** [comment]
verified
