### ISSUE TITLE
activate in an RC file doesn't show the terminal prompt

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#814]
STR:
* `flox init` in `~`
* add `eval "$(flox activate -d ~/)"` to your RC file
* open a new terminal window

Result: no prompt telling you the flox env is active
Expected: flox prompt

**Comment by ysndr** [comment]
which file are you writing this to?
at which end?
On a clean macos (vm) and otherwise empty .zshrc i can't reproduce this with the information provided.

**Comment by ghudgins** [comment]
you're right - this was a "which end" problem. thanks 😅
