### ISSUE TITLE
non-interactive `flox activate` (from dotfile) does not set same env variables as activation from controlling TTY

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#817]
**Describe the bug:**

The output of `flox activate` when invoked without a controlling terminal (e.g. from a user's "dotfile") does not include the setting of important (nix-related) variables that are set in an interactive context.

**Steps to reproduce:**
1. create an environment (can be empty)
2. activate it noninteractively with `flox activate -- sh -c 'echo $FLOX_VERSION'` and note that the variable is not set
3. activate the environment interactively and note that the `$FLOX_VERSION` variable is set within the activated shell
    * same is true for any of `$NIX_SSL_CERT_FILE` on all systems, either of `$NIX_COREFOUNDATION_RPATH` or `$PATH_LOCALE` on Darwin, or `$LOCALE_ARCHIVE` on Linux

```
brantley@Michaels-MacBook-Pro ~ % flox activate -- sh -c 'echo $FLOX_VERSION'

brantley@Michaels-MacBook-Pro ~ % flox activate                              
flox [limeytexan/default] brantley@Michaels-MacBook-Pro ~ % echo $FLOX_VERSION
0.3.6-245-g789d493
flox [limeytexan/default] brantley@Michaels-MacBook-Pro ~ % 
```

**flox Version (run `flox --version` if possible):**
See above.

**Comment by rossturk** [comment]
I am also seeing this behavior within `containerize`:

```
~ % cd $(mktemp -d) && flox init && flox install git
[...]

tmp.dsmS6pLYeD % flox containerize -o - | podman load -q
[...]
Adding manifests...
Done.
Loaded image(s): localhost/flox-env-container:nrzgbbxgc4ffz0h1lbbmp29mr664cvz0

tmp.dsmS6pLYeD % podman run -it localhost/flox-env-container:nrzgbbxgc4ffz0h1lbbmp29mr664cvz0

flox [floxenv] bash-5.2# git clone https://github.com/xterminal86/nrogue.git
Cloning into 'nrogue'...
fatal: unable to access 'https://github.com/xterminal86/nrogue.git/': OpenSSL/3.0.12: error:16000069:STORE routines::unregistered scheme
```

**Comment by mkenigs** [comment]
Container issue hasn't been fixed

**Comment by ysndr** [comment]
The export for a container are not set in the `activate` code within flox but are baked into the container.
Lets split the container part out as a separate ticket, as only the variables are the same but the logistics are different.

**Comment by ysndr** [comment]
Closing in favor of #1130, to tackle the docker case.
