### ISSUE TITLE
flox pull with miss-matched architectures offers options

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#823]
# Acceptance Criteria

_flox pull on a miss-matched system offers resolution_
**Given** I have an environment in floxhub (`ghudgins/singlearch`) that has only `aarch64-linux` in the manifest under `[options.systems]`
**And** I am on an `aarch64-darwin` machine
**When** I `flox pull ghudgins/singlearch`
**Then** I see an interactive choice:

```
! This environment is not yet compatible with your system (aarch64-darwin).
> Don't pull this environment
  Pull this environment anyway and add `aarch64-darwin` to the supported systems list.  
[↑↓ to move, enter to select, type to filter]
```

_Pull anyway option_
**And When** a user picks "  Pull this environment anyway and add `aarch64-darwin` to the supported systems list."
**Then** flox adds `aarch64-darwin` to the manifest in a new local generation (not yet pushed)
**And** the system attempts to build the environment
**And When** the environment fails to build
**Then** the user still gets the environment's .flox 
**And** the user can attempt to fix it with `flox edit`

_Add a system has an explicit option_
**When** I `flox pull --add-system ghudgins/cli`
**Then** I get the environment
**And** I don't see the interactive prompt

**Comment by mkenigs** [comment]
What do we do if appending your system to the supported systems fails to lock?

**Comment by ghudgins** [comment]
added additional AC - I think we should give the user the environment anyway so they could try to add support.

**Comment by ysndr** [comment]
Can we start this with an explicit mode?
I.e. have a flag `--amend-systems` (bike sheddable) to do the "pull anyway" explicitly?

We figured using `--force` for this would conflate the usage of force-(git)-pull and force-system

**Comment by ghudgins** [comment]
I agree we should have explicit options for this. can we still offer interactive on the naked flox pull?

i'm not too worried about the generation as the user that owns this environment would flox push it back up.

**Comment by ysndr** [comment]
Sure adding interactivity on top works, just saying we should start with the flag, i.e. for testing and scripting

**Comment by ghudgins** [comment]
hangs on my pi 
<img width="879" alt="image" src="https://github.com/flox/flox/assets/5465514/d00fc692-4f1b-4735-8e8f-a03d90ff2568">

**Comment by ghudgins** [comment]
pkgdb is crashing

<img width="897" alt="image" src="https://github.com/flox/flox/assets/5465514/2fc9b8d8-6f97-42f6-bfbf-7a5a507669b7">

**Comment by ghudgins** [comment]
seeing this work might be dependent on https://github.com/flox/flox/issues/839 or me getting a beefier linux machine.

would be good to print a different message in the case of a build error

**Comment by ghudgins** [comment]
specifically: this issue is blocked because I can crash an 8GB RAM aarch64-linux machine by `flox pull ghudgins/default` and choosing to "Try anyway" on a aarch64-linux

**Comment by ghudgins** [comment]
I found a way to test this. can we extend the coverage of this feature to include pulling an existing environment that has an unsupported system error? 

STR:
* be on a mac
* `flox pull ghudigns/multi-arch`

Result: nix error for unsupported system type
Expected: a choice to pull the env anyway

Seems I can only get the prompt if the environment is missing the system in `[options]` but I'd _also_ like it if some package goes wrong with this error. this might be a separate issue

**Comment by ghudgins** [comment]
was able to test. will log the above in its own issue
