### ISSUE TITLE
flox activate -r with miss-matched architectures

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#824]
# Acceptance Criteria

**Given** I have an environment in floxhub (`ghudgins/singlearch`) that has only `aarch64-linux` in the manifest under `[options.systems]`
**And** I am on an `aarch64-darwin` machine
**When** I `flox activate -r ghudgins/singlearch`
**Then** I see an error message:
```
ERROR: ❌ This environment is not yet compatible with your system (aarch64-darwin). 

Use `flox pull --add-system ghudgins/singlearch' to update and verify this environment on your system.  
````

**Comment by ghudgins** [comment]
related to https://github.com/flox/flox/issues/823

**Comment by ysndr** [comment]
Same here, i think it should be :
> `You can try to add support for your system with 'flox pull --amend-system ghudgins/singlearch'`

**Comment by ghudgins** [comment]
@ysndr I get a weird error out of flox on this

`Version: 0.3.6-283-ge4618f1`

<img width="1133" alt="image" src="https://github.com/flox/flox/assets/5465514/54e5e243-c66e-4511-9744-705fed8ffa14">

**Comment by ghudgins** [comment]
`flox activate -r ghudgins/linuxonly`

**Comment by ysndr** [comment]
Issue for that error: #948, fixing in #949

**Comment by ghudgins** [comment]
really nice work! it's much better now
