### ISSUE TITLE
flox install/uninstall/edit choice interactive prompt is chatty

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#833]
**When** I am using a default environment in my RC file
**And** I am working on an environment that layers on from a project
**I need** a way to tell flox to ignore the home / RC file defined enviornment
**So I can** avoid having to see the interactive prompt when installing/uninstalling/editing project environments

# Acceptance Criteria

don't ask for the default environment: any active default environment is only the target of a naked install/uninstall/edit command if the user is in home

**Given** I have an environment named `default` environment active in my rc file
**And** I in `/project` directory that contains a `.flox`
**When** I `flox install` (or uninstall or search, etc)
**Then** I do not see the prompt

**Given** I have a `project` directory that has a `.flox
**And** I in `project/package` directory that contains a `.flox`
**And** I am in the `project/package` directory
**When** I `flox install` (or uninstall or search, etc)
**Then** I see a prompt

**Comment by aakropotkin** [comment]
```console
$ flox activate --quiet
```

**Comment by stahnma** [comment]
I'd like to have some way of not prompting for interaction per directory. Like "remember that I don't want you to ask me for every search, list, install" in this directory.

**Comment by ghudgins** [comment]
yeah I don't think passing an option only is an acceptable solution. I want the 'naked commands' experience to be a good one

**Comment by ghudgins** [comment]
@stahnma  do you think we can start by not prompting for the default environment before we do config? (if you're in a default environment don't prompt about the active shell...require the user be in `~` to modify)

**Comment by ghudgins** [comment]
okay - absent more discussion, I'd like the scope of this ticket to be don't prompt interactively for default environment. the only way to edit a default environment is to either explicitly option for it or be in the home directory. the "which target" prompt will only apply when stacking project-style environments (i.e. monorepos--"do you want this in the base env or the package-specific env")

I think that's good to me!

**Comment by ysndr** [comment]
implemented in https://github.com/flox/flox/pull/1034 with some details:

* `default` is preferred by _all_ commands that perform environment detection

Making a less consistent thing  is actually more work, for what is probably a worse experience, lmk if that is wrong assumption and we should make it more specific.

* when the default is used we print a message

Testing this i found it rather annoying that a different env is used quietly.
I added a warning in a separate commit.
We can change the wording, or remove it entirely, again, let me know

@ghudgins, @jennymahmoudi

**Comment by mkenigs** [comment]
> implemented in #1034 with some details:
> 
>     * `default` is preferred by _all_ commands that perform environment detection
> 
> 
> Making a less consistent thing is actually more work, for what is probably a worse experience, lmk if that is wrong assumption and we should make it more specific.
> 
>     * when the default is used we print a message
> 
> 
> Testing this i found it rather annoying that a different env is used quietly. I added a warning in a separate commit. We can change the wording, or remove it entirely, again, let me know
> 
> @ghudgins, @jennymahmoudi

Not sure if I'm confused, but isn't that the opposite of "the only way to edit a default environment is to either explicitly option for it or be in the home directory"? But in that PR, if I have default activated and `.flox` in the current directory, it uses default

**Comment by ghudgins** [comment]
@mkenigs I was expecting what you described. we _ignore_ the active environment in prompting when the active environment is 'default'

the only way to install/edit default is to explicitly option for it or be in your home directory (where the default is)

**Comment by ysndr** [comment]
Yeah I got that wrong..,
should be the right way around now on #1034

**Comment by ghudgins** [comment]
looks good now after testing on the branch this morning. this can close once it's through code review
