### ISSUE TITLE
flox doesn't run on 4GB (8GB?) of RAM: search encountered an error: error running pkgdb: couldn't initialize read-only package database

### ISSUE THREAD

**Issue by stahnma** [flox/flox#839]
# Acceptance Criteria
* investigate why our memory requirements are 4GB+ 
* attempt to reduce the requirements
* document the system requirements 

**Describe the bug:**

On brand new setup. (I had removed flox, rm -rf .flox and .cache/flox and .config/flox). 

This is a 2 core 4 GB of RAM linode running Fedora 39. 

```
stahnma@funk:~$ flox init
✨ Created environment default (x86_64-linux)

Next:
  $ flox search <package>    <- Search for a package
  $ flox install <package>   <- Install a package into an environment
  $ flox activate            <- Enter the environment

stahnma@funk:~$ flox search tailscale
ERROR: search encountered an error: error running pkgdb: couldn't initialize read-only package database
```

📓 This one took probably 8-9 minutes. 

📓  Immediately after

```
stahnma@funk:~$ time flox search tailscale
ERROR: search encountered an error: error running pkgdb: couldn't initialize read-only package database

real	0m25.483s
user	0m0.014s
sys	0m0.026s
```

## Ok, let's try removing .cache/flox again and see if it might work.
```

stahnma@funk:~$ rm -rf .cache/flox/
stahnma@funk:~$ time flox search tail
ERROR: No packages matched this search term: tail

real	5m0.344s
user	0m30.384s
sys	0m33.865s

stahnma@funk:~$ time flox search neovim
ERROR: search encountered an error: error running pkgdb: couldn't initialize read-only package database

real	0m25.349s
user	0m0.013s
sys	0m0.017s
```

Ok, let's look more into why it thinks it's read-only. 

```
stahnma@funk:~$ ll -a | grep cache
drwxr-xr-x.   5 stahnma stahnma      4096 Jan 24 02:42 .cache
stahnma@funk:~$ cd .cache
stahnma@funk:~/.cache$ ls
flox  go-build  nix
stahnma@funk:~/.cache$ cd flox
stahnma@funk:~/.cache/flox$ ls
metrics-events-v2.json  metrics-lock  pkgdb-v2  process
stahnma@funk:~/.cache/flox$ cd ^C
stahnma@funk:~/.cache/flox$ ll -a
total 20
drwxr-xr-x. 4 stahnma stahnma 4096 Jan 24 02:42 .
drwxr-xr-x. 5 stahnma stahnma 4096 Jan 24 02:42 ..
-rw-r--r--. 1 stahnma stahnma  727 Jan 24 02:47 metrics-events-v2.json
-rw-r--r--. 1 stahnma stahnma    0 Jan 24 02:47 metrics-lock
drwxr-xr-x. 2 stahnma stahnma 4096 Jan 24 02:42 pkgdb-v2
drwxr-xr-x. 2 stahnma stahnma 4096 Jan 24 02:48 process
stahnma@funk:~/.cache/flox$ cd pkgdb-v2/
stahnma@funk:~/.cache/flox/pkgdb-v2$ ls -al
total 14200
drwxr-xr-x. 2 stahnma stahnma     4096 Jan 24 02:42 .
drwxr-xr-x. 4 stahnma stahnma     4096 Jan 24 02:42 ..
-rw-r--r--. 1 stahnma stahnma 14561280 Jan 24 02:43 c0c128b5e5824f83016a9a311e0a58200f566efe3111422624ac1b642f7094b4.sqlite
-rw-r--r--. 1 stahnma stahnma    42496 Jan 24 02:42 c0c128b5e5824f83016a9a311e0a58200f566efe3111422624ac1b642f7094b4.sqlite-journal
stahnma@funk:~/.cache/flox/pkgdb-v2$
```
Nothing out of the ordinary there.  Do I just assume it's selinux? I'mma take a look at selinux. 

📓 Nothing from `ausearch`

📓 Reboot, just for fun.

Same results. I guess I'll run with more debugging.

```
stahnma@funk:~$ time flox search --debug -vvvv tail
[DEBUG] [flox::config] `$FLOX_CONFIG_HOME` not set, using "/home/stahnma/.config/flox/"
[DEBUG] [flox::utils::init] no default user nix.conf found
[DEBUG] [flox::utils::init::metrics] Attempting to read own UUID from file
[DEBUG] [flox::utils::metrics] pushing entry to metrics buffer: MetricEntry { subcommand: Some("search"), extras: {"search_term": "tail"}, timestamp: 2024-01-24 3:01:42.541804001 +00:00:00, flox_version: "0.3.6-255-gdd6d765", os_family: Some("Linux"), os_family_release: Some("6.6.11-200.fc39.x86_64"), os: Some("fedora"), os_version: Some("39"), empty_flags: [] }
[DEBUG] [flox::commands::search] performing search for term: tail
[DEBUG] [flox_rust_sdk::models::environment] looking for .flox: starting_path=/home/stahnma/.flox
[DEBUG] [flox_rust_sdk::models::environment] .flox found: path=/home/stahnma/.flox
[DEBUG] [flox::utils::search] using environment default at /home/stahnma
[DEBUG] [flox::commands] detected concrete environment type: path
[DEBUG] [flox_rust_sdk::models::environment::path_environment] attempting to open .flox directory: /home/stahnma/.flox
[DEBUG] [flox::utils::search] checking lockfile: path=/home/stahnma/.flox/env/manifest.lock
[DEBUG] [flox::utils::search] lockfile exists
[DEBUG] [flox_rust_sdk::models::environment] global manifest path is /home/stahnma/.config/flox/global-manifest.toml
[DEBUG] [flox::utils::search] search params raw: SearchParams { manifest: Some(Path("/home/stahnma/.flox/env/manifest.toml")), global_manifest: Path("/home/stahnma/.config/flox/global-manifest.toml"), lockfile: Path("/home/stahnma/.flox/env/manifest.lock"), query: Query { name: None, pname: None, version: None, semver: None, match: None, match_name: None, match_name_or_rel_path: Some("tail"), limit: Some(10) } }
[DEBUG] [flox_rust_sdk::models::search] running search command "/nix/store/r7v15j2wr75s41qh7xs239vsjxhnp6vq-flox-pkgdb-0.1.0/bin/pkgdb" "search" "--quiet" "--ga-registry" "{\"manifest\":\"/home/stahnma/.flox/env/manifest.toml\",\"global-manifest\":\"/home/stahnma/.config/flox/global-manifest.toml\",\"lockfile\":\"/home/stahnma/.flox/env/manifest.lock\",\"query\":{\"match-name-or-rel-path\":\"tail\",\"limit\":10}}"
⠤ Searching for packages...                                             This may take a while the first time you run it.[DEBUG] [flox_rust_sdk::models::search] record = Error(PkgDbError { exit_code: 113, category_message: "error running pkgdb", context_message: Some(ContextMsgError { message: "couldn't initialize read-only package database", caught: None }) })
[ERROR] [flox] search encountered an error: error running pkgdb: couldn't initialize read-only package database

real	0m25.344s
user	0m0.008s
sys	0m0.017s
```

📓  Now clearing everything again and seeing full debug output. 

```
stahnma@funk:~$ rm -rf .flox/ .cache/flox/ .config/flox/
stahnma@funk:~$ time flox search --debug -vvv vim
[DEBUG] [flox::config] `$FLOX_CONFIG_HOME` not set, using "/home/stahnma/.config/flox/"
[DEBUG] [flox::utils::init] no default user nix.conf found
[DEBUG] [flox::utils::init::metrics] Attempting to read own UUID from file
[INFO] [flox_rust_sdk::flox] Updating nix.conf: "/home/stahnma/.config/flox/nix.conf"
[DEBUG] [flox::utils::metrics] pushing entry to metrics buffer: MetricEntry { subcommand: Some("search"), extras: {"search_term": "vim"}, timestamp: 2024-01-24 3:03:51.938334582 +00:00:00, flox_version: "0.3.6-255-gdd6d765", os_family: Some("Linux"), os_family_release: Some("6.6.11-200.fc39.x86_64"), os: Some("fedora"), os_version: Some("39"), empty_flags: [] }
[DEBUG] [flox::commands::search] performing search for term: vim
[DEBUG] [flox_rust_sdk::models::environment] looking for .flox: starting_path=/home/stahnma/.flox
[DEBUG] [flox_rust_sdk::providers::git] "/nix/store/f7b2yl226nbikiv6sbdhmaxg2452c8h5-git-minimal-2.42.0/bin/git" "-C" "/home/stahnma" "rev-parse" "--is-bare-repository"
[DEBUG] [flox::utils::search] no environment found
[DEBUG] [flox_rust_sdk::models::environment] global manifest lockfile path is /home/stahnma/.config/flox/global-manifest.lock
[DEBUG] [flox_rust_sdk::models::lockfile] Global lockfile does not exist, updating to create one
[DEBUG] [flox_rust_sdk::models::environment] global manifest lockfile path is /home/stahnma/.config/flox/global-manifest.lock
[DEBUG] [flox_rust_sdk::models::lockfile] no existing lockfile found
[DEBUG] [flox_rust_sdk::models::environment] global manifest path is /home/stahnma/.config/flox/global-manifest.toml
[DEBUG] [flox_rust_sdk::models::lockfile] updating lockfile with command: "/nix/store/r7v15j2wr75s41qh7xs239vsjxhnp6vq-flox-pkgdb-0.1.0/bin/pkgdb" "manifest" "update" "--ga-registry" "--global-manifest" "/home/stahnma/.config/flox/global-manifest.toml"
[DEBUG] [flox_rust_sdk::models::lockfile] writing lockfile to /home/stahnma/.config/flox/global-manifest.lock
[DEBUG] [flox_rust_sdk::models::environment] global manifest path is /home/stahnma/.config/flox/global-manifest.toml
[DEBUG] [flox::utils::search] search params raw: SearchParams { manifest: None, global_manifest: Path("/home/stahnma/.config/flox/global-manifest.toml"), lockfile: Path("/home/stahnma/.config/flox/global-manifest.lock"), query: Query { name: None, pname: None, version: None, semver: None, match: None, match_name: None, match_name_or_rel_path: Some("vim"), limit: Some(10) } }
[DEBUG] [flox_rust_sdk::models::search] running search command "/nix/store/r7v15j2wr75s41qh7xs239vsjxhnp6vq-flox-pkgdb-0.1.0/bin/pkgdb" "search" "--quiet" "--ga-registry" "{\"global-manifest\":\"/home/stahnma/.config/flox/global-manifest.toml\",\"lockfile\":\"/home/stahnma/.config/flox/global-manifest.lock\",\"query\":{\"match-name-or-rel-path\":\"vim\",\"limit\":10}}"
[DEBUG] [flox::commands::search] search call exit status: signal: 9 (SIGKILL)
[DEBUG] [flox::commands::search] printing search results as user facing
[ERROR] [flox] No packages matched this search term: vim

real	2m6.591s
user	0m31.179s
sys	0m16.271s
```

Put the search query into a json file. Validate it. 
```

stahnma@funk:~$ /nix/store/r7v15j2wr75s41qh7xs239vsjxhnp6vq-flox-pkgdb-0.1.0/bin/pkgdb search --ga-registry 1.json
error running pkgdb: couldn't initialize read-only package database
```

⚠️  I'm not positive that is the correct syntax. I tried just using the output from the debug logs but that kept getting JSON parse errors. So, I tried to clean it up and pass a file. It says I can pass a file, but it's not clear exactly how. I tried `file:///` first, and that seemed to break horribly, so then tried just the filename to see what happened. It also seems like if I pass `--debug` or `-vvv` to flox, it should remove the `--quiet` invocation from pkgdb. 

📓 Tried `chmod 755 $HOME/.config` to see if there was something like that blocking it. Nope.

Using `strace` and other tools to poke around, I didn't see much that gave me a clue. 

If you want the complete syscall trace, I have it. It's 4.7MB zipped and 165MB unzipped. I'm not sure it's super useful, but if so let me know. 

I may be getting OOM killed -- at least some of the time. I wouldn't expect that on a system with 4GB of ram and only using about 500MB when not doing flox operations. 

While running, I switched to another tab ( and it was barely responding) 

```
               total        used        free      shared  buff/cache   available
Mem:         4007144     3910768       96376           8       27520       96376
Swap:         524284      524236          48
```

Looks almost certainly like an oom-kill on a 4GB box. 

```
stahnma@funk:~$ sudo grep -i oom /var/log/messages | tail -7
Jan 24 03:48:47 funk kernel: gmain invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=0
Jan 24 03:48:47 funk kernel: oom_kill_process+0xf9/0x190
Jan 24 03:48:47 funk kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jan 24 03:48:47 funk kernel: [    657]   999   657     4060       32    69632      192          -900 systemd-oomd
Jan 24 03:48:47 funk kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-13802.slice/session-3.scope,task=pkgdb,pid=22292,uid=13802
Jan 24 03:48:47 funk kernel: Out of memory: Killed process 22292 (pkgdb) total-vm:4320380kB, anon-rss:3774660kB, file-rss:128kB, shmem-rss:0kB, UID:13802 pgtables:8304kB oom_score_adj:0
Jan 24 03:48:47 funk systemd[1]: session-3.scope: A process of this unit has been killed by the OOM killer.
```

Result: 

Unable to use flox at all. 

Expected: 

I literally just wanted to setup tailscale. :( 

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

Version: 0.3.6-255-gdd6d765

# Possible solutions

* scope evaluations, trade more time for memory

**Comment by ghudgins** [comment]
while we know the issue will improve with our catalog plan, it would be good to take action in the near term to decrease the memory requirements for these operations such that they can run on smaller machines. flox's memory requirements are somewhere above 4GB and less than 8GB right now

**Comment by ghudgins** [comment]
scope an investigation into short term solutions.

**Comment by tomberek** [comment]
Some data points of maximum resident size:
- `nix search nixpkgs ^ --no-eval-cache` ~= 3.8GB
- `nix-eval-jobs --flake nixpkgs#legacyPackages.x86_64-linux --max-memory-size 2048` ~= 2.1GB
- `pkgdb scrape --force -d test.db nixpkgs legacyPackages` ~= 3.6GB
- `flox search hello` ~= 3.7 GB
- `pkgdb scrape --force -d test.db nixpkgs legacyPackages x86_64-linux pythonPackages` ~= 0.6 GB
- `pkgdb scrape --force -d test.db nixpkgs legacyPackages x86_64-linux perlPackages` ~= 0.25 GB
- `pkgdb scrape --force -d test.db nixpkgs legacyPackages x86_64-linux haskellPackages` ~= 0.84 GB

Note: the nix-eval-jobs "trick" is to spawn eval workers, then kill them if they exceed their memory, then respawn them to keep working on the queue.

sub-package sets are quite expensive

### Ideas
- Our search does recurseForDerivations and keeps all resident things in memory as it does so. Instead, perform each level of recursion as an independent evalutaion + transaction, allowing for less memory usage, GC in-between, etc.
-  split the Todos queue to be worked on by worker(s) with an equivalent to "max-memory-size" as an en-masse GC mechanism.

**Comment by zmitchell** [comment]
- When I was doing the perf investigation I had thought about splitting the scrape up into chunks for different workers to do (eg one worker takes `pythonPackages`, one takes `haskellPackages`, etc). I think the better approach would be doing the first idea mentioned above e.g. chunking the scrape in-process so that we have a smaller memory footprint at any point in time.
- Using workers will make the database locking problem much worse, so I strongly recommend against that.
- We can also do a little bit of investigation to optimize the memory footprint. I don't know that we've spent much time at all on that. A very basic idea is to check the number of attributes you get back under a package set and chunk that as well so that you aren't holding the entire package set in memory.

**Comment by ghudgins** [comment]
https://github.com/flox/flox/issues/823 also has an OOM error when pulling / building a pulled environment. looks related but the system requirements are higher on that command

**Comment by mkenigs** [comment]
Do you have a file with `journal` hanging around in `~/.cache/flox/pkgdb-v2`? If `pkgdb` get's OOM killed sometimes it leaves behind a lock

**Comment by ghudgins** [comment]
yes, I do. should I remove it?

**Comment by ghudgins** [comment]
removed it and watched the device reach an OOM 
<img width="903" alt="image" src="https://github.com/flox/flox/assets/5465514/93aa7b8a-b472-46b6-94eb-b02797e884dc">

str:
* `rm -r .cache/flox/pkgdb-v2`
* be on linux
* `flox pull -r ghudgins/example-project`

**Comment by ghudgins** [comment]
updated specifics: I don't ever witness flox consuming all of the memory of my system when testing with `flox search`. I observe total system crash on a separate issue (#823). I see "Failed to initialize" error _occasionally_ and sometimes on upgrade or blowing away the cache I can recover the search functionality. I don't witness the memory usage run away.

**Comment by aakropotkin** [comment]
The error message we're seeing and the memory consumption are separate issues.

Is this ticket asking to fix both?
Should this be split into two issues?

The error message may caused by the DB retry timeout being shorter than the average time spent fetching, evaluating, and scraping all 4 systems; but investigating the _real cause_ is something separate from the memory consumption issue we're investigating.

**Comment by aakropotkin** [comment]
I agree with the approach @tomberek outlined and I think we'll be doing something along these lines using `fork` in `pkgdb`.

**Comment by billlevine** [comment]
There seem to be two separate memory consumption issues.  Recording some findings before moving on.

The symptoms are as follows and may be related.
1. Running `valgrind --tool=massif` profiles *heap memory*.  Running `pkgdb` using this shows around a 400mb leak for each *input* that is scraped.  An environment that references multiple nixpkgs revs will grow for each, accumulating that 400mb.
2. The BoehmGC used in the nix library uses `mmap` directly and serves up allocations on it's own and thus does NOT show up in the valgrind profiles.  Setting `--pages-as-heap=yes` show ALL pages allocated by the process.  Using this and a simple `pkgdb search --match-name hello --ga-registry` grows to 4.3gb.  At least 3.7gb is allocated in `GC_unix_mmap_get_mem` in the BoehmGC libs.

Running a `flox search helllo` in a docker container constrained to 4gb, works, but 3gb does not.  Peak RSS for a 6gb container matches this 4.3gb shown in point 2 above.  It's likely the 4.3gb will grow with additional inputs, but I haven't looked at that yet.  It's possible forking will still work, if done at a granular enough level (e.g. lower than per input).  

I think the first goal might be a simple search with a peak RSS less than 1gb?  @aakropotkin, I think you were playing with the GC settings, maybe prove them out w/o the fork and using the `--pages-as-heap` setting or just use `time` with the peak RSS output and see if that decreases with your settings?
