### ISSUE TITLE
flox init reads requirements.txt and suggests installation/config

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#844]
# Acceptance Criteria

**Given** the project has `requirements.txt` file
**And** i'm in the project directory
**When** I `flox init`
**Then** I see an interactive prompt

```
Flox detected a requirements.txt

Python projects typically need:
* python, pip
* A python venv to install dependencies

Would you like Flox to apply the standard python environment? 
You can always revisit the environment's declaration with 'flox edit'

>Yes 
No
Show environment manifest

```

_The option version of this functionality `--auto-setup`_

# Details

Suggested installs

```
python311Packages.pip ?
```

be inspired by: https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/interpreters/python/hooks

Suggested shell hook
```
        # this was automatically generated...
        if [ ! -d bin ]; then
                echo -n "Creating python virtual environment in {location}"
                python -m venv .
        fi

        echo -n "Activating the python virtual environment"
        . bin/activate
	
	echo "Installing requirements.txt dependencies"
	pip install -r requirements.txt

      # Write additional setup steps here 
```

**Comment by tomberek** [comment]
A few pip setups that have been pretty good that show the common needs of such a feature:
- https://github.com/cachix/devenv/blob/main/src/modules/languages/python.nix#L20-L47
- https://github.com/flox/minicapacitor/blob/__functor/flake.nix#L207-L230
- https://github.com/flox/etc-profiles/blob/main/profile.d/0500_python3.sh
- a conda example: https://nixos.wiki/wiki/Python#conda
- worth reviewing: https://github.com/nix-community/pyproject.nix

**Comment by ghudgins** [comment]
todo: write AC this week @ghudgins and @jennymahmoudi

**Comment by stahnma** [comment]
https://github.com/jetpack-io/devbox/tree/main/internal/initrec is also some prior art.

**Comment by mkenigs** [comment]
Running through some of these options, I think it's pretty clear our first step should just be to add venv + pip exactly as @ghudgins described. Tickets:
- [ ] https://github.com/flox/flox/issues/1027
- [ ] https://github.com/flox/flox/issues/1028

Notes on options linked above:

>     * https://github.com/cachix/devenv/blob/main/src/modules/languages/python.nix#L20-L47
venv + pip
>     * https://github.com/flox/minicapacitor/blob/__functor/flake.nix#L207-L230
>       * setup that allows for pip usage, but nothing else is automatic
Uses PIP_PREFIX

>     * https://github.com/flox/etc-profiles/blob/main/profile.d/0500_python3.sh
>       * adds .flox-specific portions to PYTHONPATH
Just sets PYTHONPATH

>     * a conda example: https://nixos.wiki/wiki/Python#conda
Not addressing conda in this ticket
> 
>     * worth reviewing: https://github.com/nix-community/pyproject.nix
Parses requirements.txt and then grabs stuff out of nixpkgs with pythonWithPackages

>     * Upstream hooks for various situations: https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/interpreters/python/hooks
venv + pip https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/hooks/venv-shell-hook.sh



>     * SDXL: https://www.notion.so/floxdev/Stable-diffusion-3ab52661da6e4ffcb81fe24946de78ce?pvs=4
venv + pip

>     * floxdocs: https://github.com/flox/floxdocs/pull/470/files#diff-3486ebd6b7c3165f69d0cd02be3307f07d937b34f25b943825ae3fe361de8125

venv + pip

**Comment by mkenigs** [comment]
@ghudgins ready for review

**Comment by ghudgins** [comment]
looks good on the branch!

**Comment by mkenigs** [comment]
Closing because it merged
