### ISSUE TITLE
wrap all `-h` pages to 80 characters

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#853]
# Acceptance criteria

1. update help across the product to wrap at 80 characters:

`flox search -h`
Result: 
<img width="960" alt="image" src="https://github.com/flox/flox/assets/5465514/a538be5f-9a88-4db5-93df-096c541ce0de">

Expected: wrapping on help commands at 80 characters

@ysndr could use input on effort for this

**Comment by ysndr** [comment]
though it does look like we _do_ have some wrapping, just at the odd width of 104 characters 🤔:
<img width="850" alt="image" src="https://github.com/flox/flox/assets/7040031/1292dfa4-c633-4c8d-a3aa-29ae6db05ed6">

**Comment by ysndr** [comment]
<img width="1606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51757206bba63981548d054e165aa9e4387734ea/image.png" alt="image.png" />

**Comment by ghudgins** [comment]
in the near future we can do this. @ysndr will put in sprint when it's time

**Comment by ghudgins** [comment]
verified on branch

**Comment by stahnma** [comment]
@ghudgins with the PR merged can this be closed?
