### ISSUE TITLE
[dev-env]: BUG: default `devShell` depends on `flox-pkgdb`

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#861]
**Describe the bug:**

We have a regression in our `pkgs/*/default.nix` or `shells/*/default.nix` definitions which is causing `nix develop` to build `flox-pkgdb` as a dependency of the development shell.

**Steps to reproduce:**
1. `nix develop`

Result: 
Triggers a `nix` build of `flox-pkgdb`

Expected: 
Does NOT trigger a `nix` build of `flox-pkgdb`

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

**Comment by tomberek** [comment]
This is most likely due to the inputsFrom, line. pkgdb is one of the inputs from flox-cli.
https://github.com/flox/flox/blob/main/shells/default/default.nix#L40

**Comment by tomberek** [comment]
need:
```
(flox-cli.override {
          flox-pkgdb = null;
          flox-env-builder = null;
        })
```

**Comment by aakropotkin** [comment]
> need:
> 
> ```
> (flox-cli.override {
>           flox-pkgdb = null;
>         })
> ```

The actual fix is quite a bit longer - use what we drafted together on Spatial.

Please add CONTRIBUTING docs explaining the chamges needed to "add a new build time artifact to test wrappers and build system". @garbas may be helpful on design rationale for those patterns.

**Comment by tomberek** [comment]
fixed by: https://github.com/flox/flox/pull/874/files
