### ISSUE TITLE
user missing [options] can't fix their enviornments

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#870]
STR:
* delete your options
* push the environment
* `flox list -r ghudgins/no-options-env`

Result: nothing
Expected:

details about the packages installed

```
gh.path = "gh"
git.path = "git"
bat.path = "bat"
nmap-unfree.path = "nmap-unfree"
tree.path = "tree"
jless.path = "jless"
coreutils.path = "coreutils"
imgcat.path = "imgcat"
neovim.path = "neovim"
textplots.path = "textplots"
subfinder.path = "subfinder"
eureka-ideas.path = "eureka-ideas"
graph-cli.path = "graph-cli"
html5validator.path = "html5validator"
ripgrep.path = "ripgrep"
sharing.path = "sharing"
whatweb.path = "whatweb"
tmux-sessionizer.path = "tmux-sessionizer"
tmux.path = "tmux"
```

oddly the `-c` option works fine. This is something unique to this environment it seems

**Comment by mkenigs** [comment]
Smells like a cross system bug. That environment doesn't have any systems in the manifest

**Comment by ghudgins** [comment]
ah nice. we made a change and this metadata lags. that answer that.

**Comment by ghudgins** [comment]
completed by other tickets that added the "pull anyway" functionality
