### ISSUE TITLE
flox list -r does nothing on linux

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#887]
STR:
* be on linux (this is `aarch64-linux`) and don't have this environment pulled / built
* `flox list -r ghudgins/default`

Result: nothing
Expected (at the time of this writing):
```
almonds: almonds (1.25b)
awscli: awscli (1.30.2)
gitFull: gitFull (2.42.0)
gnupg: gnupg (2.4.1)
inetutils: inetutils (2.5)
vim: vim (9.0.2116)
```

note: works on macos.

**Comment by ysndr** [comment]
```
$ flox list --config -r ghudgins/default
...

# An environment that works on one system is guaranteed to work on the
# same type of system,
# but other systems may not have the same packages available, etc.
# In order to use the environment on a system you must explicitly
# add it to this list.

[options]
systems = ["aarch64-darwin"]
```

Flox list only lists those packages installed/locked for the current system.
The environment does not lock `aarch64-linux` thus, does not show _any_ packages.

**Comment by ghudgins** [comment]
I see. removed bug label. would be good to consider an enhancement at some point to tell the user that there's nothing in here for the current system but you can see the manifest with `-c`

**Comment by ghudgins** [comment]
verified
