### ISSUE TITLE
[pkgdb/doc]: (SPIKE) Document existing strategy for deduplicating revisions in lockfiles

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#895]
Investigate and Document the existing `pkgdb manifest lock` strategy ( especially for updates ) for de-duplicating `nixpkgs` revisions.

Consider how the following cases differ when adding a new package and/or new system :
- no previous lockfile, no global lockfile
- no previous lockfile, global lockfile
- previous lockfile with multiple groups and multiple `nixpkgs` revs, no global lockfile
- previous lockfile with multiple groups and multiple `nixpkgs` revs, global lockfile

## Outputs

1. Some sort of notion document, power-point slides, or control flow diagram that is accessible to team members outside of ENG is ideal.
  a. This document could be a useful jumping off point ( potentially update it ) https://www.figma.com/file/XfKHgzXLqH2UivO9g5eCpB/Lockfile-Ops?type=whiteboard&t=sBws49VMHzOcik2c-0
3. Tickets to potentially optimize this de-duplication strategy ( if any ).

**Comment by mkenigs** [comment]
Just a note: `pkgdb manifest` doesn't currently have a concept of environment vs global lockfile; it accepts just one lockfile currently
