### ISSUE TITLE
[buildenv/opt]: skip evaluation of packages which record `packages.<SYSTEM>.<IID>.cache.out-path`

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#900]
To be completed after: https://github.com/flox/flox/issues/896

**Describe the feature:**
If a package carries `packages.<SYSTEM>.<IID>.cache.out-path` information, try to substitute the package in any available `nix` stores ( caches ) before attempting evaluation or builds.

**Describe a use case of this feature:**
Faster `flox activate`.

**Acceptance criteria:**
1. Do not require `out-path` field to be present.
2. Do not require `caches` field to be present.
3. Implement as an extension of C++ `buildenv` routines.
4. Use existing `nix` interfaces to check caches.

**Hints**
```C++
  bool
isSubstitutable( std::string_view storePath )
{
  for ( const nix::ref<nix::Store> & s : nix::getDefaultSubstituters() )
    {
      if ( s->isValidPath( s->parseStorePath( storePath ) ) ) { return true; }
    }
  return false;
}
```

**Comment by mkenigs** [comment]
@aakropotkin does this gain us much after the first eval? E.g. if I `flox install hello && flox edit # change an env var` will the edit be much faster with this optimization, or are we already reasonably fast because of eval cache?

If we're already reasonably fast because of eval cache, then isn't this mostly just speeding up `flox pull`?

**Comment by aakropotkin** [comment]
Yes this optimizes for people pulling and activating without modifications

**Comment by aakropotkin** [comment]
Deferring to later sprint:

This change has a larger scope than initially anticipated.

Requires changes to _remote environments_ and cross-language interface changes that essentially double the amount of effort.

Will revisit in the near future.
