### ISSUE TITLE
flox pull offers interactive prompt when a package is unsupported

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#902]
**When** an environment is already marked for both systems
**And** someone has installed something only compatible to one system
**I need** flox pull to allow me to pull the environment anyway
**So I can** fix the issue without having to match system types with the package that's problemmatic

# Acceptance Criteria

**Given** an environment has two systems in its manifest.options (linux & darwin)
**And** from linux, a package was pushed to floxhub that doesn't work on darwin (gdb)
**When** from darwin, I `flox pull` this environment (`flox pull ghudgins/multi-arch`)
**Then** I see the interactive prompt:

```
❌  ERROR: The environment you are trying to pull could not be built locally.
! 'gdb' is unavailable on your system (aarch64-darwin)
  Don't pull this environment.
> Pull this environment anyway, 'flox edit' to address issues
```

**Comment by ysndr** [comment]
is this specific to evaluation failures due to the supported system, or any eval/build errors?

**Comment by ysndr** [comment]
We are also (again) running into a separation issue, between pkgdb errors and flox messaging.

* Pkgdb errors cannot communicate which _package_ is incompatible (i.e. we cant construct the message pointing to "gdb" on the flox side)
* Pkgdb does not know the context in which it is used ("trying to pull")

What I'd propose is, print the pkgdb error, then provide options.
The message below is general over the cause of build failure, but it doesn't have to be

```
❌  ERROR: 'gdb' is unavailable on your system (aarch64-darwin)
! The environment you are trying to pull could not be built locally.
  Don't pull this environment.
> Pull this environment anyway, 'flox edit' to address issues
```

**Comment by ghudgins** [comment]
@ysndr and I discussed and think we can make this a bit more general to cover any error case during the eval/build. this way you can always work on remote environments even if they don't build for your system (or some other reason)

**Comment by ysndr** [comment]
@graham, `pull` is gathering more flags to skip the interactive prompts with this, since `--add-system` does not really fit semantically. I'm wondering if we _want_ multiple flags, just defer to one `--gnore-incompatible`, `--allow-broken`, etc?

**Comment by ghudgins** [comment]
I think just one is fine. we could even re-use `--force` in this context?

**Comment by graham** [comment]
I believe you may have the wrong graham, good luck!

**Comment by mkenigs** [comment]
Are we okay with a big long ugly error if the environment doesn't have the system added yet?
```
> flox pull mkenigs/gdb --add-system
failed to build environment: system unsupported by package: 'gdb' is not available on the requested hostPlatform ('aarch64-darwin'): error:
       … in the condition of the assert statement

         at /nix/store/s8k7m3p35h77mqlljcgqrb984n2mqz3b-source/lib/customisation.nix:229:17:

          228|       drvPath = assert condition; drv.drvPath;
          229|       outPath = assert condition; drv.outPath;
             |                 ^
          230|     };

       … while evaluating the attribute 'handled'

         at /nix/store/s8k7m3p35h77mqlljcgqrb984n2mqz3b-source/pkgs/stdenv/generic/check-meta.nix:447:7:

          446|       # or, alternatively, just output a warning message.
          447|       handled =
             |       ^
          448|         {

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘gdb-13.1’ in /nix/store/s8k7m3p35h77mqlljcgqrb984n2mqz3b-source/pkgs/development/tools/misc/gdb/default.nix:146 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mipsel-linux"
           "mips64el-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
           "i686-cygwin"
           "x86_64-cygwin"
           "x86_64-darwin"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.

Could not build modified environment, build errors need to be resolved manually.
✨  Pulled mkenigs/gdb from https://hub-dev.flox.dev/

You can activate this environment with 'flox activate'
```

**Comment by ghudgins** [comment]
@mkenigs if the _environment_ doesn't have the system I would expect we'd catch that with https://github.com/flox/flox/issues/823

if the package hasn't yet been set to a specific system (this error), then yes. at least for now

**Comment by mkenigs** [comment]
> @mkenigs if the _environment_ doesn't have the system I would expect we'd catch that with #823
> 
> if the package hasn't yet been set to a specific system (this error), then yes. at least for now

Right, we catch it with 823, but then when it fails to build, we dump the ugly error in my comment, rather than catching it. Asking because it's the same error as caught in this ticket, just in a slightly different scenario

**Comment by ghudgins** [comment]
I think that's because in 823's case we know exactly what's wrong and how to fix it so they don't need to see the error. 

in this case we would need to be 100% certain in how to parse the build error and display to the user exactly the packages that failed and offer them to fix it. since I'm not as certain in all the ways you can fix things we're showing the error. If you feel we can be confident and can offer the user the exact solution we could do that but it feels like the solution would be complicated or heavy handed. I think it's okay that it's slightly different between the simpler scenario (the entire env wasn't for your system) vs. nuanced (this package is failing for some reason, go figure it out)

**Comment by mkenigs** [comment]
> I think that's because in 823's case we know exactly what's wrong and how to fix it so they don't need to see the error.

If someone pulls in the way of 823, but then the build fails, we might know exactly what's wrong.

This ticket is:
If system in manifest && package doesn't build for very specific reason, then print very specific error.

I'm saying:
If system not in manifest -> user says to put it in -> system in manifest && package doesn't build for very specific reason, should we print the same very specific error as we're printing in this ticket? In other words, if someone runs `flox pull mkenigs/gdb --add-system`, should we print `'gdb' is unavailable on your system (aarch64-darwin)`

**Comment by aakropotkin** [comment]
@ghudgins while we're making this change, is this a good opportunity to mention the `optional` or `systems` fields to help users recover?

**Comment by ghudgins** [comment]
yes we should - similar to what's asked for here https://github.com/flox/flox/issues/864
'
"Read more about system errors here https://flox.dev/docs/tutorials/multi-arch-environments" <-- link will work once we publish doc

**Comment by ghudgins** [comment]
verified
