### ISSUE TITLE
non-interactive use first default for "would you like to initialize"

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#904]
**Describe the feature:**

Currently when users run commands non-interactively we throw errors in some cases where we expect a "sane default" to be chosen instead.

One common case is the "would you like to initialize an environment in this directory?" when we could instead fall-back to using the default environment.

**Describe a use case of this feature:**

In a non-project directory:
```
$ flox list|xargs -I{} sh -c 'echo {}' \; ;
```

**Acceptance criteria:**
1. In the snippet above use default env as fallback.
2. If no default env exists assume empty env and print nothing.
3. Handle similar non-interactive fallbacks similarly.

**Comment by ghudgins** [comment]
current directory is the default

**Comment by ysndr** [comment]
The issue description and title are not congruent.
I think what we discussed with the result "current directory is the default", was, environment detection should use a default in non-interactive situations.

Adding a dialog for "would you like to initialize" when there is no environment should be a different issue

**Comment by ysndr** [comment]
```
flox [cli] ↕ 4 /tmp/nix-shell.OUMRiD/tmp.yV6jAUfzKQ via ❄️  impure (flox-dev-env) took 7s 
⚡️1 ❯ cat /dev/null | flox install hello
✅ 'hello' installed to environment tmp.yV6jAUfzKQ at /private/tmp/nix-shell.OUMRiD/tmp.yV6jAUfzKQ
```

with #933 it should now just use the first option, at least for these _pick which environment_ situations.

There is more dialogs, that might require similar behaviour, that's now a separate change

**Comment by ghudgins** [comment]
verified
