### ISSUE TITLE
Add man pages to flox package

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#909]
Generate man pages from cli/flox/doc/*.md and put them in the flox output at share/man/man1/

I'm not completely sure how we did that before, but it looks like we may have used pandoc? See:
https://github.com/flox/flox/blob/57fa7b03b5887df3f3e6e2fc073cbf77991d9e91/flox-bash/Makefile#L85

I'm not sure how we handled includes

**Comment by ysndr** [comment]
The building was still there in the `flox-cli` package but `symlinkJoin` did not join the `$man` output.
