### ISSUE TITLE
flox search fails with 'attempted to write to a readonly database'

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#925]
STR:

It's tricky. Happened one time on a machine with lower system specs

![image](https://github.com/flox/flox/assets/5465514/0e627aed-5b7e-4a83-b178-73487c6bfa9c)

**Comment by aakropotkin** [comment]
I have been able to reproduce this issue reliably by killing `pkgdb` while it is creating a database, then attempting to open a read-only connection to the DB ( by performing any query ).

The crashes seem to be associated with `<DB-NAME>.sqlite-journal` files being present, which may indicate that a database connection was killed unexpectedly and there are pending writes that must be processed from the journal before reads are permitted.

**Comment by tomberek** [comment]
The trick here is to check for an initialized DB, but to fail as quickly as possible to allow another connection to gain an exclusive lock required by WAL to incorporate the journal. That's the purpose of setting the sqlite timeout to 0 for that step, but then set it to a higher value for actual queries.

https://gist.github.com/tomberek/c6fa7eb91ff7ca620f99da4acbb7bac6#file-main-rs-L27-L30 

Otherwise you can end up in a deadlock-style situation. Where the multiple readers keep trying with an open connection, even though another process has obtained a PENDING lock.

**Comment by aakropotkin** [comment]
I'm not sure if this is related but I got that error ( with different formatting ) to appear from underlying routines in `libnix-fetchers` when trying to create a reproducer for this.
If you kill `pkgdb` while it's creating `nix` caches for the first time, and then immediately retry:
```
error locking flake: failed to lock flake "github:NixOS/nixpkgs/release-23.11": error:
       … while fetching the input 'github:NixOS/nixpkgs/release-23.11'

       error: executing SQLite statement 'insert or replace into Cache(input, info, path, immutable, timestamp) values ('{"name":"source","type":"tarball","url":"https://api.github.com/repos/NixOS/nixpkgs/tarball/88d128f5f35be5d405fe874495604f3f29350a5f"}', '{"etag":"W/\"71dfbc2c71c6e9d02b9da2b637a74dd1bc7b92cf8636aad8a552e2da8d6c5f5d\"","lastModified":1707272513}', '/nix/store/jbpc1rgls0p9pd3fr4zg0akmdfmrq3vq-source', 1, 1707307394)': attempt to write a readonly database, attempt to write a readonly database (in '/tmp/nix-shell.3SbPu3/tmp.R0jor7ktsv/cache/nix/fetcher-cache-v1.sqlite')
```

**Comment by aakropotkin** [comment]
I was able to reproduce by killing `flox search` while `pkgdb` was creating a database.
This produces a "journal file" which is essentially a file used to recover unwritten DB changes.
Once that file exists, if you attempt to run `flox search` again you will attempt to re-create the database; but at the end of that process you will crash ( presumably trying to write ).

Note the `^C%` indicating `<CTRL>-C`.
```shell
$ rm -rf ~/.cache/flox/pkgdb-v2 ~/.cache/nix/eval-cache-v5;
$ flox search url
⠴ Searching for packages...                                                                                  This may take a while the first time you run it.
^C%                                                                                                                                                           
$ ls ~/.cache/flox/pkgdb-v2
fe7f9f95896546c73d4e9a7f1f75727638c1360d96a22baef58e6e5714f2b8e5.sqlite  fe7f9f95896546c73d4e9a7f1f75727638c1360d96a22baef58e6e5714f2b8e5.sqlite-journal
$ flox search url
ERROR: search encountered an error: error running pkgdb: couldn't initialize read-only package database
```

Attempting to rerun the command additional times will consistently get the crash.
