### ISSUE TITLE
flox says it found a .flox when there isn't one

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#926]
STR:
* be in a directory that does not contain a `.flox`
* `flox push`

Result:
<img width="697" alt="image" src="https://github.com/flox/flox/assets/5465514/7364dc04-f221-41e2-9441-bdc63a27d9ac">

Expected: 

Not to see statements that are not true

>Found a '.flox' directory, but were unable to locate an environment directory.
>Try deleting the '.flox' directory and reinitializing the environment.
>If you cloned this environment from a remote repository, verify that
`.flox/env/maifest.toml` is commited to the version control system.

**Comment by aakropotkin** [comment]
Spellcheck:
> but **was** unable to
