### ISSUE TITLE
list all environments on local machine (flox envs)

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#934]
**When** I don’t remember what environments I’ve created,
**I need** a way to see where all my environments are
**So I can** navigate to the directory with the environment I want
**AND  I can** copy and paste the directory path to use with `--dir` 

**When** I am looking at a list of my local and managed environments, 
**I need** to quickly see which environments are activated, 
**So I can** check that it’s working as I expected.

# Acceptance Criteria
`flox envs` : shows local env names (w/owner if managed) and their path; show active envs in a list first, with the most recently activated env in bold 

- Does not include envs in floxhub that have *not* been pushed or pulled from the local machine.
- Does not include any .flox directories that have been created with `git pull` but not yet used

`flox envs --active` : shows only active envs

`flox envs --json` : active and inactive environments and all their info in JSON format

`flox envs --active --json` : contents of `_FLOX_ACTIVE_ENVIRONMENTS` - only active environments and all their info

See Notion for output for each command:
https://www.notion.so/floxdev/View-environments-CLI-design-8f68c6465e944cba8f3ab474b1785ca4?pvs=4#f36eea0623564801a7ec717f11203c65

**Comment by ghudgins** [comment]
+1 from user research today

**Comment by ysndr** [comment]
Sample implementation in #988

**Comment by ghudgins** [comment]
+1 from https://discourse.flox.dev/t/some-notes-for-people-migrating-to-flox-0-9-0/830

**Comment by jennymahmoudi** [comment]
@ysndr @ghudgins apologies for the slowness here. I wanted to take a holistic look before introducing a new command. 
Please review and comment on the design options in Notion:
https://www.notion.so/floxdev/View-environments-CLI-design-8f68c6465e944cba8f3ab474b1785ca4

**Comment by ysndr** [comment]
> Indent the environments under the title

done

> Add sparkle emoji to the Active title (I had ✨ Active ✨ , but we can keep the longer title and just add one emoji to the beginning: ✨ Active environments:

TBF there are two examples if this in the notion:
1. `✨ Active ✨`: https://www.notion.so/floxdev/View-environments-CLI-design-8f68c6465e944cba8f3ab474b1785ca4?pvs=4#5f8ccf0ae7e1473db58cab91a90f2296
2. `Active environments:` https://www.notion.so/floxdev/View-environments-CLI-design-8f68c6465e944cba8f3ab474b1785ca4?pvs=4#c98d0cb23481404abe9d54f469306321

lets go with `✨ Active environments` as a mix of both that also does not have a 1/3 ration of emojis ^^

But is it then `Inactive`, or `Inactive Environments` or `💤 Inactive Environments`? 

Besides, ✨ was defined as the emoji for a "created" message, do we need to have another look at the emoji guidelines, maybe use `🟢 Active Environments` (and `🟠 Inactive Environments`) or `▶️ Active Environments` and `⏸️ Inactive Environments` (the other ⏯️ emoji does not seem to render correctly in zenhub)

> Should the envs command be listed in help yet? I didn't see it.

added, let me know if the command should go into the main section instead, for now its under Additional Commands

> The flox plain command should also have a different output, but it looks like that's unchanged.

yep forgot about that, added now

#1370

**Comment by jennymahmoudi** [comment]
> TBF there are two examples if this in the notion:
> 
> 1. `✨ Active ✨`: https://www.notion.so/floxdev/View-environments-CLI-design-8f68c6465e944cba8f3ab474b1785ca4?pvs=4#5f8ccf0ae7e1473db58cab91a90f2296
> 2. `Active environments:` https://www.notion.so/floxdev/View-environments-CLI-design-8f68c6465e944cba8f3ab474b1785ca4?pvs=4#c98d0cb23481404abe9d54f469306321
> 
> lets go with `✨ Active environments` as a mix of both that also does not have a 1/3 ration of emojis ^^

My thinking at the time was to differentiate the Active list from the Inactive list with the sparkle, so when there was just one list (`--active`), it wasn't needed. 🤷  I'm good with how you have it now (emoji every time we say Active).

> But is it then `Inactive`, or `Inactive Environments` or `💤 Inactive Environments`?

`Inactive Environments` 👍 
 
> Besides, ✨ was defined as the emoji for a "created" message, do we need to have another look at the emoji guidelines, maybe use `🟢 Active Environments` (and `🟠 Inactive Environments`) or `▶️ Active Environments` and `⏸️ Inactive Environments` (the other ⏯️ emoji does not seem to render correctly in zenhub)

I don't think we need to pick a different emoji. Some emojis will be reserved for specific situations (like the ❌ for errors and 🗑️ for delete), just like some colors in FloxHub are (like red for errors). But I think emojis like ✨  can be used for multiple scenarios for emphasis, similar to how a primary color or other text styling like bold can be used throughout FloxHub. 

If this causes any confusion between init and activate, we can revisit.

> > Should the envs command be listed in help yet? I didn't see it.
> 
> added, let me know if the command should go into the main section instead, for now its under Additional Commands

Additional commands makes sense. 👍

**Comment by jennymahmoudi** [comment]
looks good!
