### ISSUE TITLE
[pkgdb/fix]: Do not write views definitions to database

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#946]
After running into a few headaches attempting to write updated views definitions to databases, we'd like to take an alternative approach.

Rather than writing views definitions to DBs - instead prefix any queries which require views with their definitions inline ( using temporary views ).

This allows us to avoid views updates on DBs which would otherwise be _read-only_ operations, and it simplifies DB initialization in `PkgDbInput`.

When removing existing views definitions from `PkgDb::init()` be sure to bump the DB's major version.

Associated Ticket: https://github.com/flox/flox/issues/942

**Comment by mkenigs** [comment]
Just a note: I find it convenient having views in the db when I'm debugging. Probably not too hard to copy and paste it or something, but just something to keep in mind

**Comment by aakropotkin** [comment]
I totally agree which was initially why I included them.

After seeing it's effect on sync though I want to try making them hermetic.

**Comment by ghudgins** [comment]
will hopefully resolve this with catalog service
