### ISSUE TITLE
telemetry for failed installs

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#950]
# Acceptance Criteria

We send the package name that was attempted to flox data lake for analysis

**Comment by ysndr** [comment]
Do you want to catch specific errors, or just the fact that an install failed and which packages were attempted?

**Comment by ysndr** [comment]
On the rust side we don't have access to the specific package that failed, we essentially add all new packages to the manifest and pass it to pkgdb (which may produce package specific error **texts**.
If we were to install package by package, we'd kick off multiple builds which would significantly increase the runtime of `flox install` with multiple packages.

returning an error condition with the _list_ of packages would greatly simplify this issue.

Optimally, pkgdb would provide this kind of information but we opted to format errors on that side and provide an opaque error, addressing that would greatly exceed the scope of this issue IMO

**Comment by mkenigs** [comment]
I think it would be relatively easy to report what packages changed and what the error was. That wouldn't correlate the error with a single package in the case of installing multiple packages at the same time, but it would give us a good idea a lot of the time
