### ISSUE TITLE
Direct users to man pages in command help

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#960]
At the bottom of the help for tools like `cargo` you often find a line of text of the form:
```
Run `cargo help build` for more detailed information.
```

This is the last line of the help text, which puts it right above the terminal prompt after running `cargo build -h`, making it very visible. This is a good way to direct users to man pages and indicates that there may be further description or details than what's seen in the `-h` for a command.

**Acceptance criteria:**
- Determine whether `bpaf` can include arbitrary text at the bottom of the help description.
- Include `Run 'man flox-<cmd>' for more details` at the bottom of command help text, filling in `<cmd>` with whatever command's help was generated.

Example output:
```
Search for system or library packages to install

Usage: flox search [--json] [--refresh] [-a] <search-term>

Search for packages to install
        --json     print search as JSON
        --refresh  force update of catalogs from remote sources before searching
    -a, --all      Print all search results
    <search-term>  query string of the form `<REGEX>[@<SEMVER-RANGE>]` used to filter match against package
                   names/descriptions, and semantic version. Regex pattern is `PCRE` style, and semver
                   ranges use the `node-semver` syntax. Exs: `(hello|coreutils)`, `node@>=16`, `coreutils@9.1`

Available options:
    -h, --help     Prints help information

Run 'man flox-search' for more details.
```

**Comment by mkenigs** [comment]
See footer https://docs.rs/bpaf/latest/bpaf/struct.OptionParser.html#method.footer
