### ISSUE TITLE
Developer config file detected during integration tests

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#963]
In your `~/.config/flox/flox.toml` put an invalid `floxhub_url` and you'll see tests fail.

We currently set XDG environment variables in `xdg_reals_setup()` in `cli/tests/setup_suite.sh`, so we're _attempting_ to provide isolation between integration tests and the developer's local config, but that attempt appears to have holes in it.

**Acceptance criteria:**
- An invalid config file in `~/.config/flox/flox.toml` shouldn't cause integration test failures.

**Comment by ysndr** [comment]
I think this is fixed now by #1045 and #1145[sic]
