### ISSUE TITLE
Install packages to "pkg-path" instead of "path"

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#972]
We're now going to use the term "pkg-path" to refer to relative attribute paths to avoid confusion with filesystem paths.

**Acceptance criteria:**
- The manifest installs packages by setting `pkg-path` instead of `path`

**Comment by ghudgins** [comment]
needs high priority fixes. still getting errors - see thread in slack - https://flox-dev.slack.com/archives/C054SAD6NLD/p1707873232003389?thread_ts=1707868084.836129&cid=C054SAD6NLD

**Comment by ghudgins** [comment]
we'll amend the procedure manually this time
