### ISSUE TITLE
add option to stream `pkgdb` `STDERR`

### ISSUE THREAD

**Issue by alex-ameen** [flox/flox#974]
Toggle using a `--debug`, undocumented verbosity flag, or `FLOX_PKGDB_STDERR=1`.

In this mode all invocations of `pkgdb` pass `-vvvv` and connect/stream `STDERR` from `pkgdb` to the CLI's `STDERR`.

This is incredibly useful for debugging `pkgdb`.

See prior art: https://github.com/flox/flox/tree/f29368bad2beea05b8c545460ed5d19aaa6bdff1

**Comment by mkenigs** [comment]
Should we just let some number of `-v` control that?

**Comment by aakropotkin** [comment]
I liked the idea of having a separate toggle and maybe passing thru the `-v` or `-vv` "level".
Otherwise `pkgdb` output is either "nothing" or "vomit".

**Comment by ysndr** [comment]
suggestion: log it to the "pkgdb" target then it can be toggled with `RUST_LOG=pkgdb=debug` (and also  with `-vv`) not sure if it needs a special _flag_ for that as well
