### ISSUE TITLE
Create common error code/name lookup table

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#998]
**Describe the feature:**

**Describe a use case of this feature:**

**Acceptance criteria:**
1. Declare error codes, names, and _short description_ in a plain format such as `.tsv` or `.json`.
2. Migrate existing error table from C++ to this format.
3. Using a lightweight script ( e.g. `awk`, `sed`, `m4`, `sh`, etc ) convert this lookup table to a C++ header file, and a Rust source code file.
4. Ensure generated files contain inline documentation so that tools such as Doxygen and `rustdoc` work as expected.
5. Modify existing builds ( `Makefile`, `cargo`, `Justfile`, `nix` derivations ) to consume these generated file.
6. Do **not** check the generated files into version control.

**Comment by ysndr** [comment]
Consider using any of the _existing_ solutions to this problem:

* https://github.com/kondrak/codespawn (their own format but generates both rust and C++)
* JSON Schema -- known format with existing parsers/codegen integrated in the build system e.g.
  + https://github.com/oxidecomputer/typify
  + https://github.com/Marwes/schemafy

JSON Schemas have the additional benefit that they may scale to _also_ represent further output types of pkgdb calls apart from just errors which currently also have to be kept in sync manually.
If things become more service oriented, we may also consider using an _actual_ rpc protocol/types e.g. protobufs.

**Comment by mkenigs** [comment]
I don't think not having this has been hurting us much, so closing
